import React from "react";
import { CheckCircle2, Database, Eye, ShieldCheck } from "lucide-react";
import { commandCenterSummary } from "./JobCommandCenter";

type Props={data:any;documents:any[];tt:(en:string,es:string)=>string};
export function IntakeReleaseReadiness({data,documents,tt}:Props){const s=commandCenterSummary(data,documents);const checks=[
  [tt("Existing records remain the source", "Los registros existentes siguen siendo la fuente"),true],
  [tt("Company-to-resource chain is complete", "La cadena de empresa a recurso está completa"),s.attention.length===0],
  [tt("No automatic approval or financial posting", "Sin aprobación ni registro financiero automático"),true],
  [tt("Compatibility is previewed before activation", "La compatibilidad se previsualiza antes de activar"),true],
] as const;return <section className="irr" aria-labelledby="irr-title"><style>{css}</style><header><div><span>{tt("BUILD 10 · RELEASE READINESS", "BUILD 10 · PREPARACIÓN PARA LIBERACIÓN")}</span><h2 id="irr-title">{tt("Compatibility and complete-scenario check", "Verificación de compatibilidad y escenario completo")}</h2><p>{tt("A final, read-only view of what will be preserved and what still blocks release.", "Una vista final de solo lectura de lo que se conservará y lo que aún bloquea la liberación.")}</p></div><Eye aria-hidden="true"/></header><div className="irr-grid"><article><Database/><strong>{tt("Migration preview", "Vista previa de migración")}</strong><p>{tt("Legacy identity, scope, contracts and assignments are preserved. New relationship, APU, package and resource containers are added only when absent.", "Se conservan identidad, alcance, contratos y asignaciones anteriores. Los nuevos contenedores de relaciones, APU, paquetes y recursos se agregan solo cuando faltan.")}</p></article><article><ShieldCheck/><strong>{tt("No hidden action", "Sin acción oculta")}</strong><p>{tt("This view does not migrate, approve, activate, post, push or publish anything.", "Esta vista no migra, aprueba, activa, registra, envía ni publica nada.")}</p></article></div><ul>{checks.map(([label,pass])=><li key={label} className={pass?"pass":"wait"}><CheckCircle2 aria-hidden="true"/><span>{label}</span><strong>{pass?tt("PASS","CUMPLE"):tt("REVIEW","REVISAR")}</strong></li>)}</ul><footer>{s.attention.length?tt(`${s.attention.length} structural item(s) still need attention before activation.`,`${s.attention.length} elemento(s) estructural(es) aún requieren atención antes de activar.`):tt("The represented scenario has no structural gaps. External release gates remain separate.","El escenario representado no tiene brechas estructurales. Las puertas externas de liberación permanecen separadas.")}</footer></section>}
const css=`.irr{margin:18px 0;padding:22px;border:1px solid #b7c7da;border-radius:18px;background:#fff;color:#10233f}.irr header{display:flex;justify-content:space-between;gap:16px}.irr header span{font-size:11px;font-weight:900;letter-spacing:.13em;color:#0f766e}.irr h2{margin:5px 0;font-size:23px}.irr header p{margin:0;color:#526176}.irr header>svg{color:#0f766e}.irr-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:16px 0}.irr-grid article{padding:14px;border:1px solid #dbe4ef;border-radius:12px;background:#f8fbfd}.irr-grid strong{display:block;margin:6px 0}.irr-grid p{margin:0;color:#526176;font-size:12px;line-height:1.45}.irr ul{list-style:none;padding:0;margin:0}.irr li{display:grid;grid-template-columns:auto 1fr auto;gap:9px;align-items:center;padding:10px;border-top:1px solid #e2e8f0}.irr li.pass svg{color:#0f766e}.irr li.wait svg{color:#b45309}.irr li strong{font-size:10px}.irr footer{margin-top:12px;padding:11px;border-radius:9px;background:#eef6ff;color:#234263;font-weight:700}@media(max-width:650px){.irr{padding:15px}.irr-grid{grid-template-columns:1fr}.irr h2{font-size:20px}.irr li{align-items:start}}`;
