import assert from "node:assert/strict";
import fs from "node:fs";
const component = fs.readFileSync(new URL("./MasterClassificationSelectors.tsx", import.meta.url), "utf8");
const quick = fs.readFileSync(new URL("./QuickJobIntake.tsx", import.meta.url), "utf8");
assert.match(component, /\/master-catalogs\/disciplines/);
assert.doesNotMatch(component, /<select[^>]*service/i);
assert.doesNotMatch(component, /<select[^>]*phase/i);
assert.match(component, /Services and phases belong to work packages and tasks/);
assert.match(component, /entry\.aliases/);
assert.match(component, /classification/);
assert.doesNotMatch(component, /<input/);
assert.match(quick, /<MasterClassificationSelectors data=\{data\}/);
console.log("master project classification selectors: PASS");
