import assert from "node:assert/strict";
import fs from "node:fs";
const component = fs.readFileSync(new URL("./MasterClassificationSelectors.tsx", import.meta.url), "utf8");
const quick = fs.readFileSync(new URL("./QuickJobIntake.tsx", import.meta.url), "utf8");
assert.match(component, /\/master-catalogs\/disciplines/);
assert.doesNotMatch(component, /\/master-catalogs\/(services|phases)/);
assert.doesNotMatch(component, /Select service|Select phase|Seleccione servicio|Seleccione fase/);
assert.match(component, /classification/);
assert.doesNotMatch(component, /<input/);
assert.match(quick, /<MasterClassificationSelectors data=\{data\}/);
console.log("master project classification selectors: PASS");
