import React from "react";
import { Layers3, Plus, Trash2 } from "lucide-react";

type Props = { data: any; setData: (updater: (old: any) => any) => void; tt: (en: string, es: string) => string };
const blank = (apuDraftId: string) => ({ id: `WP-${crypto.randomUUID()}`, apuDraftId, title: "", floor: "", zone: "", task: "", deliverable: "" });

export function WorkPackageBuilder({ data, setData, tt }: Props) {
  const packages = data.workPackages || [], apus = data.apuDrafts || [];
  const setPackages = (next: any[]) => setData((old: any) => ({ ...old, workPackages: next }));
  const update = (id: string, patch: any) => setPackages(packages.map((row: any) => row.id === id ? { ...row, ...patch } : row));
  const remove = (id: string) => setPackages(packages.filter((row: any) => row.id !== id));
  const floorCount = new Set(packages.map((row: any) => row.floor).filter(Boolean)).size;
  const zoneCount = new Set(packages.map((row: any) => row.zone).filter(Boolean)).size;
  return <section className="wp-builder" aria-labelledby="wp-title"><style>{css}</style>
    <header><div><span className="wp-kicker">{tt("BREAK DOWN THE WORK", "DIVIDA EL TRABAJO")}</span><h2 id="wp-title">{tt("From APU to work packages", "Del APU a paquetes de trabajo")}</h2><p>{tt("Split each priced service by floor, zone, task, or deliverable. Use only the detail you need now; blank fields are allowed.", "Divida cada servicio valorado por piso, zona, tarea o entregable. Use solo el detalle que necesita ahora; se permiten campos vacíos.")}</p></div><div className="wp-stats"><span><strong>{packages.length}</strong>{tt("Packages", "Paquetes")}</span><span><strong>{floorCount}</strong>{tt("Floors", "Pisos")}</span><span><strong>{zoneCount}</strong>{tt("Zones", "Zonas")}</span></div></header>
    {!apus.length && <div className="wp-empty">{tt("Create an APU first. Work packages always belong to one APU.", "Primero cree un APU. Los paquetes de trabajo siempre pertenecen a un APU.")}</div>}
    {apus.map((apu: any) => { const rows = packages.filter((row: any) => row.apuDraftId === apu.id); return <article className="wp-apu" key={apu.id}><div className="wp-apu-head"><div><Layers3 size={18}/><span><strong>{apu.title}</strong><small>{rows.length} {tt("work packages", "paquetes de trabajo")}</small></span></div><button type="button" onClick={() => setPackages([...packages, blank(apu.id)])}><Plus size={15}/>{tt("Add package", "Agregar paquete")}</button></div>
      {!rows.length && <div className="wp-empty">{tt("No split needed yet. Add a package when this APU must be delegated or tracked by location or deliverable.", "Aún no necesita división. Agregue un paquete cuando este APU deba delegarse o controlarse por ubicación o entregable.")}</div>}
      <div className="wp-list">{rows.map((row: any, index: number) => <div className="wp-row" key={row.id}><div className="wp-row-title"><span>{index + 1}</span><input aria-label={tt("Package name", "Nombre del paquete")} placeholder={tt("Package name", "Nombre del paquete")} value={row.title || ""} onChange={(event) => update(row.id, { title: event.target.value })}/><button type="button" aria-label={tt("Delete package", "Eliminar paquete")} onClick={() => remove(row.id)}><Trash2 size={15}/></button></div><div className="wp-fields"><label>{tt("Floor / level", "Piso / nivel")}<input value={row.floor || ""} placeholder={tt("Example: Level 10", "Ejemplo: Nivel 10")} onChange={(event) => update(row.id, { floor: event.target.value })}/></label><label>{tt("Zone / area", "Zona / área")}<input value={row.zone || ""} placeholder={tt("Example: East", "Ejemplo: Este")} onChange={(event) => update(row.id, { zone: event.target.value })}/></label><label>{tt("Task", "Tarea")}<input value={row.task || ""} placeholder={tt("What must be done?", "¿Qué se debe hacer?")} onChange={(event) => update(row.id, { task: event.target.value })}/></label><label>{tt("Deliverable", "Entregable")}<input value={row.deliverable || ""} placeholder={tt("What will be delivered?", "¿Qué se entregará?")} onChange={(event) => update(row.id, { deliverable: event.target.value })}/></label></div></div>)}</div>
    </article>})}
    <div className="wp-note"><strong>{tt("One source of truth", "Una sola fuente de verdad")}</strong> {tt("These packages describe the Intake scope. Activation may link them to the existing schedule, tasks, and documents; this screen does not create a second schedule or document store.", "Estos paquetes describen el alcance del Ingreso. La activación puede vincularlos al calendario, tareas y documentos existentes; esta pantalla no crea un segundo calendario ni almacén de documentos.")}</div>
  </section>;
}

const css = `.wp-builder{margin:18px 0;padding:22px;border:1px solid #c7d7ee;border-radius:20px;background:#f8fbff;color:#172b4d}.wp-builder header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.wp-builder h2{font-size:24px;margin:4px 0 6px}.wp-builder p{margin:0;color:#526681;max-width:760px}.wp-kicker{font-size:11px;font-weight:800;letter-spacing:.15em;color:#245bb4}.wp-stats{display:flex;gap:8px}.wp-stats span{min-width:72px;padding:8px;border-radius:10px;background:#e8f0fc;text-align:center;font-size:11px}.wp-stats strong{display:block;font-size:19px}.wp-apu{margin-top:16px;border:1px solid #d6e1f0;border-radius:14px;background:white;padding:14px}.wp-apu-head,.wp-apu-head>div,.wp-row-title{display:flex;align-items:center;gap:10px}.wp-apu-head{justify-content:space-between}.wp-apu-head span,.wp-apu-head small{display:block}.wp-apu-head small{color:#6a7890}.wp-apu-head button,.wp-row-title button{display:flex;align-items:center;gap:6px;border:1px solid #afc5e6;border-radius:8px;padding:8px 10px;background:#eef4fd;font-weight:700}.wp-empty{margin-top:12px;padding:16px;border-radius:10px;background:#f1f5fa;text-align:center;color:#66758a}.wp-list{display:grid;gap:10px;margin-top:12px}.wp-row{border:1px solid #dce5f1;border-radius:11px;padding:12px}.wp-row-title span{display:grid;place-items:center;width:26px;height:26px;border-radius:50%;background:#dce9fb;font-weight:800}.wp-row-title input{flex:1;font-weight:800;font-size:15px}.wp-row-title input,.wp-fields input{box-sizing:border-box;border:1px solid #c8d5e5;border-radius:8px;padding:9px;background:white}.wp-row-title button{margin-left:auto;padding:7px}.wp-fields{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.wp-fields label{font-size:12px;font-weight:700;color:#53647c}.wp-fields input{display:block;width:100%;margin-top:5px}.wp-note{margin-top:14px;padding:12px 14px;border-left:4px solid #2a69c7;border-radius:8px;background:#eaf2fd}@media(max-width:700px){.wp-builder{padding:14px}.wp-builder header{display:block}.wp-stats{margin-top:12px}.wp-stats span{flex:1}.wp-apu-head{align-items:flex-start}.wp-apu-head button{white-space:nowrap}.wp-fields{grid-template-columns:1fr 1fr}}@media(max-width:430px){.wp-fields{grid-template-columns:1fr}.wp-apu-head{display:block}.wp-apu-head button{width:100%;justify-content:center;margin-top:10px}}`;
