import { useEffect, useMemo, useRef, useState } from "react";
import { Settings2, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useAuthStore } from "@/store/auth";
import { useI18n } from "@/lib/i18n";
import { useToast } from "@/hooks/use-toast";

const API_BASE=import.meta.env.BASE_URL.replace(/\/$/,"");
type Decision="enabled"|"disabled"|"inherit";
type ConfigurationField={key:string;label:{en:string;es:string};description:{en:string;es:string};options:{value:string;label:{en:string;es:string}}[]};
type Entry={featureKey:string;name:{en:string;es:string};description?:{en:string;es:string};availability:string;decision?:Decision;effectiveDecision?:Decision;version?:number;configuration?:Record<string,string>;configurationDefinition?:ConfigurationField[]};
type Capabilities={companyPolicyAdmin:boolean;superAdminMetadataOnly:boolean;projects:{id:number;name:string;active:boolean;bindingRequired?:boolean;canConfigure:boolean}[]};
type ReasonDraft={code:string;en:string;es:string;reviewed:boolean};
const emptyReason:ReasonDraft={code:"",en:"",es:"",reviewed:false};
const availabilityColor=(value:string)=>value==="available"?"#166534":value==="preview"?"#92400E":"#475569";

export function FeaturePolicySettingsPanel(){
  const {token}=useAuthStore();const {tt}=useI18n();const {toast}=useToast();
  const [capabilities,setCapabilities]=useState<Capabilities|null>(null);const [preferences,setPreferences]=useState<Entry[]>([]);const [company,setCompany]=useState<Entry[]>([]);const [project,setProject]=useState<Entry[]>([]);
  const [selectedProject,setSelectedProject]=useState<number|null>(null);const [tab,setTab]=useState<"user"|"company"|"project">("user");const [draft,setDraft]=useState<Record<string,Decision>>({});const [configurationDraft,setConfigurationDraft]=useState<Record<string,Record<string,string>>>({});const [reasons,setReasons]=useState<Record<string,ReasonDraft>>({});
  const [busy,setBusy]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [loadError,setLoadError]=useState<string|null>(null);const [projectError,setProjectError]=useState<string|null>(null);const loadSequence=useRef(0);const projectSequence=useRef(0);
  const headers=useMemo(()=>({"Content-Type":"application/json",Authorization:`Bearer ${token}`}),[token]);
  async function request(path:string,init?:RequestInit){const response=await fetch(`${API_BASE}/api/v1${path}`,{...init,headers:{...headers,...init?.headers}});const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body?.error?.en||tt("The policy request was rejected.","La solicitud de política fue rechazada."));(error as Error&{code?:string}).code=body?.code;throw error;}return body;}
  async function load(){const sequence=++loadSequence.current;setLoading(true);setLoadError(null);try{const caps=await request("/features/policies/capabilities") as Capabilities;const prefs=await request("/features/preferences");if(sequence!==loadSequence.current)return;setCapabilities(caps);setPreferences(prefs.preferences||[]);if(caps.companyPolicyAdmin){const result=await request("/features/policies/company");if(sequence!==loadSequence.current)return;setCompany(result.policies||[]);}else setCompany([]);const first=(caps.projects||[]).find(item=>item.active);setSelectedProject(current=>current??first?.id??null);}catch{if(sequence!==loadSequence.current)return;const message=tt("Feature controls could not be loaded. Retry when the connection is available.","No se pudieron cargar los controles de funciones. Reintenta cuando la conexión esté disponible.");setLoadError(message);toast({title:tt("Feature controls unavailable","Controles de funciones no disponibles"),description:message,variant:"destructive"});}finally{if(sequence===loadSequence.current)setLoading(false);}}
  async function loadProject(){const sequence=++projectSequence.current;const requested=selectedProject;if(requested===null){setProject([]);setProjectError(null);return;}setProjectError(null);try{const body=await request(`/features/policies/projects/${requested}`);if(sequence!==projectSequence.current||requested!==selectedProject)return;setProject(body.policies||[]);}catch{if(sequence!==projectSequence.current||requested!==selectedProject)return;setProjectError(tt("Project controls could not be loaded. Retry this project scope.","No se pudieron cargar los controles del proyecto. Reintenta este alcance de proyecto."));}}
  useEffect(()=>{void load();},[]);useEffect(()=>{void loadProject();},[selectedProject]);
  function clear(key:string){setDraft(current=>{const next={...current};delete next[key];return next;});setConfigurationDraft(current=>{const next={...current};delete next[key];return next;});setReasons(current=>{const next={...current};delete next[key];return next;});}
  async function save(entry:Entry,scope:"user"|"company"|"project"){const key=`${scope}:${entry.featureKey}`;const decision=draft[key]??entry.decision??"inherit";const reason=reasons[key]??emptyReason;const configuration=configurationDraft[key]??entry.configuration??{};setBusy(key);try{const path=scope==="user"?`/features/preferences/${entry.featureKey}`:scope==="company"?`/features/policies/company/${entry.featureKey}`:`/features/policies/projects/${selectedProject}/${entry.featureKey}`;const body=scope==="user"?{decision,expectedVersion:entry.version??0}:{decision,configuration,expectedVersion:entry.version??0,reasonCode:reason.code,explanation:{en:reason.en,es:reason.es}};await request(path,{method:scope==="user"?"PUT":"POST",body:JSON.stringify(body)});clear(key);await load();if(scope==="project")await loadProject();toast({title:tt("Policy saved","Política guardada"),description:tt("The governed defaults are recorded. Saving did not activate or run the project.","Los valores predeterminados gobernados quedaron registrados. Guardar no activó ni ejecutó el proyecto.")});}catch(error){toast({title:tt("Save failed","Error al guardar"),description:(error as Error&{code?:string}).code==="POLICY_VERSION_CONFLICT"?tt("This policy changed. Reload and review its new version.","Esta política cambió. Recargue y revise su nueva versión."):error instanceof Error?error.message:undefined,variant:"destructive"});}finally{setBusy(null);}}
  const rows=tab==="user"?preferences:tab==="company"?company:project;const selected=capabilities?.projects.find(item=>item.id===selectedProject);const canEdit=tab==="user"||(tab==="company"?capabilities?.companyPolicyAdmin===true:selected?.canConfigure===true);
  return <section aria-label={tt("Feature policy settings","Configuración de políticas de funciones")} aria-busy={loading||busy!==null} style={{border:"1px solid hsl(var(--border))",borderRadius:12,background:"hsl(var(--card))",padding:18}}>
    <header style={{display:"flex",gap:10,marginBottom:14}}><span style={{width:34,height:34,borderRadius:8,background:"#EFF6FF",display:"grid",placeItems:"center"}}><Settings2 size={17} color="#2563EB"/></span><div><h2 style={{fontSize:15,fontWeight:750,margin:0}}>{tt("Feature Policy Settings","Configuración de políticas de funciones")}</h2><p style={{fontSize:12,color:"hsl(var(--muted-foreground))",margin:"3px 0 0"}}>{tt("Company and project policy may supply governed defaults. BIMLog defaults remain usable when no policy is configured.","La política de empresa y proyecto puede proporcionar valores gobernados. Los valores de BIMLog siguen disponibles cuando no hay política configurada.")}</p></div></header>
    <div role="tablist" style={{display:"flex",flexWrap:"wrap",gap:8,marginBottom:14}}>{(["user","company","project"] as const).map(value=>value==="company"&&!capabilities?.companyPolicyAdmin?null:<Button key={value} type="button" role="tab" aria-selected={tab===value} size="sm" variant={tab===value?"default":"outline"} disabled={loading||busy!==null} onClick={()=>setTab(value)}>{value==="user"?tt("My Feature Preferences","Mis preferencias de funciones"):value==="company"?tt("Company Controls","Controles de empresa"):tt("Project Controls","Controles de proyecto")}</Button>)}</div>
    {capabilities?.superAdminMetadataOnly&&<div style={{fontSize:12,padding:10,border:"1px solid #FDE68A",background:"#FFFBEB",borderRadius:8,marginBottom:12}}>{tt("Super Administrator status permits binding and grant metadata only; it does not grant confidential company or project access.","El estado de Superadministrador solo permite metadatos de vinculaciones y concesiones; no concede acceso confidencial de empresa o proyecto.")}</div>}
    {tab==="project"&&<label style={{display:"block",fontSize:12,fontWeight:650,marginBottom:12}}>{tt("Project","Proyecto")}<select value={selectedProject??""} onChange={event=>setSelectedProject(Number(event.target.value))} style={{display:"block",width:"100%",marginTop:5,padding:8}}>{capabilities?.projects.map(item=><option key={item.id} value={item.id}>{item.name}{item.bindingRequired?" · "+tt("binding required","vinculación requerida"):item.canConfigure?"":" · "+tt("read only","solo lectura")}</option>)}</select></label>}
    {projectError&&<div role="alert">{projectError} <Button size="sm" variant="outline" onClick={()=>void loadProject()}>{tt("Retry","Reintentar")}</Button></div>}
    {loading?<p>{tt("Loading feature controls…","Cargando controles de funciones…")}</p>:loadError?<div role="alert">{loadError} <Button size="sm" variant="outline" onClick={()=>void load()}>{tt("Retry","Reintentar")}</Button></div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(280px,100%),1fr))",gap:10}}>{rows.map(entry=>{const key=`${tab}:${entry.featureKey}`;const value=draft[key]??entry.decision??"inherit";const unavailable=entry.availability!=="available";const reason=reasons[key]??emptyReason;const reasonReady=tab==="user"||(reason.code.length>=3&&reason.en.trim().length>0&&reason.es.trim().length>0&&reason.reviewed);const configured=configurationDraft[key]??entry.configuration??{};return <article key={entry.featureKey} style={{border:"1px solid hsl(var(--border))",borderRadius:9,padding:12,minWidth:0}}>
      <div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{tt(entry.name.en,entry.name.es)}</strong><Badge variant="outline" style={{color:availabilityColor(entry.availability)}}>{entry.availability==="available"?tt("Available","Disponible"):entry.availability}</Badge></div><p style={{fontSize:11,color:"hsl(var(--muted-foreground))"}}>{entry.description?tt(entry.description.en,entry.description.es):tt("Inherited company and project policy.","Política heredada de empresa y proyecto.")}</p><div style={{fontSize:11,marginBottom:8}}><ShieldCheck size={12} style={{display:"inline",marginRight:4}}/>{tt("Effective inherited result","Resultado heredado efectivo")}: {entry.effectiveDecision==="disabled"?tt("Off","Desactivado"):tt("On, subject to higher controls","Activado, sujeto a controles superiores")}</div>
      <label style={{fontSize:11}}>{tt("Selected decision","Decisión seleccionada")}<select value={value} disabled={!canEdit||busy!==null||unavailable} onChange={event=>setDraft(current=>({...current,[key]:event.target.value as Decision}))} style={{display:"block",width:"100%",marginTop:4,padding:7}}><option value="inherit">{tt("Use Default / Inherit","Usar predeterminado / Heredar")}</option><option value="enabled">{tt("On","Activado")}</option><option value="disabled">{tt("Off","Desactivado")}</option></select></label>
      {tab!=="user"&&(entry.configurationDefinition?.length??0)>0&&<fieldset style={{border:"1px solid hsl(var(--border))",borderRadius:7,padding:9,margin:"9px 0 0",display:"grid",gap:8}}><legend style={{fontSize:11,fontWeight:700}}>{tt("Governed defaults","Valores predeterminados gobernados")}</legend>{entry.configurationDefinition?.map(field=><label key={field.key} style={{fontSize:11}}>{tt(field.label.en,field.label.es)}<select value={configured[field.key]??""} disabled={!canEdit||busy!==null||unavailable} onChange={event=>{setConfigurationDraft(current=>({...current,[key]:{...(current[key]??entry.configuration??{}),[field.key]:event.target.value}}));setDraft(current=>({...current,[key]:current[key]??entry.decision??"inherit"}));}} style={{display:"block",width:"100%",marginTop:4,padding:7}}><option value="">{tt("Use inherited / BIMLog default","Usar heredado / predeterminado de BIMLog")}</option>{field.options.map(item=><option key={item.value} value={item.value}>{tt(item.label.en,item.label.es)}</option>)}</select><small style={{display:"block",marginTop:3,color:"hsl(var(--muted-foreground))"}}>{tt(field.description.en,field.description.es)}</small></label>)}</fieldset>}
      {tab!=="user"&&draft[key]!==undefined&&<div style={{display:"grid",gap:6,marginTop:8}}><select aria-label={tt("Reason","Motivo")} value={reason.code} onChange={event=>setReasons(current=>({...current,[key]:{...reason,code:event.target.value,reviewed:false}}))}><option value="">{tt("Select a reason","Seleccione un motivo")}</option><option value="PROJECT_REQUIREMENT">{tt("Project requirement","Requisito del proyecto")}</option><option value="ACCESS_GOVERNANCE">{tt("Access governance","Gobernanza de acceso")}</option></select><input maxLength={1000} placeholder={tt("English explanation","Explicación en inglés")} value={reason.en} onChange={event=>setReasons(current=>({...current,[key]:{...reason,en:event.target.value,reviewed:false}}))}/><input maxLength={1000} placeholder={tt("Spanish explanation","Explicación en español")} value={reason.es} onChange={event=>setReasons(current=>({...current,[key]:{...reason,es:event.target.value,reviewed:false}}))}/><label style={{fontSize:11}}><input type="checkbox" checked={reason.reviewed} onChange={event=>setReasons(current=>({...current,[key]:{...reason,reviewed:event.target.checked}}))}/> {tt("I reviewed this decision and bilingual explanation.","Revisé esta decisión y la explicación bilingüe.")}</label></div>}
      <div style={{display:"flex",justifyContent:"flex-end",gap:6,marginTop:10}}><Button type="button" size="sm" variant="ghost" disabled={draft[key]===undefined||busy!==null} onClick={()=>clear(key)}>{tt("Cancel","Cancelar")}</Button><Button type="button" size="sm" disabled={!canEdit||draft[key]===undefined||busy!==null||unavailable||!reasonReady} onClick={()=>save(entry,tab)}>{busy===key?tt("Saving…","Guardando…"):tt("Save","Guardar")}</Button></div>
    </article>})}</div>}
  </section>;
}
