import { useState } from "react";
import { Crop, Eye, EyeOff, Image, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { NormalizedCrop } from "./RfiImageCropEditor";

export function RfiImagePresentationControls({lang,imageUrl,label,crop,showInRfi,includeInCompletePdf,editable,canRestore,onCrop,onFullImage,onShowChange,onPdfChange,onRestore}:{lang:string;imageUrl?:string|null;label:string;crop?:NormalizedCrop|null;showInRfi:boolean;includeInCompletePdf:boolean;editable:boolean;canRestore?:boolean;onCrop?:()=>void;onFullImage?:()=>void;onShowChange?:(value:boolean)=>void;onPdfChange?:(value:boolean)=>void;onRestore?:()=>void}){
  const [imageSize,setImageSize]=useState<{width:number;height:number}|null>(null);
  const es=lang==="es";
  if(!imageUrl&&!label)return null;
  const cropRatio=crop&&imageSize?(crop.width*imageSize.width)/(crop.height*imageSize.height):null;
  const renderedImage=imageUrl&&showInRfi&&(crop&&cropRatio?<div style={{marginTop:10,display:"grid",placeItems:"center"}}><div style={{position:"relative",width:`min(100%, ${320*cropRatio}px)`,aspectRatio:String(cropRatio),overflow:"hidden",border:"1px solid hsl(var(--border))"}}><img src={imageUrl} alt={label} onLoad={e=>setImageSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} style={{position:"absolute",width:`${100/crop.width}%`,height:`${100/crop.height}%`,left:`${-crop.x/crop.width*100}%`,top:`${-crop.y/crop.height*100}%`,maxWidth:"none"}}/></div></div>:<div style={{marginTop:10,overflow:"hidden",maxHeight:320,border:"1px solid hsl(var(--border))"}}><img src={imageUrl} alt={label} onLoad={e=>setImageSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} style={{display:"block",maxWidth:"100%",maxHeight:320,objectFit:"contain",margin:"auto"}}/></div>);
  return <div style={{marginTop:10,padding:12,border:"1px solid hsl(var(--border))",borderRadius:6}}><div style={{display:"flex",alignItems:"center",gap:8,fontWeight:700}}><Image style={{width:16,height:16}}/>{label}{crop&&<span style={{fontSize:11,fontWeight:500,color:"hsl(var(--muted-foreground))"}}>{es?"Recorte guardado":"Saved crop"}</span>}{!showInRfi&&<span style={{fontSize:11,fontWeight:500,color:"hsl(var(--muted-foreground))"}}>{es?"Oculta del RFI":"Hidden from RFI"}</span>}</div>{renderedImage}<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{editable&&onCrop&&<Button type="button" size="sm" variant="outline" onClick={onCrop}><Crop style={{width:13,height:13}}/>{crop?(es?"Volver a Recortar":"Re-crop"):(es?"Recortar Imagen":"Crop Image")}</Button>}{editable&&crop&&onFullImage&&<Button type="button" size="sm" variant="outline" onClick={onFullImage}><RotateCcw style={{width:13,height:13}}/>{es?"Usar Imagen Completa":"Use Full Image"}</Button>}{editable&&onShowChange&&<Button type="button" size="sm" variant="outline" onClick={()=>onShowChange(!showInRfi)}>{showInRfi?<EyeOff style={{width:13,height:13}}/>:<Eye style={{width:13,height:13}}/>}{showInRfi?(es?"Ocultar en RFI":"Hide in RFI"):(es?"Mostrar en RFI":"Show in RFI")}</Button>}{editable&&canRestore&&onRestore&&<Button type="button" size="sm" variant="outline" onClick={onRestore}><RotateCcw style={{width:13,height:13}}/>{es?"Restaurar Imagen Original":"Restore Original Viewpoint Image"}</Button>}</div><label style={{display:"flex",gap:7,alignItems:"center",marginTop:10,fontSize:12}}><input type="checkbox" checked={includeInCompletePdf} disabled={!editable} onChange={e=>onPdfChange?.(e.target.checked)}/>{es?"Incluir imagen en PDF RFI Completo":"Include image in Complete RFI PDF"}</label></div>;
}
