import { useEffect, useMemo, useRef, useState, type KeyboardEvent, type PointerEvent } from "react";
import { Check, Crop, Maximize2, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";

export type NormalizedCrop = { x: number; y: number; width: number; height: number };
type Handle = "nw" | "n" | "ne" | "e" | "se" | "s" | "sw" | "w";
type Interaction = { kind: "draw" | "move" | "resize"; handle?: Handle; startX: number; startY: number; initial: NormalizedCrop | null };
const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));
const validCrop = (crop: NormalizedCrop | null) => !!crop && [crop.x, crop.y, crop.width, crop.height].every(Number.isFinite) && crop.width > 0 && crop.height > 0 && crop.x >= 0 && crop.y >= 0 && crop.x + crop.width <= 1.000001 && crop.y + crop.height <= 1.000001;

export function RfiImageSelectionSurface({ src, alt, value, onChange, naturalSize, onNaturalSize, lang }: { src:string; alt:string; value:NormalizedCrop|null; onChange:(crop:NormalizedCrop|null)=>void; naturalSize:{width:number;height:number}|null; onNaturalSize:(size:{width:number;height:number})=>void; lang:string }) {
  const imageRef=useRef<HTMLImageElement>(null); const [interaction,setInteraction]=useState<Interaction|null>(null); const es=lang==="es";
  const minimum=useMemo(()=>({x:8/Math.max(naturalSize?.width||8,8),y:8/Math.max(naturalSize?.height||8,8)}),[naturalSize]);
  const point=(clientX:number,clientY:number)=>{const rect=imageRef.current?.getBoundingClientRect();if(!rect||rect.width<=0||rect.height<=0)return null;return{x:clamp((clientX-rect.left)/rect.width),y:clamp((clientY-rect.top)/rect.height)};};
  const begin=(event:PointerEvent,kind:Interaction["kind"],handle?:Handle)=>{const p=point(event.clientX,event.clientY);if(!p)return;event.currentTarget.setPointerCapture(event.pointerId);setInteraction({kind,handle,startX:p.x,startY:p.y,initial:value});if(kind==="draw")onChange({x:Math.min(p.x,1-minimum.x),y:Math.min(p.y,1-minimum.y),width:minimum.x,height:minimum.y});};
  const move=(event:PointerEvent)=>{if(!interaction)return;const p=point(event.clientX,event.clientY);if(!p)return;const dx=p.x-interaction.startX,dy=p.y-interaction.startY;if(interaction.kind==="draw"){const x=Math.min(interaction.startX,p.x),y=Math.min(interaction.startY,p.y);onChange({x,y,width:Math.min(1-x,Math.max(minimum.x,Math.abs(p.x-interaction.startX))),height:Math.min(1-y,Math.max(minimum.y,Math.abs(p.y-interaction.startY)))});return;}if(!interaction.initial)return;if(interaction.kind==="move"){onChange({...interaction.initial,x:clamp(interaction.initial.x+dx,0,1-interaction.initial.width),y:clamp(interaction.initial.y+dy,0,1-interaction.initial.height)});return;}const next={...interaction.initial},handle=interaction.handle||"se";if(handle.includes("w")){const right=next.x+next.width;next.x=clamp(next.x+dx,0,right-minimum.x);next.width=right-next.x;}if(handle.includes("e"))next.width=clamp(next.width+dx,minimum.x,1-next.x);if(handle.includes("n")){const bottom=next.y+next.height;next.y=clamp(next.y+dy,0,bottom-minimum.y);next.height=bottom-next.y;}if(handle.includes("s"))next.height=clamp(next.height+dy,minimum.y,1-next.y);onChange(next);};
  const keyboardMove=(event:KeyboardEvent,handle?:Handle)=>{if(!value||!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key))return;event.preventDefault();const stepX=(event.shiftKey?10:1)/Math.max(naturalSize?.width||1,1),stepY=(event.shiftKey?10:1)/Math.max(naturalSize?.height||1,1),dx=event.key==="ArrowLeft"?-stepX:event.key==="ArrowRight"?stepX:0,dy=event.key==="ArrowUp"?-stepY:event.key==="ArrowDown"?stepY:0;if(!handle){onChange({...value,x:clamp(value.x+dx,0,1-value.width),y:clamp(value.y+dy,0,1-value.height)});return;}const next={...value};if(handle.includes("w")){const right=next.x+next.width;next.x=clamp(next.x+dx,0,right-minimum.x);next.width=right-next.x;}if(handle.includes("e"))next.width=clamp(next.width+dx,minimum.x,1-next.x);if(handle.includes("n")){const bottom=next.y+next.height;next.y=clamp(next.y+dy,0,bottom-minimum.y);next.height=bottom-next.y;}if(handle.includes("s"))next.height=clamp(next.height+dy,minimum.y,1-next.y);onChange(next);};
  const handles:Handle[]=["nw","n","ne","e","se","s","sw","w"];const position:Record<Handle,React.CSSProperties>={nw:{left:0,top:0},n:{left:"50%",top:0},ne:{right:0,top:0},e:{right:0,top:"50%"},se:{right:0,bottom:0},s:{left:"50%",bottom:0},sw:{left:0,bottom:0},w:{left:0,top:"50%"}};
  return <div style={{position:"relative",display:"inline-block",maxWidth:"100%",lineHeight:0,cursor:"crosshair",userSelect:"none"}} onPointerDown={e=>begin(e,"draw")} onPointerMove={move} onPointerUp={()=>setInteraction(null)} onPointerCancel={()=>setInteraction(null)}><img ref={imageRef} src={src} alt={alt} draggable={false} onLoad={e=>onNaturalSize({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight})} style={{display:"block",maxWidth:"100%",maxHeight:"62vh",objectFit:"contain"}}/>{value&&validCrop(value)&&<><div aria-hidden style={{position:"absolute",left:0,top:0,right:0,height:`${value.y*100}%`,background:"rgba(0,0,0,.58)"}}/><div aria-hidden style={{position:"absolute",left:0,top:`${value.y*100}%`,width:`${value.x*100}%`,height:`${value.height*100}%`,background:"rgba(0,0,0,.58)"}}/><div aria-hidden style={{position:"absolute",left:`${(value.x+value.width)*100}%`,right:0,top:`${value.y*100}%`,height:`${value.height*100}%`,background:"rgba(0,0,0,.58)"}}/><div aria-hidden style={{position:"absolute",left:0,top:`${(value.y+value.height)*100}%`,right:0,bottom:0,background:"rgba(0,0,0,.58)"}}/><div role="region" aria-label={es?"Selección de imagen":"Image selection"} tabIndex={0} onKeyDown={e=>keyboardMove(e)} onPointerDown={e=>{e.stopPropagation();begin(e,"move");}} style={{position:"absolute",left:`${value.x*100}%`,top:`${value.y*100}%`,width:`${value.width*100}%`,height:`${value.height*100}%`,border:"2px solid #38BDF8",boxShadow:"0 0 0 1px #082F49",cursor:"move",outlineOffset:3}}>{handles.map(handle=><button key={handle} type="button" aria-label={`${es?"Redimensionar":"Resize"} ${handle}`} onKeyDown={e=>keyboardMove(e,handle)} onPointerDown={e=>{e.stopPropagation();begin(e,"resize",handle);}} style={{position:"absolute",...position[handle],width:14,height:14,background:"#fff",border:"2px solid #0284C7",borderRadius:2,transform:"translate(-50%,-50%)",padding:0,cursor:`${handle}-resize`}}/>)}</div></>}</div>;
}

export function RfiImageCropEditor({src,fileName,initialCrop,lang,onApply,onCancel,onReplace,onRetake}:{src:string;fileName:string;initialCrop:NormalizedCrop|null;lang:string;onApply:(crop:NormalizedCrop|null)=>void;onCancel:()=>void;onReplace?:()=>void;onRetake?:()=>void}){
  const [selection,setSelection]=useState<NormalizedCrop|null>(initialCrop);const [size,setSize]=useState<{width:number;height:number}|null>(null);const confirming=useRef(false);const es=lang==="es";const commit=(crop:NormalizedCrop|null)=>{if(confirming.current)return;confirming.current=true;onApply(crop);};useEffect(()=>{const key=(e:globalThis.KeyboardEvent)=>{if(e.key==="Escape")onCancel();if(e.key==="Enter"&&validCrop(selection)&&!(e.target instanceof HTMLButtonElement))commit(selection);};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[selection,onCancel]);const pixels=selection&&size?{width:Math.round(selection.width*size.width),height:Math.round(selection.height*size.height)}:null;
  return <div role="dialog" aria-modal="true" aria-label={es?"Herramienta de recorte BIMLog":"BIMLog Crop Tool"} style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(3,7,18,.92)",display:"grid",gridTemplateRows:"auto 1fr auto",color:"white"}}><header style={{padding:"14px 18px",display:"flex",alignItems:"center",gap:10,borderBottom:"1px solid #334155"}}><Crop/><div><strong>{es?"Herramienta de Recorte BIMLog":"BIMLog Crop Tool"}</strong><div style={{fontSize:12,color:"#CBD5E1"}}>{fileName}</div></div><Button variant="outline" size="icon" onClick={onCancel} aria-label={es?"Cancelar":"Cancel"} style={{marginLeft:"auto"}}><X/></Button></header><main style={{overflow:"auto",padding:18,display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(220px,260px)",gap:18,alignItems:"start"}}><div style={{textAlign:"center"}}><p style={{fontSize:13,lineHeight:1.5}}>{es?"Arrastre para crear. Mueva dentro de la selección y use los controles para redimensionar.":"Drag to create. Move inside the selection and use the handles to resize."}</p><RfiImageSelectionSurface src={src} alt={es?"Imagen real para recortar":"Real image to crop"} value={selection} onChange={setSelection} naturalSize={size} onNaturalSize={setSize} lang={lang}/></div><aside><div aria-live="polite" aria-label={es?"Dimensiones seleccionadas":"Selected pixel dimensions"} style={{padding:12,border:"1px solid #475569",borderRadius:6}}><strong>{pixels?`${pixels.width} × ${pixels.height} px`:(es?"Dibuje una selección":"Draw a selection")}</strong></div>{selection&&pixels&&<div aria-label={es?"Vista previa recortada":"Cropped preview"} style={{position:"relative",width:"100%",aspectRatio:`${pixels.width} / ${pixels.height}`,maxHeight:180,overflow:"hidden",marginTop:12,border:"1px solid #475569",background:"#111827"}}><img src={src} alt="" style={{position:"absolute",width:`${100/selection.width}%`,height:`${100/selection.height}%`,left:`${-selection.x/selection.width*100}%`,top:`${-selection.y/selection.height*100}%`,maxWidth:"none"}}/></div>}</aside></main><footer style={{padding:14,display:"flex",gap:8,flexWrap:"wrap",borderTop:"1px solid #334155"}}><Button onClick={()=>selection&&commit(selection)} disabled={!validCrop(selection)}><Check/>{es?"Aplicar Recorte":"Apply Crop"}</Button><Button variant="outline" onClick={()=>commit(null)}><Maximize2/>{es?"Usar Imagen Completa":"Use Full Image"}</Button><Button variant="outline" onClick={()=>setSelection(initialCrop)}><RotateCcw/>{es?"Restablecer Selección":"Reset Selection"}</Button>{onReplace&&<Button variant="outline" onClick={onReplace}>{es?"Reemplazar Imagen":"Replace Image"}</Button>}{onRetake&&<Button variant="outline" onClick={onRetake}>{es?"Repetir Recorte de Pantalla":"Retake Snip"}</Button>}<Button variant="outline" onClick={onCancel}>{es?"Cancelar":"Cancel"}</Button></footer></div>;
}
