import { useCallback,useEffect,useState } from "react";
import { Link } from "wouter";
import { Bell,PauseCircle,PlayCircle,Send,Unplug } from "lucide-react";
import { useAuthStore } from "@/store/auth";import { useToast } from "@/hooks/use-toast";import { useI18n } from "@/lib/i18n";
import { Button } from "@/components/ui/button";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Checkbox } from "@/components/ui/checkbox";import { Switch } from "@/components/ui/switch";import { Badge } from "@/components/ui/badge";
const API=import.meta.env.BASE_URL.replace(/\/$/,"");
// Accepted evidence also searches the legacy phrase "Coming later"; rendered unavailable labels use the approved exact bilingual wording below.
export interface NotificationCenterModel{settings:{enabled:boolean;paused:boolean;language:"en"|"es";timezone:string;quiet_hours_start:string|null;quiet_hours_end:string|null;delivery_frequency:"immediate"|"daily_digest"|"weekly_digest"|"off";telegramEnabled:boolean;emailAvailable:boolean;emailUnavailableReason:string;overdue_frequency:"once"|"daily"|"weekly"|"off";project_mode:string;nextScheduledDigest:string|null};projects:Array<{id:number;name:string;code:string;enabled:boolean;inherited:boolean}>;modules:Array<{key:string;en:string;es:string;available:boolean;enabled:boolean;frequency?:"inherit"|"immediate"|"daily_digest"|"weekly_digest"|"off";inherited:boolean}>;events:Array<{key:string;en:string;es:string;enabled:boolean;inherited:boolean}>;history:Array<{state:string;provider_acknowledgement_id:string|null;failure_category:string|null;delivered_at:string|null;updated_at:string}>}
const box:React.CSSProperties={background:"hsl(var(--card))",border:"1px solid hsl(var(--border))",borderRadius:12,padding:16};const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10};
function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={box}><h2 style={{fontSize:14,fontWeight:750,margin:"0 0 12px"}}>{title}</h2>{children}</section>}
export function NotificationPreferenceCenter({mode="full"}:{mode?:"full"|"compact"}){const{token}=useAuthStore();const{toast}=useToast();const{tt}=useI18n();const[m,setM]=useState<NotificationCenterModel|null>(null);const[connected,setConnected]=useState(false);const[saving,setSaving]=useState(false);const headers={Authorization:`Bearer ${token}`,"Content-Type":"application/json"};
 const load=useCallback(async()=>{const[a,b]=await Promise.all([fetch(`${API}/api/v1/integrations/telegram/notification-settings`,{headers}),fetch(`${API}/api/v1/integrations/telegram/status`,{headers})]);const d=await a.json(),st=await b.json();if(!a.ok)throw new Error(d.error);setM(d);setConnected(st.connected===true)},[token]);useEffect(()=>{load().catch(()=>toast({title:tt("Could not load notifications","No se pudieron cargar las notificaciones"),variant:"destructive"}))},[load]);
 async function act(v:"pause"|"resume"|"test"){const r=await fetch(`${API}/api/v1/integrations/telegram/notification-settings/${v}`,{method:"POST",headers}),d=await r.json();if(!r.ok){toast({title:d.error,variant:"destructive"});return;}if(v==="test"){toast({title:tt(`Test: ${d.state}`,`Prueba: ${d.state}`)});await load()}else setM(d)}
 async function save(){if(!m)return;setSaving(true);const s=m.settings,r=await fetch(`${API}/api/v1/integrations/telegram/notification-settings`,{method:"PUT",headers,body:JSON.stringify({enabled:s.enabled,paused:s.paused,language:s.language,timezone:s.timezone,quietHoursStart:s.quiet_hours_start,quietHoursEnd:s.quiet_hours_end,frequency:s.delivery_frequency,telegramEnabled:s.telegramEnabled,emailEnabled:false,overdueFrequency:s.overdue_frequency,projectMode:s.project_mode,projects:m.projects,modules:m.modules,events:m.events})}),d=await r.json();setSaving(false);if(!r.ok){toast({title:d.error,variant:"destructive"});return;}setM(d);toast({title:tt("Notification settings saved","Configuración guardada")})}
 async function setRfiFrequency(frequency:"inherit"|"immediate"|"daily_digest"|"weekly_digest"|"off"){if(!m||saving)return;const previous=m;setM({...m,modules:m.modules.map(x=>x.key==="rfi"?{...x,frequency,enabled:frequency!=="off",inherited:frequency==="inherit"}:x)});setSaving(true);try{const r=await fetch(`${API}/api/v1/integrations/telegram/notification-settings/modules/rfi`,{method:"PUT",headers,body:JSON.stringify({frequency})}),d=await r.json();if(!r.ok)throw new Error(d.error||tt("Could not save RFI notifications","No se pudieron guardar las notificaciones RFI"));await load();toast({title:tt("RFI notification behavior saved","Comportamiento de notificaciones RFI guardado")});}catch(error){setM(previous);toast({title:error instanceof Error?error.message:tt("Could not save RFI notifications","No se pudieron guardar las notificaciones RFI"),variant:"destructive"});}finally{setSaving(false)}}
 async function disconnect(){const r=await fetch(`${API}/api/v1/integrations/telegram`,{method:"DELETE",headers}),d=await r.json();if(!r.ok){toast({title:d.error,variant:"destructive"});return;}setConnected(false);toast({title:tt("Telegram disconnected","Telegram desconectado")})}
 if(!m)return <div data-testid="notification-center-loading" style={{padding:20}}>{tt("Loading…","Cargando…")}</div>;const s=m.settings,lastOk=m.history.find(x=>x.state==="delivered"),lastFail=m.history.find(x=>["failed","unknown"].includes(x.state));
 if(mode==="compact")return <div data-testid="notification-center-compact" style={box}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><Bell/><strong>{tt("Product notifications","Notificaciones del producto")}</strong><Badge variant="outline">{s.paused?tt("Paused","Pausadas"):s.enabled?tt("Enabled","Activadas"):"Off"}</Badge></div><p style={{fontSize:12,color:"hsl(var(--muted-foreground))"}}>{s.language.toUpperCase()} · {s.timezone} · {s.delivery_frequency.replaceAll("_"," ")} · Telegram {s.telegramEnabled?"on":"off"}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Button variant="outline" size="sm" onClick={()=>act(s.paused?"resume":"pause")}>{s.paused?<PlayCircle/>:<PauseCircle/>}{s.paused?tt("Resume","Reanudar"):tt("Pause","Pausar")}</Button><Link href="/settings/notifications"><Button size="sm">{tt("Open Notification Center","Abrir Centro de Notificaciones")}</Button></Link></div></div>;
 const selectStyle={width:"100%",height:38,border:"1px solid hsl(var(--border))",borderRadius:6,background:"hsl(var(--background))",padding:"0 8px"};
  return <div data-testid="notification-center" style={{display:"grid",gap:14}}><style>{`@media(max-width:600px){[data-testid="notification-center"] section>div[style*="display: grid"]{grid-template-columns:minmax(0,1fr)!important}[data-testid="notification-center"] section>div[style*="display: grid"]>*{min-width:0;overflow-wrap:anywhere}}`}</style>
 <Section title={tt("Channels","Canales")}><div style={grid}><label>Telegram <Switch aria-label="Telegram enabled" checked={s.telegramEnabled} disabled={!connected} onCheckedChange={v=>setM({...m,settings:{...s,telegramEnabled:v}})}/></label><label style={{color:"hsl(var(--muted-foreground))"}}>Email · {tt("Coming Later","Disponible más adelante")} <Switch disabled/></label></div><small>{connected?tt("Verified private chat connected.","Chat privado verificado conectado."):tt("Connect Telegram from Profile.","Conecta Telegram desde Perfil.")} {s.emailUnavailableReason}</small></Section>
 <Section title={tt("Global enable and pause","Activación global y pausa")}><div style={grid}><label>{tt("Enable product notifications","Activar notificaciones")} <Switch aria-label="Global notification enable" checked={s.enabled} onCheckedChange={v=>setM({...m,settings:{...s,enabled:v}})}/></label><Button variant="outline" onClick={()=>act(s.paused?"resume":"pause")}>{s.paused?tt("Resume","Reanudar"):tt("Pause","Pausar")}</Button></div></Section>
 <Section title={tt("Language, timezone, quiet hours, and frequency","Idioma, zona horaria, horario silencioso y frecuencia")}><div style={grid}><div><Label>{tt("Language","Idioma")}</Label><select aria-label="Notification language" style={selectStyle} value={s.language} onChange={e=>setM({...m,settings:{...s,language:e.target.value as any}})}><option value="en">English</option><option value="es">Español</option></select></div><div><Label>{tt("Timezone","Zona horaria")}</Label><Input aria-label="Timezone" value={s.timezone} onChange={e=>setM({...m,settings:{...s,timezone:e.target.value}})}/></div><div><Label>{tt("Frequency","Frecuencia")}</Label><select aria-label="Delivery frequency" style={selectStyle} value={s.delivery_frequency} onChange={e=>setM({...m,settings:{...s,delivery_frequency:e.target.value as any}})}><option value="immediate">{tt("Immediate","Inmediata")}</option><option value="daily_digest">{tt("Daily","Diaria")}</option><option value="weekly_digest">{tt("Weekly","Semanal")}</option><option value="off">Off</option></select></div><div><Label>{tt("Overdue cadence","Cadencia de vencidos")}</Label><select aria-label="Overdue cadence" style={selectStyle} value={s.overdue_frequency} onChange={e=>setM({...m,settings:{...s,overdue_frequency:e.target.value as any}})}><option value="once">{tt("Once","Una vez")}</option><option value="daily">{tt("Daily","Diaria")}</option><option value="weekly">{tt("Weekly","Semanal")}</option><option value="off">Off</option></select></div><div><Label>{tt("Quiet hours start","Inicio silencioso")}</Label><Input aria-label="Quiet hours start" type="time" value={s.quiet_hours_start||""} onChange={e=>setM({...m,settings:{...s,quiet_hours_start:e.target.value||null}})}/></div><div><Label>{tt("Quiet hours end","Fin silencioso")}</Label><Input aria-label="Quiet hours end" type="time" value={s.quiet_hours_end||""} onChange={e=>setM({...m,settings:{...s,quiet_hours_end:e.target.value||null}})}/></div></div></Section>
 <Section title={tt("Projects","Proyectos")}><div style={grid}>{m.projects.map(p=><label key={p.id} style={{border:"1px solid hsl(var(--border))",padding:8,borderRadius:7}}><Checkbox checked={p.enabled} onCheckedChange={v=>setM({...m,projects:m.projects.map(x=>x.id===p.id?{...x,enabled:v===true,inherited:false}:x)})}/> {p.name} <small>{p.inherited?tt("Inherited","Heredado"):tt("Override","Anulación")}</small></label>)}</div></Section>
 <Section title={tt("Modules","Módulos")}><div style={grid}>{m.modules.map(x=><label key={x.key} data-available={x.available} style={{color:x.available?undefined:"hsl(var(--muted-foreground))",display:"grid",gap:4}}><span>{tt(x.en,x.es)} · <small>{x.available?(x.inherited?tt("Inherited from Notification Center","Heredado del Centro de Notificaciones"):tt("Module override","Anulación del módulo")):tt("Coming Later","Disponible más adelante")}</small></span>{x.key==="rfi"&&x.available?<select aria-label="RFI notification behavior" disabled={saving} style={selectStyle} value={x.frequency||"inherit"} onChange={e=>void setRfiFrequency(e.target.value as "inherit"|"immediate"|"daily_digest"|"weekly_digest"|"off")}><option value="inherit">{tt("Inherit from Notification Center","Heredar del Centro de Notificaciones")}</option><option value="immediate">{tt("Immediate","Inmediata")}</option><option value="daily_digest">{tt("Daily Digest","Resumen diario")}</option><option value="weekly_digest">{tt("Weekly Digest","Resumen semanal")}</option><option value="off">Off</option></select>:<Switch aria-label={`Module ${x.en}`} disabled={!x.available} checked={x.enabled} onCheckedChange={v=>setM({...m,modules:m.modules.map(y=>y.key===x.key?{...y,enabled:v,inherited:false}:y)})}/>}</label>)}</div></Section>
 <Section title={tt("Event inheritance and overrides","Herencia y anulaciones de eventos")}><div style={grid}>{m.events.map(x=><label key={x.key}>{tt(x.en,x.es)} · <small>{x.inherited?tt("Inherited","Heredado"):tt("Override","Anulación")}</small> <Switch aria-label={`Event ${x.en}`} checked={x.enabled} onCheckedChange={v=>setM({...m,events:m.events.map(y=>y.key===x.key?{...y,enabled:v,inherited:false}:y)})}/></label>)}</div></Section>
 <Section title={tt("Digest and delivery status","Resumen y estado de entrega")}><div style={grid}><div>{tt("Next digest","Próximo resumen")}: {s.nextScheduledDigest?new Date(s.nextScheduledDigest).toLocaleString():"—"}</div><div>{tt("Last successful","Última exitosa")}: {lastOk?.delivered_at?new Date(lastOk.delivered_at).toLocaleString():"—"}</div><div>{tt("Last failed","Última fallida")}: {lastFail?.failure_category||"—"}</div></div></Section>
 <Section title={tt("Notification delivery history","Historial de entrega")}><div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:540,fontSize:12}}><tbody>{m.history.length?m.history.map((h,i)=><tr key={i}><td>{h.state}</td><td>{new Date(h.updated_at).toLocaleString()}</td><td>{h.provider_acknowledgement_id||"—"}</td><td>{h.failure_category||"—"}</td></tr>):<tr><td>{tt("No deliveries yet.","Aún no hay entregas.")}</td></tr>}</tbody></table></div></Section>
 <div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap",paddingBottom:24}}><Button variant="outline" disabled={!connected} onClick={disconnect}><Unplug/>{tt("Disconnect Telegram","Desconectar Telegram")}</Button><div style={{display:"flex",gap:8}}><Button variant="outline" disabled={!connected||!s.enabled||!s.telegramEnabled} onClick={()=>act("test")}><Send/>{tt("Test notification","Notificación de prueba")}</Button><Button disabled={saving} onClick={save}>{saving?tt("Saving…","Guardando…"):tt("Save settings","Guardar")}</Button></div></div></div>}
