import {useEffect,useState} from "react";
import {CheckCircle2,RefreshCw,TriangleAlert} from "lucide-react";
import {parseCommercialLaunch,parseCommercialLiveVerification,type CommercialLaunchDto,type CommercialLiveVerificationDto} from "@/lib/commercial-launch-client";
const API_BASE=(import.meta.env.VITE_API_URL as string|undefined)??"";

export function CommercialLaunchPanel({token}:{token:string}){
  const spanish=typeof window!=="undefined"&&localStorage.getItem("bimlog-lang")==="es",t=(en:string,es:string)=>spanish?es:en;
  const [data,setData]=useState<CommercialLaunchDto|null>(null),[error,setError]=useState(""),[nonce,setNonce]=useState(0),[live,setLive]=useState<CommercialLiveVerificationDto|null>(null),[verifying,setVerifying]=useState(false);
  useEffect(()=>{const controller=new AbortController();setError("");fetch(`${API_BASE}/api/v1/admin/commercial-launch`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Commercial launch status unavailable");return parseCommercialLaunch(body);}).then(setData).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));});return()=>controller.abort();},[token,nonce]);
  const verify=async()=>{setVerifying(true);setError("");try{const response=await fetch(`${API_BASE}/api/v1/admin/commercial-launch/verify`,{method:"POST",headers:{Authorization:`Bearer ${token}`}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Live verification unavailable");setLive(parseCommercialLiveVerification(body));}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setVerifying(false);}};
  return <section aria-labelledby="commercial-launch-heading"><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12,flexWrap:"wrap"}}><div><h2 id="commercial-launch-heading" style={{margin:"0 0 6px"}}>{t("Commercial launch activation","Activación del lanzamiento comercial")}</h2><p style={{margin:0,color:"#64748B"}}>{t("BIMLog-owned production services required before customers can buy subscriptions.","Servicios de producción administrados por BIMLog requeridos antes de vender suscripciones.")}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={!data?.ready||verifying} onClick={()=>void verify()} style={{padding:"8px 12px",border:"1px solid #1D4ED8",borderRadius:8,background:data?.ready?"#1D4ED8":"#E2E8F0",color:data?.ready?"white":"#64748B",cursor:data?.ready?"pointer":"not-allowed"}}>{verifying?t("Verifying…","Verificando…"):t("Verify live services","Verificar servicios reales")}</button><button onClick={()=>setNonce(value=>value+1)} style={{display:"inline-flex",gap:6,alignItems:"center",padding:"8px 12px",border:"1px solid #CBD5E1",borderRadius:8,background:"white",cursor:"pointer"}}><RefreshCw size={15}/>{t("Refresh","Actualizar")}</button></div></div>
    {error&&<div role="alert" style={{marginTop:16,padding:14,border:"1px solid #FCA5A5",background:"#FEF2F2",borderRadius:10}}>{error}</div>}
    {!data&&!error&&<div role="status" style={{padding:"24px 0",color:"#64748B"}}>{t("Checking launch services…","Verificando servicios de lanzamiento…")}</div>}
    {live&&<div role="status" style={{marginTop:16,padding:16,border:`1px solid ${live.verified?"#86EFAC":"#FCA5A5"}`,background:live.verified?"#F0FDF4":"#FEF2F2",borderRadius:12}}><strong>{live.verified?t("Live provider verification passed","Verificación real de proveedores aprobada"):t("Live provider verification failed","Falló la verificación real de proveedores")}</strong>{live.evidence?<div style={{fontSize:12,color:"#475569",marginTop:6,overflowWrap:"anywhere"}}>{t("Bound source","Fuente vinculada")}: <code>{live.evidence.sourceCommit.slice(0,12)}</code> · {t("Valid until","Válido hasta")}: {new Date(live.evidence.validUntil).toLocaleString()} · {t("Evidence","Evidencia")}: <code>{live.evidence.evidenceSha256.slice(0,12)}</code></div>:<div style={{fontSize:12,color:"#B45309",marginTop:6}}>{t("No source-bound evidence was issued.","No se emitió evidencia vinculada a la fuente.")}</div>}<ul style={{marginBottom:0}}>{live.checks.map(check=><li key={check.id}>{check.id}: {check.status==="verified"?t("Verified","Verificado"):t("Failed","Falló")} ({check.code})</li>)}</ul></div>}
    {data&&<><div role="status" style={{marginTop:16,padding:16,border:`1px solid ${data.ready?"#86EFAC":"#FDE68A"}`,background:data.ready?"#F0FDF4":"#FFFBEB",borderRadius:12}}><strong>{data.ready?t("Ready to sell live subscriptions","Listo para vender suscripciones reales"):t(`${data.requiredActionCount} launch actions remaining`,`${data.requiredActionCount} acciones de lanzamiento pendientes`)}</strong><div style={{fontSize:13,color:"#64748B",marginTop:4}}>{t(`Payment mode: ${data.providerMode}`,`Modo de pago: ${data.providerMode}`)}</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(280px,100%),1fr))",gap:12,marginTop:14}}>{data.steps.map(step=><article key={step.id} style={{padding:14,border:"1px solid #E2E8F0",borderRadius:10,background:"white"}}><div style={{display:"flex",gap:8,alignItems:"start"}}>{step.status==="ready"?<CheckCircle2 size={18} color="#047857"/>:<TriangleAlert size={18} color="#B45309"/>}<div><strong>{step.title}</strong><div style={{fontSize:12,color:"#64748B",marginTop:6}}>{step.status==="ready"?t("Ready","Listo"):t("BIMLog action required","Acción requerida de BIMLog")}</div>{step.status!=="ready"&&<code style={{display:"block",fontSize:11,whiteSpace:"normal",overflowWrap:"anywhere",marginTop:8}}>{step.configurationKeys.join(" · ")}</code>}</div></div></article>)}</div></>}
  </section>;
}
