import {useEffect,useState} from "react";
import {CheckCircle2,RefreshCw,TriangleAlert} from "lucide-react";
import {evaluateCommercialVerificationEvidence,parseCommercialLaunch,parseCommercialLaunchAuthorization,parseCommercialLaunchDossier,parseCommercialVerificationHistory,type CommercialEvidenceDecision,type CommercialHealthIdentityDto,type CommercialLaunchAuthorizationDto,type CommercialLaunchDossierDto,type CommercialLaunchDto,type CommercialLiveVerificationDto,type CommercialVerificationHistoryItem} from "@/lib/commercial-launch-client";
import {verifyCommercialLaunchForLiveSource} from "@/lib/commercial-launch-verification-workflow";
const API_BASE=(import.meta.env.VITE_API_URL as string|undefined)??"";

export function CommercialLaunchPanel({token}:{token:string}){
  const spanish=typeof window!=="undefined"&&localStorage.getItem("bimlog-lang")==="es",t=(en:string,es:string)=>spanish?es:en;
  const [data,setData]=useState<CommercialLaunchDto|null>(null),[dossier,setDossier]=useState<CommercialLaunchDossierDto|null>(null),[authorization,setAuthorization]=useState<CommercialLaunchAuthorizationDto|null>(null),[history,setHistory]=useState<CommercialVerificationHistoryItem[]>([]),[error,setError]=useState(""),[nonce,setNonce]=useState(0),[live,setLive]=useState<CommercialLiveVerificationDto|null>(null),[identity,setIdentity]=useState<CommercialHealthIdentityDto|null>(null),[decision,setDecision]=useState<CommercialEvidenceDecision|null>(null),[verifying,setVerifying]=useState(false);
  useEffect(()=>{const controller=new AbortController();setError("");fetch(`${API_BASE}/api/v1/admin/commercial-launch`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Commercial launch status unavailable");return parseCommercialLaunch(body);}).then(setData).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));});return()=>controller.abort();},[token,nonce]);
  useEffect(()=>{const controller=new AbortController();fetch(`${API_BASE}/api/v1/admin/commercial-launch/verifications`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Commercial verification history unavailable");return parseCommercialVerificationHistory(body);}).then(setHistory).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));});return()=>controller.abort();},[token,nonce]);
  useEffect(()=>{const controller=new AbortController();fetch(`${API_BASE}/api/v1/admin/commercial-launch/authorization`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Commercial launch authorization unavailable");return parseCommercialLaunchAuthorization(body);}).then(setAuthorization).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));});return()=>controller.abort();},[token,nonce]);
  useEffect(()=>{const controller=new AbortController();fetch(`${API_BASE}/api/v1/admin/commercial-launch/dossier`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:"Commercial launch dossier unavailable");return parseCommercialLaunchDossier(body);}).then(setDossier).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));});return()=>controller.abort();},[token,nonce]);
  useEffect(()=>{if(!live?.evidence||!identity)return;const expire=()=>setDecision(evaluateCommercialVerificationEvidence(live,identity.sourceCommit));const delay=Math.max(0,Date.parse(live.evidence.validUntil)-Date.now()+50),timer=window.setTimeout(expire,Math.min(delay,2_147_483_647));return()=>window.clearTimeout(timer);},[live,identity]);
  const verify=async()=>{setVerifying(true);setError("");try{const result=await verifyCommercialLaunchForLiveSource({apiBase:API_BASE,token});setLive(result.live);setIdentity(result.identity);setDecision(result.decision);setNonce(value=>value+1);}catch(reason){setError(reason instanceof Error?reason.message:String(reason));setDecision(null);}finally{setVerifying(false);}};
  const verificationReady=decision?.ready===true;
  return <section aria-labelledby="commercial-launch-heading"><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12,flexWrap:"wrap"}}><div><h2 id="commercial-launch-heading" style={{margin:"0 0 6px"}}>{t("Commercial launch activation","Activación del lanzamiento comercial")}</h2><p style={{margin:0,color:"#64748B"}}>{t("BIMLog-owned production services required before customers can buy subscriptions.","Servicios de producción administrados por BIMLog requeridos antes de vender suscripciones.")}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={!data?.ready||verifying} onClick={()=>void verify()} style={{padding:"8px 12px",border:"1px solid #1D4ED8",borderRadius:8,background:data?.ready?"#1D4ED8":"#E2E8F0",color:data?.ready?"white":"#64748B",cursor:data?.ready?"pointer":"not-allowed"}}>{verifying?t("Verifying…","Verificando…"):t("Verify live services","Verificar servicios reales")}</button><button onClick={()=>setNonce(value=>value+1)} style={{display:"inline-flex",gap:6,alignItems:"center",padding:"8px 12px",border:"1px solid #CBD5E1",borderRadius:8,background:"white",cursor:"pointer"}}><RefreshCw size={15}/>{t("Refresh","Actualizar")}</button></div></div>
    {error&&<div role="alert" style={{marginTop:16,padding:14,border:"1px solid #FCA5A5",background:"#FEF2F2",borderRadius:10}}>{error}</div>}
    {!data&&!error&&<div role="status" style={{padding:"24px 0",color:"#64748B"}}>{t("Checking launch services…","Verificando servicios de lanzamiento…")}</div>}
    {live&&<div role="status" style={{marginTop:16,padding:16,border:`1px solid ${verificationReady?"#86EFAC":"#FCA5A5"}`,background:verificationReady?"#F0FDF4":"#FEF2F2",borderRadius:12}}><strong>{verificationReady?t("Current live provider verification passed","Verificación vigente de proveedores reales aprobada"):t("Live provider verification is not current","La verificación de proveedores reales no está vigente")}</strong>{decision&&!verificationReady&&<div style={{fontSize:12,color:"#B45309",marginTop:6}}>{t(`Evidence status: ${decision.status}. Run verification again.`,`Estado de evidencia: ${decision.status}. Ejecute la verificación nuevamente.`)}</div>}{live.evidence?<div style={{fontSize:12,color:"#475569",marginTop:6,overflowWrap:"anywhere"}}>{t("Bound source","Fuente vinculada")}: <code>{live.evidence.sourceCommit.slice(0,12)}</code> · {t("Live source","Fuente activa")}: <code>{identity?.sourceCommit.slice(0,12)??"—"}</code> · {t("Valid until","Válido hasta")}: {new Date(live.evidence.validUntil).toLocaleString()} · {t("Evidence","Evidencia")}: <code>{live.evidence.evidenceSha256.slice(0,12)}</code></div>:<div style={{fontSize:12,color:"#B45309",marginTop:6}}>{t("No source-bound evidence was issued.","No se emitió evidencia vinculada a la fuente.")}</div>}<ul style={{marginBottom:0}}>{live.checks.map(check=><li key={check.id}>{check.id}: {check.status==="verified"?t("Verified","Verificado"):t("Failed","Falló")} ({check.code})</li>)}</ul></div>}
    {data&&<><div role="status" style={{marginTop:16,padding:16,border:`1px solid ${data.ready?"#86EFAC":"#FDE68A"}`,background:data.ready?"#F0FDF4":"#FFFBEB",borderRadius:12}}><strong>{data.ready?t("Ready to sell live subscriptions","Listo para vender suscripciones reales"):t(`${data.requiredActionCount} launch actions remaining`,`${data.requiredActionCount} acciones de lanzamiento pendientes`)}</strong><div style={{fontSize:13,color:"#64748B",marginTop:4}}>{t(`Payment mode: ${data.providerMode}`,`Modo de pago: ${data.providerMode}`)}</div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(280px,100%),1fr))",gap:12,marginTop:14}}>{data.steps.map(step=><article key={step.id} style={{padding:14,border:"1px solid #E2E8F0",borderRadius:10,background:"white"}}><div style={{display:"flex",gap:8,alignItems:"start"}}>{step.status==="ready"?<CheckCircle2 size={18} color="#047857"/>:<TriangleAlert size={18} color="#B45309"/>}<div><strong>{step.title}</strong><div style={{fontSize:12,color:"#64748B",marginTop:6}}>{step.status==="ready"?t("Ready","Listo"):t("BIMLog action required","Acción requerida de BIMLog")}</div>{step.status!=="ready"&&<code style={{display:"block",fontSize:11,whiteSpace:"normal",overflowWrap:"anywhere",marginTop:8}}>{step.configurationKeys.join(" · ")}</code>}</div></div></article>)}</div></>}
    {dossier&&<section aria-labelledby="commercial-launch-dossier" style={{marginTop:20,padding:16,border:"1px solid #CBD5E1",borderRadius:12,background:"#F8FAFC"}}><h3 id="commercial-launch-dossier" style={{marginTop:0}}>{t("Launch dossier","Expediente de lanzamiento")}</h3><p style={{color:"#475569"}}>{t("One source-bound decision across verified supplier identity, commercial services and current provider evidence.","Una decisión vinculada a la fuente para identidad verificada del proveedor, servicios comerciales y evidencia vigente de proveedores.")}</p><div role="status" style={{fontWeight:700,color:dossier.ready?"#047857":"#B45309"}}>{dossier.ready?t("Complete — commercial launch may proceed","Completo — el lanzamiento comercial puede continuar"):t(`${dossier.blockerCount} dossier blockers remain`,`${dossier.blockerCount} bloqueos permanecen en el expediente`)}</div><dl style={{display:"grid",gridTemplateColumns:"minmax(140px,1fr) minmax(180px,2fr)",gap:"8px 12px",marginBottom:0}}><dt>{t("Supplier","Proveedor")}</dt><dd>{dossier.profile.supplierName??t("Not configured","No configurado")}</dd><dt>{t("Registration / tax identity","Registro / identidad fiscal")}</dt><dd>{dossier.profile.registrationNumber&&dossier.profile.taxIdentifier?`${dossier.profile.registrationNumber} · ${dossier.profile.taxIdentifier}`:t("Incomplete","Incompleta")}</dd><dt>{t("Invoice jurisdiction","Jurisdicción de facturación")}</dt><dd>{dossier.profile.invoiceJurisdiction??t("Not configured","No configurada")}</dd><dt>{t("Billing and support","Facturación y soporte")}</dt><dd>{[dossier.profile.billingEmail,dossier.profile.supportEmail].filter(Boolean).join(" · ")||t("Not configured","No configurado")}</dd><dt>{t("Deployed source","Fuente desplegada")}</dt><dd><code>{dossier.sourceCommit.slice(0,12)}</code></dd></dl>{dossier.missingConfigurationKeys.length>0&&<div style={{marginTop:12,fontSize:12,color:"#92400E"}}><strong>{t("BIMLog configuration required","Configuración de BIMLog requerida")}:</strong> <code style={{overflowWrap:"anywhere"}}>{dossier.missingConfigurationKeys.join(" · ")}</code></div>}</section>}
    {authorization&&<div role="status" style={{marginTop:20,padding:16,border:`1px solid ${authorization.ready?"#86EFAC":"#FDE68A"}`,background:authorization.ready?"#F0FDF4":"#FFFBEB",borderRadius:12}}><strong>{authorization.ready?t("Commercial launch currently authorized","Lanzamiento comercial autorizado actualmente"):t("Commercial launch is not currently authorized","El lanzamiento comercial no está autorizado actualmente")}</strong><div style={{fontSize:12,color:"#64748B",marginTop:6}}>{t("Authorization status","Estado de autorización")}: {authorization.status} · {t("Deployed source","Fuente desplegada")}: <code>{authorization.sourceCommit.slice(0,12)}</code></div></div>}
    <section aria-labelledby="commercial-verification-history" style={{marginTop:20}}><h3 id="commercial-verification-history">{t("Verification history","Historial de verificaciones")}</h3>{history.length===0?<p style={{color:"#64748B"}}>{t("No durable verification receipts recorded yet.","Todavía no hay comprobantes duraderos de verificación.")}</p>:<ol style={{paddingLeft:20}}>{history.map(item=>{const isCurrent=authorization?.ready===true&&authorization.receipt?.id===item.id;return <li key={item.id} style={{marginBottom:10}}><strong>{isCurrent?t("Current authorization","Autorización vigente"):item.verified?t("Historical verification","Verificación histórica"):t("Not verified","No verificado")}</strong> · {new Date(item.checkedAt).toLocaleString()}<div style={{fontSize:12,color:"#64748B",overflowWrap:"anywhere"}}>{t("Source","Fuente")}: <code>{item.sourceCommit.slice(0,12)}</code> · {t("Evidence","Evidencia")}: <code>{item.evidenceSha256.slice(0,12)}</code></div></li>;})}</ol>}</section>
  </section>;
}
