import {useCallback,useEffect,useState} from "react";
import {parseSalesInquiryList,SALES_INQUIRY_STATUSES,type SalesInquiry,type SalesInquiryStatus} from "@/lib/sales-inquiry-client";

const API_BASE=(import.meta.env.VITE_API_URL as string|undefined)??"";
const statusColor:Record<SalesInquiryStatus,string>={new:"#2563eb",acknowledged:"#d97706",qualified:"#16a34a",closed:"#64748b"};
const nextStatuses:Record<SalesInquiryStatus,readonly SalesInquiryStatus[]>={new:["acknowledged","qualified","closed"],acknowledged:["qualified","closed"],qualified:["closed"],closed:[]};

export function SalesInquiryQueue({token}:{token:string}){
  const es=typeof window!=="undefined"&&localStorage.getItem("bimlog-lang")==="es";
  const copy=es?{title:"Consultas comerciales",subtitle:"Solicitudes de precios y contacto guardadas por BIMLog.",status:"Estado",all:"Todas",refresh:"Actualizar",loading:"Cargando consultas…",empty:"Ninguna consulta coincide con este estado.",received:"Recibida",contact:"Contacto",company:"Compañía",interest:"Interés",action:"Acción",review:"Revisar",close:"Cerrar",country:"País",plan:"Plan",useCase:"Caso de uso",message:"Mensaje",notSelected:"No seleccionado",notProvided:"No proporcionado",mark:"Marcar",closed:"Esta consulta está cerrada."}:{title:"Sales inquiries",subtitle:"Pricing and contact requests saved by BIMLog.",status:"Status",all:"All",refresh:"Refresh",loading:"Loading sales inquiries…",empty:"No inquiries match this status.",received:"Received",contact:"Contact",company:"Company",interest:"Interest",action:"Action",review:"Review",close:"Close",country:"Country",plan:"Plan",useCase:"Use case",message:"Message",notSelected:"Not selected",notProvided:"Not provided",mark:"Mark",closed:"This inquiry is closed."};
  const [items,setItems]=useState<SalesInquiry[]>([]),[status,setStatus]=useState<""|SalesInquiryStatus>("");
  const [selected,setSelected]=useState<SalesInquiry|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState("");
  const [updating,setUpdating]=useState(false),[actionError,setActionError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const query=status?`?status=${status}`:"";const response=await fetch(`${API_BASE}/api/v1/admin/sales-inquiries${query}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("request_failed");setItems(parseSalesInquiryList(await response.json()).items);}catch{setError("Sales inquiries could not be loaded.");}finally{setLoading(false);}},[status,token]);
  useEffect(()=>{void load();},[load]);
  const transition=async(nextStatus:SalesInquiryStatus)=>{if(!selected||!nextStatuses[selected.status].includes(nextStatus))return;setUpdating(true);setActionError("");try{const response=await fetch(`${API_BASE}/api/v1/admin/sales-inquiries/${selected.id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({expectedStatus:selected.status,status:nextStatus})});if(response.status===409){setActionError("This inquiry changed in another session. Refresh and review it again.");await load();return;}if(!response.ok)throw new Error("transition_failed");const result=await response.json() as {status?:unknown;updatedAt?:unknown};if(result.status!==nextStatus||typeof result.updatedAt!=="string")throw new Error("invalid_transition_response");const updated={...selected,status:nextStatus,updatedAt:result.updatedAt};setSelected(updated);setItems(current=>current.map(item=>item.id===updated.id?updated:item));}catch{setActionError("The inquiry status could not be updated.");}finally{setUpdating(false);}};
  return <section aria-labelledby="sales-inquiry-queue-title" data-testid="sales-inquiry-queue">
    <div style={{display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",marginBottom:16}}>
      <div><h2 id="sales-inquiry-queue-title" style={{margin:0,fontSize:20}}>{copy.title}</h2><p style={{margin:"4px 0 0",color:"#64748b",fontSize:13}}>{copy.subtitle}</p></div>
      <div style={{display:"flex",gap:8}}><label style={{fontSize:12,fontWeight:700}}>{copy.status} <select aria-label="Filter sales inquiries by status" value={status} onChange={event=>setStatus(event.target.value as ""|SalesInquiryStatus)} style={{marginLeft:6,padding:"7px 10px",border:"1px solid #cbd5e1",borderRadius:7}}><option value="">{copy.all}</option>{SALES_INQUIRY_STATUSES.map(value=><option key={value} value={value}>{value}</option>)}</select></label><button onClick={()=>void load()} style={{padding:"7px 12px",border:"1px solid #cbd5e1",borderRadius:7,background:"white"}}>{copy.refresh}</button></div>
    </div>
    {loading&&<p role="status">{copy.loading}</p>}
    {error&&<div role="alert" style={{padding:12,border:"1px solid #fecaca",borderRadius:8,color:"#b91c1c"}}>{error} <button onClick={()=>void load()}>Retry</button></div>}
    {!loading&&!error&&items.length===0&&<p style={{padding:20,border:"1px dashed #cbd5e1",borderRadius:10}}>{copy.empty}</p>}
    {!loading&&!error&&items.length>0&&<div style={{overflowX:"auto",border:"1px solid #e2e8f0",borderRadius:10}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:760}}><thead><tr><th>{copy.received}</th><th>{copy.contact}</th><th>{copy.company}</th><th>{copy.interest}</th><th>{copy.status}</th><th>{copy.action}</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.createdAt).toLocaleString()}</td><td><strong>{item.fullName}</strong><br/><span>{item.email}</span></td><td>{item.companyName}<br/><span>{item.country}</span></td><td>{item.plan?[item.plan,item.billingCycle].filter(Boolean).join(" · "):item.interest}</td><td><span style={{color:statusColor[item.status],fontWeight:800}}>{item.status}</span></td><td><button onClick={()=>setSelected(item)} aria-label={`${copy.review} ${item.fullName}`}>{copy.review}</button></td></tr>)}</tbody></table></div>}
    {selected&&<div role="dialog" aria-modal="true" aria-labelledby="sales-inquiry-detail-title" style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(15,23,42,.55)",display:"grid",placeItems:"center",padding:16}}><article style={{width:"min(680px,100%)",maxHeight:"85vh",overflowY:"auto",background:"white",borderRadius:14,padding:24,boxSizing:"border-box"}}><div style={{display:"flex",justifyContent:"space-between",gap:16}}><div><p style={{margin:0,color:"#64748b",fontSize:12}}>Inquiry #{selected.id}</p><h3 id="sales-inquiry-detail-title" style={{margin:"4px 0"}}>{selected.fullName} · {selected.companyName}</h3></div><button onClick={()=>setSelected(null)}>{copy.close}</button></div><dl style={{display:"grid",gridTemplateColumns:"minmax(110px,auto) minmax(0,1fr)",gap:"10px 16px",marginTop:20}}><dt>Email</dt><dd style={{margin:0,overflowWrap:"anywhere"}}>{selected.email}</dd><dt>{copy.country}</dt><dd style={{margin:0}}>{selected.country}</dd><dt>{copy.interest}</dt><dd style={{margin:0}}>{selected.interest}</dd><dt>{copy.plan}</dt><dd style={{margin:0}}>{[selected.plan,selected.billingCycle].filter(Boolean).join(" · ")||copy.notSelected}</dd><dt>{copy.useCase}</dt><dd style={{margin:0}}>{selected.useCase||copy.notProvided}</dd><dt>{copy.message}</dt><dd style={{margin:0,whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{selected.message}</dd></dl>{actionError&&<p role="alert" style={{color:"#b91c1c"}}>{actionError}</p>}<div aria-label="Inquiry status actions" style={{display:"flex",flexWrap:"wrap",gap:8,marginTop:20}}>{nextStatuses[selected.status].map(next=><button key={next} disabled={updating} onClick={()=>void transition(next)} style={{padding:"8px 12px"}}>{copy.mark} {next}</button>)}{nextStatuses[selected.status].length===0&&<span style={{color:"#64748b"}}>{copy.closed}</span>}</div></article></div>}
  </section>;
}
