import {FormEvent,useCallback,useEffect,useState} from "react";
import {parseAdminSupportCases,type AdminSupportCase,type AdminSupportCasePage} from "@/lib/support-case-admin-client";import {SupportConversation} from "@/components/commercial/SupportConversation";
const API_BASE=import.meta.env.VITE_API_URL??"",LIMIT=25;
type Scope="all"|"urgent"|"waiting"|"resolved";type Assignment="all"|"mine"|"unassigned";

export function SupportCaseQueue({token}:{token:string}){
 const es=typeof window!=="undefined"&&localStorage.getItem("bimlog-lang")==="es";
 const [page,setPage]=useState<AdminSupportCasePage>({items:[],limit:LIMIT,offset:0,total:0}),[scope,setScope]=useState<Scope>("all"),[assignment,setAssignment]=useState<Assignment>("all"),[overdueOnly,setOverdueOnly]=useState(false),[searchDraft,setSearchDraft]=useState(""),[search,setSearch]=useState(""),[offset,setOffset]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updating,setUpdating]=useState<number|null>(null),[openCase,setOpenCase]=useState<number|null>(null);
 const copy=es?{title:"Servicio al cliente",subtitle:"Casos enviados por clientes de todas las compañías.",all:"Todos",urgent:"Urgentes",waiting:"En espera",resolved:"Resueltos",empty:"No hay casos en esta vista.",retry:"Reintentar",load:"No se pudo cargar la cola de soporte.",start:"Iniciar trabajo",resolve:"Resolver",reopen:"Reabrir",close:"Cerrar",stale:"El caso cambió. Actualice e intente nuevamente.",assign:"Asignarme",release:"Liberar",mine:"Asignado a mí",owner:"Responsable",unassigned:"Sin asignar",due:"Responder antes de",overdue:"Respuesta vencida",search:"Buscar casos",searchAction:"Buscar",ownership:"Responsable",overdueOnly:"Solo vencidos",previous:"Anterior",next:"Siguiente",showing:"Mostrando",of:"de"}:{title:"Customer service",subtitle:"Customer-submitted cases across all companies.",all:"All",urgent:"Urgent",waiting:"Waiting",resolved:"Resolved",empty:"No cases in this view.",retry:"Try again",load:"Support queue could not be loaded.",start:"Start work",resolve:"Resolve",reopen:"Reopen",close:"Close",stale:"This case changed. Refresh and try again.",assign:"Assign to me",release:"Release",mine:"Assigned to me",owner:"Owner",unassigned:"Unassigned",due:"Response due",overdue:"Response overdue",search:"Search cases",searchAction:"Search",ownership:"Ownership",overdueOnly:"Overdue only",previous:"Previous",next:"Next",showing:"Showing",of:"of"};
 const load=useCallback(async()=>{setLoading(true);setError("");try{const params=new URLSearchParams({limit:String(LIMIT),offset:String(offset)});if(scope!=="all")params.set("workload",scope);if(assignment!=="all")params.set("assignment",assignment);if(overdueOnly)params.set("overdue","true");if(search)params.set("search",search);const response=await fetch(`${API_BASE}/api/v1/admin/support/cases?${params}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error();setPage(parseAdminSupportCases(await response.json()));}catch{setError(copy.load);}finally{setLoading(false);}},[assignment,copy.load,offset,overdueOnly,scope,search,token]);
 useEffect(()=>{void load();},[load]);
 const reset=(change:()=>void)=>{setOffset(0);change();};
 const submitSearch=(event:FormEvent)=>{event.preventDefault();reset(()=>setSearch(searchDraft.trim()));};
 async function mutate(item:AdminSupportCase,path:string,body:Record<string,unknown>){setUpdating(item.id);setError("");try{const response=await fetch(`${API_BASE}/api/v1/admin/support/cases/${item.id}/${path}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(response.status===409){setError(copy.stale);await load();return;}if(!response.ok)throw new Error();await load();}catch{setError(copy.load);}finally{setUpdating(null);}}
 const transition=(item:AdminSupportCase,status:AdminSupportCase["status"])=>mutate(item,"status",{expectedStatus:item.status,status,expectedUpdatedAt:item.updatedAt}),setOwner=(item:AdminSupportCase,assigned:boolean)=>mutate(item,"assignment",{assigned,expectedUpdatedAt:item.updatedAt}),date=(value:string)=>new Intl.DateTimeFormat(es?"es":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)),first=page.total===0?0:page.offset+1,last=Math.min(page.offset+page.items.length,page.total);
 return <section aria-labelledby="support-operations-title" data-testid="support-case-queue" style={{marginTop:28}}><header><h2 id="support-operations-title">{copy.title}</h2><p>{copy.subtitle}</p></header>
  <form onSubmit={submitSearch} style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}><label>{copy.search} <input value={searchDraft} maxLength={120} onChange={e=>setSearchDraft(e.target.value)}/></label><button type="submit">{copy.searchAction}</button><label>{copy.ownership} <select value={assignment} onChange={e=>reset(()=>setAssignment(e.target.value as Assignment))}><option value="all">{copy.all}</option><option value="mine">{copy.mine}</option><option value="unassigned">{copy.unassigned}</option></select></label><label><input type="checkbox" checked={overdueOnly} onChange={e=>reset(()=>setOverdueOnly(e.target.checked))}/> {copy.overdueOnly}</label></form>
  <div role="group" aria-label={copy.title} style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}>{(["all","urgent","waiting","resolved"] as const).map(value=><button key={value} aria-pressed={scope===value} onClick={()=>reset(()=>setScope(value))}>{copy[value]}</button>)}<button onClick={()=>void load()}>{copy.retry}</button></div>
  {error&&<p role="alert">{error}</p>}{loading?<p aria-live="polite">…</p>:page.items.length===0?<p>{copy.empty}</p>:<div style={{display:"grid",gap:12}}>{page.items.map(item=><article key={item.id} style={{border:"1px solid #dbe3ef",borderRadius:10,padding:14,overflowWrap:"anywhere"}}><strong>{item.subject}</strong><p>{item.companyName} · {item.requesterName} · {item.requesterEmail}</p><p>{item.description}</p><p>{item.priority} · {item.status}</p><p><strong>{item.assignedToCurrentUser?copy.mine:item.assignedToName?`${copy.owner}: ${item.assignedToName}`:copy.unassigned}</strong>{item.responseDueAt&&<> · <span style={{color:item.overdue?"#b42318":undefined}}>{item.overdue?copy.overdue:copy.due}: {date(item.responseDueAt)}</span></>}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{item.assignedToUserId===null&&!["resolved","closed"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void setOwner(item,true)}>{copy.assign}</button>}{item.assignedToCurrentUser&&!["resolved","closed"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void setOwner(item,false)}>{copy.release}</button>}{item.status==="open"&&<button disabled={updating===item.id} onClick={()=>void transition(item,"in_progress")}>{copy.start}</button>}{["open","in_progress"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void transition(item,"resolved")}>{copy.resolve}</button>}{item.status==="resolved"&&<><button disabled={updating===item.id} onClick={()=>void transition(item,"in_progress")}>{copy.reopen}</button><button disabled={updating===item.id} onClick={()=>void transition(item,"closed")}>{copy.close}</button></>}</div><button type="button" onClick={()=>setOpenCase(openCase===item.id?null:item.id)}>{openCase===item.id?(es?"Ocultar conversación":"Hide conversation"):(es?"Abrir conversación":"Open conversation")}</button>{openCase===item.id&&<SupportConversation caseId={item.id} token={token} admin canPost={item.assignedToCurrentUser&&!["resolved","closed"].includes(item.status)}/>}</article>)}</div>}
  <footer style={{display:"flex",gap:8,alignItems:"center",marginTop:12}}><span aria-live="polite">{copy.showing} {first}–{last} {copy.of} {page.total}</span><button disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-LIMIT))}>{copy.previous}</button><button disabled={loading||offset+page.items.length>=page.total} onClick={()=>setOffset(offset+LIMIT)}>{copy.next}</button></footer>
 </section>;
}
