import {useCallback,useEffect,useState} from "react";
import {parseAdminSupportCases,type AdminSupportCase} from "@/lib/support-case-admin-client";
const API_BASE=import.meta.env.VITE_API_URL??"";

export function SupportCaseQueue({token}:{token:string}){
  const es=typeof window!=="undefined"&&localStorage.getItem("bimlog-lang")==="es";
  const [items,setItems]=useState<AdminSupportCase[]>([]),[scope,setScope]=useState<"all"|"urgent"|"waiting"|"resolved">("all"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updating,setUpdating]=useState<number|null>(null);
  const copy=es?{title:"Servicio al cliente",subtitle:"Casos enviados por clientes de todas las compañías.",all:"Todos",urgent:"Urgentes",waiting:"En espera",resolved:"Resueltos",empty:"No hay casos en esta vista.",retry:"Reintentar",load:"No se pudo cargar la cola de soporte.",start:"Iniciar trabajo",resolve:"Resolver",reopen:"Reabrir",close:"Cerrar",stale:"El caso cambió. Actualice e intente nuevamente.",assign:"Asignarme",release:"Liberar",mine:"Asignado a mí",owner:"Responsable",unassigned:"Sin asignar",due:"Responder antes de",overdue:"Respuesta vencida"}:{title:"Customer service",subtitle:"Customer-submitted cases across all companies.",all:"All",urgent:"Urgent",waiting:"Waiting",resolved:"Resolved",empty:"No cases in this view.",retry:"Try again",load:"Support queue could not be loaded.",start:"Start work",resolve:"Resolve",reopen:"Reopen",close:"Close",stale:"This case changed. Refresh and try again.",assign:"Assign to me",release:"Release",mine:"Assigned to me",owner:"Owner",unassigned:"Unassigned",due:"Response due",overdue:"Response overdue"};
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`${API_BASE}/api/v1/admin/support/cases`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error();setItems(parseAdminSupportCases(await response.json()));}catch{setError(copy.load);}finally{setLoading(false);}},[copy.load,token]);
  useEffect(()=>{void load();},[load]);
  async function mutate(item:AdminSupportCase,path:string,body:Record<string,unknown>){setUpdating(item.id);setError("");try{const response=await fetch(`${API_BASE}/api/v1/admin/support/cases/${item.id}/${path}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(response.status===409){setError(copy.stale);await load();return;}if(!response.ok)throw new Error();await load();}catch{setError(copy.load);}finally{setUpdating(null);}}
  const transition=(item:AdminSupportCase,status:AdminSupportCase["status"])=>mutate(item,"status",{expectedStatus:item.status,status,expectedUpdatedAt:item.updatedAt});
  const assignment=(item:AdminSupportCase,assigned:boolean)=>mutate(item,"assignment",{assigned,expectedUpdatedAt:item.updatedAt});
  const visible=scope==="all"?items:items.filter(item=>item.workload===scope),date=(value:string)=>new Intl.DateTimeFormat(es?"es":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
  return <section aria-labelledby="support-operations-title" data-testid="support-case-queue" style={{marginTop:28}}><header><h2 id="support-operations-title">{copy.title}</h2><p>{copy.subtitle}</p></header><div role="group" aria-label={copy.title} style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}>{(["all","urgent","waiting","resolved"] as const).map(value=><button key={value} aria-pressed={scope===value} onClick={()=>setScope(value)}>{copy[value]}</button>)}<button onClick={()=>void load()}>{copy.retry}</button></div>{error&&<p role="alert">{error}</p>}{loading?<p aria-live="polite">…</p>:visible.length===0?<p>{copy.empty}</p>:<div style={{display:"grid",gap:12}}>{visible.map(item=><article key={item.id} style={{border:"1px solid #dbe3ef",borderRadius:10,padding:14,overflowWrap:"anywhere"}}><strong>{item.subject}</strong><p>{item.companyName} · {item.requesterName} · {item.requesterEmail}</p><p>{item.description}</p><p>{item.priority} · {item.status}</p><p><strong>{item.assignedToCurrentUser?copy.mine:item.assignedToName?`${copy.owner}: ${item.assignedToName}`:copy.unassigned}</strong>{item.responseDueAt&&<> · <span style={{color:item.overdue?"#b42318":undefined}}>{item.overdue?copy.overdue:copy.due}: {date(item.responseDueAt)}</span></>}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{item.assignedToUserId===null&&!["resolved","closed"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void assignment(item,true)}>{copy.assign}</button>}{item.assignedToCurrentUser&&!["resolved","closed"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void assignment(item,false)}>{copy.release}</button>}{item.status==="open"&&<button disabled={updating===item.id} onClick={()=>void transition(item,"in_progress")}>{copy.start}</button>}{["open","in_progress"].includes(item.status)&&<button disabled={updating===item.id} onClick={()=>void transition(item,"resolved")}>{copy.resolve}</button>}{item.status==="resolved"&&<><button disabled={updating===item.id} onClick={()=>void transition(item,"in_progress")}>{copy.reopen}</button><button disabled={updating===item.id} onClick={()=>void transition(item,"closed")}>{copy.close}</button></>}</div></article>)}</div>}</section>;
}
