import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import {useI18n} from "@/lib/i18n";
import {requestCommercialBillingHistory,type BillingHistoryStatus,type CommercialBillingHistoryDto} from "@/lib/commercial-billing-history-client";

export function BillingHistoryPanel({token}:{token:string}){
  const {language,tt}=useI18n(),[data,setData]=useState<CommercialBillingHistoryDto|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[nonce,setNonce]=useState(0),[status,setStatus]=useState<BillingHistoryStatus>("all"),[page,setPage]=useState(1);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");requestCommercialBillingHistory({token,status,page,pageSize:10,signal:controller.signal}).then(setData).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,status,page,nonce]);
  const money=(cents:number,currency:string)=>new Intl.NumberFormat(language==="es"?"es-US":"en-US",{style:"currency",currency}).format(cents/100);
  const date=(value:string|null)=>value?new Intl.DateTimeFormat(language==="es"?"es":"en",{dateStyle:"medium"}).format(new Date(value)):tt("Not recorded","No registrado");
  const invoiceStatus:Record<string,[string,string]>={draft:["Draft","Borrador"],open:["Open","Abierta"],paid:["Paid","Pagada"],void:["Void","Anulada"],uncollectible:["Uncollectible","Incobrable"]};
  const disputeStatus:Record<string,[string,string]>={needs_response:["Response required","Respuesta requerida"],under_review:["Under review","En revisión"],won:["Resolved in BIMLog’s favor","Resuelta a favor de BIMLog"],lost:["Resolved for customer","Resuelta para el cliente"],withdrawn:["Withdrawn","Retirada"]};
  return <section aria-labelledby="billing-history-title" style={{marginTop:18,padding:18,border:"1px solid #CBD5E1",borderRadius:12,background:"white"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12,flexWrap:"wrap"}}><div><h2 id="billing-history-title" style={{fontSize:19,margin:0}}>{tt("Billing history","Historial de facturación")}</h2><p style={{color:"#64748B",margin:"6px 0 14px"}}>{tt("Review your company’s invoices, credits and payment disputes. Provider credentials and payment methods are never shown.","Revise las facturas, créditos y disputas de pago de su empresa. Nunca se muestran credenciales del proveedor ni métodos de pago.")}</p></div><Button variant="outline" disabled={loading} onClick={()=>setNonce(value=>value+1)}>{tt("Refresh history","Actualizar historial")}</Button></div>
    <div style={{display:"flex",alignItems:"end",gap:12,flexWrap:"wrap",marginBottom:14}}><label style={{fontWeight:700}}>{tt("Invoice status","Estado de factura")}<select value={status} disabled={loading} onChange={event=>{setStatus(event.target.value as BillingHistoryStatus);setPage(1);}} style={{display:"block",padding:8,marginTop:4}}><option value="all">{tt("All statuses","Todos los estados")}</option>{Object.entries(invoiceStatus).map(([value,label])=><option key={value} value={value}>{tt(...label)}</option>)}</select></label>{data&&!error&&<span role="status" style={{color:"#475569"}}>{data.totalInvoices} {tt(data.totalInvoices===1?"invoice":"invoices",data.totalInvoices===1?"factura":"facturas")}</span>}</div>
    {loading&&<p role="status">{tt("Loading billing history…","Cargando historial de facturación…")}</p>}
    {error&&<div role="alert" style={{padding:12,border:"1px solid #FCA5A5",background:"#FEF2F2",borderRadius:10}}><strong>{tt("Billing history unavailable","Historial de facturación no disponible")}</strong><p style={{margin:"6px 0 10px"}}>{error}</p><Button onClick={()=>setNonce(value=>value+1)}>{tt("Try again","Intentar de nuevo")}</Button></div>}
    {data&&!loading&&!error&&<>{data.subscription&&<p style={{marginTop:0}}><strong>{tt("Subscription","Suscripción")}:</strong> {data.subscription.planCode} · {data.subscription.billingCycle} · {data.subscription.status}</p>}{data.invoices.length===0?<p>{status==="all"?tt("No invoices have been recorded for this company yet.","Todavía no se han registrado facturas para esta empresa."):tt("No invoices match this status.","Ninguna factura coincide con este estado.")}</p>:<div style={{display:"grid",gap:12}}>{data.invoices.map(invoice=><article key={invoice.id} style={{border:"1px solid #E2E8F0",borderRadius:10,padding:14,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{invoice.invoiceNumber}</strong><div style={{fontSize:13,color:"#64748B"}}>{tt("Issued","Emitida")}: {date(invoice.issuedAt)}</div></div><div style={{textAlign:"right"}}><strong>{money(invoice.totalCents,invoice.currency)}</strong><div style={{fontSize:13,color:invoice.status==="paid"?"#047857":"#92400E",fontWeight:700}}>{tt(...invoiceStatus[invoice.status])}</div></div></div><dl style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(150px,100%),1fr))",gap:8,margin:"12px 0 0"}}><div><dt style={{color:"#64748B",fontSize:12}}>{tt("Subtotal","Subtotal")}</dt><dd style={{margin:0}}>{money(invoice.subtotalCents,invoice.currency)}</dd></div><div><dt style={{color:"#64748B",fontSize:12}}>{tt("Tax","Impuesto")}</dt><dd style={{margin:0}}>{money(invoice.taxCents,invoice.currency)}</dd></div><div><dt style={{color:"#64748B",fontSize:12}}>{tt("Paid","Pagada")}</dt><dd style={{margin:0}}>{date(invoice.paidAt)}</dd></div></dl>{invoice.credits.length>0&&<div style={{marginTop:12}}><strong>{tt("Credits","Créditos")}</strong><ul>{invoice.credits.map(credit=><li key={credit.id}>{credit.creditNumber}: {money(credit.amountCents,invoice.currency)} · {credit.reason}</li>)}</ul></div>}{invoice.disputes.length>0&&<div style={{marginTop:12}}><strong>{tt("Payment disputes","Disputas de pago")}</strong><ul>{invoice.disputes.map(dispute=><li key={dispute.id}>{money(dispute.amountCents,invoice.currency)} · {tt(...disputeStatus[dispute.status])}{dispute.evidenceDueAt?` · ${tt("Evidence due","Evidencia vence")}: ${date(dispute.evidenceDueAt)}`:""}</li>)}</ul></div>}</article>)}</div>}{data.totalPages>1&&<nav aria-label={tt("Billing history pages","Páginas del historial de facturación")} style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:14,flexWrap:"wrap"}}><span>{tt("Page","Página")} {data.page} {tt("of","de")} {data.totalPages}</span><div style={{display:"flex",gap:8}}><Button variant="outline" disabled={data.page<=1} onClick={()=>setPage(value=>Math.max(1,value-1))}>{tt("Previous","Anterior")}</Button><Button variant="outline" disabled={data.page>=data.totalPages} onClick={()=>setPage(value=>value+1)}>{tt("Next","Siguiente")}</Button></div></nav>}</>}
  </section>;
}
