type HistoryEvent={actorUserId:number;paymentApplicationId:string;paymentVersionId:string;eventType:string;beforeState:string|null;afterState:string|null;reasonCode:string;evidence:Record<string,unknown>;occurredAt:string};
type Props={history:unknown[];language:string;tt:(en:string,es:string)=>string;error?:"denied"|"suspended"|"unavailable"};
const eventLabels:Record<string,[string,string]>={payment_application_created:["Draft created","Borrador creado"],payment_application_submit:["Submitted","Enviado"],payment_application_review:["Independent review recorded","Revisión independiente registrada"],payment_application_return:["Returned for correction","Devuelto para corrección"],payment_application_revised:["Corrected successor created","Sucesor corregido creado"],payment_application_approved:["Exact request approved","Solicitud exacta aprobada"],payment_application_reject:["Rejected","Rechazado"],payment_application_withdraw:["Withdrawn","Retirado"],payment_application_void:["Voided","Anulado"]};
const stateLabels:Record<string,[string,string]>={draft:["Draft","Borrador"],submitted:["Submitted","Enviado"],returned:["Returned","Devuelto"],approved:["Approved","Aprobado"],rejected:["Rejected","Rechazado"],withdrawn:["Withdrawn","Retirado"],voided:["Voided","Anulado"]};
const text=(value:unknown)=>typeof value==="string"?value:"";
export const paymentHistoryDto=(row:any):HistoryEvent=>({actorUserId:Number(row.actorUserId??row.actor_user_id),paymentApplicationId:text(row.paymentApplicationId??row.payment_application_id),paymentVersionId:text(row.paymentVersionId??row.payment_version_id),eventType:text(row.eventType??row.event_type),beforeState:row.beforeState??row.before_state??null,afterState:row.afterState??row.after_state??null,reasonCode:text(row.reasonCode??row.reason_code),evidence:row.evidence&&typeof row.evidence==="object"&&!Array.isArray(row.evidence)?row.evidence:{},occurredAt:text(row.occurredAt??row.occurred_at)});
export function ContractPaymentHistoryPanel({history,language,tt,error}:Props){
 const index=language==="es"?1:0,state=(value:string|null)=>value?(stateLabels[value]?.[index]??tt("Unknown state","Estado desconocido")):tt("Not applicable","No aplica");
 if(error)return <section className="fc-payment-history fc-error" role="alert"><strong>{error==="suspended"?tt("Payment history authority suspended","Autoridad de historial de pagos suspendida"):error==="denied"?tt("Payment history access denied","Acceso al historial de pagos denegado"):tt("Payment history unavailable","Historial de pagos no disponible")}</strong><p>{error==="suspended"?tt("An authorized administrator must restore financial authority before this history can be accessed.","Un administrador autorizado debe restablecer la autoridad financiera antes de acceder a este historial."):tt("The server did not authorize attributable payment history for this record.","El servidor no autorizó el historial de pagos atribuible para este registro.")}</p></section>;
 const events=history.map(paymentHistoryDto).filter(event=>event.paymentApplicationId&&event.paymentVersionId);
 return <section className="fc-payment-history" aria-labelledby="payment-history-heading"><h4 id="payment-history-heading">{tt("Attributable payment history","Historial de pagos atribuible")}</h4>{events.length===0?<p className="fc-payment-history-empty">{tt("No payment lifecycle history is recorded for this contract.","No hay historial del ciclo de pagos registrado para este contrato.")}</p>:<ol>{events.map((event,indexKey)=>{const reason=text(event.evidence.outcomeReason),predecessor=text(event.evidence.supersededPaymentVersionId),revision=Number(event.evidence.revision);return <li key={`${event.occurredAt}-${event.paymentVersionId}-${indexKey}`}><header><strong>{eventLabels[event.eventType]?.[index]??tt("Payment lifecycle event","Evento del ciclo de pagos")}</strong><time dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleString(language==="es"?"es":"en")}</time></header><dl><div><dt>{tt("Actor","Actor")}</dt><dd>#{event.actorUserId}</dd></div><div><dt>{tt("Application root ID","ID raíz de solicitud")}</dt><dd><code>{event.paymentApplicationId}</code></dd></div><div><dt>{tt("Version ID","ID de versión")}</dt><dd><code>{event.paymentVersionId}</code></dd></div><div><dt>{tt("State change","Cambio de estado")}</dt><dd>{state(event.beforeState)} → {state(event.afterState)}</dd></div></dl>{predecessor&&<p><strong>{tt("Revision linkage","Vínculo de revisión")}:</strong> <code>{predecessor}</code> → <code>{event.paymentVersionId}</code></p>}{Number.isSafeInteger(revision)&&revision>0&&<p>{tt("Resulting revision","Revisión resultante")}: {revision}</p>}{reason&&<p><strong>{tt("Decision reason","Motivo de decisión")}:</strong> {reason}</p>}</li>})}</ol>}</section>;
}
