import assert from "node:assert/strict";
import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {ContractProductionAllocationReview} from "./ContractProductionAllocationReview";
const lines=[{stableLineId:"TEST-1",contractItem:{displayName:"TEST Shop Drawing",productionAllocation:"100.25"}},{stableLineId:"TEST-2",description:"TEST Sleeve",contractItem:{productionAllocation:"0"}},{stableLineId:"TEST-3"}];
const render=(status:string,es=false,items=lines)=>renderToStaticMarkup(<ContractProductionAllocationReview lines={items} currency="USD" status={status} tt={(en,spanish)=>es?spanish:en}/>);
assert.match(render("draft"),/not yet approved funding/);
assert.match(render("approved"),/do not authorize payment/);
assert.match(render("draft",true),/aún no son fondos aprobados/);
assert.match(render("approved",true),/no autorizan pagos/);
assert.match(render("draft"),/100.25 USD/);
assert.match(render("draft"),/>0 USD</);
assert.match(render("draft"),/Not allocated/);
assert.equal(render("draft",false,[]),"");
assert.equal(render("draft",false,[{stableLineId:"legacy"}]),"");
const classified=renderToStaticMarkup(<ContractProductionAllocationReview lines={lines} currency="USD" status="draft" pools={{directProduction:"100.25",projectAdministration:"20",incentiveReserve:"30",projectEarnings:"10",fixedCompanyCost:"5"}} tt={en=>en}/>);
assert.match(classified,/Contract pools — counted once/);
assert.equal(classified.split('>30 USD<').length-1,1,"The contract reserve must appear once, not once per item");
console.log("Contract production allocation review: legacy omission, exact zero, pending/approved distinction and bilingual rendering PASS");
