import {FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {newSupportSatisfactionKey,parseSupportCaseSatisfaction,type SupportCaseSatisfactionDto} from "@/lib/support-case-satisfaction-client";
import {Button} from "@/components/ui/button";
import {useI18n} from "@/lib/i18n";
const API_BASE=import.meta.env.BASE_URL.replace(/\/$/,"");
export function SupportSatisfaction({caseId,token}:{caseId:number;token:string}){const {tt}=useI18n(),[item,setItem]=useState<SupportCaseSatisfactionDto|null>(null),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),key=useRef(newSupportSatisfactionKey());
 const load=useCallback(async()=>{setState("loading");setMessage("");try{const response=await fetch(`${API_BASE}/api/v1/support/cases/${caseId}/satisfaction`,{headers:{Authorization:`Bearer ${token}`}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error();setItem(parseSupportCaseSatisfaction(body));setState("ready");}catch{setMessage(tt("Your rating could not be loaded.","No se pudo cargar su calificación."));setState("error");}},[caseId,token,tt]);useEffect(()=>{void load();},[load]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),rating=Number(form.get("rating")),comment=String(form.get("comment")??"").trim();setSaving(true);setMessage("");try{const response=await fetch(`${API_BASE}/api/v1/support/cases/${caseId}/satisfaction`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({rating,comment:comment||null,requestKey:key.current})}),body=await response.json().catch(()=>({}));if(response.status===409)throw new Error(tt("A rating was already recorded for this request.","Ya se registró una calificación para esta solicitud."));if(!response.ok)throw new Error(tt("Your rating could not be saved.","No se pudo guardar su calificación."));setItem(parseSupportCaseSatisfaction({item:body}));setMessage(tt("Thank you. Your rating was recorded.","Gracias. Se registró su calificación."));}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason));}finally{setSaving(false);}}
 if(state==="loading")return <p role="status">{tt("Loading service rating…","Cargando calificación del servicio…")}</p>;
 if(state==="error")return <div><p role="alert">{message}</p><Button variant="outline" onClick={()=>void load()}>{tt("Try again","Intentar de nuevo")}</Button></div>;
 if(item)return <section aria-label={tt("Service rating","Calificación del servicio")}><strong>{tt("Your service rating","Su calificación del servicio")}: {item.rating}/5</strong>{item.comment&&<p>{item.comment}</p>}<small>{new Date(item.createdAt).toLocaleString()}</small>{message&&<p role="status">{message}</p>}</section>;
 return <form onSubmit={submit} style={{display:"grid",gap:8,margin:"10px 0"}}><fieldset><legend>{tt("How was the support you received?","¿Cómo fue el soporte que recibió?")}</legend>{([1,2,3,4,5] as const).map(value=><label key={value} style={{marginRight:12}}><input type="radio" name="rating" value={value} required/> {value}</label>)}</fieldset><label>{tt("Comment (optional)","Comentario (opcional)")}<textarea name="comment" minLength={4} maxLength={1000} rows={2}/></label><Button type="submit" disabled={saving}>{saving?tt("Saving…","Guardando…"):tt("Submit rating","Enviar calificación")}</Button>{message&&<p role="status">{message}</p>}</form>;
}
