import { useState } from "react";
import { AlertTriangle, CheckCircle2, History, LockKeyhole, ShieldCheck } from "lucide-react";
import { useI18n } from "@/lib/i18n";

type Mutate = (path: string, init: RequestInit, message: string) => Promise<void>;
const amount = (value: unknown) => Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const bgCss = `.bg-panel{background:#fff;border:1px solid #cbd5e1;border-radius:14px;padding:18px;margin-bottom:18px}.bg-disabled{display:flex;gap:12px;background:#f8fafc}.bg-head{display:flex;justify-content:space-between;gap:16px}.bg-head h2{margin:8px 0 0}.bg-version{text-align:center;background:#eff6ff;border-radius:12px;padding:10px 18px}.bg-version strong,.bg-version span{display:block}.bg-version strong{font-size:24px}.bg-version span{font-size:11px}.bg-first{padding:12px;background:#f8fafc;border-radius:10px}.bg-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.bg-metrics article{display:grid;gap:4px;border:1px solid #dbe4f0;border-radius:12px;padding:12px}.bg-metrics article.over{border-color:#fb923c;background:#fff7ed;color:#9a3412}.bg-metrics article.within{background:#f0fdf4;color:#166534}.bg-metrics small{font-weight:700}.bg-warning{display:flex;gap:8px;padding:10px;border-radius:9px;background:#fff7ed;color:#9a3412;font-weight:700}.bg-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:14px 0}.bg-actions form{border:1px solid #dbe4f0;border-radius:12px;padding:12px;display:grid;gap:9px}.bg-actions h3{margin:0}.bg-history h3{display:flex;gap:7px}.bg-history>div{display:grid;grid-template-columns:45px 1fr 1fr 2fr;gap:8px;padding:8px;border-top:1px solid #e2e8f0;font-size:12px}.bg-reviews{margin-top:14px}.bg-reviews article{border:1px solid #e2e8f0;border-radius:10px;padding:10px;margin-top:8px}.bg-reviews article>.jo-chip{float:right}@media(max-width:900px){.bg-head{display:block}.bg-actions,.bg-metrics{grid-template-columns:1fr}.bg-history>div{grid-template-columns:45px 1fr}}`;

export function BudgetGovernancePanel({ projectId, governance, canManage, busy, mutate }: { projectId: number; governance: any; canManage: boolean; busy: boolean; mutate: Mutate }) {
  const { tt } = useI18n();
  const [revisionReason, setRevisionReason] = useState("");
  const [metric, setMetric] = useState("hours");
  const [reason, setReason] = useState("");
  const [action, setAction] = useState("");
  const post = (path: string, body: unknown, message: string) => mutate(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }, message);
  if (!governance?.enabled) return <section className="bg-panel bg-disabled"><ShieldCheck/><div><h2>{tt("Budget Governance", "Gobernanza del Presupuesto")}</h2><p>{tt("Available with Project Budget or Cost & Value Planner access.", "Disponible con acceso a Presupuesto del Proyecto o al Planificador de Costos y Valor.")}</p></div></section>;
  const latest = governance.latestBaseline;
  const overruns = (governance.metrics ?? []).filter((item: any) => item.overrun);
  const metricLabel = (value: string) => ({ hours: tt("Hours", "Horas"), internal_cost: tt("Internal cost", "Costo interno"), billable_value: tt("Billable value", "Valor facturable") } as Record<string,string>)[value] ?? value;
  return <section className="bg-panel"><style>{bgCss}</style><header className="bg-head"><div><span className="jo-chip"><LockKeyhole size={12}/> {tt("CONTROLLED BASELINE", "LÍNEA BASE CONTROLADA")}</span><h2>{tt("Budget Governance & Change Control", "Gobernanza del Presupuesto y Control de Cambios")}</h2><p>{tt("Freeze the approved plan, compare actual performance, explain overruns, and preserve every revision.", "Congele el plan aprobado, compare el desempeño real, explique excesos y preserve cada revisión.")}</p></div>{latest&&<div className="bg-version"><strong>v{latest.version}</strong><span>{tt("Current baseline", "Línea base vigente")}</span></div>}</header>
    {!latest?<div className="bg-first"><p>{tt("Freeze the current Intake hours, rates, costs, and billable value before recording performance decisions.", "Congele las horas, tarifas, costos y valor facturable actuales del Ingreso antes de registrar decisiones de desempeño.")}</p>{canManage&&<button className="primary" disabled={busy} onClick={()=>void post(`/projects/${projectId}/operations/budget/baselines`,{baselineId:crypto.randomUUID(),revisionReason:""},tt("Execution budget baseline frozen.","Línea base del presupuesto congelada."))}><LockKeyhole size={14}/> {tt("Freeze approved baseline", "Congelar línea base aprobada")}</button>}</div>:<>
      <div className="bg-metrics">{governance.metrics.map((item:any)=><article className={item.overrun?"over":"within"} key={item.metric}>{item.overrun?<AlertTriangle/>:<CheckCircle2/>}<strong>{metricLabel(item.metric)}</strong><span>{tt("Baseline", "Línea base")}: {amount(item.planned)}</span><span>{tt("Actual", "Real")}: {amount(item.actual)}</span><b>{item.overrun?"+":""}{amount(item.variance)}</b><small>{item.overrun?tt("Explanation required", "Explicación requerida"):tt("Within baseline", "Dentro de la línea base")}</small></article>)}</div>
      {governance.unresolvedOverruns>0&&<div className="bg-warning"><AlertTriangle/>{tt(`${governance.unresolvedOverruns} overrun(s) require a management explanation.`,`${governance.unresolvedOverruns} exceso(s) requieren una explicación gerencial.`)}</div>}
      {canManage&&<div className="bg-actions"><form onSubmit={(e)=>{e.preventDefault();void post(`/projects/${projectId}/operations/budget/baselines`,{baselineId:crypto.randomUUID(),revisionReason},tt("Controlled budget revision created.","Revisión controlada creada."));}}><h3>{tt("Controlled revision", "Revisión controlada")}</h3><label>{tt("Reason for changing the approved baseline", "Justificación para cambiar la línea base")}<textarea required minLength={10} maxLength={1000} value={revisionReason} onChange={e=>setRevisionReason(e.target.value)}/></label><button className="primary" disabled={busy||revisionReason.trim().length<10}><History size={14}/> {tt("Create new baseline version", "Crear nueva versión")}</button></form>
      {overruns.length>0&&<form onSubmit={(e)=>{e.preventDefault();void post(`/projects/${projectId}/operations/budget/variance-reviews`,{reviewId:crypto.randomUUID(),metric,reason,correctiveAction:action},tt("Budget variance explanation recorded.","Explicación de variación registrada."));}}><h3>{tt("Explain an overrun", "Explicar un exceso")}</h3><label>{tt("Metric", "Métrica")}<select value={metric} onChange={e=>setMetric(e.target.value)}>{overruns.map((item:any)=><option value={item.metric} key={item.metric}>{metricLabel(item.metric)} (+{amount(item.variance)})</option>)}</select></label><label>{tt("Root cause", "Causa raíz")}<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>{tt("Corrective action", "Acción correctiva")}<textarea required maxLength={2000} value={action} onChange={e=>setAction(e.target.value)}/></label><button className="primary" disabled={busy||!reason.trim()||!action.trim()}>{tt("Record explanation", "Registrar explicación")}</button></form>}</div>}
      <div className="bg-history"><h3><History size={15}/> {tt("Immutable baseline history", "Historial inmutable de líneas base")}</h3>{governance.history.map((item:any)=><div key={item.id}><strong>v{item.version}</strong><span>{item.createdBy||"—"}</span><span>{new Date(item.createdAt).toLocaleString()}</span><span>{item.revisionReason||tt("Original approved baseline", "Línea base original")}</span></div>)}</div>
      {governance.reviews.length>0&&<div className="bg-reviews"><h3>{tt("Variance explanations", "Explicaciones de variación")}</h3>{governance.reviews.map((review:any)=><article key={review.id}><strong>{metricLabel(review.metric)} · +{amount(review.variance)}</strong><span className="jo-chip">{review.status}</span><p><b>{tt("Cause", "Causa")}:</b> {review.reason}</p><p><b>{tt("Action", "Acción")}:</b> {review.correctiveAction}</p>{canManage&&review.status!=="resolved"&&<button disabled={busy} onClick={()=>void mutate(`/projects/${projectId}/operations/budget/variance-reviews/${review.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedVersion:review.version,status:"resolved"})},tt("Variance review resolved.","Revisión resuelta."))}>{tt("Mark resolved", "Marcar resuelta")}</button>}</article>)}</div>}
    </>}
  </section>;
}
