import{addPageNumbers,computeContentHash,createPdfDocument,drawBrandedHeader,REPORT_THEMES}from"./pdf-kit";import type{CustomerInvoiceStatement}from"./commercial-invoice-statement";
const money=(cents:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(cents/100),date=(value:string|null)=>value?new Date(value).toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"}):"Not recorded";
export async function buildCustomerInvoiceStatementPdf(data:CustomerInvoiceStatement):Promise<{buffer:Buffer;contentHash:string}>{
 const contentHash=computeContentHash(data),doc=createPdfDocument({size:"LETTER",margin:42,bufferPages:true,info:{Title:`Billing statement ${data.invoice.invoiceNumber}`,Author:"BIMLog by IgniteSmart",Subject:"Customer billing record statement"}}),chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));
 doc.y=drawBrandedHeader(doc,{margin:42,companyName:"BIMLog by IgniteSmart",projectName:data.customer.legalName,projectCode:`Company ${data.companyId}`,title:"Customer billing statement",subtitle:"Recorded invoice, credits and disputes",reportNumber:data.invoice.invoiceNumber,reportDate:new Date(data.generatedAt),theme:REPORT_THEMES.platform.standard})+16;
 doc.fontSize(9).fillColor("#475569").text("Customer billing record. This statement does not authorize a payment, refund, tax filing, or accounting entry.").moveDown();
 doc.fontSize(12).fillColor("#111827").text(`Invoice ${data.invoice.invoiceNumber}`).fontSize(9).text(`Status: ${data.invoice.status}`).text(`Issued: ${date(data.invoice.issuedAt)}`).text(`Due: ${date(data.invoice.dueAt)}`).text(`Paid: ${date(data.invoice.paidAt)}`).moveDown();
 doc.fontSize(11).text("Amounts").fontSize(9).text(`Subtotal: ${money(data.invoice.subtotalCents,data.invoice.currency)}`).text(`Tax: ${money(data.invoice.taxCents,data.invoice.currency)}`).text(`Total: ${money(data.invoice.totalCents,data.invoice.currency)}`).text(`Credits issued: ${money(data.creditedCents,data.invoice.currency)}`).font("Helvetica-Bold").text(`Remaining balance: ${money(data.balanceCents,data.invoice.currency)}`).font("Helvetica").moveDown();
 doc.fontSize(11).text("Customer").fontSize(9).text(data.customer.legalName);if(data.customer.address)doc.text(data.customer.address);if(data.customer.phone)doc.text(data.customer.phone);
 if(data.invoice.credits.length){doc.moveDown().fontSize(11).text("Credits").fontSize(9);for(const credit of data.invoice.credits)doc.text(`${credit.creditNumber} | ${credit.status} | ${money(credit.amountCents,data.invoice.currency)} | ${credit.reason}`);}
 if(data.invoice.disputes.length){doc.moveDown().fontSize(11).text("Payment disputes").fontSize(9);for(const dispute of data.invoice.disputes)doc.text(`${dispute.status} | ${money(dispute.amountCents,data.invoice.currency)} | ${dispute.reasonCode}`);}
 addPageNumbers(doc,{margin:42,footerY:760,fingerprintY:742,contentHash,companyName:"BIMLog by IgniteSmart",projectName:data.customer.legalName,reportNumber:data.invoice.invoiceNumber,timestamp:data.generatedAt});doc.end();
 return{buffer:await new Promise<Buffer>((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject);}),contentHash};
}
