import assert from "node:assert/strict";
import {readCustomerBillingHistory} from "./commercial-billing-history";

const calls:{text:string;values?:readonly unknown[]}[]=[];
const client={async query(text:string,values?:readonly unknown[]){calls.push({text,values});if(text.includes("commercial_subscriptions"))return {rows:[{plan_code:"professional",billing_cycle:"monthly",status:"active"}],rowCount:1};if(text.includes("count(*)"))return {rows:[{total:21}],rowCount:1};if(text.includes("commercial_invoices"))return {rows:[{id:"invoice-1",invoice_number:"INV-100",currency:"USD",subtotal_cents:3000,tax_cents:0,total_cents:3000,status:"paid",issued_at:"2026-10-01T12:00:00Z",due_at:null,paid_at:"2026-10-01T12:05:00Z"}],rowCount:1};if(text.includes("commercial_credit_notes"))return {rows:[{id:"credit-1",invoice_id:"invoice-1",credit_number:"CR-1",amount_cents:500,reason:"Service adjustment",status:"issued",issued_at:"2026-10-02T12:00:00Z",provider_event_reference:"evt_secret"}],rowCount:1};if(text.includes("commercial_disputes"))return {rows:[{id:"dispute-1",invoice_id:"invoice-1",amount_cents:1000,reason_code:"duplicate",status:"under_review",evidence_due_at:"2026-10-10T12:00:00Z",closed_at:null,provider_dispute_reference:"dp_secret"}],rowCount:1};throw new Error("Unexpected query");}};
const history=await readCustomerBillingHistory(client,7,{status:"paid",page:2,pageSize:10,offset:10});
assert.equal(history.companyId,7);assert.equal(history.subscription?.planCode,"professional");assert.equal(history.invoices[0].credits[0].amountCents,500);assert.equal(history.invoices[0].disputes[0].status,"under_review");
const serialized=JSON.stringify(history);assert.doesNotMatch(serialized,/evt_secret|dp_secret|provider|payload|digest|customerReference/i);
assert.equal(history.totalInvoices,21);assert.equal(history.totalPages,3);assert.equal(history.page,2);
assert.match(calls[1].text,/status=\$2/);assert.deepEqual(calls[1].values,[7,"paid"]);assert.deepEqual(calls[2].values,[7,"paid",10,10]);
const empty=await readCustomerBillingHistory({async query(text){return text.includes("count(*)")?{rows:[{total:0}],rowCount:1}:{rows:[],rowCount:0};}},8);assert.deepEqual(empty,{companyId:8,subscription:null,invoices:[],page:1,pageSize:10,totalInvoices:0,totalPages:0});
for(const replacement of [{status:"secret"},{currency:"BOB"},{total_cents:3001},{status:"open",paid_at:"2026-10-01T12:05:00Z"}])await assert.rejects(()=>readCustomerBillingHistory({async query(text){if(text.includes("commercial_subscriptions"))return {rows:[],rowCount:0};if(text.includes("count(*)"))return {rows:[{total:1}],rowCount:1};if(text.includes("commercial_invoices"))return {rows:[{id:"invoice-1",invoice_number:"INV-100",currency:"USD",subtotal_cents:3000,tax_cents:0,total_cents:3000,status:"paid",issued_at:"2026-10-01T12:00:00Z",due_at:null,paid_at:"2026-10-01T12:05:00Z",...replacement}],rowCount:1};return {rows:[],rowCount:0};}},7));
console.log("B241 customer billing history projection: PASS");
