import assert from "node:assert/strict";
import {createCompanySubscription} from "./subscription-authority";
import {deriveSubscriptionAccess} from "./commercial-billing-operations";
import {assembleCommercialWorkspace,assessCommercialLaunch,previewPlanChange,projectCommercialWorkspace,reconcileCommercialSeats} from "./commercial-workspace";
const draft=createCompanySubscription({id:"sub-workspace",companyId:42,planId:"business",catalogPriceVersion:3,billingCycle:"monthly",currency:"USD",amount:3000,now:"2026-10-01T00:00:00Z"});
const subscription={...draft,status:"active" as const,revision:2,updatedAt:"2026-10-01T00:01:00.000Z"};
const term={subscriptionId:subscription.id,sequence:1,billingCycle:"monthly" as const,startsAt:"2026-10-01T00:00:00.000Z",endsAt:"2026-11-01T00:00:00.000Z",renewsAt:"2026-11-01T00:00:00.000Z",sourceOrderId:"order-workspace",sourceInvoiceId:"invoice-workspace"};
const access=deriveSubscriptionAccess({subscription,term,catalogPriceVersionId:"price-v3",features:["projects","coordination"],seatLimit:10,existing:[],now:"2026-10-01T00:02:00Z"});
const workspace=assembleCommercialWorkspace({subscription,access,now:"2026-10-02T00:00:00Z"});
assert.deepEqual({companyId:workspace.companyId,planId:workspace.planId,seatLimit:workspace.seatLimit,accessStatus:workspace.accessStatus},{companyId:42,planId:"business",seatLimit:10,accessStatus:"active"});
assert.equal(workspace.fingerprint.length,64);
assert.throws(()=>assembleCommercialWorkspace({subscription,access:{...access,companyId:43},now:"2026-10-02T00:00:00Z"}),/lineage/);
console.log("B061 canonical authenticated commercial workspace state: PASS");
const upgrade=previewPlanChange({workspace,toPlan:"enterprise",toSeatLimit:25,assignedSeats:8,effectiveAt:"2026-11-01T00:00:00Z"});
assert.deepEqual({canSubmit:upgrade.canSubmit,writes:upgrade.writesPerformed,blockers:upgrade.blockers},{canSubmit:true,writes:0,blockers:[]});
const reduction=previewPlanChange({workspace,toPlan:"professional",toSeatLimit:3,assignedSeats:8,effectiveAt:"2026-11-01T00:00:00Z"});
assert.deepEqual({canSubmit:reduction.canSubmit,requiresSeatReduction:reduction.requiresSeatReduction,blocker:reduction.blockers[0]},{canSubmit:false,requiresSeatReduction:true,blocker:"ASSIGNED_SEATS_EXCEED_TARGET"});
console.log("B062 non-mutating plan-change preview: PASS");
const seats=reconcileCommercialSeats({workspace,assignments:[{userId:1,email:"OWNER@EXAMPLE.COM",role:"administrator",status:"active"},{userId:2,email:"coordinator@example.com",role:"member",status:"invited"}]});
assert.deepEqual({assigned:seats.assigned,available:seats.available,email:seats.assignments[0]?.email,canInvite:seats.canInvite},{assigned:2,available:8,email:"owner@example.com",canInvite:true});
assert.throws(()=>reconcileCommercialSeats({workspace:{...workspace,seatLimit:1},assignments:seats.assignments}),/limit exceeded/);
assert.throws(()=>reconcileCommercialSeats({workspace,assignments:[seats.assignments[0]!,{...seats.assignments[0]!,userId:3}]}),/duplicated/);
console.log("B063 company seat roster and allowance enforcement: PASS");
const launch=assessCommercialLaunch({workspace,billingIdentityComplete:true,providerReady:true,webhookReady:true,portalReady:true,supportReady:true,now:"2026-10-02T00:00:00Z"});
assert.deepEqual({status:launch.status,blockers:launch.blockers},{status:"ready",blockers:[]});
const blockedLaunch=assessCommercialLaunch({workspace,billingIdentityComplete:true,providerReady:false,webhookReady:false,portalReady:false,supportReady:true,now:"2026-10-02T00:00:00Z"});
assert.deepEqual(blockedLaunch.blockers,["PROVIDER_NOT_READY","WEBHOOK_NOT_READY","PORTAL_NOT_READY"]);
console.log("B064 fail-closed payment-provider launch readiness: PASS");
const customerView=projectCommercialWorkspace({workspace,role:"customer_admin",launch,seats});
assert.deepEqual({canChangePlan:customerView.canChangePlan,canOpenBillingPortal:customerView.canOpenBillingPortal,canManageProvider:customerView.canManageProvider},{canChangePlan:true,canOpenBillingPortal:true,canManageProvider:false});
const auditorView=projectCommercialWorkspace({workspace,role:"auditor",launch:blockedLaunch,seats});
assert.deepEqual((auditorView.launch as {blockers:unknown[]}).blockers,[]);
assert.equal(JSON.stringify(customerView).includes("secret"),false);
console.log("B065 permission-safe customer, billing, support and audit workspace: PASS");
export {subscription,access,workspace};
