import type {CommercialLiveCheck} from "./commercial-stripe-live-verification";import type {CommercialVerificationTransport} from "./commercial-launch-verification-transport";
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"?value as Record<string,unknown>:{};const email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export async function verifySendGridSupport(environment:NodeJS.ProcessEnv,transport:CommercialVerificationTransport):Promise<readonly CommercialLiveCheck[]>{
  const key=(environment.SENDGRID_API_KEY??"").trim(),sender=(environment.BIMLOG_SUPPORT_FROM_EMAIL??"").trim().toLowerCase(),inbox=(environment.BIMLOG_SUPPORT_INBOX_EMAIL??"").trim().toLowerCase();
  if(!/^SG\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}$/.test(key)||!email.test(sender)||!email.test(inbox))return Object.freeze([{id:"sendgrid_account",status:"failed",code:"support_configuration_invalid"},{id:"sendgrid_sender",status:"failed",code:"support_configuration_invalid"},{id:"support_inbox",status:"failed",code:"support_inbox_invalid"}]);
  const [profileResponse,senderResponse]=await Promise.all([transport({provider:"sendgrid",path:"/v3/user/profile",authorization:`Bearer ${key}`}),transport({provider:"sendgrid",path:"/v3/verified_senders",authorization:`Bearer ${key}`})]),profile=object(profileResponse.body),senderBody=object(senderResponse.body),senders=Array.isArray(senderBody.results)?senderBody.results.map(object):[];
  const accountVerified=profileResponse.status===200&&typeof profile.email==="string"&&email.test(profile.email),senderVerified=senderResponse.status===200&&senders.some(item=>String(item.from_email??"").toLowerCase()===sender&&item.verified===true);
  return Object.freeze([Object.freeze({id:"sendgrid_account",status:accountVerified?"verified":"failed",code:accountVerified?"sendgrid_account_verified":"sendgrid_account_unusable"}),Object.freeze({id:"sendgrid_sender",status:senderVerified?"verified":"failed",code:senderVerified?"sendgrid_sender_verified":"sendgrid_sender_unusable"}),Object.freeze({id:"support_inbox",status:"verified",code:"support_inbox_valid"})]);
}
