import {pool} from "@workspace/db";
let migration:Promise<void>|null=null;
export function startCommercialSubscriptionMigration(){if(!migration)migration=ensureCommercialSubscriptionSchema();return migration;}
export async function waitForCommercialSubscriptionMigration(){await startCommercialSubscriptionMigration();}
export async function ensureCommercialSubscriptionSchema(){
 const client=await pool.connect();
 try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtext('bimlog:commercial-subscription-schema-v1'))");await client.query(`
CREATE TABLE IF NOT EXISTS commercial_subscriptions(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),plan_code text NOT NULL,billing_cycle text NOT NULL,status text NOT NULL,currency text NOT NULL,seat_quantity integer NOT NULL,revision integer NOT NULL DEFAULT 1,started_at timestamptz,canceled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscriptions_plan_chk CHECK(plan_code IN ('professional','team','business','enterprise')),CONSTRAINT commercial_subscriptions_cycle_chk CHECK(billing_cycle IN ('monthly','annual','contract')),CONSTRAINT commercial_subscriptions_status_chk CHECK(status IN ('pending','trialing','active','past_due','suspended','canceling','canceled')),CONSTRAINT commercial_subscriptions_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_subscriptions_seats_chk CHECK(seat_quantity>0),CONSTRAINT commercial_subscriptions_revision_chk CHECK(revision>0));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscriptions_company_active_uidx ON commercial_subscriptions(company_id) WHERE status IN ('pending','trialing','active','past_due','suspended','canceling');
CREATE INDEX IF NOT EXISTS commercial_subscriptions_company_time_idx ON commercial_subscriptions(company_id,created_at DESC);
CREATE TABLE IF NOT EXISTS commercial_subscription_terms(id text PRIMARY KEY,subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),sequence integer NOT NULL,status text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,ended_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscription_terms_sequence_chk CHECK(sequence>0),CONSTRAINT commercial_subscription_terms_status_chk CHECK(status IN ('pending','active','ended','void')),CONSTRAINT commercial_subscription_terms_dates_chk CHECK(ends_at>starts_at));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_terms_sequence_uidx ON commercial_subscription_terms(subscription_id,sequence);
CREATE INDEX IF NOT EXISTS commercial_subscription_terms_status_time_idx ON commercial_subscription_terms(subscription_id,status,starts_at DESC);
CREATE TABLE IF NOT EXISTS commercial_subscription_seats(id text PRIMARY KEY,subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),company_id integer NOT NULL REFERENCES companies(id),seat_number integer NOT NULL,status text NOT NULL,assigned_user_id integer REFERENCES users(id),assigned_at timestamptz,released_at timestamptz,revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscription_seats_number_chk CHECK(seat_number>0),CONSTRAINT commercial_subscription_seats_status_chk CHECK(status IN ('available','assigned','released','revoked')),CONSTRAINT commercial_subscription_seats_assignment_chk CHECK((status='assigned' AND assigned_user_id IS NOT NULL AND assigned_at IS NOT NULL) OR status<>'assigned'),CONSTRAINT commercial_subscription_seats_revision_chk CHECK(revision>0));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_seats_number_uidx ON commercial_subscription_seats(subscription_id,seat_number);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_seats_active_user_uidx ON commercial_subscription_seats(subscription_id,assigned_user_id) WHERE status='assigned';
CREATE INDEX IF NOT EXISTS commercial_subscription_seats_company_status_idx ON commercial_subscription_seats(company_id,status,seat_number);
CREATE TABLE IF NOT EXISTS commercial_orders(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),request_key text NOT NULL,fingerprint text NOT NULL,status text NOT NULL,currency text NOT NULL,subtotal_cents integer NOT NULL,tax_cents integer,total_cents integer,created_by_user_id integer NOT NULL REFERENCES users(id),submitted_at timestamptz,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_orders_status_chk CHECK(status IN ('draft','ready','submitted','completed','canceled','failed')),CONSTRAINT commercial_orders_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_orders_amounts_chk CHECK(subtotal_cents>=0 AND (tax_cents IS NULL OR tax_cents>=0) AND (total_cents IS NULL OR total_cents>=0)),CONSTRAINT commercial_orders_total_chk CHECK(total_cents IS NULL OR (tax_cents IS NOT NULL AND total_cents=subtotal_cents+tax_cents)));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_orders_company_request_uidx ON commercial_orders(company_id,request_key);
CREATE INDEX IF NOT EXISTS commercial_orders_subscription_time_idx ON commercial_orders(subscription_id,created_at DESC);
CREATE TABLE IF NOT EXISTS commercial_provider_bindings(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),provider text NOT NULL,environment text NOT NULL,customer_reference text NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_provider_bindings_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_provider_bindings_environment_chk CHECK(environment IN ('test','live')),CONSTRAINT commercial_provider_bindings_status_chk CHECK(status IN ('active','revoked')));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_provider_bindings_company_provider_uidx ON commercial_provider_bindings(company_id,provider,environment);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_provider_bindings_customer_uidx ON commercial_provider_bindings(provider,environment,customer_reference);
CREATE TABLE IF NOT EXISTS commercial_checkout_attempts(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),order_id text NOT NULL REFERENCES commercial_orders(id),provider_binding_id text NOT NULL REFERENCES commercial_provider_bindings(id),idempotency_key text NOT NULL,request_fingerprint text NOT NULL,provider_session_reference text,status text NOT NULL,expires_at timestamptz NOT NULL,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_checkout_attempts_status_chk CHECK(status IN ('creating','open','completed','expired','canceled','failed')));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_checkout_attempts_company_key_uidx ON commercial_checkout_attempts(company_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_checkout_attempts_provider_session_uidx ON commercial_checkout_attempts(provider_binding_id,provider_session_reference) WHERE provider_session_reference IS NOT NULL;
CREATE INDEX IF NOT EXISTS commercial_checkout_attempts_order_time_idx ON commercial_checkout_attempts(order_id,created_at DESC);
`);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}
