import assert from "node:assert/strict";
import {deriveCommercialRuntimeWorkspace} from "./commercial-workspace-runtime";
import fs from "node:fs";
const checks=(ready:boolean[])=>["subscription_catalog","payment_provider","payment_webhook","billing_portal","support_channel"].slice(0,ready.length).map((service,index)=>({service,status:ready[index]?"ready":"not_configured",code:ready[index]?"service_ready":"service_invalid"})) as any;
const coverage=(ready:boolean)=>["professional.monthly","professional.annual","team.monthly","team.annual","business.monthly","business.annual"].map((slot,index)=>({slot,status:ready||index>0?"ready":"missing"})) as any;
const incomplete=deriveCommercialRuntimeWorkspace({companyId:7,companyName:"BIMCorp",memberCount:12,commercialAccess:true,subscriptionStatus:"not_configured",catalogConfigured:false,billingIdentityComplete:false,paymentProviderConfigured:false,webhookConfigured:false,billingPortalConfigured:false,supportConfigured:true,providerMode:"unavailable",salesLaunchStatus:"blocked",salesLaunchBlockers:["catalog","provider","webhook","portal"],platformChecks:checks([false,false,false,false,true]),catalogCoverage:coverage(false)});
assert.equal(incomplete.readiness,"action_required");
assert.deepEqual(incomplete.blockers,["SUBSCRIPTION_NOT_CONFIGURED","BILLING_IDENTITY_INCOMPLETE","PAYMENT_PROVIDER_NOT_CONFIGURED","WEBHOOK_NOT_CONFIGURED","BILLING_PORTAL_NOT_CONFIGURED"]);
assert.deepEqual(incomplete.actions.map(action=>[action.id,action.status,action.href]),[["complete_billing_identity","available","/settings/company-profile"],["review_plans","available","/pricing"],["contact_support","available","/contact"]]);
assert.deepEqual(incomplete.responsibilities,{customer:["BILLING_IDENTITY_INCOMPLETE"],bimlog:["SUBSCRIPTION_NOT_CONFIGURED","PAYMENT_PROVIDER_NOT_CONFIGURED","WEBHOOK_NOT_CONFIGURED","BILLING_PORTAL_NOT_CONFIGURED"],customerReadiness:"action_required",platformReadiness:"action_required"});
const ready=deriveCommercialRuntimeWorkspace({companyId:7,companyName:"BIMCorp",memberCount:12,commercialAccess:true,subscriptionStatus:"active",catalogConfigured:true,billingIdentityComplete:true,paymentProviderConfigured:true,webhookConfigured:true,billingPortalConfigured:true,supportConfigured:true,providerMode:"live",salesLaunchStatus:"ready",salesLaunchBlockers:[],platformChecks:checks([true,true,true,true,true]),catalogCoverage:coverage(true)});
assert.deepEqual({mode:ready.providerMode,status:ready.salesLaunchStatus,blockers:ready.salesLaunchBlockers},{mode:"live",status:"ready",blockers:[]});
assert.deepEqual({readiness:ready.readiness,provider:ready.paymentProviderStatus,portal:ready.billingPortalStatus},{readiness:"ready",provider:"ready",portal:"ready"});
assert.equal(ready.actions.find(action=>action.id==="complete_billing_identity")?.status,"complete");
assert.deepEqual(ready.responsibilities,{customer:[],bimlog:[],customerReadiness:"ready",platformReadiness:"ready"});
assert.equal(JSON.stringify(ready).includes("secret"),false);
assert.equal(ready.platformChecks.length,5);
assert.throws(()=>deriveCommercialRuntimeWorkspace({...ready,subscriptionStatus:"active",catalogConfigured:true,billingIdentityComplete:true,paymentProviderConfigured:true,webhookConfigured:true,billingPortalConfigured:true,supportConfigured:true,platformChecks:checks([true,true,true,true]),catalogCoverage:coverage(true)}),/incomplete/);
assert.throws(()=>deriveCommercialRuntimeWorkspace({...ready,subscriptionStatus:"active",catalogConfigured:true,billingIdentityComplete:true,paymentProviderConfigured:true,webhookConfigured:true,billingPortalConfigured:true,supportConfigured:true,platformChecks:checks([true,true,true,true,true]),catalogCoverage:coverage(false)}),/catalog coverage/);
assert.throws(()=>deriveCommercialRuntimeWorkspace({...ready,subscriptionStatus:"active",catalogConfigured:true,billingIdentityComplete:true,paymentProviderConfigured:true,webhookConfigured:true,billingPortalConfigured:true,supportConfigured:true,salesLaunchStatus:"ready",salesLaunchBlockers:["live_mode"],providerMode:"test"}),/contradictory/);
console.log("B066 live commercial readiness projection: PASS");
const route=fs.readFileSync(new URL("../routes/commercial-workspace.ts",import.meta.url),"utf8");
assert.match(route,/router\.get\("\/commercial\/workspace",authMiddleware/);
assert.match(route,/COMMERCIAL_WORKSPACE_UNAVAILABLE/);
assert.match(route,/Cache-Control","private, no-store, max-age=0/);
assert.match(route,/Vary","Authorization/);
assert.match(route,/inspectCommercialPlatformReadiness\(process\.env\)/);
assert.doesNotMatch(route,/configured\("STRIPE_SECRET_KEY"\)/);
assert.doesNotMatch(route,/process\.env\[[^\]]+\]\s*[},]/);
console.log("B067 authenticated secret-free commercial workspace endpoint: PASS");
