import assert from "node:assert/strict";
import {deriveCommercialRuntimeWorkspace} from "./commercial-workspace-runtime";
import fs from "node:fs";
const incomplete=deriveCommercialRuntimeWorkspace({companyId:7,companyName:"BIMCorp",memberCount:12,commercialAccess:true,subscriptionConfigured:false,billingIdentityComplete:false,paymentProviderConfigured:false,webhookConfigured:false,billingPortalConfigured:false,supportConfigured:true});
assert.equal(incomplete.readiness,"action_required");
assert.deepEqual(incomplete.blockers,["SUBSCRIPTION_NOT_CONFIGURED","BILLING_IDENTITY_INCOMPLETE","PAYMENT_PROVIDER_NOT_CONFIGURED","WEBHOOK_NOT_CONFIGURED","BILLING_PORTAL_NOT_CONFIGURED"]);
assert.deepEqual(incomplete.actions.map(action=>[action.id,action.status,action.href]),[["complete_billing_identity","available","/settings/company-profile"],["review_plans","available","/pricing"],["contact_support","available","/contact"]]);
assert.deepEqual(incomplete.responsibilities,{customer:["BILLING_IDENTITY_INCOMPLETE"],bimlog:["SUBSCRIPTION_NOT_CONFIGURED","PAYMENT_PROVIDER_NOT_CONFIGURED","WEBHOOK_NOT_CONFIGURED","BILLING_PORTAL_NOT_CONFIGURED"],customerReadiness:"action_required",platformReadiness:"action_required"});
const ready=deriveCommercialRuntimeWorkspace({companyId:7,companyName:"BIMCorp",memberCount:12,commercialAccess:true,subscriptionConfigured:true,billingIdentityComplete:true,paymentProviderConfigured:true,webhookConfigured:true,billingPortalConfigured:true,supportConfigured:true});
assert.deepEqual({readiness:ready.readiness,provider:ready.paymentProviderStatus,portal:ready.billingPortalStatus},{readiness:"ready",provider:"ready",portal:"ready"});
assert.equal(ready.actions.find(action=>action.id==="complete_billing_identity")?.status,"complete");
assert.deepEqual(ready.responsibilities,{customer:[],bimlog:[],customerReadiness:"ready",platformReadiness:"ready"});
assert.equal(JSON.stringify(ready).includes("secret"),false);
console.log("B066 live commercial readiness projection: PASS");
const route=fs.readFileSync(new URL("../routes/commercial-workspace.ts",import.meta.url),"utf8");
assert.match(route,/router\.get\("\/commercial\/workspace",authMiddleware/);
assert.match(route,/COMMERCIAL_WORKSPACE_UNAVAILABLE/);
assert.match(route,/paymentProviderConfigured:configured\("STRIPE_SECRET_KEY"\)/);
assert.doesNotMatch(route,/process\.env\[[^\]]+\]\s*[},]/);
console.log("B067 authenticated secret-free commercial workspace endpoint: PASS");
