import {pool} from "@workspace/db";
let migration:Promise<void>|null=null;
export function startCommercialSubscriptionMigration(){if(!migration)migration=ensureCommercialSubscriptionSchema();return migration;}
export async function waitForCommercialSubscriptionMigration(){await startCommercialSubscriptionMigration();}
export async function ensureCommercialSubscriptionSchema(){
 const client=await pool.connect();
 try{await client.query("BEGIN");await client.query("SELECT pg_advisory_xact_lock(hashtext('bimlog:commercial-subscription-schema-v1'))");await client.query(`
CREATE TABLE IF NOT EXISTS commercial_subscriptions(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),plan_code text NOT NULL,billing_cycle text NOT NULL,status text NOT NULL,currency text NOT NULL,seat_quantity integer NOT NULL,revision integer NOT NULL DEFAULT 1,started_at timestamptz,canceled_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscriptions_plan_chk CHECK(plan_code IN ('professional','team','business','enterprise')),CONSTRAINT commercial_subscriptions_cycle_chk CHECK(billing_cycle IN ('monthly','annual','contract')),CONSTRAINT commercial_subscriptions_status_chk CHECK(status IN ('pending','trialing','active','past_due','suspended','canceling','canceled')),CONSTRAINT commercial_subscriptions_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_subscriptions_seats_chk CHECK(seat_quantity>0),CONSTRAINT commercial_subscriptions_revision_chk CHECK(revision>0));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscriptions_company_active_uidx ON commercial_subscriptions(company_id) WHERE status IN ('pending','trialing','active','past_due','suspended','canceling');
CREATE INDEX IF NOT EXISTS commercial_subscriptions_company_time_idx ON commercial_subscriptions(company_id,created_at DESC);
CREATE TABLE IF NOT EXISTS commercial_subscription_terms(id text PRIMARY KEY,subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),sequence integer NOT NULL,status text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,ended_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscription_terms_sequence_chk CHECK(sequence>0),CONSTRAINT commercial_subscription_terms_status_chk CHECK(status IN ('pending','active','ended','void')),CONSTRAINT commercial_subscription_terms_dates_chk CHECK(ends_at>starts_at));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_terms_sequence_uidx ON commercial_subscription_terms(subscription_id,sequence);
CREATE INDEX IF NOT EXISTS commercial_subscription_terms_status_time_idx ON commercial_subscription_terms(subscription_id,status,starts_at DESC);
CREATE TABLE IF NOT EXISTS commercial_subscription_seats(id text PRIMARY KEY,subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),company_id integer NOT NULL REFERENCES companies(id),seat_number integer NOT NULL,status text NOT NULL,assigned_user_id integer REFERENCES users(id),assigned_at timestamptz,released_at timestamptz,revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_subscription_seats_number_chk CHECK(seat_number>0),CONSTRAINT commercial_subscription_seats_status_chk CHECK(status IN ('available','assigned','released','revoked')),CONSTRAINT commercial_subscription_seats_assignment_chk CHECK((status='assigned' AND assigned_user_id IS NOT NULL AND assigned_at IS NOT NULL) OR status<>'assigned'),CONSTRAINT commercial_subscription_seats_revision_chk CHECK(revision>0));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_seats_number_uidx ON commercial_subscription_seats(subscription_id,seat_number);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_subscription_seats_active_user_uidx ON commercial_subscription_seats(subscription_id,assigned_user_id) WHERE status='assigned';
CREATE INDEX IF NOT EXISTS commercial_subscription_seats_company_status_idx ON commercial_subscription_seats(company_id,status,seat_number);
CREATE TABLE IF NOT EXISTS commercial_orders(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),request_key text NOT NULL,fingerprint text NOT NULL,status text NOT NULL,currency text NOT NULL,subtotal_cents integer NOT NULL,tax_cents integer,total_cents integer,created_by_user_id integer NOT NULL REFERENCES users(id),submitted_at timestamptz,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_orders_status_chk CHECK(status IN ('draft','ready','submitted','completed','canceled','failed')),CONSTRAINT commercial_orders_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_orders_amounts_chk CHECK(subtotal_cents>=0 AND (tax_cents IS NULL OR tax_cents>=0) AND (total_cents IS NULL OR total_cents>=0)),CONSTRAINT commercial_orders_total_chk CHECK(total_cents IS NULL OR (tax_cents IS NOT NULL AND total_cents=subtotal_cents+tax_cents)));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_orders_company_request_uidx ON commercial_orders(company_id,request_key);
CREATE INDEX IF NOT EXISTS commercial_orders_subscription_time_idx ON commercial_orders(subscription_id,created_at DESC);
CREATE TABLE IF NOT EXISTS commercial_provider_bindings(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),provider text NOT NULL,environment text NOT NULL,customer_reference text NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_provider_bindings_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_provider_bindings_environment_chk CHECK(environment IN ('test','live')),CONSTRAINT commercial_provider_bindings_status_chk CHECK(status IN ('active','revoked')));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_provider_bindings_company_provider_uidx ON commercial_provider_bindings(company_id,provider,environment);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_provider_bindings_customer_uidx ON commercial_provider_bindings(provider,environment,customer_reference);
CREATE TABLE IF NOT EXISTS commercial_checkout_attempts(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),order_id text NOT NULL REFERENCES commercial_orders(id),provider_binding_id text NOT NULL REFERENCES commercial_provider_bindings(id),idempotency_key text NOT NULL,request_fingerprint text NOT NULL,provider_session_reference text,status text NOT NULL,expires_at timestamptz NOT NULL,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_checkout_attempts_status_chk CHECK(status IN ('creating','open','completed','expired','canceled','failed')));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_checkout_attempts_company_key_uidx ON commercial_checkout_attempts(company_id,idempotency_key);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_checkout_attempts_provider_session_uidx ON commercial_checkout_attempts(provider_binding_id,provider_session_reference) WHERE provider_session_reference IS NOT NULL;
CREATE INDEX IF NOT EXISTS commercial_checkout_attempts_order_time_idx ON commercial_checkout_attempts(order_id,created_at DESC);
CREATE TABLE IF NOT EXISTS commercial_invoices(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),order_id text NOT NULL REFERENCES commercial_orders(id),checkout_attempt_id text NOT NULL REFERENCES commercial_checkout_attempts(id),invoice_number text NOT NULL,provider text NOT NULL,provider_invoice_reference text NOT NULL,currency text NOT NULL,subtotal_cents integer NOT NULL,tax_cents integer NOT NULL,total_cents integer NOT NULL,status text NOT NULL,issued_at timestamptz NOT NULL,due_at timestamptz,paid_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_invoices_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_invoices_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_invoices_status_chk CHECK(status IN ('draft','open','paid','void','uncollectible')),CONSTRAINT commercial_invoices_amounts_chk CHECK(subtotal_cents>=0 AND tax_cents>=0 AND total_cents=subtotal_cents+tax_cents),CONSTRAINT commercial_invoices_paid_chk CHECK(status<>'paid' OR paid_at IS NOT NULL));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_invoices_number_uidx ON commercial_invoices(invoice_number);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_invoices_provider_ref_uidx ON commercial_invoices(provider,provider_invoice_reference);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_invoices_checkout_uidx ON commercial_invoices(checkout_attempt_id);
CREATE INDEX IF NOT EXISTS commercial_invoices_company_time_idx ON commercial_invoices(company_id,issued_at DESC);
CREATE INDEX IF NOT EXISTS commercial_invoices_subscription_time_idx ON commercial_invoices(subscription_id,issued_at DESC);
CREATE TABLE IF NOT EXISTS commercial_credit_notes(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),invoice_id text NOT NULL REFERENCES commercial_invoices(id),credit_number text NOT NULL,provider text NOT NULL,provider_event_reference text NOT NULL,currency text NOT NULL,amount_cents integer NOT NULL,reason text NOT NULL,status text NOT NULL,approved_by_user_id integer NOT NULL REFERENCES users(id),issued_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_credit_notes_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_credit_notes_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_credit_notes_amount_chk CHECK(amount_cents>0),CONSTRAINT commercial_credit_notes_reason_chk CHECK(char_length(reason) BETWEEN 3 AND 500),CONSTRAINT commercial_credit_notes_status_chk CHECK(status IN ('issued','void')));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_credit_notes_number_uidx ON commercial_credit_notes(credit_number);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_credit_notes_provider_event_uidx ON commercial_credit_notes(provider,provider_event_reference);
CREATE INDEX IF NOT EXISTS commercial_credit_notes_invoice_time_idx ON commercial_credit_notes(invoice_id,issued_at DESC);
CREATE TABLE IF NOT EXISTS commercial_disputes(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text NOT NULL REFERENCES commercial_subscriptions(id),invoice_id text NOT NULL REFERENCES commercial_invoices(id),provider text NOT NULL,provider_dispute_reference text NOT NULL,currency text NOT NULL,amount_cents integer NOT NULL,reason_code text NOT NULL,status text NOT NULL,evidence_due_at timestamptz,closed_at timestamptz,revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_disputes_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_disputes_currency_chk CHECK(currency ~ '^[A-Z]{3}$'),CONSTRAINT commercial_disputes_amount_chk CHECK(amount_cents>0),CONSTRAINT commercial_disputes_status_chk CHECK(status IN ('needs_response','under_review','won','lost','withdrawn')),CONSTRAINT commercial_disputes_closed_chk CHECK(status IN ('needs_response','under_review') OR closed_at IS NOT NULL),CONSTRAINT commercial_disputes_revision_chk CHECK(revision>0));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_disputes_provider_ref_uidx ON commercial_disputes(provider,provider_dispute_reference);
CREATE INDEX IF NOT EXISTS commercial_disputes_company_status_idx ON commercial_disputes(company_id,status,updated_at DESC);
CREATE INDEX IF NOT EXISTS commercial_disputes_invoice_idx ON commercial_disputes(invoice_id);
CREATE TABLE IF NOT EXISTS commercial_provider_receipts(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),provider_binding_id text NOT NULL REFERENCES commercial_provider_bindings(id),provider text NOT NULL,provider_event_reference text NOT NULL,event_type text NOT NULL,payload_digest text NOT NULL,raw_payload text NOT NULL,signature_verified_at timestamptz NOT NULL,processing_status text NOT NULL,processed_at timestamptz,failure_code text,received_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_provider_receipts_provider_chk CHECK(provider IN ('stripe')),CONSTRAINT commercial_provider_receipts_digest_chk CHECK(payload_digest ~ '^[0-9a-f]{64}$'),CONSTRAINT commercial_provider_receipts_status_chk CHECK(processing_status IN ('received','processing','applied','ignored','failed')),CONSTRAINT commercial_provider_receipts_processed_chk CHECK(processing_status IN ('received','processing') OR processed_at IS NOT NULL));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_provider_receipts_event_uidx ON commercial_provider_receipts(provider,provider_event_reference);
CREATE INDEX IF NOT EXISTS commercial_provider_receipts_company_time_idx ON commercial_provider_receipts(company_id,received_at DESC);
CREATE INDEX IF NOT EXISTS commercial_provider_receipts_status_time_idx ON commercial_provider_receipts(processing_status,received_at);
CREATE TABLE IF NOT EXISTS commercial_audit_events(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),subscription_id text REFERENCES commercial_subscriptions(id),provider_receipt_id text REFERENCES commercial_provider_receipts(id),sequence integer NOT NULL,event_type text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,actor_user_id integer REFERENCES users(id),event_digest text NOT NULL,previous_event_digest text,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_audit_events_sequence_chk CHECK(sequence>0),CONSTRAINT commercial_audit_events_digest_chk CHECK(event_digest ~ '^[0-9a-f]{64}$'),CONSTRAINT commercial_audit_events_previous_digest_chk CHECK(previous_event_digest IS NULL OR previous_event_digest ~ '^[0-9a-f]{64}$'));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_audit_events_company_sequence_uidx ON commercial_audit_events(company_id,sequence);
CREATE UNIQUE INDEX IF NOT EXISTS commercial_audit_events_digest_uidx ON commercial_audit_events(company_id,event_digest);
CREATE INDEX IF NOT EXISTS commercial_audit_events_entity_time_idx ON commercial_audit_events(company_id,entity_type,entity_id,occurred_at);
CREATE TABLE IF NOT EXISTS commercial_launch_verifications(id text PRIMARY KEY,actor_user_id integer NOT NULL REFERENCES users(id),source_commit text NOT NULL,status text NOT NULL,verified text NOT NULL,checked_at timestamptz NOT NULL,valid_until timestamptz NOT NULL,check_count integer NOT NULL,failed_check_ids_json text NOT NULL,checks_json text NOT NULL,evidence_sha256 text NOT NULL,recorded_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT commercial_launch_verifications_source_chk CHECK(source_commit ~ '^[0-9a-f]{40}$'),CONSTRAINT commercial_launch_verifications_status_chk CHECK(status IN ('configuration_blocked','verified','failed')),CONSTRAINT commercial_launch_verifications_verified_chk CHECK(verified IN ('true','false')),CONSTRAINT commercial_launch_verifications_count_chk CHECK(check_count>=0 AND check_count<=32),CONSTRAINT commercial_launch_verifications_digest_chk CHECK(evidence_sha256 ~ '^[0-9a-f]{64}$'),CONSTRAINT commercial_launch_verifications_window_chk CHECK(valid_until>checked_at));
CREATE UNIQUE INDEX IF NOT EXISTS commercial_launch_verifications_digest_uidx ON commercial_launch_verifications(evidence_sha256);
CREATE INDEX IF NOT EXISTS commercial_launch_verifications_source_time_idx ON commercial_launch_verifications(source_commit,checked_at DESC);
`);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}
}
