import assert from "node:assert/strict";
import crypto from "node:crypto";
import {prepareCompanySubscription} from "./commercial-subscription-setup";
const calls:string[]=[];const client={query:async(text:string)=>{calls.push(text);if(text.startsWith("SELECT * FROM commercial_subscriptions")||text.startsWith("SELECT s.id"))return {rows:[],rowCount:0};return {rows:[{id:47}],rowCount:1};}};
const base={client,environment:{STRIPE_SECRET_KEY:"sk_test_abcdefghijklmnop",STRIPE_WEBHOOK_SECRET:"whsec_abcdefghijklmnop",BIMLOG_STRIPE_PRICE_IDS:"team.annual=price_team_annual",BIMLOG_APP_ORIGIN:"https://bimlog.app"},companyId:47,userId:9,companyName:"BIM Tech",billingEmail:"owner@example.com",billingAddress:"100 Test Way",billingPhone:"+1 555 0100",requestKey:"subscription-setup-47-0001",plan:"team",cycle:"annual"} as const;
const result=await prepareCompanySubscription({...base,transport:async request=>{assert.equal(request.path,"/v1/customers");assert.equal(request.headers["Idempotency-Key"],`customer-${crypto.createHash("sha256").update("47").digest("hex").slice(0,32)}`);return {status:200,body:{id:"cus_company_47",metadata:{company_id:"47"}}};}});
assert.deepEqual({status:result.status,replayed:result.replayed,plan:result.plan,billingCycle:result.billingCycle,seatQuantity:result.seatQuantity},{status:"pending",replayed:false,plan:"team",billingCycle:"annual",seatQuantity:5});assert.ok(calls.some(text=>text.includes("INSERT INTO commercial_subscriptions")));
await assert.rejects(()=>prepareCompanySubscription({...base,requestKey:"short"}),/request identity/);
await assert.rejects(()=>prepareCompanySubscription({...base,billingAddress:null}),/Complete company billing identity/);
console.log("B293 end-to-end company subscription preparation: PASS");
