import assert from "node:assert/strict";
import fs from "node:fs";
import { COMPANY_MASTER_CATALOG_SQL, ensureCompanyMasterCatalogSchema } from "./company-master-catalog-migration";

const calls: string[] = [];
let released = false;
await ensureCompanyMasterCatalogSchema({ connect: async () => ({ query: async sql => { calls.push(sql); }, release: () => { released = true; } }) });
assert.equal(calls[0], "BEGIN");
assert.match(calls[1]!, /pg_advisory_xact_lock/);
assert.equal(calls[2], COMPANY_MASTER_CATALOG_SQL);
assert.equal(calls[3], "COMMIT");
assert.equal(released, true);
const failedCalls: string[] = [];
let failureReleased = false;
await assert.rejects(ensureCompanyMasterCatalogSchema({ connect: async () => ({ query: async sql => { failedCalls.push(sql); if (sql === COMPANY_MASTER_CATALOG_SQL) throw new Error("migration-failed"); }, release: () => { failureReleased = true; } }) }), /migration-failed/);
assert.equal(failedCalls.at(-1), "ROLLBACK");
assert.equal(failureReleased, true);
assert.match(COMPANY_MASTER_CATALOG_SQL, /UNIQUE\(company_id,kind,code\)/);
assert.match(COMPANY_MASTER_CATALOG_SQL, /company_master_catalog_admin_active_uq/);
assert.match(COMPANY_MASTER_CATALOG_SQL, /canonical_company_id integer REFERENCES companies/);
assert.doesNotMatch(COMPANY_MASTER_CATALOG_SQL, /\bDROP\b|\bDELETE\b/i);

const route = fs.readFileSync(new URL("../routes/company-master-catalogs.ts", import.meta.url), "utf8");
const selector = fs.readFileSync(new URL("../routes/master-catalogs.ts", import.meta.url), "utf8");
const intake = fs.readFileSync(new URL("./job-intake-service.ts", import.meta.url), "utf8");
const directory = fs.readFileSync(new URL("../routes/project_directory.ts", import.meta.url), "utf8");
const admin = fs.readFileSync(new URL("../../../../artifacts/bimlog/src/components/admin/CompanyMasterCatalogsTab.tsx", import.meta.url), "utf8");
const clientUi = fs.readFileSync(new URL("../../../../artifacts/bimlog/src/components/job-intake/ProjectCompanyCreator.tsx", import.meta.url), "utf8");
const intakeUi = fs.readFileSync(new URL("../../../../artifacts/bimlog/src/pages/JobIntakeWorkspace.tsx", import.meta.url), "utf8");
for (const kind of ["client", "discipline", "service", "phase"]) assert.match(route, new RegExp(`"${kind}"`));
assert.match(route, /a\.company_id=u\.company_id AND a\.user_id=u\.id AND a\.state='active'/);
assert.match(route, /WHERE company_id=\$1 AND kind=\$2/);
assert.match(route, /authMiddleware, isSuperAdminMiddleware/);
assert.match(route, /expectedVersion/);
assert.match(route, /SELECT id,company_id,email,full_name FROM users WHERE lower\(email\)/);
assert.match(selector, /PROJECT_CATALOG_SCOPE_FORBIDDEN/);
assert.match(selector, /company_master_catalog_entries WHERE company_id=\$1 AND kind=\$2/);
assert.match(intake, /company_master_catalog_entries WHERE id=\$1 AND company_id=\$2 AND kind=\$3/);
assert.match(intake, /JOB_INTAKE_CLIENT_CATALOG_REQUIRED/);
assert.match(directory, /approved_client_catalog_selection_required/);
assert.match(directory, /client_not_in_company_catalog/);
assert.match(admin, /Company Master Catalogs/);
assert.match(admin, /client: \["Clients", "Clientes"\]/);
assert.match(admin, /company\/master-catalogs\/capabilities/);
assert.match(admin, /grant\("grant"\)/);
assert.match(clientUi, /master-catalogs\/clients\?projectId=/);
assert.match(clientUi, /catalogGoverned/);
assert.match(clientUi, /canonical_company_id/);
assert.match(intakeUi, /clientName: value/);
assert.match(intakeUi, /aria-readonly="true"/);
assert.doesNotMatch(route, /\.delete\(|\bDELETE FROM\b/i);
console.log("Company master catalogs: transaction, four kinds, PMO grant, tenant-bound choices, optimistic version, and Intake scope PASS");
