import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const read = (relative: string) => fs.readFileSync(path.resolve(here, relative), "utf8");
const app = read("../app.ts");
const routesIndex = read("../routes/index.ts");
const route = read("../routes/coordination-hub.ts");
const store = read("./coordination-hub-postgres-store.ts");
const configurationService = read("./coordination-hub-configuration-service.ts");
const configurationStore = read("./coordination-hub-configuration-postgres-store.ts");
const sharePointValidator = read("./sharepoint-credential-validator.ts");
const protectedExecutor = read("./protected-provider-probe-executor.ts");
const connectorEnvelope = read("./connector-credential-envelope.ts");

assert.match(app, /queueDatabaseStartup\(async \(\) => \{[\s\S]*startEnterpriseIdentityMigration\(\)[\s\S]*waitForEnterpriseIdentityMigration\(\)[\s\S]*ensureConnectorFoundationSchema\(pool\)/);
assert.match(routesIndex, /coordinationHubRouter/);
assert.match(route, /authMiddleware, requireProjectMember\(\)/);
assert.match(route, /router\.get\("\/projects\/:projectId\/coordination-hub\/summary"/);
assert.match(route, /coordination-hub\/credentials", authMiddleware, requireProjectMember\("project_admin"\)/);
assert.match(route, /coordination-hub\/credentials\/:credentialId\/validate", authMiddleware, requireProjectMember\("project_admin"\)/);
assert.match(route, /coordination-hub\/sharepoint-mapping", authMiddleware, requireProjectMember\("project_admin"\)/);
assert.match(route, /companyId: req\.user!\.companyId/);
assert.match(route, /createRuntimeSharePointCredentialValidator/);
assert.match(route, /actorUserId: req\.user!\.userId/);
assert.doesNotMatch(route, /body\.scope/);
assert.match(route, /COORDINATION_INPUT_INVALID/);
assert.match(route, /COORDINATION_OPERATION_FAILED/);
assert.doesNotMatch(route, /error instanceof Error \? error\.message/);
assert.match(store, /BEGIN/);
assert.match(store, /COMMIT/);
assert.match(store, /ROLLBACK/);
assert.match(store, /BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY/);
assert.match(store, /ORDER BY f\.created_at DESC,f\.id ASC LIMIT 20/);
assert.match(store, /ORDER BY created_at DESC,id ASC LIMIT 20/);
assert.match(store, /u\.is_super_admin OR EXISTS\([\s\S]*project_members/);
assert.match(store, /c\.company_id=\$2 AND c\.provider=\$4 AND c\.state='active'/);
assert.match(store, /EXISTS\(SELECT 1 FROM files WHERE id=\$5 AND project_id=\$3\)/);
assert.doesNotMatch(store, /SELECT \*/);
assert.match(configurationService, /state: "pending_validation"/);
assert.match(configurationService, /Folder path cannot contain a parent traversal segment/);
assert.doesNotMatch(configurationService, /secret:\s*z\./);
assert.match(configurationStore, /provider='sharepoint' AND state='active'/);
assert.match(configurationStore, /coordination_credential_activated/);
assert.match(configurationStore, /coordination_credential_validation_rejected/);
assert.match(configurationStore, /state='pending_validation'/);
assert.match(configurationStore, /pm\.role='project_admin'/);
assert.match(configurationStore, /BEGIN/);
assert.match(configurationStore, /ROLLBACK/);
assert.doesNotMatch(configurationStore, /SELECT \*/);
assert.match(sharePointValidator, /https:\/\/graph\.microsoft\.com/);
assert.match(sharePointValidator, /BIMLOG_SHAREPOINT_VALIDATION_ENABLED/);
assert.match(sharePointValidator, /isSharePointValidationAllowed/);
assert.match(sharePointValidator, /createRuntimeProtectedProviderProbeExecutor/);
assert.doesNotMatch(sharePointValidator, /\bfetch\s*\(/);
assert.doesNotMatch(sharePointValidator, /client_secret|access_token|Authorization/i);
assert.match(protectedExecutor, /unavailableProtectedBearerLeaseResolver/);
assert.match(protectedExecutor, /response\.body\.cancel\(\)/);
assert.match(protectedExecutor, /token\.fill\(0\)/);
assert.match(protectedExecutor, /request\.url !== GRAPH_PROBE_URL/);
assert.doesNotMatch(protectedExecutor, /console\.(?:log|error|warn)/);
assert.match(connectorEnvelope, /aes-256-gcm/);
assert.match(connectorEnvelope, /BIMLOG_CONNECTOR_KEK_V/);
assert.match(connectorEnvelope, /bimlog\.connector-credential-envelope\.v1/);
assert.match(connectorEnvelope, /credentialId: context\.credentialId/);
assert.match(connectorEnvelope, /companyId: context\.companyId/);
assert.match(connectorEnvelope, /provider: context\.provider/);
assert.match(connectorEnvelope, /keyVersion: context\.keyVersion/);
assert.doesNotMatch(connectorEnvelope, /AI_PROVIDER_KEK/);
assert.doesNotMatch(connectorEnvelope, /console\.(?:log|error|warn)/);
console.log("coordination hub runtime behavior: PASS");
