import assert from "node:assert/strict";
import { prepareBonusProposal, verifyBonusCapacity, verifyIndependentBonusDecision, type BonusReservation } from "./cost-value-bonus-allocation";
import type { FinancialDecision } from "./financial-control-contract";
const funding = { id: "reserve-1", version: 2, fingerprint: "a".repeat(64), companyId: 7, projectId: 11, reserve: { amount: "100", currency: "USD" } };
const input = { funding, makerUserId: 1, reason: "Verified manual proposal", entries: [{ userId: 3, amount: "0.000001" }, { userId: 2, amount: "49.999999" }], eligibleUserIds: [2, 3] };
const proposal = prepareBonusProposal(input);
assert.equal(proposal.total.amount, "50");
assert.equal(proposal.paymentAuthorized, false);
assert.equal(prepareBonusProposal({ ...input, entries: [...input.entries].reverse() }).fingerprint, proposal.fingerprint);
const rejects = (work: () => unknown, code: string) => assert.throws(work, (e: any) => e.code === code);
rejects(() => prepareBonusProposal({ ...input, entries: [{ userId: 2, amount: "1" }, { userId: 2, amount: "2" }] }), "BONUS_RECIPIENT_DUPLICATE");
rejects(() => prepareBonusProposal({ ...input, eligibleUserIds: [2] }), "BONUS_RECIPIENT_INELIGIBLE");
rejects(() => prepareBonusProposal({ ...input, entries: [{ userId: 2, amount: "0" }] }), "BONUS_AMOUNT_REQUIRED");
rejects(() => prepareBonusProposal({ ...input, entries: [{ userId: 2, amount: "100.000001" }] }), "BONUS_RESERVE_EXCEEDED");
const reservation: BonusReservation = { id: "other", fundingId: funding.id, companyId: 7, projectId: 11, state: "pending", amount: { amount: "50", currency: "USD" } };
verifyBonusCapacity(proposal, [reservation]);
verifyBonusCapacity(proposal, [{ ...reservation, state: "rejected", amount: { amount: "999", currency: "USD" } }]);
for (const state of ["pending", "approved"] as const)
  rejects(() => verifyBonusCapacity(proposal, [{ ...reservation, state, amount: { amount: "50.000001", currency: "USD" } }]), "BONUS_RESERVE_EXCEEDED");
rejects(() => verifyBonusCapacity(proposal, [reservation, reservation]), "BONUS_RESERVATION_DUPLICATE");
rejects(() => verifyBonusCapacity(proposal, [{ ...reservation, companyId: 8 }]), "BONUS_RESERVATION_SCOPE_MISMATCH");
rejects(() => verifyBonusCapacity(proposal, [{ ...reservation, amount: { amount: "1", currency: "EUR" } }]), "BONUS_CURRENCY_MISMATCH");
const authority: FinancialDecision = { decision: "allow", code: "FIN_ALLOWED", explanation: { en: "Allowed", es: "Permitido" }, matchedGrantIds: ["grant"], policyId: "policy-2" };
const decision = { actorUserId: 4, expectedFingerprint: proposal.fingerprint, authority };
verifyIndependentBonusDecision(proposal, decision);
for (const actorUserId of [1, 2, 3]) rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, actorUserId }), "BONUS_INDEPENDENT_REVIEW_REQUIRED");
rejects(() => verifyIndependentBonusDecision({ ...proposal, reason: "Changed after submission" }, decision), "BONUS_PROPOSAL_STALE");
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, authority: { ...authority, decision: "deny", code: "FIN_AUTHORITY_MISSING" } }), "FIN_AUTHORITY_MISSING");
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, authority: { ...authority, requiresHigherReview: true } }), "BONUS_HIGHER_REVIEW_REQUIRED");
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, authority: { ...authority, policyId: undefined } }), "BONUS_APPROVAL_POLICY_REQUIRED");
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, authority: { ...authority, matchedGrantIds: [] } }), "BONUS_APPROVAL_POLICY_REQUIRED");
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, authority: { ...authority, selfApprovalOverride: true } }), "BONUS_HIGHER_REVIEW_REQUIRED");
assert.equal(proposal.paymentAuthorized, false);
console.log("C018 manual bonus proposal rules PASS: exact amounts, reservation capacity, scoped sources, independent decisions; no persistence or payment claim");
verifyIndependentBonusDecision(proposal, { ...decision, outcome: "rejected", authority: { ...authority, policyId: undefined } });
rejects(() => verifyIndependentBonusDecision(proposal, { ...decision, actorUserId: 1, outcome: "rejected" }), "BONUS_INDEPENDENT_REVIEW_REQUIRED");
