import assert from "node:assert/strict";
import fs from "node:fs";
const route=fs.readFileSync(new URL("../routes/edt-engine.ts",import.meta.url),"utf8");
assert.match(route,/activation-requests", authMiddleware/);
assert.match(route,/activation-requests\/:requestId\/approve", authMiddleware/);
assert.match(route,/companyId: actor\.actorCompanyId, projectId/);
assert.match(route,/workflowVersionIds must be a string array/);
assert.doesNotMatch(route,/companyId:\s*Number\(body/);
assert.doesNotMatch(route,/actor:\s*body/);
console.log("EDT_ENGINE_BUILD297_RESULT=PASS");
console.log("ACTIVATION_ROUTES=PASS");
