type MigrationPool = { connect(): Promise<{ query(sql: string): Promise<unknown>; release(): void }> };

export async function ensureFeedbackSchema(pool: MigrationPool) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    const statements = [
      `CREATE TABLE IF NOT EXISTS feedback_items (id serial PRIMARY KEY,user_id integer NOT NULL REFERENCES users(id),project_id integer REFERENCES projects(id),feedback_type text NOT NULL,priority text NOT NULL DEFAULT 'normal',module text,page_url text NOT NULL,message text NOT NULL,status text NOT NULL DEFAULT 'new',stable_id text,company_id integer,owner_user_id integer REFERENCES users(id),target_release text,disposition_reason text,customer_visible boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,idempotency_key text,request_hash text,transcript text,transcript_provenance text,metadata jsonb,created_at timestamp NOT NULL DEFAULT now(),updated_at timestamp NOT NULL DEFAULT now(),resolved_at timestamp)`,
      `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS stable_id text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS company_id integer`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS owner_user_id integer REFERENCES users(id)`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS target_release text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS disposition_reason text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS customer_visible boolean NOT NULL DEFAULT true`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS idempotency_key text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS request_hash text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS transcript text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS transcript_provenance text`,
      `UPDATE feedback_items SET status=CASE status WHEN 'open' THEN 'new' WHEN 'in_review' THEN 'triaged' WHEN 'planned' THEN 'accepted' WHEN 'done' THEN 'verified' ELSE status END WHERE status IN ('open','in_review','planned','done')`,
      `UPDATE feedback_items SET stable_id='FB-'||lpad(id::text,8,'0') WHERE stable_id IS NULL`, `UPDATE feedback_items f SET company_id=u.company_id FROM users u WHERE f.user_id=u.id AND f.company_id IS NULL`,
      `ALTER TABLE feedback_items ALTER COLUMN stable_id SET NOT NULL`, `ALTER TABLE feedback_items ALTER COLUMN company_id SET NOT NULL`,
      `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_company_id_fkey FOREIGN KEY(company_id) REFERENCES companies(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$`, `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_status_chk CHECK(status IN ('new','triaged','accepted','in_progress','blocked','fixed','verified','rejected','deferred')); EXCEPTION WHEN duplicate_object THEN NULL; END $$`, `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_version_chk CHECK(version>0); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `CREATE UNIQUE INDEX IF NOT EXISTS feedback_items_stable_id_idx ON feedback_items(stable_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_items_user_idempotency_idx ON feedback_items(user_id,idempotency_key) WHERE idempotency_key IS NOT NULL`,
      `CREATE INDEX IF NOT EXISTS feedback_items_status_created_idx ON feedback_items(status,created_at DESC)`, `CREATE INDEX IF NOT EXISTS feedback_items_user_created_idx ON feedback_items(user_id,created_at DESC)`, `CREATE INDEX IF NOT EXISTS feedback_items_project_created_idx ON feedback_items(project_id,created_at DESC)`,
      `CREATE TABLE IF NOT EXISTS feedback_assets (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),project_id integer REFERENCES projects(id),uploaded_by_id integer NOT NULL REFERENCES users(id),kind text NOT NULL,original_name text NOT NULL,safe_name text NOT NULL,media_type text NOT NULL,byte_size bigint NOT NULL,sha256 text NOT NULL,storage_path text NOT NULL,scan_state text NOT NULL DEFAULT 'quarantined',scanner_adapter text NOT NULL DEFAULT 'default-deny',scanned_at timestamp,retention_hold boolean NOT NULL DEFAULT true,expires_at timestamp,provenance jsonb NOT NULL DEFAULT '{}',created_at timestamp NOT NULL DEFAULT now())`,
      `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS scanner_adapter text NOT NULL DEFAULT 'default-deny'`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS scanned_at timestamp`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS retention_hold boolean NOT NULL DEFAULT true`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS expires_at timestamp`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS provenance jsonb NOT NULL DEFAULT '{}'`,
      `CREATE UNIQUE INDEX IF NOT EXISTS feedback_assets_feedback_hash_idx ON feedback_assets(feedback_id,sha256)`,
      `CREATE TABLE IF NOT EXISTS feedback_audit_events (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),actor_user_id integer NOT NULL REFERENCES users(id),event_type text NOT NULL,before_state jsonb,after_state jsonb,reason text,created_at timestamp NOT NULL DEFAULT now())`,
      `CREATE INDEX IF NOT EXISTS feedback_audit_feedback_idx ON feedback_audit_events(feedback_id,created_at)`,
      `CREATE TABLE IF NOT EXISTS feedback_capture_consents (id text PRIMARY KEY,actor_user_id integer NOT NULL REFERENCES users(id),feedback_id integer REFERENCES feedback_items(id),capture_kind text NOT NULL,purpose text NOT NULL,notice_version text NOT NULL,granted_at timestamp NOT NULL DEFAULT now(),revoked_at timestamp)`,
      `CREATE INDEX IF NOT EXISTS feedback_capture_consents_actor_idx ON feedback_capture_consents(actor_user_id,granted_at)`,
      `CREATE TABLE IF NOT EXISTS feedback_transcription_jobs (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),asset_id integer NOT NULL REFERENCES feedback_assets(id),requested_by_id integer NOT NULL REFERENCES users(id),state text NOT NULL DEFAULT 'queued',adapter text NOT NULL,result text,error_code text,attempts integer NOT NULL DEFAULT 0,request_key text NOT NULL,request_hash text NOT NULL,consent_id text NOT NULL REFERENCES feedback_capture_consents(id),provider text NOT NULL,model text NOT NULL,adapter_version text NOT NULL,source_sha256 text NOT NULL,output_sha256 text,completed_at timestamp,review_state text NOT NULL DEFAULT 'pending',reviewed_by_id integer REFERENCES users(id),reviewed_at timestamp,review_reason text,created_at timestamp NOT NULL DEFAULT now(),updated_at timestamp NOT NULL DEFAULT now())`,
      `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS request_key text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS request_hash text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS consent_id text REFERENCES feedback_capture_consents(id)`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS provider text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS model text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS adapter_version text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS source_sha256 text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS output_sha256 text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS completed_at timestamp`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS review_state text NOT NULL DEFAULT 'pending'`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS reviewed_by_id integer REFERENCES users(id)`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS reviewed_at timestamp`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS review_reason text`,
      `CREATE UNIQUE INDEX IF NOT EXISTS feedback_transcription_request_idx ON feedback_transcription_jobs(requested_by_id,request_key)`,
    ];
    for (const statement of statements) await client.query(statement);
    await client.query("COMMIT");
  } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
}
