type MigrationPool = { connect(): Promise<{ query(sql: string): Promise<unknown>; release(): void }> };
export const FEEDBACK_SCHEMA_ADVISORY_LOCK = 1603508;

export async function ensureFeedbackSchema(pool: MigrationPool) {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(`SELECT pg_advisory_xact_lock(${FEEDBACK_SCHEMA_ADVISORY_LOCK})`);
    const statements = [
      `CREATE TABLE IF NOT EXISTS feedback_items (id serial PRIMARY KEY,user_id integer NOT NULL REFERENCES users(id),project_id integer REFERENCES projects(id),feedback_type text NOT NULL,priority text NOT NULL DEFAULT 'normal',module text,page_url text NOT NULL,message text NOT NULL,status text NOT NULL DEFAULT 'new',stable_id text,company_id integer,owner_user_id integer REFERENCES users(id),target_release text,disposition_reason text,customer_visible boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,idempotency_key text,request_hash text,transcript text,transcript_provenance text,metadata jsonb,created_at timestamp NOT NULL DEFAULT now(),updated_at timestamp NOT NULL DEFAULT now(),resolved_at timestamp)`,
      `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS stable_id text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS company_id integer`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS owner_user_id integer REFERENCES users(id)`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS target_release text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS disposition_reason text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS customer_visible boolean NOT NULL DEFAULT true`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS idempotency_key text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS request_hash text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS transcript text`, `ALTER TABLE feedback_items ADD COLUMN IF NOT EXISTS transcript_provenance text`,
      `UPDATE feedback_items SET status=CASE status WHEN 'open' THEN 'new' WHEN 'in_review' THEN 'triaged' WHEN 'planned' THEN 'accepted' WHEN 'done' THEN 'verified' ELSE status END WHERE status IN ('open','in_review','planned','done')`,
      `UPDATE feedback_items SET stable_id='FB-'||lpad(id::text,8,'0') WHERE stable_id IS NULL`, `UPDATE feedback_items f SET company_id=u.company_id FROM users u WHERE f.user_id=u.id AND f.company_id IS NULL`,
      `ALTER TABLE feedback_items ALTER COLUMN stable_id SET NOT NULL`, `ALTER TABLE feedback_items ALTER COLUMN company_id SET NOT NULL`,
      `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_company_id_fkey FOREIGN KEY(company_id) REFERENCES companies(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$`, `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_status_chk CHECK(status IN ('new','triaged','accepted','in_progress','blocked','fixed','verified','rejected','deferred')); EXCEPTION WHEN duplicate_object THEN NULL; END $$`, `DO $$ BEGIN ALTER TABLE feedback_items ADD CONSTRAINT feedback_items_version_chk CHECK(version>0); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
      `CREATE UNIQUE INDEX IF NOT EXISTS feedback_items_stable_id_idx ON feedback_items(stable_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_items_user_idempotency_idx ON feedback_items(user_id,idempotency_key) WHERE idempotency_key IS NOT NULL`, `CREATE INDEX IF NOT EXISTS feedback_items_status_created_idx ON feedback_items(status,created_at DESC)`, `CREATE INDEX IF NOT EXISTS feedback_items_user_created_idx ON feedback_items(user_id,created_at DESC)`, `CREATE INDEX IF NOT EXISTS feedback_items_project_created_idx ON feedback_items(project_id,created_at DESC)`,
      `CREATE TABLE IF NOT EXISTS feedback_assets (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),project_id integer REFERENCES projects(id),uploaded_by_id integer NOT NULL REFERENCES users(id),kind text NOT NULL,original_name text NOT NULL,safe_name text NOT NULL,media_type text NOT NULL,byte_size bigint NOT NULL,sha256 text NOT NULL,storage_path text NOT NULL,scan_state text NOT NULL DEFAULT 'quarantined',scanner_adapter text NOT NULL DEFAULT 'default-deny',scanned_at timestamp,retention_hold boolean NOT NULL DEFAULT true,expires_at timestamp,provenance jsonb NOT NULL DEFAULT '{}',created_at timestamp NOT NULL DEFAULT now())`,
      `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS scanner_adapter text NOT NULL DEFAULT 'default-deny'`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS scanned_at timestamp`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS retention_hold boolean NOT NULL DEFAULT true`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS expires_at timestamp`, `ALTER TABLE feedback_assets ADD COLUMN IF NOT EXISTS provenance jsonb NOT NULL DEFAULT '{}'`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_assets_feedback_hash_idx ON feedback_assets(feedback_id,sha256)`,
      `CREATE TABLE IF NOT EXISTS feedback_audit_events (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),actor_user_id integer NOT NULL REFERENCES users(id),event_type text NOT NULL,before_state jsonb,after_state jsonb,reason text,created_at timestamp NOT NULL DEFAULT now())`, `CREATE INDEX IF NOT EXISTS feedback_audit_feedback_idx ON feedback_audit_events(feedback_id,created_at)`,
      `CREATE TABLE IF NOT EXISTS feedback_capture_consents (id text PRIMARY KEY,actor_user_id integer NOT NULL REFERENCES users(id),feedback_id integer REFERENCES feedback_items(id),capture_kind text NOT NULL,purpose text NOT NULL,notice_version text NOT NULL,granted_at timestamp NOT NULL DEFAULT now(),revoked_at timestamp)`, `CREATE INDEX IF NOT EXISTS feedback_capture_consents_actor_idx ON feedback_capture_consents(actor_user_id,granted_at)`,
      `CREATE TABLE IF NOT EXISTS feedback_transcription_jobs (id serial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),asset_id integer NOT NULL REFERENCES feedback_assets(id),requested_by_id integer NOT NULL REFERENCES users(id),state text NOT NULL DEFAULT 'queued',adapter text NOT NULL,result text,error_code text,attempts integer NOT NULL DEFAULT 0,request_key text NOT NULL,request_hash text NOT NULL,consent_id text NOT NULL REFERENCES feedback_capture_consents(id),provider text NOT NULL,model text NOT NULL,adapter_version text NOT NULL,source_sha256 text NOT NULL,output_sha256 text,completed_at timestamp,review_state text NOT NULL DEFAULT 'pending',reviewed_by_id integer REFERENCES users(id),reviewed_at timestamp,review_reason text,created_at timestamp NOT NULL DEFAULT now(),updated_at timestamp NOT NULL DEFAULT now())`,
      `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS request_key text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS request_hash text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS consent_id text REFERENCES feedback_capture_consents(id)`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS provider text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS model text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS adapter_version text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS source_sha256 text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS output_sha256 text`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS completed_at timestamp`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS review_state text NOT NULL DEFAULT 'pending'`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS reviewed_by_id integer REFERENCES users(id)`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS reviewed_at timestamp`, `ALTER TABLE feedback_transcription_jobs ADD COLUMN IF NOT EXISTS review_reason text`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_transcription_request_idx ON feedback_transcription_jobs(requested_by_id,request_key)`,
      ...feedbackRelayStatements,
    ];
    for (const statement of statements) await client.query(statement);
    await client.query("COMMIT");
  } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
}

const feedbackRelayStatements = [
  `CREATE TABLE IF NOT EXISTS feedback_relay_jobs (id bigserial PRIMARY KEY,feedback_id integer NOT NULL REFERENCES feedback_items(id),asset_id integer NOT NULL REFERENCES feedback_assets(id),company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),state text NOT NULL DEFAULT 'queued',version integer NOT NULL DEFAULT 1,destination_id text NOT NULL,object_id text NOT NULL,policy_id text NOT NULL,policy_version text NOT NULL,policy_sha256 text NOT NULL,attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamp,lease_owner text,lease_token text,lease_expires_at timestamp,fencing_token bigint NOT NULL DEFAULT 0,last_error_code text,created_at timestamp NOT NULL DEFAULT now(),updated_at timestamp NOT NULL DEFAULT now(),CONSTRAINT feedback_relay_jobs_state_chk CHECK(state IN ('queued','transferring','delivered','cleanup-pending','manual-review','held','expired')),CONSTRAINT feedback_relay_jobs_version_chk CHECK(version>0),CONSTRAINT feedback_relay_jobs_attempts_chk CHECK(attempts>=0),CONSTRAINT feedback_relay_jobs_fencing_chk CHECK(fencing_token>=0),CONSTRAINT feedback_relay_jobs_policy_hash_chk CHECK(policy_sha256 ~ '^[a-f0-9]{64}$'),CONSTRAINT feedback_relay_jobs_lease_chk CHECK((lease_owner IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL) OR (lease_owner IS NOT NULL AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL)))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_jobs_asset_destination_idx ON feedback_relay_jobs(asset_id,destination_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_jobs_object_destination_idx ON feedback_relay_jobs(destination_id,object_id)`, `CREATE INDEX IF NOT EXISTS feedback_relay_jobs_claim_idx ON feedback_relay_jobs(state,next_attempt_at,lease_expires_at,id)`, `CREATE INDEX IF NOT EXISTS feedback_relay_jobs_scope_idx ON feedback_relay_jobs(company_id,project_id,created_at DESC)`,
  `CREATE OR REPLACE FUNCTION feedback_relay_derive_job_scope() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE a feedback_assets%ROWTYPE; f feedback_items%ROWTYPE; BEGIN SELECT * INTO a FROM feedback_assets WHERE id=NEW.asset_id; IF NOT FOUND THEN RAISE EXCEPTION 'feedback relay asset does not exist'; END IF; SELECT * INTO f FROM feedback_items WHERE id=a.feedback_id; IF NOT FOUND THEN RAISE EXCEPTION 'feedback relay feedback does not exist'; END IF; IF NEW.feedback_id IS NOT NULL AND NEW.feedback_id<>f.id THEN RAISE EXCEPTION 'feedback relay feedback mismatch'; END IF; IF NEW.company_id IS NOT NULL AND NEW.company_id<>f.company_id THEN RAISE EXCEPTION 'feedback relay company mismatch'; END IF; IF NEW.project_id IS NOT NULL AND NEW.project_id IS DISTINCT FROM COALESCE(a.project_id,f.project_id) THEN RAISE EXCEPTION 'feedback relay project mismatch'; END IF; IF a.project_id IS NOT NULL AND f.project_id IS DISTINCT FROM a.project_id THEN RAISE EXCEPTION 'feedback relay asset project mismatch'; END IF; NEW.feedback_id:=f.id; NEW.company_id:=f.company_id; NEW.project_id:=COALESCE(a.project_id,f.project_id); RETURN NEW; END $$`,
  `DO $$ BEGIN CREATE TRIGGER feedback_relay_jobs_derive_scope BEFORE INSERT OR UPDATE OF feedback_id,asset_id,company_id,project_id ON feedback_relay_jobs FOR EACH ROW EXECUTE FUNCTION feedback_relay_derive_job_scope(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE OR REPLACE FUNCTION feedback_relay_guard_job_fence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.fencing_token<OLD.fencing_token THEN RAISE EXCEPTION 'feedback relay stale fencing token'; END IF; IF NEW.lease_token IS DISTINCT FROM OLD.lease_token AND NEW.lease_token IS NOT NULL AND NEW.fencing_token<=OLD.fencing_token THEN RAISE EXCEPTION 'feedback relay lease requires a new fencing token'; END IF; RETURN NEW; END $$`,
  `DO $$ BEGIN CREATE TRIGGER feedback_relay_jobs_guard_fence BEFORE UPDATE ON feedback_relay_jobs FOR EACH ROW EXECUTE FUNCTION feedback_relay_guard_job_fence(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_custody_events (id bigserial PRIMARY KEY,job_id bigint NOT NULL REFERENCES feedback_relay_jobs(id),sequence integer NOT NULL,event_id text NOT NULL,event_type text NOT NULL,from_state text,to_state text NOT NULL,job_version integer NOT NULL,fencing_token bigint NOT NULL,actor_type text NOT NULL,actor_id text,reason_code text,metadata jsonb NOT NULL DEFAULT '{}',occurred_at timestamp NOT NULL DEFAULT now(),CONSTRAINT feedback_relay_custody_sequence_chk CHECK(sequence>0),CONSTRAINT feedback_relay_custody_version_chk CHECK(job_version>0),CONSTRAINT feedback_relay_custody_fencing_chk CHECK(fencing_token>=0),CONSTRAINT feedback_relay_custody_to_state_chk CHECK(to_state IN ('queued','transferring','delivered','cleanup-pending','manual-review','held','expired')),CONSTRAINT feedback_relay_custody_from_state_chk CHECK(from_state IS NULL OR from_state IN ('queued','transferring','delivered','cleanup-pending','manual-review','held','expired')))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_custody_job_sequence_idx ON feedback_relay_custody_events(job_id,sequence)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_custody_event_id_idx ON feedback_relay_custody_events(event_id)`, `CREATE INDEX IF NOT EXISTS feedback_relay_custody_job_time_idx ON feedback_relay_custody_events(job_id,occurred_at,id)`,
  `CREATE OR REPLACE FUNCTION feedback_relay_validate_custody_event() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE j feedback_relay_jobs%ROWTYPE; prior feedback_relay_custody_events%ROWTYPE; BEGIN SELECT * INTO j FROM feedback_relay_jobs WHERE id=NEW.job_id FOR UPDATE; IF NOT FOUND OR NEW.job_version<>j.version OR NEW.fencing_token<>j.fencing_token OR NEW.to_state<>j.state THEN RAISE EXCEPTION 'feedback relay custody event is stale'; END IF; SELECT * INTO prior FROM feedback_relay_custody_events WHERE job_id=NEW.job_id ORDER BY sequence DESC LIMIT 1; IF (NOT FOUND AND (NEW.sequence<>1 OR NEW.from_state IS NOT NULL)) OR (FOUND AND (NEW.sequence<>prior.sequence+1 OR NEW.from_state IS DISTINCT FROM prior.to_state)) THEN RAISE EXCEPTION 'feedback relay custody sequence mismatch'; END IF; RETURN NEW; END $$`,
  `DO $$ BEGIN CREATE TRIGGER feedback_relay_custody_events_validate BEFORE INSERT ON feedback_relay_custody_events FOR EACH ROW EXECUTE FUNCTION feedback_relay_validate_custody_event(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_nonces (id bigserial PRIMARY KEY,audience text NOT NULL,key_id text NOT NULL,nonce text NOT NULL,request_id text NOT NULL,request_timestamp timestamp NOT NULL,consumed_at timestamp NOT NULL DEFAULT now(),expires_at timestamp NOT NULL,CONSTRAINT feedback_relay_nonces_expiry_chk CHECK(expires_at>request_timestamp))`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_nonces_authority_idx ON feedback_relay_nonces(audience,key_id,nonce)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_nonces_request_idx ON feedback_relay_nonces(request_id)`, `CREATE INDEX IF NOT EXISTS feedback_relay_nonces_expiry_idx ON feedback_relay_nonces(expires_at)`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_receipts (id bigserial PRIMARY KEY,job_id bigint NOT NULL REFERENCES feedback_relay_jobs(id),protocol_version text NOT NULL,request_id text NOT NULL,request_nonce text NOT NULL,destination_id text NOT NULL,object_id text NOT NULL,byte_count bigint NOT NULL,sha256 text NOT NULL,received_at timestamp NOT NULL,receiver_key_id text NOT NULL,canonical_sha256 text NOT NULL,signature text NOT NULL,verified_at timestamp NOT NULL,readback_verified_at timestamp,readback_sha256 text,created_at timestamp NOT NULL DEFAULT now(),CONSTRAINT feedback_relay_receipts_bytes_chk CHECK(byte_count>=0),CONSTRAINT feedback_relay_receipts_hash_chk CHECK(sha256 ~ '^[a-f0-9]{64}$' AND canonical_sha256 ~ '^[a-f0-9]{64}$'),CONSTRAINT feedback_relay_receipts_readback_chk CHECK((readback_verified_at IS NULL AND readback_sha256 IS NULL) OR (readback_verified_at IS NOT NULL AND readback_sha256=sha256 AND readback_verified_at>=verified_at)))`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_receipts_job_idx ON feedback_relay_receipts(job_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_receipts_request_idx ON feedback_relay_receipts(request_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_receipts_destination_object_idx ON feedback_relay_receipts(destination_id,object_id)`,
  `CREATE OR REPLACE FUNCTION feedback_relay_validate_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE j feedback_relay_jobs%ROWTYPE; a feedback_assets%ROWTYPE; BEGIN SELECT * INTO j FROM feedback_relay_jobs WHERE id=NEW.job_id; SELECT * INTO a FROM feedback_assets WHERE id=j.asset_id; IF NOT FOUND OR j.state NOT IN ('delivered','cleanup-pending') OR NEW.destination_id<>j.destination_id OR NEW.object_id<>j.object_id OR NEW.byte_count<>a.byte_size OR NEW.sha256<>a.sha256 THEN RAISE EXCEPTION 'feedback relay receipt mismatch'; END IF; RETURN NEW; END $$`,
  `DO $$ BEGIN CREATE TRIGGER feedback_relay_receipts_validate BEFORE INSERT ON feedback_relay_receipts FOR EACH ROW EXECUTE FUNCTION feedback_relay_validate_receipt(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_holds (id bigserial PRIMARY KEY,job_id bigint NOT NULL REFERENCES feedback_relay_jobs(id),hold_key text NOT NULL,reason text NOT NULL,placed_by_user_id integer REFERENCES users(id),placed_at timestamp NOT NULL DEFAULT now(),released_by_user_id integer REFERENCES users(id),released_at timestamp,release_reason text,CONSTRAINT feedback_relay_holds_release_chk CHECK((released_at IS NULL AND released_by_user_id IS NULL AND release_reason IS NULL) OR (released_at IS NOT NULL AND released_by_user_id IS NOT NULL AND release_reason IS NOT NULL AND released_at>=placed_at)))`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_holds_key_idx ON feedback_relay_holds(job_id,hold_key)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_holds_active_idx ON feedback_relay_holds(job_id) WHERE released_at IS NULL`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_temporary_objects (id bigserial PRIMARY KEY,job_id bigint NOT NULL REFERENCES feedback_relay_jobs(id),storage_backend text NOT NULL,storage_key text NOT NULL,byte_count bigint NOT NULL,sha256 text NOT NULL,encrypted boolean NOT NULL,created_at timestamp NOT NULL DEFAULT now(),expires_at timestamp NOT NULL,delete_started_at timestamp,deleted_at timestamp,absence_verified_at timestamp,delete_fencing_token bigint,CONSTRAINT feedback_relay_temp_bytes_chk CHECK(byte_count>=0),CONSTRAINT feedback_relay_temp_hash_chk CHECK(sha256 ~ '^[a-f0-9]{64}$'),CONSTRAINT feedback_relay_temp_expiry_chk CHECK(expires_at>created_at),CONSTRAINT feedback_relay_temp_delete_chk CHECK((deleted_at IS NULL AND absence_verified_at IS NULL) OR (delete_started_at IS NOT NULL AND deleted_at IS NOT NULL AND absence_verified_at IS NOT NULL AND delete_fencing_token IS NOT NULL AND delete_fencing_token>=0 AND delete_started_at<=deleted_at AND deleted_at<=absence_verified_at)))`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_temp_job_idx ON feedback_relay_temporary_objects(job_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_temp_storage_idx ON feedback_relay_temporary_objects(storage_backend,storage_key)`, `CREATE INDEX IF NOT EXISTS feedback_relay_temp_expiry_idx ON feedback_relay_temporary_objects(expires_at) WHERE deleted_at IS NULL`,
  `CREATE TABLE IF NOT EXISTS feedback_relay_deletion_proofs (id bigserial PRIMARY KEY,job_id bigint NOT NULL REFERENCES feedback_relay_jobs(id),temporary_object_id bigint NOT NULL REFERENCES feedback_relay_temporary_objects(id),receipt_id bigint NOT NULL REFERENCES feedback_relay_receipts(id),approval_id text NOT NULL,approved_by_user_id integer NOT NULL REFERENCES users(id),inventory jsonb NOT NULL,inventory_sha256 text NOT NULL,deleted_at timestamp NOT NULL,absence_verified_at timestamp NOT NULL,proof_sha256 text NOT NULL,created_at timestamp NOT NULL DEFAULT now(),CONSTRAINT feedback_relay_deletion_hash_chk CHECK(inventory_sha256 ~ '^[a-f0-9]{64}$' AND proof_sha256 ~ '^[a-f0-9]{64}$'),CONSTRAINT feedback_relay_deletion_order_chk CHECK(deleted_at<=absence_verified_at AND absence_verified_at<=created_at))`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_deletion_job_idx ON feedback_relay_deletion_proofs(job_id)`, `CREATE UNIQUE INDEX IF NOT EXISTS feedback_relay_deletion_temp_idx ON feedback_relay_deletion_proofs(temporary_object_id)`,
  `CREATE OR REPLACE FUNCTION feedback_relay_validate_deletion_proof() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE r feedback_relay_receipts%ROWTYPE; t feedback_relay_temporary_objects%ROWTYPE; BEGIN SELECT * INTO r FROM feedback_relay_receipts WHERE id=NEW.receipt_id AND job_id=NEW.job_id; IF NOT FOUND OR r.readback_verified_at IS NULL THEN RAISE EXCEPTION 'feedback relay verified receipt/readback required'; END IF; SELECT * INTO t FROM feedback_relay_temporary_objects WHERE id=NEW.temporary_object_id AND job_id=NEW.job_id; IF NOT FOUND OR t.absence_verified_at IS NULL OR t.deleted_at IS NULL THEN RAISE EXCEPTION 'feedback relay absence proof required'; END IF; IF EXISTS(SELECT 1 FROM feedback_relay_holds WHERE job_id=NEW.job_id AND released_at IS NULL) THEN RAISE EXCEPTION 'feedback relay active hold prevents deletion proof'; END IF; IF NEW.deleted_at<>t.deleted_at OR NEW.absence_verified_at<>t.absence_verified_at OR NEW.deleted_at<r.verified_at THEN RAISE EXCEPTION 'feedback relay deletion proof ordering mismatch'; END IF; RETURN NEW; END $$`, `DO $$ BEGIN CREATE TRIGGER feedback_relay_deletion_proofs_validate BEFORE INSERT ON feedback_relay_deletion_proofs FOR EACH ROW EXECUTE FUNCTION feedback_relay_validate_deletion_proof(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`,
  `CREATE OR REPLACE FUNCTION feedback_relay_reject_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'feedback relay evidence is immutable'; END $$`,
  ...["feedback_relay_custody_events","feedback_relay_nonces","feedback_relay_receipts","feedback_relay_deletion_proofs"].map(table => `DO $$ BEGIN CREATE TRIGGER ${table}_immutable BEFORE UPDATE OR DELETE ON ${table} FOR EACH ROW EXECUTE FUNCTION feedback_relay_reject_mutation(); EXCEPTION WHEN duplicate_object THEN NULL; END $$`),
];
