import assert from "node:assert/strict";
import crypto from "node:crypto";
import { pool } from "@workspace/db";
import { previewContractImport, confirmContractImport } from "./financial-contract-import";
import { startFeaturePolicyMigration } from "./feature-policy-migration";
import { startFinancialControlMigration } from "./financial-control-migration";
import { startFinancialBudgetMigration } from "./financial-budget-migration";
import { startFinancialContractMigration } from "./financial-contract-migration";

const url = process.env.PROD_DATABASE_URL;
if (!url) throw new Error("Disposable database required");
const target = new URL(url);
if (target.port !== "55435" || target.pathname !== "/bimlog_financial_build3") throw new Error("Refusing non-disposable database");
await startFeaturePolicyMigration(); await startFinancialControlMigration(); await startFinancialBudgetMigration(); await startFinancialContractMigration();
const ids = (await pool.query(`SELECT u.id user_id,u.company_id,p.id project_id FROM users u JOIN projects p ON p.created_by_id=u.id WHERE u.email='finance-build3@example.test' AND p.name='Disposable Build 3 Project'`)).rows[0];
const source = async (bytes: Buffer) => Number((await pool.query(`INSERT INTO files(project_id,file_hash) VALUES($1,$2) RETURNING id`, [ids.project_id, crypto.createHash("sha256").update(bytes).digest("hex")])).rows[0].id);
const csv = Buffer.from("stableLineId,budgetLine,description,amount,currency\nIMPORT-1,sl1,Imported exact SOV,20.000001,USD\n", "utf8");
const sourceFileId = await source(csv);
const preview = await previewContractImport({ actorUserId: Number(ids.user_id), projectId: ids.project_id, sourceFileId, fileName: "controlled.csv", bytes: csv, currency: "USD", budgetSnapshotId: "snap", idempotencyKey: "build3-import-proof" });
assert.equal(preview.acceptedCount, 1); assert.equal(preview.rejectedCount, 0); assert.equal(preview.total, "20.000001");
const confirmation = { actorUserId: Number(ids.user_id), projectId: ids.project_id, sessionId: preview.id, fileHash: preview.fileHash, parsedFingerprint: preview.parsedFingerprint, currency: "USD", total: preview.total, legalNumber: "SC-IMPORT-001", perspective: "downstream", contractType: "subcontract", counterpartyName: "Disposable Import Trade", title: "Controlled imported SOV", initialGrants: [] };
const concurrent = await Promise.all([confirmContractImport(confirmation), confirmContractImport(confirmation)]);
assert.equal(concurrent[0].contractVersionId, concurrent[1].contractVersionId); assert.equal(concurrent.filter((result) => result.idempotent).length, 1);
assert.equal(Number((await pool.query(`SELECT count(*)::int n FROM financial_contract_versions WHERE id=$1`, [concurrent[0].contractVersionId])).rows[0].n), 1);
const changed = Buffer.from("stableLineId,budgetLine,description,amount,currency\nIMPORT-2,sl1,Changed payload,20.000001,USD\n", "utf8");
await assert.rejects(previewContractImport({ actorUserId: Number(ids.user_id), projectId: ids.project_id, sourceFileId: await source(changed), fileName: "changed.csv", bytes: changed, currency: "USD", budgetSnapshotId: "snap", idempotencyKey: "build3-import-proof" }), (error: any) => error?.code === "CONTRACT_IMPORT_IDEMPOTENCY_CONFLICT");
const formula = Buffer.from("stableLineId,budgetLine,description,amount,currency\nIMPORT-3,sl1,=HYPERLINK(1),1,USD\n", "utf8");
await assert.rejects(previewContractImport({ actorUserId: Number(ids.user_id), projectId: ids.project_id, sourceFileId: await source(formula), fileName: "formula.csv", bytes: formula, currency: "USD", budgetSnapshotId: "snap", idempotencyKey: "build3-formula-proof" }), (error: any) => error?.code === "CONTRACT_IMPORT_FORMULA_REJECTED");
console.log(JSON.stringify({ suite: "cost-financial-control-build-3-import-concurrency", status: "passed", checks: ["exact CSV preview", "atomic concurrent confirmation", "duplicate retry convergence", "changed payload conflict", "formula injection rejection"] }, null, 2));
await pool.end();
