import crypto from "crypto";
import { pool } from "@workspace/db";
import { FinancialControlError } from "./financial-control-contract";
import { authorizeFinancialOperation } from "./financial-control-service";
import { waitForFinancialContractMigration } from "./financial-contract-migration";
import { positiveId, scaledSignedDecimal } from "./financial-budget-contract";
import { normalizePaymentApplication, normalizePaymentRevision } from "./financial-contract-payment";

type Client = { query: (sql: string, values?: unknown[]) => Promise<{ rows: any[] }> };
const uuid = () => crypto.randomUUID();
const text = (value: unknown, name: string) => { const result = String(value ?? "").trim(); if (result.length < 3 || result.length > 200) throw new FinancialControlError(400, "CONTRACT_PAYMENT_VALUE_INVALID", `${name} is invalid.`); return result; };
async function tx<T>(fn: (client: any) => Promise<T>) { await waitForFinancialContractMigration(); const client = await pool.connect(); try { await client.query("BEGIN"); const value = await fn(client); await client.query("COMMIT"); return value; } catch (error) { await client.query("ROLLBACK"); if (error instanceof Error && error.message.includes("approved payment total exceeds")) throw new FinancialControlError(409, "CONTRACT_PAYMENT_SOV_EXCEEDED", "Approved payments cannot exceed the effective governed SOV line."); if (error instanceof Error && error.message.includes("requires attributed review")) throw new FinancialControlError(409, "CONTRACT_PAYMENT_REVIEW_REQUIRED", "Independent attributed review is required before approval."); if (error instanceof Error && error.message.includes("must be separate")) throw new FinancialControlError(409, "CONTRACT_PAYMENT_DUTIES_CONFLICT", "Payment maker, reviewer, and approver must be separate people."); throw error; } finally { client.release(); } }
async function recordPermission(client: Client, contractId: string, userId: number, permission: string) { const row = (await client.query(`SELECT state FROM financial_contract_record_grants WHERE contract_id=$1 AND user_id=$2 AND permission=$3 ORDER BY version DESC LIMIT 1`, [contractId, userId, permission])).rows[0]; if (!row || row.state !== "active") throw new FinancialControlError(403, "CONTRACT_RECORD_ACCESS_DENIED", "Explicit current access to this confidential financial record is required."); }
async function history(client: Client, values: any) { await client.query(`INSERT INTO financial_contract_history(id,company_id,project_id,contract_id,contract_version_id,payment_application_id,payment_version_id,actor_user_id,event_type,before_state,after_state,reason_code,evidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb)`, [uuid(), values.companyId, values.projectId, values.contractId, values.contractVersionId, values.paymentApplicationId, values.paymentVersionId, values.actorUserId, values.eventType, values.beforeState ?? null, values.afterState ?? null, values.reasonCode, JSON.stringify(values.evidence ?? {})]); }

export async function createContractPaymentApplication(input: any) {
  const projectId = positiveId(input.projectId, "projectId"), contractId = text(input.contractId, "contractId"), normalized = normalizePaymentApplication(input);
  return tx(async (client) => {
    const auth = await authorizeFinancialOperation({ actorUserId: input.actorUserId, projectId, featureKey: "cost.commitment.prepare", operation: "prepare", client });
    await recordPermission(client, contractId, auth.actor.userId, "prepare");
    await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`, [`contract-payment:${contractId}`]);
    const existing = (await client.query(`SELECT a.id,v.id version_id,v.content_fingerprint FROM financial_contract_payment_applications a JOIN financial_contract_payment_versions v ON v.payment_application_id=a.id AND v.version=1 WHERE a.contract_id=$1 AND a.idempotency_key=$2`, [contractId, normalized.idempotencyKey])).rows[0];
    if (existing) { if (existing.content_fingerprint !== normalized.contentFingerprint) throw new FinancialControlError(409, "CONTRACT_PAYMENT_IDEMPOTENCY_CONFLICT", "This idempotency key was already used for different payment content."); return getContractPaymentApplications({ actorUserId: input.actorUserId, projectId, contractId, paymentApplicationId: existing.id }, client); }
    const contract = (await client.query(`SELECT c.company_id,v.id version_id,v.currency FROM financial_contracts c JOIN financial_contract_versions v ON v.contract_id=c.id WHERE c.id=$1 AND c.project_id=$2 AND v.status='executed' ORDER BY v.version DESC LIMIT 1 FOR UPDATE OF c`, [contractId, projectId])).rows[0];
    if (!contract) throw new FinancialControlError(409, "CONTRACT_PAYMENT_CONTRACT_NOT_EXECUTED", "Payment applications require an executed governed contract.");
    if (contract.currency !== normalized.currency) throw new FinancialControlError(400, "CONTRACT_PAYMENT_CURRENCY_MISMATCH", "Payment currency must match the executed contract.");
    const ids = normalized.lines.map((line) => line.contractSovLineId);
    const sov = (await client.query(`SELECT base.id,(base.amount+COALESCE((SELECT sum(line.amount_delta) FROM financial_contract_amendment_lines line JOIN financial_contract_amendment_versions version ON version.id=line.amendment_version_id JOIN financial_contract_amendments amendment ON amendment.id=version.amendment_id WHERE amendment.contract_id=$3 AND version.status='executed' AND line.stable_line_id=base.stable_line_id),0))::text amount FROM financial_contract_sov_lines base WHERE base.contract_version_id=$1 AND base.id=ANY($2::text[])`, [contract.version_id, ids, contractId])).rows;
    if (sov.length !== ids.length) throw new FinancialControlError(400, "CONTRACT_PAYMENT_SOV_SCOPE_INVALID", "Every payment line must belong to the executed contract version.");
    const prior = (await client.query(`SELECT l.contract_sov_line_id,COALESCE(sum(l.current_amount),0)::text paid FROM financial_contract_payment_lines l JOIN financial_contract_payment_versions v ON v.id=l.payment_version_id JOIN financial_contract_payment_applications a ON a.id=v.payment_application_id WHERE a.contract_id=$1 AND v.status='approved' GROUP BY l.contract_sov_line_id`, [contractId])).rows;
    const paid = new Map(prior.map((row: any) => [String(row.contract_sov_line_id), String(row.paid)]));
    const limit = new Map(sov.map((row: any) => [String(row.id), String(row.amount)]));
    for (const line of normalized.lines) if (scaledSignedDecimal(String(paid.get(line.contractSovLineId) ?? "0")) + scaledSignedDecimal(line.currentAmount) > scaledSignedDecimal(String(limit.get(line.contractSovLineId)))) throw new FinancialControlError(409, "CONTRACT_PAYMENT_SOV_EXCEEDED", "Approved plus requested payment cannot exceed the governed SOV line.");
    const applicationId = uuid(), versionId = uuid();
    await client.query(`INSERT INTO financial_contract_payment_applications(id,contract_id,bimlog_id,application_number,idempotency_key,created_by_id) VALUES($1,$2,$3,$4,$5,$6)`, [applicationId, contractId, `BIMLOG-PAY-${applicationId}`, normalized.applicationNumber, normalized.idempotencyKey, auth.actor.userId]);
    await client.query(`INSERT INTO financial_contract_payment_versions(id,payment_application_id,contract_version_id,version,status,period_start,period_end,currency,gross_amount,retainage_amount,net_amount,content_fingerprint,prepared_by_id) VALUES($1,$2,$3,1,'draft',$4,$5,$6,$7,$8,$9,$10,$11)`, [versionId, applicationId, contract.version_id, normalized.periodStart, normalized.periodEnd, normalized.currency, normalized.grossAmount, normalized.retainageAmount, normalized.netAmount, normalized.contentFingerprint, auth.actor.userId]);
    for (const line of normalized.lines) await client.query(`INSERT INTO financial_contract_payment_lines(id,payment_version_id,contract_sov_line_id,current_amount,evidence,sort_order) VALUES($1,$2,$3,$4,$5::jsonb,$6)`, [uuid(), versionId, line.contractSovLineId, line.currentAmount, JSON.stringify(line.evidence), line.sortOrder]);
    await history(client, { companyId: auth.scope.companyId, projectId, contractId, contractVersionId: contract.version_id, paymentApplicationId: applicationId, paymentVersionId: versionId, actorUserId: auth.actor.userId, eventType: "payment_application_created", afterState: "draft", reasonCode: "CONTRACT_PAYMENT_CREATED", evidence: { contentFingerprint: normalized.contentFingerprint, grossAmount: normalized.grossAmount, netAmount: normalized.netAmount } });
    return getContractPaymentApplications({ actorUserId: input.actorUserId, projectId, contractId, paymentApplicationId: applicationId }, client);
  });
}

export async function reviseContractPaymentApplication(input: any) {
  const projectId = positiveId(input.projectId, "projectId"), contractId = text(input.contractId, "contractId"), paymentApplicationId = text(input.paymentApplicationId, "paymentApplicationId"), expectedRevision = positiveId(input.expectedRevision, "expectedRevision"), normalized = normalizePaymentRevision(input);
  return tx(async (client) => {
    const auth = await authorizeFinancialOperation({ actorUserId: input.actorUserId, projectId, featureKey: "cost.commitment.prepare", operation: "prepare", client });
    await recordPermission(client, contractId, auth.actor.userId, "prepare");
    await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`, [`contract-payment:${contractId}`]);
    const current = (await client.query(`SELECT a.application_number,v.* FROM financial_contract_payment_applications a JOIN financial_contracts c ON c.id=a.contract_id JOIN LATERAL(SELECT * FROM financial_contract_payment_versions WHERE payment_application_id=a.id ORDER BY version DESC LIMIT 1)v ON true WHERE a.id=$1 AND a.contract_id=$2 AND c.project_id=$3 FOR UPDATE OF a`, [paymentApplicationId, contractId, projectId])).rows[0];
    if (!current) throw new FinancialControlError(404, "CONTRACT_PAYMENT_NOT_FOUND", "Payment application not found.");
    if (current.supersedes_id) {
      const superseded = (await client.query(`SELECT revision FROM financial_contract_payment_versions WHERE id=$1 AND payment_application_id=$2`, [current.supersedes_id, paymentApplicationId])).rows[0];
      if (Number(superseded?.revision) === expectedRevision) {
        if (current.content_fingerprint !== normalized.contentFingerprint) throw new FinancialControlError(409, "CONTRACT_PAYMENT_REVISION_REPLAY_CONFLICT", "This returned payment revision was already replaced with different immutable content.");
        return getContractPaymentApplications({ actorUserId: input.actorUserId, projectId, contractId, paymentApplicationId }, client);
      }
    }
    if (current.status !== "returned" || Number(current.revision) !== expectedRevision) throw new FinancialControlError(409, "CONTRACT_PAYMENT_STALE", "Only the current returned payment version can be revised.");
    if (current.application_number !== normalized.applicationNumber) throw new FinancialControlError(409, "CONTRACT_PAYMENT_ROOT_IMMUTABLE", "A payment revision cannot change its application number.");
    const contract = (await client.query(`SELECT v.id version_id,v.currency FROM financial_contract_versions v WHERE v.contract_id=$1 AND v.status='executed' ORDER BY v.version DESC LIMIT 1`, [contractId])).rows[0];
    if (!contract || contract.currency !== normalized.currency) throw new FinancialControlError(409, "CONTRACT_PAYMENT_CONTRACT_CHANGED", "The executed contract authority changed; reload before revising.");
    const ids = normalized.lines.map((line) => line.contractSovLineId);
    const sov = (await client.query(`SELECT base.id,(base.amount+COALESCE((SELECT sum(line.amount_delta) FROM financial_contract_amendment_lines line JOIN financial_contract_amendment_versions version ON version.id=line.amendment_version_id JOIN financial_contract_amendments amendment ON amendment.id=version.amendment_id WHERE amendment.contract_id=$3 AND version.status='executed' AND line.stable_line_id=base.stable_line_id),0))::text amount FROM financial_contract_sov_lines base WHERE base.contract_version_id=$1 AND base.id=ANY($2::text[])`, [contract.version_id, ids, contractId])).rows;
    if (sov.length !== ids.length) throw new FinancialControlError(400, "CONTRACT_PAYMENT_SOV_SCOPE_INVALID", "Every payment line must belong to the executed contract version.");
    const prior = (await client.query(`SELECT l.contract_sov_line_id,COALESCE(sum(l.current_amount),0)::text paid FROM financial_contract_payment_lines l JOIN financial_contract_payment_versions v ON v.id=l.payment_version_id JOIN financial_contract_payment_applications a ON a.id=v.payment_application_id WHERE a.contract_id=$1 AND v.status='approved' GROUP BY l.contract_sov_line_id`, [contractId])).rows;
    const paid = new Map(prior.map((row: any) => [String(row.contract_sov_line_id), String(row.paid)])), limit = new Map(sov.map((row: any) => [String(row.id), String(row.amount)]));
    for (const line of normalized.lines) if (scaledSignedDecimal(String(paid.get(line.contractSovLineId) ?? "0")) + scaledSignedDecimal(line.currentAmount) > scaledSignedDecimal(String(limit.get(line.contractSovLineId)))) throw new FinancialControlError(409, "CONTRACT_PAYMENT_SOV_EXCEEDED", "Approved plus requested payment cannot exceed the effective governed SOV line.");
    const versionId = uuid(), nextVersion = Number(current.version) + 1;
    await client.query(`INSERT INTO financial_contract_payment_versions(id,payment_application_id,contract_version_id,supersedes_id,version,status,period_start,period_end,currency,gross_amount,retainage_amount,net_amount,content_fingerprint,prepared_by_id) VALUES($1,$2,$3,$4,$5,'draft',$6,$7,$8,$9,$10,$11,$12,$13)`, [versionId, paymentApplicationId, contract.version_id, current.id, nextVersion, normalized.periodStart, normalized.periodEnd, normalized.currency, normalized.grossAmount, normalized.retainageAmount, normalized.netAmount, normalized.contentFingerprint, auth.actor.userId]);
    for (const line of normalized.lines) await client.query(`INSERT INTO financial_contract_payment_lines(id,payment_version_id,contract_sov_line_id,current_amount,evidence,sort_order) VALUES($1,$2,$3,$4,$5::jsonb,$6)`, [uuid(), versionId, line.contractSovLineId, line.currentAmount, JSON.stringify(line.evidence), line.sortOrder]);
    await history(client, { companyId: auth.scope.companyId, projectId, contractId, contractVersionId: contract.version_id, paymentApplicationId, paymentVersionId: versionId, actorUserId: auth.actor.userId, eventType: "payment_application_revised", beforeState: "returned", afterState: "draft", reasonCode: "CONTRACT_PAYMENT_SUCCESSOR_CREATED", evidence: { supersededPaymentVersionId: current.id, version: nextVersion, contentFingerprint: normalized.contentFingerprint } });
    return getContractPaymentApplications({ actorUserId: input.actorUserId, projectId, contractId, paymentApplicationId }, client);
  });
}

export async function transitionContractPaymentApplication(input: any) {
  const projectId = positiveId(input.projectId, "projectId"), contractId = text(input.contractId, "contractId"), paymentApplicationId = text(input.paymentApplicationId, "paymentApplicationId"), expectedRevision = positiveId(input.expectedRevision, "expectedRevision");
  const action = String(input.action ?? ""); if (!['submit','review','return','reject','withdraw','void'].includes(action)) throw new FinancialControlError(400, "CONTRACT_PAYMENT_ACTION_INVALID", "Unsupported payment action.");
  const rules: any = { submit: ['draft','submitted','prepare'], review: ['submitted','submitted','review'], return: ['submitted','returned','review'], reject: ['submitted','rejected','review'], withdraw: ['submitted','withdrawn','prepare'], void: ['draft','voided','prepare'] }; const [before, after, permission] = rules[action];
  return tx(async (client) => { const featureKey = permission === 'review' ? "cost.commitment.review" : "cost.commitment.prepare"; const auth = await authorizeFinancialOperation({ actorUserId: input.actorUserId, projectId, featureKey, operation: permission, client }); await recordPermission(client, contractId, auth.actor.userId, permission); const row = (await client.query(`SELECT a.id,v.*,c.company_id FROM financial_contract_payment_applications a JOIN financial_contract_payment_versions v ON v.payment_application_id=a.id JOIN financial_contracts c ON c.id=a.contract_id WHERE a.id=$1 AND a.contract_id=$2 AND c.project_id=$3 ORDER BY v.version DESC LIMIT 1 FOR UPDATE OF v`, [paymentApplicationId, contractId, projectId])).rows[0]; if (!row) throw new FinancialControlError(404, "CONTRACT_PAYMENT_NOT_FOUND", "Payment application not found."); if (row.revision !== expectedRevision || row.status !== before) throw new FinancialControlError(409, "CONTRACT_PAYMENT_STALE", "Payment application state changed; reload before retrying."); if (action === 'reject' || action === 'return') text(input.reason, "reason"); const updated = (await client.query(`UPDATE financial_contract_payment_versions SET status=$1,revision=revision+1,submitted_by_id=CASE WHEN $1='submitted' AND submitted_by_id IS NULL THEN $2 ELSE submitted_by_id END,submitted_at=CASE WHEN $1='submitted' AND submitted_at IS NULL THEN now() ELSE submitted_at END,reviewed_by_id=CASE WHEN $4='review' THEN $2 ELSE reviewed_by_id END,reviewed_at=CASE WHEN $4='review' THEN now() ELSE reviewed_at END,outcome_reason=$3,updated_at=now() WHERE id=$5 AND revision=$6 RETURNING *`, [after, auth.actor.userId, input.reason ?? null, action, row.id, expectedRevision])).rows[0]; await history(client, { companyId: auth.scope.companyId, projectId, contractId, contractVersionId: row.contract_version_id, paymentApplicationId, paymentVersionId: row.id, actorUserId: auth.actor.userId, eventType: `payment_application_${action}`, beforeState: before, afterState: after, reasonCode: `CONTRACT_PAYMENT_${action.toUpperCase()}`, evidence: { revision: updated.revision, reviewerAttributed: action === 'review', outcomeReason: action === 'reject' || action === 'return' ? input.reason : null } }); return updated; });
}

export async function approveContractPaymentApplication(input: any) {
  const projectId = positiveId(input.projectId, "projectId"), contractId = text(input.contractId, "contractId"), paymentApplicationId = text(input.paymentApplicationId, "paymentApplicationId"), expectedRevision = positiveId(input.expectedRevision, "expectedRevision");
  return tx(async (client) => { await client.query(`SELECT pg_advisory_xact_lock(hashtext($1))`, [`contract-payment:${contractId}`]); const row = (await client.query(`SELECT a.id,v.*,c.company_id FROM financial_contract_payment_applications a JOIN financial_contract_payment_versions v ON v.payment_application_id=a.id JOIN financial_contracts c ON c.id=a.contract_id WHERE a.id=$1 AND a.contract_id=$2 AND c.project_id=$3 ORDER BY v.version DESC LIMIT 1 FOR UPDATE OF v`, [paymentApplicationId, contractId, projectId])).rows[0]; if (!row) throw new FinancialControlError(404, "CONTRACT_PAYMENT_NOT_FOUND", "Payment application not found."); const auth = await authorizeFinancialOperation({ actorUserId: input.actorUserId, projectId, featureKey: "cost.commitment.approve", operation: "approve", makerUserId: Number(row.prepared_by_id), category: "payment_approval", amount: { amount: String(row.net_amount), currency: String(row.currency) }, client }); await recordPermission(client, contractId, auth.actor.userId, "approve"); if (row.status !== 'submitted' || row.revision !== expectedRevision) throw new FinancialControlError(409, "CONTRACT_PAYMENT_STALE", "Payment application state changed; reload before retrying."); if (String(input.confirmationFingerprint ?? '') !== row.content_fingerprint) throw new FinancialControlError(409, "CONTRACT_PAYMENT_CONFIRMATION_STALE", "Confirmation does not match the current immutable payment content."); const updated = (await client.query(`UPDATE financial_contract_payment_versions SET status='approved',revision=revision+1,approved_by_id=$1,approved_at=now(),updated_at=now() WHERE id=$2 AND revision=$3 RETURNING *`, [auth.actor.userId, row.id, expectedRevision])).rows[0]; await history(client, { companyId: auth.scope.companyId, projectId, contractId, contractVersionId: row.contract_version_id, paymentApplicationId, paymentVersionId: row.id, actorUserId: auth.actor.userId, eventType: 'payment_application_approved', beforeState: 'submitted', afterState: 'approved', reasonCode: 'CONTRACT_PAYMENT_APPROVED', evidence: { revision: updated.revision, netAmount: row.net_amount, contentFingerprint: row.content_fingerprint } }); return updated; });
}

export async function getContractPaymentApplications(input: any, client: Client = pool) { const projectId = positiveId(input.projectId, "projectId"), contractId = text(input.contractId, "contractId"); const auth = await authorizeFinancialOperation({ actorUserId: input.actorUserId, projectId, featureKey: "cost.commitment.view", operation: "read", client }); await recordPermission(client, contractId, auth.actor.userId, "view"); const values: unknown[] = [contractId, projectId]; let filter = ""; if (input.paymentApplicationId) { values.push(text(input.paymentApplicationId, "paymentApplicationId")); filter = ` AND a.id=$3`; } const rows = (await client.query(`SELECT a.*,v.id payment_version_id,v.contract_version_id,v.supersedes_id,v.version,v.revision,v.status,v.period_start,v.period_end,v.currency,v.gross_amount::text,v.retainage_amount::text,v.net_amount::text,v.content_fingerprint,v.prepared_by_id,v.submitted_by_id,v.reviewed_by_id,v.approved_by_id,v.submitted_at,v.reviewed_at,v.approved_at,v.outcome_reason,COALESCE(line_data.lines,'[]'::jsonb) lines FROM financial_contract_payment_applications a JOIN financial_contracts c ON c.id=a.contract_id JOIN LATERAL(SELECT * FROM financial_contract_payment_versions WHERE payment_application_id=a.id ORDER BY version DESC LIMIT 1)v ON true LEFT JOIN LATERAL(SELECT jsonb_agg(jsonb_build_object('id',l.id,'contractSovLineId',l.contract_sov_line_id,'currentAmount',l.current_amount::text,'evidence',l.evidence,'sortOrder',l.sort_order) ORDER BY l.sort_order) lines FROM financial_contract_payment_lines l WHERE l.payment_version_id=v.id) line_data ON true WHERE a.contract_id=$1 AND c.project_id=$2${filter} ORDER BY a.created_at DESC`, values)).rows; return input.paymentApplicationId ? rows[0] ?? null : { payments: rows }; }
