import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";
import { canonicalSpreadsheetWriteOptions } from "@workspace/api-zod";
import AdmZip from "adm-zip";
import { FinancialControlError } from "./financial-control-contract";
import { exactDelta, exactPositiveAmount } from "./financial-contract-contract";

export type ContractExport = Awaited<ReturnType<typeof import("./financial-contract-service").contractExportData>>;
export type ContractRegisterColumn = "legalNumber" | "title" | "counterparty" | "status" | "type" | "perspective" | "originalValue" | "currentCommitment" | "currency" | "approvedAt" | "executedAt";
export type ContractRegisterSection = "summary" | "filters" | "contracts";
export type ContractCurrentViewExport = Awaited<ReturnType<typeof import("./financial-contract-service").contractCurrentViewExportData>> & {
  generatedBy: string;
  filters: string[];
  counts: { matching: number; totalAccessible: number; executed: number; approved: number; draft: number; companies: number };
  selectedColumns: ContractRegisterColumn[];
  selectedSections: ContractRegisterSection[];
  sourceView: string;
  contentHash: string;
};

const safe = (value: unknown, fallback = "") => {
  const text = String(value ?? "").replace(/[\u0000-\u001f\u007f]/g, " ").trim() || fallback;
  if (/^[=+\-@\t\r]/.test(text)) return `'${text}`;
  if (/(?:storage[_ ]?path|[A-Za-z]:\\|https?:\/\/\S*[?&](?:token|key|signature)=)/i.test(text)) return "Protected value";
  return text;
};

const money = (amount: unknown, currency: unknown) => `${safe(amount)} ${safe(currency)}`.trim();

export async function buildContractCurrentViewPdf(data: ContractCurrentViewExport): Promise<Buffer> {
  const doc = new PDFDocument({ size: "LETTER", layout: "landscape", margin: 40, bufferPages: true, info: { Title: "Contracts Current View", Author: "BIMLog", Subject: "Contracts and commitments current-view register" } });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const pageWidth = doc.page.width - 80;
  const generated = safe(data.generatedAt);
  const labelColumns: Record<ContractRegisterColumn, string> = {
    legalNumber: "Legal Number",
    title: "Title",
    counterparty: "Counterparty",
    status: "Status",
    type: "Type",
    perspective: "Perspective",
    originalValue: "Original Value",
    currentCommitment: "Current Commitment",
    currency: "Currency",
    approvedAt: "Approved",
    executedAt: "Executed",
  };
  const baseColumnWidths: Record<ContractRegisterColumn, number> = {
    legalNumber: 78,
    title: 120,
    counterparty: 110,
    status: 70,
    type: 86,
    perspective: 76,
    originalValue: 82,
    currentCommitment: 92,
    currency: 48,
    approvedAt: 70,
    executedAt: 70,
  };
  const fitColumnWidths = (columns: ContractRegisterColumn[]) => {
    const baseTotal = columns.reduce((sum, column) => sum + baseColumnWidths[column], 0);
    const scale = baseTotal > 0 ? Math.min(1, pageWidth / baseTotal) : 1;
    const fitted: Partial<Record<ContractRegisterColumn, number>> = {};
    let used = 0;
    columns.forEach((column, index) => {
      const width = index === columns.length - 1 ? Math.max(24, pageWidth - used) : Math.max(24, Math.floor(baseColumnWidths[column] * scale));
      fitted[column] = width;
      used += width;
    });
    return fitted as Record<ContractRegisterColumn, number>;
  };
  const value = (column: ContractRegisterColumn, contract: any) => {
    if (column === "legalNumber") return safe(contract.legalNumber);
    if (column === "title") return safe(contract.title);
    if (column === "counterparty") return safe(contract.counterpartyName);
    if (column === "status") return safe(contract.status);
    if (column === "type") return safe(contract.contractType);
    if (column === "perspective") return safe(contract.perspective);
    if (column === "originalValue") return money(contract.originalValue, contract.currency);
    if (column === "currentCommitment") return money(contract.currentCommitment, contract.currency);
    if (column === "currency") return safe(contract.currency);
    if (column === "approvedAt") return safe(contract.approvedAt, "Not recorded").slice(0, 10);
    return safe(contract.executedAt, "Not recorded").slice(0, 10);
  };
  const header = () => {
    doc.fontSize(16).font("Helvetica-Bold").fillColor("#123f68").text("BIMLog Contracts & Commitments Current View", 40, 36);
    doc.fontSize(8).font("Helvetica").fillColor("#4b5563").text("Operational project-control register only. Not an accounting posting, invoice payment, bank movement, external portal, or automatic AI.", 40, 57, { width: pageWidth });
    doc.fontSize(9).fillColor("#111827").text(`${safe(data.project.companyName)} | ${safe(data.project.name)} (${safe(data.project.code)})`, 40, 78, { width: pageWidth });
    doc.text(`Generated: ${generated} | Generated by: ${safe(data.generatedBy)} | Source view: ${safe(data.sourceView)} | Content hash: ${safe(data.contentHash)}`, 40, 92, { width: pageWidth });
    doc.moveTo(40, 110).lineTo(doc.page.width - 40, 110).strokeColor("#cbd5e1").stroke();
    return 124;
  };
  let y = header();
  if (data.selectedSections.includes("summary")) {
    const cards = [
      ["Matching contracts", String(data.counts.matching)],
      ["Accessible contracts", String(data.counts.totalAccessible)],
      ["Executed", String(data.counts.executed)],
      ["Approved", String(data.counts.approved)],
      ["Draft", String(data.counts.draft)],
      ["Counterparties", String(data.counts.companies)],
      ["Executed commitment", `${safe(data.totals.executedCommitments)} ${safe(data.totals.currencies?.join(", "))}`],
    ];
    const gap = 7;
    const perRow = 4;
    const cardWidth = (pageWidth - gap * (perRow - 1)) / perRow;
    cards.forEach(([title, metric], index) => {
      const x = 40 + (index % perRow) * (cardWidth + gap);
      const cardY = y + Math.floor(index / perRow) * 46;
      doc.roundedRect(x, cardY, cardWidth, 40, 5).fill("#f4f6f8");
      doc.fontSize(6.5).font("Helvetica-Bold").fillColor("#64748b").text(title, x + 6, cardY + 7, { width: cardWidth - 12, lineBreak: false });
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#123f68").text(metric, x + 6, cardY + 22, { width: cardWidth - 12, lineBreak: false });
    });
    y += Math.ceil(cards.length / perRow) * 46 + 8;
  }
  if (data.selectedSections.includes("filters")) {
    doc.fontSize(10).font("Helvetica-Bold").fillColor("#123f68").text("Current-view filters", 40, y);
    y += 13;
    doc.fontSize(8).font("Helvetica").fillColor("#374151").text(data.filters.join(" | "), 40, y, { width: pageWidth });
    y += 34;
  }
  if (data.selectedSections.includes("contracts")) {
    const columns = data.selectedColumns;
    if (columns.length === 0) {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#7c2d12").text("No columns selected for the contracts section.", 40, y);
    } else if (data.contracts.length === 0) {
      doc.roundedRect(40, y, pageWidth, 58, 6).fill("#f8fafc");
      doc.fontSize(12).font("Helvetica-Bold").fillColor("#123f68").text(data.counts.totalAccessible === 0 ? "No accessible contract records" : "No contracts match the current filters", 54, y + 14);
      doc.fontSize(8).font("Helvetica").fillColor("#64748b").text(data.counts.totalAccessible === 0 ? "Authorized users can create or import controlled contracts from the Contracts workspace." : "Adjust search, status, counterparty, type, perspective, currency, date, or value filters and export again.", 54, y + 34, { width: pageWidth - 28 });
    } else {
      const renderHeader = () => {
        const fittedWidths = fitColumnWidths(columns);
        let x = 40;
        doc.rect(40, y, pageWidth, 18).fill("#123f68");
        doc.fontSize(6.5).font("Helvetica-Bold").fillColor("#ffffff");
        for (const column of columns) {
          doc.text(labelColumns[column], x + 3, y + 5, { width: fittedWidths[column] - 6, lineBreak: false });
          x += fittedWidths[column];
        }
        y += 18;
        return fittedWidths;
      };
      let fittedWidths = renderHeader();
      for (const contract of data.contracts) {
        if (y > 520) { doc.addPage(); y = header(); fittedWidths = renderHeader(); }
        let x = 40;
        doc.rect(40, y, pageWidth, 24).fill(data.contracts.indexOf(contract) % 2 === 0 ? "#ffffff" : "#f8fafc");
        doc.fontSize(6.5).font("Helvetica").fillColor("#111827");
        for (const column of columns) {
          doc.text(value(column, contract), x + 3, y + 6, { width: fittedWidths[column] - 6, height: 14, ellipsis: true });
          x += fittedWidths[column];
        }
        y += 24;
      }
    }
  }
  doc.moveDown().fontSize(7).fillColor("#64748b").text("Privacy: invitation tokens, private sign-in material, provider/storage internals, hidden authorization data, and private audit details are not included.", 40, Math.min(y + 14, 540), { width: pageWidth });
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(i);
    doc.fontSize(7).fillColor("#64748b").text(`Page ${i + 1} of ${range.count} | ${safe(data.project.name)} | ${safe(data.contentHash)}`, 40, 552, { width: pageWidth, align: "right" });
  }
  doc.end();
  return new Promise((resolve, reject) => { doc.on("end", () => resolve(Buffer.concat(chunks))); doc.on("error", reject); });
}

export async function buildContractPdf(data: ContractExport): Promise<Buffer> {
  const doc = new PDFDocument({ size: "LETTER", margin: 42, bufferPages: true, info: { Title: `Contract ${safe(data.contract.legalNumber)}`, Author: "BIMLog", Subject: "Operational contract and schedule of values" } });
  const chunks: Buffer[] = []; doc.on("data", (chunk) => chunks.push(chunk));
  doc.fontSize(18).text("BIMLog Contract & Commitment Record").fontSize(9).text("Operational project-control record — not an accounting posting or payment authorization.").moveDown();
  doc.fontSize(11).text(`${safe(data.project.companyName)} | ${safe(data.project.name)} (${safe(data.project.code)})`);
  doc.text(`${safe(data.contract.legalNumber)} | ${safe(data.contract.title)} | ${safe(data.contract.status)}`);
  doc.text(`${safe(data.contract.counterpartyName)} | ${safe(data.contract.perspective)} | ${safe(data.contract.contractType)}`);
  doc.text(`Original: ${data.contract.originalValue} ${data.contract.currency} | Executed amendments: ${data.contract.executedAmendmentTotal} | Current commitment: ${data.contract.currentCommitment}`).moveDown();
  doc.fontSize(12).text("Schedule of Values").fontSize(9);
  for (const line of data.contract.lines) {
    if (doc.y > 700) doc.addPage();
    doc.text(`${safe(line.projectCode)} — ${safe(line.description)}`, 42, doc.y, { continued: true, width: 400 }).text(`${line.amount} ${data.contract.currency}`, { align: "right" });
  }
  if (data.contract.amendments.length) {
    doc.moveDown().fontSize(12).text("Amendments").fontSize(9);
    for (const amendment of data.contract.amendments) doc.text(`${safe(amendment.legalNumber)} | ${safe(amendment.title)} | ${safe(amendment.status)} | ${amendment.amountDelta} ${amendment.currency}`);
  }
  doc.moveDown().fontSize(8).text(`BIMLog ID: ${safe(data.contract.bimlogId)}`).text(`Content fingerprint: ${data.contract.contentFingerprint}`).text(`Generated: ${data.generatedAt}`);
  const range = doc.bufferedPageRange(); for (let i = 0; i < range.count; i++) { doc.switchToPage(i); doc.fontSize(8).text(`Page ${i + 1} of ${range.count}`, 42, 742, { align: "right", width: 528 }); }
  doc.end(); return new Promise((resolve, reject) => { doc.on("end", () => resolve(Buffer.concat(chunks))); doc.on("error", reject); });
}

export function buildContractXlsx(data: ContractExport): Buffer {
  const wb = XLSX.utils.book_new();
  const sov = XLSX.utils.json_to_sheet(data.contract.lines.map((line: any) => ({ "SOV Line": safe(line.stableLineId), "Cost Code": safe(line.projectCode), "Cost Name": safe(line.projectName), Description: safe(line.description), Amount: exactPositiveAmount(line.amount), Currency: data.contract.currency, "Budget Amount": exactDelta(line.budgetAmount), "Schedule Item": line.schedule ? `${safe(line.schedule.sourceType)}:${line.schedule.sourceId}` : "" })), canonicalSpreadsheetWriteOptions({}));
  const amendments = XLSX.utils.json_to_sheet(data.contract.amendments.map((a: any) => ({ Number: safe(a.legalNumber), Title: safe(a.title), Version: a.version, Status: safe(a.status), Delta: exactDelta(a.amountDelta), Currency: a.currency, Approved: a.approvedAt ?? "", Executed: a.executedAt ?? "" })), canonicalSpreadsheetWriteOptions({}));
  const info = XLSX.utils.aoa_to_sheet([["Contract & Commitment Record"], ["Project", safe(data.project.name)], ["Project Code", safe(data.project.code)], ["Company", safe(data.project.companyName)], ["BIMLog ID", safe(data.contract.bimlogId)], ["Legal Number", safe(data.contract.legalNumber)], ["Perspective", data.contract.perspective], ["Type", data.contract.contractType], ["Counterparty", safe(data.contract.counterpartyName)], ["Status", data.contract.status], ["Currency", data.contract.currency], ["Original Value", data.contract.originalValue], ["Executed Amendment Total", data.contract.executedAmendmentTotal], ["Current Commitment", data.contract.currentCommitment], ["Content Fingerprint", data.contract.contentFingerprint], ["Generated", data.generatedAt], ["Boundary", "Operational record only; no accounting posting, invoice payment, money movement, or bank behavior."]], canonicalSpreadsheetWriteOptions({}));
  sov["!autofilter"] = { ref: sov["!ref"] ?? "A1:H1" }; sov["!cols"] = [{wch:16},{wch:16},{wch:24},{wch:42},{wch:16},{wch:10},{wch:16},{wch:20}];
  XLSX.utils.book_append_sheet(wb, sov, "Schedule of Values"); XLSX.utils.book_append_sheet(wb, amendments, "Amendments"); XLSX.utils.book_append_sheet(wb, info, "Contract Information");
  const output: Buffer = XLSX.write(wb, canonicalSpreadsheetWriteOptions({ type: "buffer", bookType: "xlsx", compression: true }));
  const zip = new AdmZip(output), entry = zip.getEntry("xl/worksheets/sheet1.xml");
  if (!entry) throw new FinancialControlError(500, "CONTRACT_EXPORT_SHEET_MISSING", "Contract worksheet could not be finalized.");
  const xml = entry.getData().toString("utf8").replace(/(<sheetView[^>]*>)/, '$1<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>');
  zip.updateFile("xl/worksheets/sheet1.xml", Buffer.from(xml, "utf8")); return zip.toBuffer();
}
