import { pool } from "@workspace/db";
let ready: Promise<void> | null = null;
export function startFinancialBudgetMigration() {
  return ready ?? (ready = ensureFinancialBudgetSchema());
}
export async function waitForFinancialBudgetMigration() {
  await startFinancialBudgetMigration();
}
export async function ensureFinancialBudgetSchema() {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(`
CREATE TABLE IF NOT EXISTS company_cost_library_versions(id text PRIMARY KEY,library_id text NOT NULL,company_id integer NOT NULL REFERENCES companies(id),version integer NOT NULL,effective_date date NOT NULL,status text NOT NULL,reason text NOT NULL,content_fingerprint text NOT NULL,supersedes_id text,created_by_id integer NOT NULL REFERENCES users(id),reviewed_by_id integer REFERENCES users(id),approved_by_id integer REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,approved_at timestamptz,CONSTRAINT company_cost_library_status_chk CHECK(status IN('draft','submitted','under_review','approved','rejected','deprecated')),UNIQUE(library_id,version));
CREATE TABLE IF NOT EXISTS company_cost_nodes(id text PRIMARY KEY,library_version_id text NOT NULL REFERENCES company_cost_library_versions(id),stable_node_id text NOT NULL,parent_stable_node_id text,hierarchical_path text NOT NULL,company_code text NOT NULL,name text NOT NULL,description text,active boolean NOT NULL DEFAULT true,sort_order integer NOT NULL,wbs_mapping text,csi_mapping text,schedule_activity_mapping text,external_mapping_profile_ref text,effective_from date NOT NULL,effective_to date,deprecation_reason text,UNIQUE(library_version_id,stable_node_id));
CREATE UNIQUE INDEX IF NOT EXISTS company_cost_active_code_uidx ON company_cost_nodes(library_version_id,company_code) WHERE active;
CREATE UNIQUE INDEX IF NOT EXISTS company_cost_sibling_order_uidx ON company_cost_nodes(library_version_id,COALESCE(parent_stable_node_id,''),sort_order);
CREATE TABLE IF NOT EXISTS project_cost_structure_versions(id text PRIMARY KEY,structure_id text NOT NULL,project_id integer NOT NULL REFERENCES projects(id),company_id integer NOT NULL REFERENCES companies(id),library_version_id text NOT NULL REFERENCES company_cost_library_versions(id),version integer NOT NULL,status text NOT NULL,reason text NOT NULL,validation_fingerprint text NOT NULL,content_fingerprint text NOT NULL,supersedes_id text,created_by_id integer NOT NULL REFERENCES users(id),reviewed_by_id integer REFERENCES users(id),approved_by_id integer REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),approved_at timestamptz,CONSTRAINT project_cost_structure_status_chk CHECK(status IN('draft','submitted','under_review','approved','rejected','deprecated')),UNIQUE(structure_id,version));
CREATE TABLE IF NOT EXISTS project_cost_nodes(id text PRIMARY KEY,structure_version_id text NOT NULL REFERENCES project_cost_structure_versions(id),stable_project_node_id text NOT NULL,company_stable_node_id text NOT NULL,company_library_version_id text NOT NULL,parent_project_node_id text,project_code text NOT NULL,project_name text NOT NULL,description text,wbs_mapping text,schedule_activity_ref text,csi_mapping text,active boolean NOT NULL DEFAULT true,sort_order integer NOT NULL,effective_from date NOT NULL,effective_to date,mapping_provenance text NOT NULL,UNIQUE(structure_version_id,stable_project_node_id));
CREATE UNIQUE INDEX IF NOT EXISTS project_cost_active_code_uidx ON project_cost_nodes(structure_version_id,project_code) WHERE active;
CREATE TABLE IF NOT EXISTS project_budget_versions(id text PRIMARY KEY,budget_id text NOT NULL,project_id integer NOT NULL REFERENCES projects(id),company_id integer NOT NULL REFERENCES companies(id),structure_version_id text NOT NULL REFERENCES project_cost_structure_versions(id),version integer NOT NULL,currency text NOT NULL,status text NOT NULL,purpose text NOT NULL,prepared_by_id integer NOT NULL REFERENCES users(id),submitted_by_id integer REFERENCES users(id),reviewed_by_id integer REFERENCES users(id),approved_by_id integer REFERENCES users(id),submitted_at timestamptz,reviewed_at timestamptz,approved_at timestamptz,outcome_reason text,previous_approved_id text,content_fingerprint text NOT NULL,calculated_total numeric(30,6) NOT NULL,approved_snapshot_id text,source_file_id integer REFERENCES files(id),revision integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT project_budget_currency_chk CHECK(currency~'^[A-Z]{3}$'),CONSTRAINT project_budget_status_chk CHECK(status IN('draft','submitted','under_review','approved','returned','rejected','withdrawn','superseded','voided')),UNIQUE(budget_id,version));
CREATE TABLE IF NOT EXISTS project_budget_lines(id text PRIMARY KEY,budget_version_id text NOT NULL REFERENCES project_budget_versions(id),stable_line_id text NOT NULL,project_cost_node_id text NOT NULL REFERENCES project_cost_nodes(id),description text NOT NULL,amount numeric(30,6) NOT NULL,quantity numeric(30,6),unit text,unit_rate numeric(30,6),notes text,provenance text,sort_order integer NOT NULL,UNIQUE(budget_version_id,stable_line_id));
CREATE TABLE IF NOT EXISTS approved_budget_snapshots(id text PRIMARY KEY,budget_version_id text NOT NULL UNIQUE REFERENCES project_budget_versions(id),budget_id text NOT NULL,budget_version integer NOT NULL,project_id integer NOT NULL REFERENCES projects(id),company_id integer NOT NULL REFERENCES companies(id),structure_version_id text NOT NULL REFERENCES project_cost_structure_versions(id),currency text NOT NULL,total numeric(30,6) NOT NULL,original_total numeric(30,6) NOT NULL,current_total numeric(30,6) NOT NULL,difference_from_original numeric(30,6) NOT NULL,approved_by_id integer NOT NULL REFERENCES users(id),approved_at timestamptz NOT NULL,approval_policy_id text NOT NULL,approval_limit numeric(30,6) NOT NULL,content_fingerprint text NOT NULL,snapshot_fingerprint text NOT NULL UNIQUE,previous_snapshot_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS approved_budget_snapshot_lines(id text PRIMARY KEY,snapshot_id text NOT NULL REFERENCES approved_budget_snapshots(id),stable_line_id text NOT NULL,project_cost_node_id text NOT NULL,project_code text NOT NULL,project_name text NOT NULL,hierarchical_path text NOT NULL,description text NOT NULL,amount numeric(30,6) NOT NULL,quantity numeric(30,6),unit text,unit_rate numeric(30,6),notes text,sort_order integer NOT NULL,UNIQUE(snapshot_id,stable_line_id));
CREATE TABLE IF NOT EXISTS budget_import_sessions(id text PRIMARY KEY,project_id integer NOT NULL REFERENCES projects(id),company_id integer NOT NULL REFERENCES companies(id),actor_user_id integer NOT NULL REFERENCES users(id),source_file_id integer NOT NULL REFERENCES files(id),file_hash text NOT NULL,parsed_fingerprint text NOT NULL,currency text NOT NULL,total numeric(30,6) NOT NULL,accepted_count integer NOT NULL,rejected_count integer NOT NULL,preview jsonb NOT NULL,confirmed_budget_version_id text UNIQUE,idempotency_key text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),confirmed_at timestamptz,UNIQUE(project_id,idempotency_key));
CREATE UNIQUE INDEX IF NOT EXISTS project_original_budget_uidx ON project_budget_versions(project_id) WHERE status='approved' AND previous_approved_id IS NULL;
`);
    await client.query(`
CREATE OR REPLACE FUNCTION reject_budget_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'financial budget history is append-only'; END $$;
CREATE OR REPLACE FUNCTION guard_budget_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN('approved','superseded','voided') THEN RAISE EXCEPTION 'approved budget is immutable'; END IF; IF OLD.status<>'draft' AND (NEW.structure_version_id<>OLD.structure_version_id OR NEW.currency<>OLD.currency OR NEW.purpose<>OLD.purpose OR NEW.content_fingerprint<>OLD.content_fingerprint OR NEW.calculated_total<>OLD.calculated_total OR NEW.source_file_id IS DISTINCT FROM OLD.source_file_id) THEN RAISE EXCEPTION 'submitted budget values are immutable'; END IF; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION guard_budget_line_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS(SELECT 1 FROM project_budget_versions WHERE id=OLD.budget_version_id AND status<>'draft') THEN RAISE EXCEPTION 'submitted or approved budget lines are immutable'; END IF; RETURN COALESCE(NEW,OLD); END $$;
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['company_cost_library_versions','company_cost_nodes','project_cost_structure_versions','project_cost_nodes','approved_budget_snapshots','approved_budget_snapshot_lines'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname=t||'_immutable') THEN EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_budget_history_mutation()',t||'_immutable',t); END IF; END LOOP; END $$;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='project_budget_guard') THEN CREATE TRIGGER project_budget_guard BEFORE UPDATE OR DELETE ON project_budget_versions FOR EACH ROW EXECUTE FUNCTION guard_budget_mutation(); END IF; IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='project_budget_line_guard') THEN CREATE TRIGGER project_budget_line_guard BEFORE UPDATE OR DELETE ON project_budget_lines FOR EACH ROW EXECUTE FUNCTION guard_budget_line_mutation(); END IF; END $$;
`);
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    ready = null;
    throw error;
  } finally {
    client.release();
  }
}
