import { pool } from "@workspace/db";

let ready: Promise<void> | null = null;
export function startFinancialControlMigration(): Promise<void> {
  if (ready) return ready;
  ready = ensureFinancialControlSchema();
  return ready;
}
export async function waitForFinancialControlMigration(): Promise<void> {
  await startFinancialControlMigration();
}
export async function ensureFinancialControlSchema(): Promise<void> {
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    await client.query(`CREATE TABLE IF NOT EXISTS financial_context_versions(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),scope_type text NOT NULL,version integer NOT NULL,base_currency text NOT NULL,reporting_currency text NOT NULL,permitted_transaction_currencies jsonb NOT NULL,effective_from timestamptz NOT NULL,effective_to timestamptz,supersedes_id text,reason text NOT NULL,created_by_id integer NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_context_scope_chk CHECK(scope_type IN('company','project')),CONSTRAINT financial_context_project_chk CHECK((scope_type='company' AND project_id IS NULL) OR (scope_type='project' AND project_id IS NOT NULL)),CONSTRAINT financial_context_dates_chk CHECK(effective_to IS NULL OR effective_to>effective_from),CONSTRAINT financial_context_reason_chk CHECK(length(reason) BETWEEN 3 AND 1000));
      CREATE UNIQUE INDEX IF NOT EXISTS financial_context_scope_version_uidx ON financial_context_versions(company_id,COALESCE(project_id,0),version);
      CREATE INDEX IF NOT EXISTS financial_context_effective_idx ON financial_context_versions(company_id,project_id,effective_from,effective_to);
      CREATE TABLE IF NOT EXISTS financial_authority_grants(id text PRIMARY KEY,user_id integer NOT NULL REFERENCES users(id),company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),scope_type text NOT NULL,authority text NOT NULL,version integer NOT NULL,effective_from timestamptz NOT NULL,effective_to timestamptz,reason text NOT NULL,granted_by_id integer NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_grant_scope_chk CHECK(scope_type IN('company','project')),CONSTRAINT financial_grant_project_chk CHECK((scope_type='company' AND project_id IS NULL) OR (scope_type='project' AND project_id IS NOT NULL)),CONSTRAINT financial_grant_authority_chk CHECK(authority IN('financial_viewer','cost_preparer','cost_reviewer','cost_approver','financial_administrator','auditor')),CONSTRAINT financial_grant_dates_chk CHECK(effective_to IS NULL OR effective_to>effective_from),CONSTRAINT financial_grant_reason_chk CHECK(length(reason) BETWEEN 3 AND 1000));
      CREATE UNIQUE INDEX IF NOT EXISTS financial_grant_version_uidx ON financial_authority_grants(user_id,company_id,COALESCE(project_id,0),authority,version);
      CREATE INDEX IF NOT EXISTS financial_grant_effective_idx ON financial_authority_grants(user_id,company_id,project_id,effective_from,effective_to);
      CREATE TABLE IF NOT EXISTS financial_authority_revocations(id text PRIMARY KEY,grant_id text NOT NULL UNIQUE REFERENCES financial_authority_grants(id),reason text NOT NULL,revoked_by_id integer NOT NULL REFERENCES users(id),revoked_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_revocation_reason_chk CHECK(length(reason) BETWEEN 3 AND 1000));
      CREATE TABLE IF NOT EXISTS financial_approval_policy_versions(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),scope_type text NOT NULL,transaction_category text NOT NULL,currency text NOT NULL,max_amount numeric(30,6) NOT NULL,version integer NOT NULL,effective_from timestamptz NOT NULL,effective_to timestamptz,supersedes_id text,state text NOT NULL,reason text NOT NULL,created_by_id integer NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_policy_scope_chk CHECK(scope_type IN('company','project')),CONSTRAINT financial_policy_project_chk CHECK((scope_type='company' AND project_id IS NULL) OR (scope_type='project' AND project_id IS NOT NULL)),CONSTRAINT financial_policy_currency_chk CHECK(currency~'^[A-Z]{3}$'),CONSTRAINT financial_policy_amount_chk CHECK(max_amount>=0),CONSTRAINT financial_policy_state_chk CHECK(state IN('active','revoked')),CONSTRAINT financial_policy_dates_chk CHECK(effective_to IS NULL OR effective_to>effective_from),CONSTRAINT financial_policy_reason_chk CHECK(length(reason) BETWEEN 3 AND 1000));
      CREATE UNIQUE INDEX IF NOT EXISTS financial_policy_scope_version_uidx ON financial_approval_policy_versions(company_id,COALESCE(project_id,0),transaction_category,currency,version);
      CREATE INDEX IF NOT EXISTS financial_policy_effective_idx ON financial_approval_policy_versions(company_id,project_id,transaction_category,currency,effective_from,effective_to);
      CREATE TABLE IF NOT EXISTS financial_suspension_events(id text PRIMARY KEY,company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),scope_type text NOT NULL,action text NOT NULL,reason text NOT NULL,actor_user_id integer NOT NULL REFERENCES users(id),occurred_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_suspension_scope_chk CHECK(scope_type IN('company','project')),CONSTRAINT financial_suspension_project_chk CHECK((scope_type='company' AND project_id IS NULL) OR (scope_type='project' AND project_id IS NOT NULL)),CONSTRAINT financial_suspension_action_chk CHECK(action IN('activate','release')),CONSTRAINT financial_suspension_reason_chk CHECK(length(reason) BETWEEN 3 AND 1000));
      CREATE INDEX IF NOT EXISTS financial_suspension_scope_time_idx ON financial_suspension_events(company_id,project_id,occurred_at);
      CREATE TABLE IF NOT EXISTS financial_authority_journal(id text PRIMARY KEY,event_type text NOT NULL,company_id integer NOT NULL REFERENCES companies(id),project_id integer REFERENCES projects(id),actor_user_id integer NOT NULL REFERENCES users(id),subject_user_id integer REFERENCES users(id),entity_type text NOT NULL,entity_id text NOT NULL,entity_version integer,decision text,reason_code text NOT NULL,explanation_en text NOT NULL,explanation_es text NOT NULL,evidence jsonb NOT NULL DEFAULT '{}'::jsonb,occurred_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT financial_journal_decision_chk CHECK(decision IS NULL OR decision IN('allow','deny')),CONSTRAINT financial_journal_explanation_chk CHECK(length(explanation_en) BETWEEN 1 AND 1000 AND length(explanation_es) BETWEEN 1 AND 1000));
      CREATE INDEX IF NOT EXISTS financial_journal_scope_time_idx ON financial_authority_journal(company_id,project_id,occurred_at);
      CREATE INDEX IF NOT EXISTS financial_journal_subject_time_idx ON financial_authority_journal(subject_user_id,occurred_at);`);
    await client.query(`CREATE OR REPLACE FUNCTION reject_financial_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'financial control history is append-only'; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_journal_immutable' AND tgrelid='financial_authority_journal'::regclass) THEN CREATE TRIGGER financial_journal_immutable BEFORE UPDATE OR DELETE ON financial_authority_journal FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_context_immutable' AND tgrelid='financial_context_versions'::regclass) THEN CREATE TRIGGER financial_context_immutable BEFORE UPDATE OR DELETE ON financial_context_versions FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_grant_immutable' AND tgrelid='financial_authority_grants'::regclass) THEN CREATE TRIGGER financial_grant_immutable BEFORE UPDATE OR DELETE ON financial_authority_grants FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_revocation_immutable' AND tgrelid='financial_authority_revocations'::regclass) THEN CREATE TRIGGER financial_revocation_immutable BEFORE UPDATE OR DELETE ON financial_authority_revocations FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_policy_immutable' AND tgrelid='financial_approval_policy_versions'::regclass) THEN CREATE TRIGGER financial_policy_immutable BEFORE UPDATE OR DELETE ON financial_approval_policy_versions FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;
      DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='financial_suspension_immutable' AND tgrelid='financial_suspension_events'::regclass) THEN CREATE TRIGGER financial_suspension_immutable BEFORE UPDATE OR DELETE ON financial_suspension_events FOR EACH ROW EXECUTE FUNCTION reject_financial_history_mutation(); END IF; END $$;`);
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    ready = null;
    throw error;
  } finally {
    client.release();
  }
}
