import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { normalizePaymentApplication } from "./financial-contract-payment";

const base = { applicationNumber: "PAY-001", idempotencyKey: "pay-001-retry", periodStart: "2026-08-01", periodEnd: "2026-08-15", currency: "usd", grossAmount: "100.000001", retainageAmount: "10.000001", lines: [{ contractSovLineId: "sov-1", currentAmount: "40.000001", sortOrder: 0 }, { contractSovLineId: "sov-2", currentAmount: "60", sortOrder: 1 }] };
const payment = normalizePaymentApplication(base);
assert.equal(payment.currency, "USD");
assert.equal(payment.netAmount, "90");
assert.equal(payment.lines.length, 2);
assert.match(payment.contentFingerprint, /^[a-f0-9]{64}$/);
assert.equal(normalizePaymentApplication(base).contentFingerprint, payment.contentFingerprint);
assert.throws(() => normalizePaymentApplication({ ...base, retainageAmount: "100.000002" }), (error: any) => error.code === "CONTRACT_PAYMENT_RETAINAGE_INVALID");
assert.throws(() => normalizePaymentApplication({ ...base, grossAmount: "100" }), (error: any) => error.code === "CONTRACT_PAYMENT_LINES_UNRECONCILED");
assert.throws(() => normalizePaymentApplication({ ...base, lines: [base.lines[0], base.lines[0]] }), (error: any) => error.code === "CONTRACT_PAYMENT_LINES_INVALID");
assert.throws(() => normalizePaymentApplication({ ...base, periodStart: "2026-08-16" }), (error: any) => error.code === "CONTRACT_PAYMENT_PERIOD_INVALID");
const root = path.dirname(fileURLToPath(import.meta.url));
const migration = fs.readFileSync(path.join(root, "financial-contract-migration.ts"), "utf8");
const service = fs.readFileSync(path.join(root, "financial-contract-payment-service.ts"), "utf8");
for (const table of ["financial_contract_payment_applications", "financial_contract_payment_versions", "financial_contract_payment_lines"]) assert.match(migration, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
assert.doesNotMatch(migration, /\bDROP\b/i);
assert.match(migration, /payment application version is immutable/);
assert.match(migration, /payment line is outside the governed contract/);
assert.match(migration, /approved payment total exceeds the governed SOV line/);
assert.match(service, /pg_advisory_xact_lock/);
assert.match(service, /CONTRACT_PAYMENT_IDEMPOTENCY_CONFLICT/);
assert.match(service, /CONTRACT_PAYMENT_STALE/);
assert.match(service, /payment_approval/);
assert.match(service, /Approved plus requested payment cannot exceed/);
assert.doesNotMatch(service, /bank_transfer|payment_provider|stripe|settlement/i);
console.log(JSON.stringify({ suite: "advanced-contract-payments", status: "passed", checks: 19 }, null, 2));
