import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import AdmZip from "adm-zip";
import { PDFParse } from "pdf-parse";
import { evaluateFinancialAuthorization, type ApprovalPolicy, type EffectiveGrant } from "./financial-control-contract";
import { assertReconciledTotal, contractCurrency, contractLineTotal, contractPermission, contractPerspective, contractType, exactDelta, exactVariance, higherLimitIsStrict, normalizeContractLines, safeCommercialMetadata } from "./financial-contract-contract";
import { buildContractPdf, buildContractXlsx } from "./financial-contract-export";

const checks: Array<{ number: number; name: string; evidence: string }> = [];
const check = (name: string, evidence: string) => checks.push({ number: checks.length + 1, name, evidence });
const throws = (fn: () => unknown, code: string) => assert.throws(fn, (e: any) => e?.code === code);
const now = new Date("2026-07-21T12:00:00Z"), before = new Date("2026-07-20T12:00:00Z"), after = new Date("2026-07-22T12:00:00Z");
const grant = (authority: any): EffectiveGrant => ({ id: `g-${authority}`, authority, scopeType: "project", companyId: 1, projectId: 2, effectiveFrom: before, effectiveTo: after, revoked: false });
const policy = (category: string, amount = "1000"): ApprovalPolicy => ({ id: `p-${category}`, scopeType: "project", companyId: 1, projectId: 2, category, money: { amount, currency: "USD" }, effectiveFrom: before, effectiveTo: after, state: "active", version: 1 });
const decide = (operation: any, authority: any, extra: any = {}) => evaluateFinancialAuthorization({ operation, userId: 10, companyId: 1, projectId: 2, entitlementDecision: "allow", membershipActive: true, companyCurrent: true, suspended: false, grants: [grant(authority)], policies: [], at: now, ...extra });

assert.equal(decide("execute", "cost_approver", { makerUserId: 11, category: "commitment_execution", amount: { amount: "100", currency: "USD" }, policies: [policy("commitment_execution")] }).decision, "allow");
check("execution is a separate controlled operation", "cost approver plus execution policy");
assert.equal(decide("execute", "financial_administrator", { makerUserId: 11, category: "commitment_execution", amount: { amount: "100", currency: "USD" }, policies: [policy("commitment_execution")] }).decision, "deny");
check("administrator cannot execute", "six-role separation retained");
assert.equal(decide("execute", "cost_approver", { makerUserId: 10, category: "commitment_execution", amount: { amount: "100", currency: "USD" }, policies: [policy("commitment_execution")] }).code, "FIN_MAKER_CHECKER_REQUIRED");
check("maker cannot execute own request", "maker-checker includes execution");
assert.equal(decide("execute", "cost_approver", { makerUserId: 11, category: "commitment_execution", amount: { amount: "100", currency: "USD" }, policies: [policy("commitment_execution")], suspended: true }).code, "FIN_SCOPE_SUSPENDED");
check("suspension precedes execution", "fail closed");
assert.equal(decide("execute", "cost_approver", { makerUserId: 11, category: "commitment_execution", amount: { amount: "100", currency: "USD" }, policies: [policy("commitment_execution")], entitlementDecision: "deny" }).code, "FIN_ENTITLEMENT_DENIED");
check("entitlement denial cannot be overridden", "execution denied before finance grant");
assert.equal(decide("execute", "cost_approver", { makerUserId: 11, category: "commitment_execution", amount: { amount: "1000.000001", currency: "USD" }, policies: [policy("commitment_execution", "1000")] }).code, "FIN_APPROVAL_LIMIT_EXCEEDED");
check("execution limit is exact", "sixth decimal enforced");

assert.equal(contractPerspective("upstream"), "upstream"); assert.equal(contractPerspective("downstream"), "downstream");
check("upstream and downstream perspectives", "separate contract views");
for (const value of ["owner_prime", "subcontract", "purchase_order", "consultant_agreement", "other_commitment"]) assert.equal(contractType(value), value);
check("approved contract types", "five bounded root types");
for (const value of ["view", "prepare", "review", "approve", "execute", "manage"]) assert.equal(contractPermission(value), value);
check("record permissions explicit", "record grant does not infer authority");
throws(() => contractPermission("admin"), "CONTRACT_VALUE_INVALID"); check("unknown record permission denied", "no admin alias");
assert.equal(contractCurrency("usd"), "USD"); throws(() => contractCurrency("US"), "FIN_CURRENCY_INVALID");
check("ISO currency controlled", "runtime ISO 4217 validation");
assert.equal(exactDelta("-0.000001"), "-0.000001"); throws(() => exactDelta("0.0000001"), "FIN_DECIMAL_INVALID");
check("amendment delta exact", "signed six-decimal boundary");
throws(() => exactDelta("1e3"), "FIN_DECIMAL_INVALID"); check("exponent notation rejected", "no floating input");
throws(() => exactDelta("1,00"), "FIN_DECIMAL_INVALID"); check("locale ambiguity rejected", "canonical dot decimal");
assert.equal(exactVariance("100.000001", "100"), "0.000001");
check("budget variance exact", "BigInt-scaled calculation");
assert.equal(higherLimitIsStrict("1000", "1000.000001"), true); assert.equal(higherLimitIsStrict("1000", "1000"), false);
check("higher approval must be strictly higher", "no equal-limit exception");

const lines = normalizeContractLines([{ stableLineId: "SOV-1", budgetSnapshotLineId: "snapshot-line-1", projectCostNodeId: "project-node-1", description: "Mobilization", amount: "40.000001", sortOrder: 0 }, { stableLineId: "SOV-2", budgetSnapshotLineId: "snapshot-line-2", projectCostNodeId: "project-node-2", scheduleItemPlacementId: 9, description: "Concrete", amount: "59.999999", sortOrder: 1 }]);
assert.equal(contractLineTotal(lines), "100"); assert.equal(assertReconciledTotal(lines, "100", "contract"), "100");
check("SOV exact reconciliation", "line sum equals original value");
throws(() => assertReconciledTotal(lines, "99.999999", "contract"), "CONTRACT_SOV_NOT_RECONCILED");
check("SOV mismatch denied", "one-millionth mismatch rejected");
throws(() => normalizeContractLines([...lines, { ...lines[0] }]), "CONTRACT_LINE_DUPLICATE");
check("stable SOV identities unique", "duplicate retry cannot duplicate lines");
throws(() => normalizeContractLines([{ ...lines[0], scheduleItemPlacementId: -1 }]), "CONTRACT_SCHEDULE_LINK_INVALID");
check("Schedule link identifier bounded", "positive canonical placement only");
assert.deepEqual(safeCommercialMetadata({ retainage: "10% metadata", tax: null, bond: "on file", insurance: "on file", calculation: "forbidden" }), { retainage: "10% metadata", tax: null, bond: "on file", insurance: "on file" });
check("commercial fields metadata only", "no retainage/tax calculation field");

const root = process.cwd(), migration = fs.readFileSync(path.join(root, "artifacts/api-server/src/lib/financial-contract-migration.ts"), "utf8"), service = fs.readFileSync(path.join(root, "artifacts/api-server/src/lib/financial-contract-service.ts"), "utf8"), routes = fs.readFileSync(path.join(root, "artifacts/api-server/src/routes/financial-contracts.ts"), "utf8"), browser = fs.readFileSync(path.join(root, "artifacts/bimlog/src/pages/FinancialContractWorkspace.tsx"), "utf8");
for (const table of ["financial_contracts", "financial_contract_versions", "financial_contract_sov_lines", "financial_contract_amendments", "financial_contract_amendment_versions", "financial_contract_amendment_lines", "financial_contract_import_sessions", "financial_contract_record_grants", "financial_contract_history"]) assert.match(migration, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
check("nine additive table families", "approved Build 3 data boundary");
assert.doesNotMatch(migration, /\bDROP\b/i); check("migration additive", "no DROP operation");
assert.match(migration, /append-only/); assert.match(migration, /immutable/); check("database immutability triggers", "history and executed records protected");
assert.match(migration, /financial line does not match pinned budget snapshot and structure/); check("snapshot and structure pins database enforced", "line-scope trigger");
assert.match(migration, /schedule relationship is outside the financial project/); check("Schedule tenancy database enforced", "link-only same-project guard");
assert.match(service, /pg_advisory_xact_lock/); assert.match(service, /FOR UPDATE/); check("concurrency serialized", "advisory and row locks");
assert.match(service, /ROLLBACK/); check("atomic rollback", "single transaction helper");
assert.match(service, /CONTRACT_APPROVAL_EXECUTION_SEPARATION/); check("approver cannot attest execution", "second actor enforced");
assert.match(service, /commitment_over_budget/); assert.match(service, /overBudgetReason/); check("over-budget exception controlled", "exact variance, reason, higher category");
assert.match(service, /commitment_aggregate_review/); check("aggregate anti-splitting escalation", "24-hour related approvals");
assert.match(service, /signed-document file reference/); check("execution evidence required", "authenticated project file");
assert.doesNotMatch(service + routes, /change_orders|rfis|submittals|meeting_|lens_/i); check("other modules cannot authorize money", "no cross-module financial write");
assert.doesNotMatch(service + routes, /\b(?:openai|anthropic|bank_account|bank_transfer|ledger_entry|erp_sync)\b/i); check("excluded behavior absent", "no AI, payment movement, bank, ledger, or ERP code");
assert.match(routes, /singleFileUpload/); assert.match(routes, /10 \* 1024 \* 1024/); check("central bounded upload reused", "Security Batch A middleware");
assert.match(browser, /@media\(max-width:720px\)/); assert.match(browser, /overflow-x:hidden/); check("390px responsive control", "mobile overflow prevented");
assert.match(browser, /Contratos y Compromisos/); assert.match(browser, /Attest signed execution/); check("bilingual execution UI", "English desktop and Spanish mobile strings");

const exportData: any = { project: { name: "Project", code: "P-1", companyName: "Company" }, contract: { id: "c", bimlogId: "BIMLOG-CON-c", legalNumber: "SC-001", title: "Concrete", status: "executed", counterpartyName: "Internal Test Trade", perspective: "downstream", contractType: "subcontract", originalValue: "100", currency: "USD", executedAmendmentTotal: "-1.000001", currentCommitment: "98.999999", versionId: "v", version: 1, contentFingerprint: "a".repeat(64), lines: [{ stableLineId: "SOV-1", projectCode: "03", projectName: "Concrete", description: "Foundations", amount: "100", budgetAmount: "120", schedule: null }], amendments: [{ legalNumber: "A-1", title: "Credit", version: 1, status: "executed", amountDelta: "-1.000001", currency: "USD", approvedAt: now.toISOString(), executedAt: now.toISOString() }] }, generatedAt: now.toISOString() };
const pdf = await buildContractPdf(exportData), parsed = await new PDFParse({ data: pdf }).getText(); assert.match(parsed.text, /Contract & Commitment Record/); assert.match(parsed.text, /SC-001/); assert.match(parsed.text, /98\.999999/);
check("searchable contract PDF", "canonical text and exact current commitment");
const xlsx = buildContractXlsx(exportData), zip = new AdmZip(xlsx); assert.ok(zip.getEntry("xl/workbook.xml")); assert.match(zip.readAsText("xl/worksheets/sheet1.xml"), /state="frozen"/); assert.doesNotMatch(zip.readAsText("xl/worksheets/sheet1.xml"), /<f[ >]/);
check("native XLSX fidelity", "workbook, frozen header, no formulas");
assert.ok(checks.length >= 38);
console.log(JSON.stringify({ suite: "cost-financial-control-build-3-focused", status: "passed", checks }, null, 2));
