import assert from "node:assert/strict";
import fs from "node:fs";

const route = fs.readFileSync(new URL("../routes/clash_reports.ts", import.meta.url), "utf8");
const start = route.indexOf('router.post("/projects/:projectId/clash-reports/lens-next/issues/create"');
const end = route.indexOf('// Registered BEFORE', start);
assert.ok(start >= 0 && end > start);
const block = route.slice(start, end);
assert.match(block, /lens-next-create\.v1/);
assert.match(block, /confirmed !== true/);
assert.match(block, /db\.transaction/);
assert.match(block, /validateAndRebindLocalVisualState/);
assert.match(block, /assignTradeFloorSeq/);
assert.match(block, /const displayId =/);
assert.match(block, /set\(\{ displayId,/);
assert.match(block, /return \{ serverId: inserted\.id, viewpointId, displayId,/);
assert.match(block, /screenshotUrl: rebound\.screenshotDataUrl/);
assert.match(block, /platform_identity_exists/);
assert.doesNotMatch(block, /lens-sync/);
const pullStart = route.indexOf('router.get("/projects/:projectId/clash-reports/lens-pull"');
const pullEnd = route.indexOf('router.post("/projects/:projectId/clash-reports/lens-viewpoints/:viewpointId/visual-state"', pullStart);
assert.ok(pullStart >= 0 && pullEnd > pullStart);
assert.match(route.slice(pullStart, pullEnd), /screenshotUrl: r\.screenshotUrl/);
console.log(JSON.stringify({ status: "PASS", tests: ["explicit-confirmation", "atomic-platform-record-and-package", "digest-rebind", "sequence-assignment", "verified-thumbnail-persistence", "thumbnail-pull-mapping", "no-overwrite"] }));
