import assert from "node:assert/strict";
import {canChangeSalesInquiryAssignment,parseSalesInquiryAssignment} from "./sales-inquiry-assignment";
assert.deepEqual(parseSalesInquiryAssignment({expectedUpdatedAt:"2026-10-02T12:00:00.000Z",assigned:true}),{expectedUpdatedAt:new Date("2026-10-02T12:00:00.000Z"),assigned:true});
for(const value of [{assigned:true},{assigned:"yes",expectedUpdatedAt:"2026-10-02T12:00:00.000Z"},{assigned:false,expectedUpdatedAt:"yesterday"}])assert.throws(()=>parseSalesInquiryAssignment(value));
assert.equal(canChangeSalesInquiryAssignment(null,7,true),true);
assert.equal(canChangeSalesInquiryAssignment(7,7,true),true);
assert.equal(canChangeSalesInquiryAssignment(8,7,true),false);
assert.equal(canChangeSalesInquiryAssignment(7,7,false),true);
assert.equal(canChangeSalesInquiryAssignment(null,7,false),false);
assert.equal(canChangeSalesInquiryAssignment(8,7,false),false);
console.log("B118 controlled sales inquiry assignment release: PASS");
