import crypto from "node:crypto";
import { pool } from "@workspace/db";
import { FinancialControlError } from "./financial-control-contract";
import { effectiveCommercialAccessForUser } from "./commercial-entitlement";
import { waitForJobIntakeMigration } from "./job-intake-migration";
import { waitForTeamResourcePlanningMigration } from "./team-resource-planning-migration";

type Queryable = { query: (text: string, values?: unknown[]) => Promise<{ rows: any[]; rowCount?: number | null }> };
type Assignment = { taskId: string; userId: number; plannedHours: number; startDate: string; endDate: string; category: string; reason: string; expectedTaskVersion: number };
type Profile = { weeklyCapacityHours: number; timezone: string; workingDays: number[]; leave: Array<{ startDate: string; endDate: string; label?: string }>; internalHourlyRate: number; billingHourlyRate: number };

const isoDate = /^\d{4}-\d{2}-\d{2}$/;
const money = (value: number) => Number(value.toFixed(2));
const canonical = (value: unknown): string => value === null || typeof value !== "object" ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : `{${Object.entries(value as Record<string, unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([key,item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;
const fingerprint = (value: unknown) => crypto.createHash("sha256").update(canonical(value)).digest("hex");
function id(value: unknown, field: string) { const n=Number(value); if(!Number.isSafeInteger(n)||n<=0) throw new FinancialControlError(400,"TEAM_RESOURCE_ID_INVALID",`${field} is invalid.`); return n; }
function text(value: unknown, field: string, min=1, max=200) { const s=String(value??"").trim(); if(s.length<min||s.length>max) throw new FinancialControlError(400,"TEAM_RESOURCE_TEXT_INVALID",`${field} is invalid.`); return s; }
function date(value: unknown, field: string) { const s=String(value??""); if(!isoDate.test(s)||Number.isNaN(Date.parse(`${s}T00:00:00Z`))) throw new FinancialControlError(400,"TEAM_RESOURCE_DATE_INVALID",`${field} is invalid.`); return s; }
function finite(value: unknown, field: string, min=0, max=1_000_000) { const n=Number(value); if(!Number.isFinite(n)||n<min||n>max) throw new FinancialControlError(400,"TEAM_RESOURCE_NUMBER_INVALID",`${field} is invalid.`); return n; }
function profile(value: any): Profile {
  const weeklyCapacityHours=finite(value?.weeklyCapacityHours,"weeklyCapacityHours",1,168);
  const timezone=text(value?.timezone||"UTC","timezone",1,100);
  const workingDays:number[]=[...new Set<number>((Array.isArray(value?.workingDays)?value.workingDays:[1,2,3,4,5]).map((item:unknown)=>finite(item,"workingDay",0,6)))].sort((a,b)=>a-b);
  if(!workingDays.length) throw new FinancialControlError(400,"TEAM_RESOURCE_WORKING_DAYS_REQUIRED","At least one working day is required.");
  const leave=(Array.isArray(value?.leave)?value.leave:[]).map((item:any)=>{const startDate=date(item.startDate,"leave.startDate"),endDate=date(item.endDate,"leave.endDate");if(startDate>endDate)throw new FinancialControlError(400,"TEAM_RESOURCE_LEAVE_RANGE_INVALID","Leave start must not be after end.");return{startDate,endDate,label:String(item.label??"").trim().slice(0,120)}});
  return {weeklyCapacityHours,timezone,workingDays,leave,internalHourlyRate:finite(value?.internalHourlyRate,"internalHourlyRate",0),billingHourlyRate:finite(value?.billingHourlyRate,"billingHourlyRate",0)};
}
function assignments(value: unknown): Assignment[] { if(!Array.isArray(value)||!value.length) throw new FinancialControlError(400,"TEAM_RESOURCE_ASSIGNMENTS_REQUIRED","At least one assignment is required."); return value.map((item:any)=>{const startDate=date(item.startDate,"assignment.startDate"),endDate=date(item.endDate,"assignment.endDate");if(startDate>endDate)throw new FinancialControlError(400,"TEAM_RESOURCE_ASSIGNMENT_RANGE_INVALID","Assignment start must not be after end.");return{taskId:text(item.taskId,"taskId",1,200),userId:id(item.userId,"userId"),plannedHours:finite(item.plannedHours,"plannedHours",0.01,100000),startDate,endDate,category:text(item.category||"general","category",1,120),reason:text(item.reason,"reason",5,500),expectedTaskVersion:id(item.expectedTaskVersion,"expectedTaskVersion")}}); }

async function access(actorUserId: number, projectId: number, client: Queryable) {
  const row=(await client.query(`SELECT p.id,p.name,p.code,u.company_id "companyId",u.is_super_admin "isSuperAdmin",pm.role FROM projects p JOIN users u ON u.id=$2 LEFT JOIN project_members pm ON pm.project_id=p.id AND pm.user_id=u.id AND pm.status='active' WHERE p.id=$1 AND p.status<>'archived'`,[projectId,actorUserId])).rows[0];
  if(!row) throw new FinancialControlError(404,"TEAM_RESOURCE_PROJECT_NOT_FOUND","Project not found.");
  if(!row.isSuperAdmin&&!row.role) throw new FinancialControlError(403,"TEAM_RESOURCE_MEMBERSHIP_REQUIRED","Active project membership is required.");
  const commercial=await effectiveCommercialAccessForUser(actorUserId,client);
  if(!row.isSuperAdmin&&!commercial.team_performance) throw new FinancialControlError(403,"TEAM_RESOURCE_ENTITLEMENT_REQUIRED","Team Performance & Skills access is required.");
  return {...row,canManage:Boolean(row.isSuperAdmin||["project_admin","admin","discipline_lead"].includes(String(row.role).toLowerCase()))};
}

function daysBetween(startDate:string,endDate:string,workingDays:number[],leave:Profile["leave"]) { let days=0; const cursor=new Date(`${startDate}T00:00:00Z`),end=new Date(`${endDate}T00:00:00Z`); while(cursor<=end){const day=cursor.getUTCDay(),stamp=cursor.toISOString().slice(0,10),away=leave.some(item=>item.startDate<=stamp&&item.endDate>=stamp);if(workingDays.includes(day)&&!away)days++;cursor.setUTCDate(cursor.getUTCDate()+1);} return days; }
export function evaluateStaffingScenario(input:{startDate:string;endDate:string;assignments:Assignment[];profiles:Map<number,Profile>;commitments:Map<number,number>;experience:Map<string,number>}) {
  const people=new Map<number,{userId:number;capacityHours:number;existingHours:number;scenarioHours:number;internalCost:number;billingValue:number;warnings:string[]}>();
  for(const assignment of input.assignments){const p=input.profiles.get(assignment.userId)??{weeklyCapacityHours:40,timezone:"UTC",workingDays:[1,2,3,4,5],leave:[],internalHourlyRate:0,billingHourlyRate:0};const capacityHours=money(daysBetween(input.startDate,input.endDate,p.workingDays,p.leave)*(p.weeklyCapacityHours/p.workingDays.length));const current=people.get(assignment.userId)??{userId:assignment.userId,capacityHours,existingHours:money(input.commitments.get(assignment.userId)??0),scenarioHours:0,internalCost:0,billingValue:0,warnings:[]};current.scenarioHours=money(current.scenarioHours+assignment.plannedHours);current.internalCost=money(current.internalCost+assignment.plannedHours*p.internalHourlyRate);current.billingValue=money(current.billingValue+assignment.plannedHours*p.billingHourlyRate);if(!(input.experience.get(`${assignment.userId}:${assignment.category}`)??0))current.warnings.push(`NO_VERIFIED_CATEGORY_EVIDENCE:${assignment.category}`);people.set(assignment.userId,current);}
  for(const person of people.values()){if(person.existingHours+person.scenarioHours>person.capacityHours)person.warnings.push("CAPACITY_EXCEEDED");}
  const rows=[...people.values()].map(item=>({...item,availableHours:money(Math.max(0,item.capacityHours-item.existingHours)),utilization:item.capacityHours?Number(((item.existingHours+item.scenarioHours)/item.capacityHours).toFixed(4)):null,warnings:[...new Set(item.warnings)]}));
  return {people:rows,totals:{scenarioHours:money(rows.reduce((s,r)=>s+r.scenarioHours,0)),internalCost:money(rows.reduce((s,r)=>s+r.internalCost,0)),billingValue:money(rows.reduce((s,r)=>s+r.billingValue,0))},warnings:[...new Set(rows.flatMap(row=>row.warnings))],decision:"review_required"};
}

async function context(actorUserId:number,projectId:number,client:Queryable){const auth=await access(actorUserId,projectId,client);const members=(await client.query(`SELECT u.id,u.full_name "name",COALESCE(u.job_title,'') "jobTitle",pm.role FROM project_members pm JOIN users u ON u.id=pm.user_id WHERE pm.project_id=$1 AND pm.status='active' ORDER BY lower(u.full_name)`,[projectId])).rows;const profiles=(await client.query(`SELECT DISTINCT ON(user_id) id,user_id "userId",version,content,created_at "createdAt" FROM team_capacity_profile_versions WHERE company_id=$1 AND user_id=ANY($2::int[]) ORDER BY user_id,version DESC`,[auth.companyId,members.map((m:any)=>m.id)])).rows;const tasks=(await client.query(`SELECT t.id,t.name_en "nameEn",t.name_es "nameEs",t.status,t.planned_hours "plannedHours",t.progress_percent "progress",t.assignee_user_id "assigneeUserId",t.version,w.name "workItem" FROM job_activation_tasks t JOIN job_activation_work_items w ON w.id=t.work_item_id WHERE w.project_id=$1 AND w.status<>'cancelled' AND t.status NOT IN('complete','cancelled') ORDER BY w.name,t.sequence`,[projectId])).rows;const loads=(await client.query(`SELECT t.assignee_user_id "userId",p.id "projectId",p.code "projectCode",p.name "projectName",SUM(t.planned_hours*(1-t.progress_percent/100.0)) "remainingHours" FROM job_activation_tasks t JOIN job_activation_work_items w ON w.id=t.work_item_id JOIN projects p ON p.id=w.project_id WHERE t.assignee_user_id=ANY($1::int[]) AND t.status NOT IN('complete','cancelled') AND EXISTS(SELECT 1 FROM project_members viewer WHERE viewer.project_id=p.id AND viewer.user_id=$2 AND viewer.status='active') GROUP BY t.assignee_user_id,p.id,p.code,p.name`,[members.map((m:any)=>m.id),actorUserId])).rows;const scenarios=(await client.query(`SELECT DISTINCT ON(scenario_key) id,scenario_key "scenarioKey",version,content,evaluation,created_at "createdAt",EXISTS(SELECT 1 FROM team_staffing_application_events e WHERE e.scenario_version_id=team_staffing_scenario_versions.id) applied FROM team_staffing_scenario_versions WHERE project_id=$1 ORDER BY scenario_key,version DESC`,[projectId])).rows;return{auth,members,profiles,tasks,loads,scenarios};}

export async function getResourcePlanning(input:{actorUserId:unknown;projectId:unknown},client:Queryable=pool){await Promise.all([waitForJobIntakeMigration(),waitForTeamResourcePlanningMigration()]);const actor=id(input.actorUserId,"actorUserId"),project=id(input.projectId,"projectId");const data=await context(actor,project,client);return{project:{id:project,name:data.auth.name,code:data.auth.code},canManage:data.auth.canManage,members:data.members.map((member:any)=>({...member,profile:data.profiles.find((p:any)=>Number(p.userId)===Number(member.id))??null,crossProjectLoad:data.loads.filter((l:any)=>Number(l.userId)===Number(member.id))})),tasks:data.tasks,scenarios:data.scenarios,methodology:"Saved availability and leave define capacity. Existing commitments come only from authorized Job Operations projects. Scenarios never change live assignments until an authorized reviewer explicitly applies them."};}

export async function saveCapacityProfile(input:{actorUserId:unknown;projectId:unknown;userId:unknown;profile:unknown;expectedVersion?:unknown},client:Queryable=pool){await waitForTeamResourcePlanningMigration();const actor=id(input.actorUserId,"actorUserId"),project=id(input.projectId,"projectId"),userId=id(input.userId,"userId"),content=profile(input.profile);const auth=await access(actor,project,client);if(!auth.isSuperAdmin&&actor!==userId)throw new FinancialControlError(403,"TEAM_RESOURCE_PROFILE_SELF_OR_ADMIN","Users may update only their own availability profile.");const member=(await client.query(`SELECT 1 FROM project_members WHERE project_id=$1 AND user_id=$2 AND status='active'`,[project,userId])).rows[0];if(!member)throw new FinancialControlError(400,"TEAM_RESOURCE_MEMBER_REQUIRED","The profile user must be an active project member.");const latest=(await client.query(`SELECT id,version FROM team_capacity_profile_versions WHERE company_id=$1 AND user_id=$2 ORDER BY version DESC LIMIT 1`,[auth.companyId,userId])).rows[0];const expected=Number(input.expectedVersion??0);if((latest?.version??0)!==expected)throw new FinancialControlError(409,"TEAM_RESOURCE_PROFILE_VERSION_CONFLICT","The availability profile changed. Reload before saving.");const row=(await client.query(`INSERT INTO team_capacity_profile_versions(id,company_id,user_id,version,content,content_fingerprint,supersedes_id,created_by_id) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8) RETURNING id,version,content,created_at "createdAt"`,[crypto.randomUUID(),auth.companyId,userId,expected+1,JSON.stringify(content),fingerprint(content),latest?.id??null,actor])).rows[0];return row;}

async function evaluationData(actor:number,project:number,content:any,client:Queryable){const data=await context(actor,project,client);const parsed=assignments(content.assignments);const startDate=date(content.startDate,"startDate"),endDate=date(content.endDate,"endDate");if(startDate>endDate)throw new FinancialControlError(400,"TEAM_RESOURCE_RANGE_INVALID","Scenario start must not be after end.");const memberIds=new Set(data.members.map((m:any)=>Number(m.id)));if(parsed.some(item=>!memberIds.has(item.userId)))throw new FinancialControlError(400,"TEAM_RESOURCE_SCENARIO_MEMBER_INVALID","Every scenario user must be an active project member.");const tasks=new Map(data.tasks.map((t:any)=>[String(t.id),t]));for(const item of parsed){const task:any=tasks.get(item.taskId);if(!task)throw new FinancialControlError(400,"TEAM_RESOURCE_SCENARIO_TASK_INVALID","Every scenario task must be an active task in this project.");if(Number(task.version)!==item.expectedTaskVersion)throw new FinancialControlError(409,"TEAM_RESOURCE_TASK_VERSION_CONFLICT","A task changed. Reload the scenario before saving.");}
  const profileMap=new Map<number,Profile>(data.members.map((m:any)=>{const row=data.profiles.find((p:any)=>Number(p.userId)===Number(m.id));return[Number(m.id),row?profile(row.content):profile({weeklyCapacityHours:40,timezone:"UTC",workingDays:[1,2,3,4,5],leave:[],internalHourlyRate:0,billingHourlyRate:0})]}));const commitments=new Map<number,number>();for(const load of data.loads)commitments.set(Number(load.userId),(commitments.get(Number(load.userId))??0)+Number(load.remainingHours));const experience=new Map<string,number>();return{parsed,startDate,endDate,evaluation:evaluateStaffingScenario({startDate,endDate,assignments:parsed,profiles:profileMap,commitments,experience})};}
export async function evaluateScenario(input:{actorUserId:unknown;projectId:unknown;content:any},client:Queryable=pool){await waitForTeamResourcePlanningMigration();const actor=id(input.actorUserId,"actorUserId"),project=id(input.projectId,"projectId");await access(actor,project,client);return(await evaluationData(actor,project,input.content,client)).evaluation;}
export async function saveScenario(input:{actorUserId:unknown;projectId:unknown;scenarioKey?:unknown;expectedVersion?:unknown;content:any},client:Queryable=pool){await waitForTeamResourcePlanningMigration();const actor=id(input.actorUserId,"actorUserId"),project=id(input.projectId,"projectId"),auth=await access(actor,project,client);if(!auth.canManage)throw new FinancialControlError(403,"TEAM_RESOURCE_MANAGE_REQUIRED","Project leadership is required to save staffing scenarios.");const scenarioKey=input.scenarioKey?text(input.scenarioKey,"scenarioKey",1,100):crypto.randomUUID();const latest=(await client.query(`SELECT id,version FROM team_staffing_scenario_versions WHERE scenario_key=$1 AND project_id=$2 ORDER BY version DESC LIMIT 1`,[scenarioKey,project])).rows[0],expected=Number(input.expectedVersion??0);if((latest?.version??0)!==expected)throw new FinancialControlError(409,"TEAM_RESOURCE_SCENARIO_VERSION_CONFLICT","The scenario changed. Reload before saving.");const data=await evaluationData(actor,project,input.content,client);const content={name:text(input.content?.name,"name",3,120),startDate:data.startDate,endDate:data.endDate,assignments:data.parsed};const row=(await client.query(`INSERT INTO team_staffing_scenario_versions(id,scenario_key,company_id,project_id,version,content,evaluation,content_fingerprint,supersedes_id,created_by_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,$10) RETURNING id,scenario_key "scenarioKey",version,content,evaluation,created_at "createdAt"`,[crypto.randomUUID(),scenarioKey,auth.companyId,project,expected+1,JSON.stringify(content),JSON.stringify(data.evaluation),fingerprint(content),latest?.id??null,actor])).rows[0];return row;}

export async function applyScenario(input:{actorUserId:unknown;projectId:unknown;scenarioVersionId:unknown;eventKey:unknown;reason:unknown},client:any=pool){await waitForTeamResourcePlanningMigration();const actor=id(input.actorUserId,"actorUserId"),project=id(input.projectId,"projectId"),auth=await access(actor,project,client);if(!auth.canManage)throw new FinancialControlError(403,"TEAM_RESOURCE_MANAGE_REQUIRED","Project leadership is required to apply staffing scenarios.");const scenarioId=text(input.scenarioVersionId,"scenarioVersionId",1,200),eventKey=text(input.eventKey,"eventKey",8,200),reason=text(input.reason,"reason",10,1000);const connection=typeof client.connect==="function"?await client.connect():client;try{await connection.query("BEGIN");const replay=(await connection.query(`SELECT result FROM team_staffing_application_events WHERE event_key=$1`,[eventKey])).rows[0];if(replay){await connection.query("COMMIT");return replay.result;}const row=(await connection.query(`SELECT content FROM team_staffing_scenario_versions WHERE id=$1 AND project_id=$2 FOR UPDATE`,[scenarioId,project])).rows[0];if(!row)throw new FinancialControlError(404,"TEAM_RESOURCE_SCENARIO_NOT_FOUND","Scenario version not found.");const list=assignments(row.content.assignments),applied=[];for(const item of list){const updated=(await connection.query(`UPDATE job_activation_tasks t SET assignee_user_id=$3,version=version+1,updated_at=now() FROM job_activation_work_items w WHERE t.id=$1 AND t.version=$2 AND w.id=t.work_item_id AND w.project_id=$4 RETURNING t.id,t.version`,[item.taskId,item.expectedTaskVersion,item.userId,project])).rows[0];if(!updated)throw new FinancialControlError(409,"TEAM_RESOURCE_TASK_VERSION_CONFLICT","A live task changed; no scenario assignments were applied.");applied.push({taskId:item.taskId,userId:item.userId,newVersion:updated.version});}const result={scenarioVersionId:scenarioId,applied,reason};await connection.query(`INSERT INTO team_staffing_application_events(id,event_key,scenario_version_id,project_id,actor_user_id,reason,result) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb)`,[crypto.randomUUID(),eventKey,scenarioId,project,actor,reason,JSON.stringify(result)]);await connection.query("COMMIT");return result;}catch(error){await connection.query("ROLLBACK");throw error;}finally{if(connection!==client)connection.release();}}
