import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root=path.resolve(import.meta.dirname,"../../../..");
const read=(file:string)=>fs.readFileSync(path.join(root,file),"utf8");
const migration=read("artifacts/api-server/src/lib/team-resource-planning-migration.ts"),schema=read("lib/db/src/schema/team-resource-planning.ts"),service=read("artifacts/api-server/src/lib/team-resource-planning-service.ts"),route=read("artifacts/api-server/src/routes/team-performance.ts"),page=read("artifacts/bimlog/src/components/team-performance/ResourceSchedulingPanel.tsx"),manual=read("artifacts/bimlog/src/lib/help-content.ts"),navbar=read("artifacts/bimlog/src/components/layout/Navbar.tsx"),help=read("artifacts/bimlog/src/pages/HelpCenter.tsx");
for(const table of ["team_capacity_profile_versions","team_staffing_scenario_versions","team_staffing_application_events"])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));
for(const name of ["team_capacity_profile_versions_company_id_fkey","team_capacity_profile_versions_user_id_fkey","team_capacity_profile_versions_supersedes_id_fkey","team_capacity_profile_versions_created_by_id_fkey","team_capacity_profile_version_positive_chk","team_capacity_profile_content_object_chk","team_staffing_scenario_versions_company_id_fkey","team_staffing_scenario_versions_project_id_fkey","team_staffing_scenario_versions_supersedes_id_fkey","team_staffing_scenario_versions_created_by_id_fkey","team_staffing_scenario_version_positive_chk","team_staffing_scenario_content_object_chk","team_staffing_scenario_evaluation_object_chk","team_staffing_application_events_event_key_key","team_staffing_application_events_scenario_version_id_fkey","team_staffing_application_events_project_id_fkey","team_staffing_application_events_actor_user_id_fkey","team_staffing_application_reason_chk"])assert.match(schema,new RegExp(name));
for(const name of ["team_capacity_profile_latest_idx","team_staffing_scenario_project_latest_idx","team_staffing_application_project_time_idx"])assert.match(schema,new RegExp(`${name}[\\s\\S]{0,180}\\.desc\\(\\)\\.nullsFirst\\(\\)`));
assert.match(service,/daysBetween/);assert.match(service,/weeklyCapacityHours/);assert.match(service,/CAPACITY_EXCEEDED/);assert.match(service,/internalCost/);assert.match(service,/billingValue/);assert.match(service,/EXISTS\(SELECT 1 FROM project_members viewer/);assert.match(service,/BEGIN/);assert.match(service,/ROLLBACK/);assert.match(service,/TASK_VERSION_CONFLICT/);assert.match(service,/event_key/);assert.match(route,/resource-planning\/evaluate/);assert.match(route,/scenarios\/:scenarioVersionId\/apply/);
assert.match(page,/What-if staffing scenario/);assert.match(page,/Programaci.n de Recursos/);assert.match(page,/Print \/ PDF/);assert.match(page,/Review & apply/);assert.match(manual,/Resource Scheduling/);assert.match(manual,/Applying fails atomically/);assert.match(navbar,/v1\.60\.27\.01/);assert.match(help,/Print complete manual/);assert.match(help,/Print filtered manual/);
console.log(JSON.stringify({status:"PASS",tests:["leave-adjusted-capacity","cross-project-commitments","cost-value-forecast","immutable-scenarios","atomic-apply","idempotent-event","task-version-conflict","bilingual-ui","csv","print-pdf","complete-manual","filtered-manual","global-print","release-version"]}));
