import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { canonicalInternalCostRate, canonicalInternalCostRole } from "./internal-cost-contract";

assert.equal(canonicalInternalCostRate("5.10"), "5.1");
assert.equal(canonicalInternalCostRate("6.50"), "6.5");
assert.equal(canonicalInternalCostRole("DRAFTER"), "drafter");
assert.throws(() => canonicalInternalCostRate("-1"), /nonnegative decimal/);
const source = fs.readFileSync(path.join(import.meta.dirname, "internal-cost-governance.ts"), "utf8");
const operations = fs.readFileSync(path.join(import.meta.dirname, "job-operations-service.ts"), "utf8");
for (const token of ["company_internal_cost_policy_versions", "member_internal_cost_profile_versions", "effective_from", "proposed_by_id", "approved_by_id", "content_fingerprint"]) assert.match(source, new RegExp(token));
assert.doesNotMatch(source, /DEFAULT\s+5\.1|DEFAULT\s+6\.5/);
assert.match(operations, /resolveApprovedMemberInternalCost/);
assert.match(source, /INTERNAL_COST_PROFILE_UNRESOLVED/);
assert.match(operations, /approvedCost\.state === "unresolved"/);
assert.match(operations, /internal_cost_profile_version_id=\$7/);
assert.doesNotMatch(operations, /COALESCE\(\$6::numeric,r\.internal_hourly_rate\)/);
console.log("UX126 internal-cost policy versions and effective dates: PASS");
console.log("UX127 approved member cost lookup and explicit unresolved state: PASS");
