import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { canonicalInternalCostRate, canonicalInternalCostRole, protectInternalCostAssignment } from "./internal-cost-contract";

assert.equal(canonicalInternalCostRate("5.10"), "5.1");
assert.equal(canonicalInternalCostRate("6.50"), "6.5");
assert.equal(canonicalInternalCostRole("DRAFTER"), "drafter");
assert.throws(() => canonicalInternalCostRate("-1"), /nonnegative decimal/);
const source = fs.readFileSync(path.join(import.meta.dirname, "internal-cost-governance.ts"), "utf8");
const operations = fs.readFileSync(path.join(import.meta.dirname, "job-operations-service.ts"), "utf8");
const routes = fs.readFileSync(path.join(import.meta.dirname, "../routes/job-operations.ts"), "utf8");
const page = fs.readFileSync(path.join(import.meta.dirname, "../../../bimlog/src/pages/JobOperationsWorkspace.tsx"), "utf8");
for (const token of ["company_internal_cost_policy_versions", "member_internal_cost_profile_versions", "effective_from", "proposed_by_id", "approved_by_id", "content_fingerprint"]) assert.match(source, new RegExp(token));
assert.doesNotMatch(source, /DEFAULT\s+5\.1|DEFAULT\s+6\.5/);
assert.match(operations, /resolveApprovedMemberInternalCost/);
assert.match(source, /INTERNAL_COST_PROFILE_UNRESOLVED/);
assert.match(operations, /approvedCost\.state === "unresolved"/);
assert.match(operations, /internal_cost_profile_version_id=\$7/);
assert.doesNotMatch(operations, /COALESCE\(\$6::numeric,r\.internal_hourly_rate\)/);
console.log("UX126 internal-cost policy versions and effective dates: PASS");
console.log("UX127 approved member cost lookup and explicit unresolved state: PASS");
for (const token of ["proposeInternalCostPolicy", "proposeMemberInternalCostProfile", "decideInternalCostVersion", "INTERNAL_COST_CEO_APPROVAL_REQUIRED"]) assert.match(source, new RegExp(token));
assert.match(routes, /internal-cost\/:kind\/:versionId\/decision/);
console.log("UX128 CEO approval workflow and immutable decision identity: PASS");
assert.match(operations, /internalCostGovernance/);
for (const phrase of ["Internal cost governance", "Gobernanza del costo interno", "Job Intake cannot edit or bypass this authority", "aprobación del CEO"]) assert.match(page, new RegExp(phrase));
console.log("UX129 permission-appropriate project governance view: PASS");
const snapshot = { internalHourlyRate:"5.1",plannedInternalCost:"51",internalCostProfileVersionId:"profile-v1",internalCostPolicyVersionId:"policy-v1",internalCostEffectiveDate:"2026-09-30",billingHourlyRate:"30" };
assert.deepEqual(protectInternalCostAssignment(snapshot,false),{...snapshot,internalHourlyRate:null,plannedInternalCost:null,internalCostProfileVersionId:null,internalCostPolicyVersionId:null,internalCostEffectiveDate:null});
assert.deepEqual(protectInternalCostAssignment(snapshot,true),snapshot);
assert.match(operations, /SUM\(e\.hours\*r\.internal_hourly_rate\)/);
assert.match(operations, /internal_cost_profile_version_id "internalCostProfileVersionId"/);
assert.match(operations, /customerBillingRateChanged: false/);
console.log("UX130 sensitive access and historical assignment snapshots: PASS");
