import assert from 'node:assert/strict';
import { normalizeJobIntakeData, jobIntakeCompletion } from './job-intake-contract';
const core = { package:false, budget:false, contracts:false, costValuePlanner:false, anyCommercial:false, fullCommercialActivation:false };
const input = { identity:{jobName:'Seven floor job',jobCode:'SEVEN',clientName:'Client',currency:'USD'}, scopeItems:[{id:'S1',name:'Shop drawings',quantity:'12',plannedHours:'800',unit:'Drawings'}], delivery:{workflowTemplate:'bim-submittal',submittalStrategy:'Review, submit and distribute'}, review:{scopeConfirmed:true,deliveryConfirmed:true,teamConfirmed:true}, team:{projectLeaderUserId:null,assignments:[]} };
const unstaffed = normalizeJobIntakeData(input);
assert.equal(jobIntakeCompletion(unstaffed, [], core).ready, true);
const plan = normalizeJobIntakeData({...input,team:{assignments:[{id:'P1',userId:null,personName:'',role:'BIM coordinator',scopeItemId:'S1',plannedHours:'20',internalHourlyRate:'6.5'}]}});
const result = jobIntakeCompletion(plan,[],{...core,budget:true,anyCommercial:true});
assert.equal(result.ready,true);
assert.equal(result.totals.plannedLaborCost,'130');
assert.equal(result.totals.assignedHours,'0');
assert.equal(result.totals.unassignedHours,'800');
assert.equal(plan.team.assignments[0].userId,null);
assert.equal(plan.team.assignments[0].personName,'');
assert.equal(jobIntakeCompletion(normalizeJobIntakeData({...input,team:{assignments:[{role:'',scopeItemId:'S1',plannedHours:'20'}]}}),[],core).ready,false);
const legacy = normalizeJobIntakeData({...input,team:{projectLeaderUserId:7,assignments:[{id:'OLD',userId:7,personName:'Existing member',role:'Coordinator',scopeItemId:'S1',plannedHours:'10',internalHourlyRate:'6.5'}]}});
assert.equal(legacy.team.assignments[0].userId,7);
assert.equal(jobIntakeCompletion(legacy,[],core).totals.assignedHours,'10');
assert.equal(jobIntakeCompletion(legacy,[],core).ready,true);
console.log('UX025 unstaffed activation / optional role budget / exact costs / legacy staff preservation PASS');

const released = normalizeJobIntakeData({...legacy,team:{...legacy.team,projectLeaderUserId:null,assignments:legacy.team.assignments.map(row=>({...row,userId:null,personName:""}))}});
assert.equal(released.team.projectLeaderUserId,null);
assert.equal(released.team.assignments[0].id,'OLD');
assert.equal(released.team.assignments[0].scopeItemId,'S1');
assert.equal(released.team.assignments[0].plannedHours,'10');
assert.equal(released.team.assignments[0].plannedLaborCost,'65');
assert.equal(jobIntakeCompletion(released,[],core).ready,true);
