<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>BIMLogLensNext.AreaSpike2021</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Autodesk.Navisworks.Api" HintPath="C:\Program Files\Autodesk\Navisworks Manage 2021\Autodesk.Navisworks.Api.dll" Private="false" />
    <Reference Include="Autodesk.Navisworks.ComApi" HintPath="C:\Program Files\Autodesk\Navisworks Manage 2021\Autodesk.Navisworks.ComApi.dll" Private="false" />
    <Reference Include="Autodesk.Navisworks.Interop.ComApi" HintPath="C:\Program Files\Autodesk\Navisworks Manage 2021\Autodesk.Navisworks.Interop.ComApi.dll" Private="false" />
  </ItemGroup>
</Project>
