import crypto from "crypto";
import { Router } from "express";
import { pool } from "@workspace/db";
import { authMiddleware } from "../middlewares/auth";
import { AiControlError, cancelRun, confirmEstimate, confirmFileEstimate, createEstimate, createProviderConnection, listProviderConnections, listUsage, reserveRun, revokeConnection, rotateConnection, updateConnectionPolicy, validateConnection, assertProvider, type Actor, type OwnerType } from "../lib/ai-control-plane";

const router: Router = Router();
router.use((req, res, next) => req.path.startsWith("/ai-control/") ? authMiddleware(req, res, next) : next());

async function actorFor(userId: number): Promise<Actor> {
  const result = await pool.query(`SELECT u.id,u.company_id,u.is_super_admin,EXISTS(SELECT 1 FROM company_ai_administrators ca WHERE ca.user_id=u.id AND ca.company_id=u.company_id AND ca.status='active') AS is_company_admin FROM users u WHERE u.id=$1`, [userId]);
  const row = result.rows[0];
  if (!row) throw new AiControlError("AUTH_USER_MISSING", "Authenticated user no longer exists.", 401);
  return { userId: row.id, companyId: row.company_id, isSuperAdmin: row.is_super_admin === true, isCompanyAdmin: row.is_company_admin === true };
}

const asyncRoute = (fn: (req: any, res: any) => Promise<void>) => async (req: any, res: any) => { try { await fn(req,res); } catch (error) { if (error instanceof AiControlError) { res.status(error.status).json({ error: error.code, message: error.message }); return; } console.error("[ai-control] request failed", error instanceof Error ? error.message : "unknown"); res.status(500).json({ error: "AI_CONTROL_FAILURE", message: "AI control request failed safely." }); } };
const integerString = (value: unknown, name: string, allowNegative=false) => { if (typeof value !== "string" || !(allowNegative ? /^-?\d+$/.test(value) : /^\d+$/.test(value))) throw new AiControlError("INPUT_INVALID", `${name} must be an integer string.`); return value; };
const date = (value: unknown, name: string) => { const d = new Date(String(value)); if (!value || Number.isNaN(d.valueOf())) throw new AiControlError("INPUT_INVALID", `${name} must be an ISO date.`); return d; };
const strings = (value: unknown, name: string) => { if (!Array.isArray(value) || value.some(v=>typeof v!=="string")) throw new AiControlError("INPUT_INVALID", `${name} must be a string array.`); return value as string[]; };
const requireCompanyAdmin = (a: Actor) => { if (!a.isCompanyAdmin && !a.isSuperAdmin) throw new AiControlError("COMPANY_AI_ADMIN_REQUIRED","An active company AI administrator grant is required.",403); };
const requireSuper = (a: Actor) => { if (!a.isSuperAdmin) throw new AiControlError("SUPER_ADMIN_REQUIRED","Super admin access required.",403); };
async function routeAudit(actorUserId:number, action:string, targetType:string, targetId:string, details:Record<string,unknown>){await pool.query(`INSERT INTO admin_actions_log(admin_user_id,admin_email,action,target_type,target_id,details) SELECT id,email,$2,$3,$4,$5::jsonb FROM users WHERE id=$1`,[actorUserId,action,targetType,targetId,JSON.stringify(details)]);}
const parseCompanyScope=(value:unknown)=>{if(value==null||value==="")return null;const n=Number(value);if(!Number.isSafeInteger(n)||n<=0)throw new AiControlError("INPUT_INVALID","companyId must be a positive integer.");return n;};

router.get("/ai-control/status", asyncRoute(async(req,res)=>{const actor=await actorFor(req.user.userId);res.json({providers:["openai","anthropic"],canManageCompany:actor.isCompanyAdmin||actor.isSuperAdmin,canManageSystem:actor.isSuperAdmin,automaticProviderRequests:false,generationEnabled:false});}));
router.get("/ai-control/companies", asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const rows=await pool.query(`SELECT id,name FROM companies ORDER BY name,id`);res.json(rows.rows);}));
router.get("/ai-control/company-ai-administrators", asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const companyId=parseCompanyScope(req.query.companyId)??a.companyId;const rows=await pool.query(`SELECT ca.id,ca.company_id,ca.user_id,ca.status,ca.granted_at,ca.revoked_at,u.full_name,u.email FROM company_ai_administrators ca JOIN users u ON u.id=ca.user_id WHERE ca.company_id=$1 ORDER BY ca.granted_at DESC`,[companyId]);res.json(rows.rows);}));
router.post("/ai-control/company-ai-administrators", asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const companyId=Number(req.body.companyId),userId=Number(req.body.userId);const target=await pool.query(`SELECT id FROM users WHERE id=$1 AND company_id=$2`,[userId,companyId]);if(!target.rows[0])throw new AiControlError("CROSS_COMPANY_FORBIDDEN","The selected user must belong to the selected company.",403);const id=crypto.randomUUID();const evidence={source:"super_admin_http",grantedAt:new Date().toISOString(),companyId,userId};const row=await pool.query(`INSERT INTO company_ai_administrators(id,company_id,user_id,status,granted_by_id,audit_evidence) VALUES($1,$2,$3,'active',$4,$5::jsonb) RETURNING *`,[id,companyId,userId,a.userId,JSON.stringify(evidence)]);await routeAudit(a.userId,"company_ai_administrator_granted","company_ai_administrator",id,evidence);res.status(201).json(row.rows[0]);}));
router.delete("/ai-control/company-ai-administrators/:id", asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const row=await pool.query(`UPDATE company_ai_administrators SET status='revoked',revoked_by_id=$2,revoked_at=now(),audit_evidence=audit_evidence||$3::jsonb WHERE id=$1 AND status='active' RETURNING *`,[String(req.params.id),a.userId,JSON.stringify({revokedBy:a.userId,revokedAt:new Date().toISOString()})]);if(!row.rows[0])throw new AiControlError("AI_ADMIN_GRANT_NOT_FOUND","Active AI administrator grant not found.",404);await routeAudit(a.userId,"company_ai_administrator_revoked","company_ai_administrator",String(req.params.id),{companyId:row.rows[0].company_id,userId:row.rows[0].user_id});res.json(row.rows[0]);}));
router.get("/ai-control/provider-connections", asyncRoute(async(req,res)=>{const actor=await actorFor(req.user.userId);res.json(await listProviderConnections(actor));}));
router.post("/ai-control/provider-connections", asyncRoute(async(req,res)=>{const actor=await actorFor(req.user.userId);const ownerType=req.body.ownerType as OwnerType;if(!["personal","company","system"].includes(ownerType))throw new AiControlError("OWNER_INVALID","Owner type must be personal, company, or system.");const row=await createProviderConnection({actorUserId:actor.userId,actorCompanyId:actor.companyId,actorIsSuperAdmin:actor.isSuperAdmin,actorIsCompanyAdmin:actor.isCompanyAdmin,ownerType,provider:assertProvider(req.body.provider),secret:String(req.body.apiKey||""),label:typeof req.body.label==="string"?req.body.label:undefined,allowedModels:strings(req.body.allowedModels||[],"allowedModels")});res.status(201).json(row);}));
router.post("/ai-control/provider-connections/:id/validate",asyncRoute(async(req,res)=>{res.json(await validateConnection(await actorFor(req.user.userId),String(req.params.id)));}));
router.post("/ai-control/provider-connections/:id/rotate",asyncRoute(async(req,res)=>{res.json(await rotateConnection(await actorFor(req.user.userId),String(req.params.id),String(req.body.apiKey||"")));}));
router.patch("/ai-control/provider-connections/:id",asyncRoute(async(req,res)=>{res.json(await updateConnectionPolicy(await actorFor(req.user.userId),String(req.params.id),{status:req.body.status,allowedModels:req.body.allowedModels===undefined?undefined:strings(req.body.allowedModels,"allowedModels")}));}));
router.delete("/ai-control/provider-connections/:id",asyncRoute(async(req,res)=>{res.json(await revokeConnection(await actorFor(req.user.userId),String(req.params.id)));}));

router.get("/ai-control/budgets",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const selectedCompanyId=parseCompanyScope(req.query.companyId);let rows;if(a.isSuperAdmin){rows=await pool.query(`SELECT b.*,COALESCE(json_agg(json_build_object('id',ua.id,'userId',ua.user_id,'userName',u.full_name,'userEmail',u.email,'limitMicros',ua.limit_micros,'dailyLimitMicros',ua.daily_limit_micros,'monthlyLimitMicros',ua.monthly_limit_micros,'sessionLimitMicros',ua.session_limit_micros,'reservedMicros',ua.reserved_micros,'settledMicros',ua.settled_micros,'status',ua.status)) FILTER(WHERE ua.id IS NOT NULL),'[]') allocations FROM company_ai_budgets b LEFT JOIN user_ai_allocations ua ON ua.budget_id=b.id LEFT JOIN users u ON u.id=ua.user_id WHERE b.funding_owner_type='system' OR ($1::int IS NOT NULL AND b.company_id=$1) GROUP BY b.id ORDER BY b.funding_owner_type,b.version DESC`,[selectedCompanyId]);}else if(a.isCompanyAdmin){rows=await pool.query(`SELECT b.*,COALESCE(json_agg(json_build_object('id',ua.id,'userId',ua.user_id,'userName',u.full_name,'userEmail',u.email,'limitMicros',ua.limit_micros,'dailyLimitMicros',ua.daily_limit_micros,'monthlyLimitMicros',ua.monthly_limit_micros,'sessionLimitMicros',ua.session_limit_micros,'reservedMicros',ua.reserved_micros,'settledMicros',ua.settled_micros,'status',ua.status)) FILTER(WHERE ua.id IS NOT NULL),'[]') allocations FROM company_ai_budgets b LEFT JOIN user_ai_allocations ua ON ua.budget_id=b.id LEFT JOIN users u ON u.id=ua.user_id WHERE (b.funding_owner_type='personal' AND b.owner_user_id=$1 AND b.company_id=$2) OR (b.funding_owner_type='company' AND b.company_id=$2) GROUP BY b.id ORDER BY b.funding_owner_type,b.version DESC`,[a.userId,a.companyId]);}else{rows=await pool.query(`SELECT b.*,COALESCE(json_agg(json_build_object('id',ua.id,'userId',ua.user_id,'limitMicros',ua.limit_micros,'dailyLimitMicros',ua.daily_limit_micros,'monthlyLimitMicros',ua.monthly_limit_micros,'sessionLimitMicros',ua.session_limit_micros,'reservedMicros',ua.reserved_micros,'settledMicros',ua.settled_micros,'status',ua.status)) FILTER(WHERE ua.id IS NOT NULL),'[]') allocations FROM company_ai_budgets b LEFT JOIN user_ai_allocations ua ON ua.budget_id=b.id AND ua.user_id=$1 WHERE (b.funding_owner_type='personal' AND b.owner_user_id=$1 AND b.company_id=$2) OR (b.funding_owner_type IN ('company','system') AND ua.user_id=$1) GROUP BY b.id ORDER BY b.funding_owner_type,b.version DESC`,[a.userId,a.companyId]);}res.json(rows.rows);}));
router.post("/ai-control/budgets",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const funding=String(req.body.fundingOwnerType||"personal");if(!["personal","company","system"].includes(funding))throw new AiControlError("INPUT_INVALID","fundingOwnerType is invalid.");if(funding==="company")requireCompanyAdmin(a);if(funding==="system")requireSuper(a);const version=Number(req.body.version);if(!Number.isSafeInteger(version)||version<=0)throw new AiControlError("INPUT_INVALID","version must be a positive integer.");const values=["limitMicros","perRequestLimitMicros","dailyLimitMicros","monthlyLimitMicros","sessionLimitMicros"] as const;for(const v of values)integerString(req.body[v],v);const companyId=funding==="system"?null:a.companyId,ownerUserId=funding==="personal"?a.userId:null;const client=await pool.connect();try{await client.query("BEGIN");const superseded=await client.query(`UPDATE company_ai_budgets SET status='superseded',effective_to=now() WHERE funding_owner_type=$1 AND COALESCE(company_id,0)=COALESCE($2::int,0) AND COALESCE(owner_user_id,0)=COALESCE($3::int,0) AND status='active' RETURNING id`,[funding,companyId,ownerUserId]);const row=await client.query(`INSERT INTO company_ai_budgets(id,funding_owner_type,company_id,owner_user_id,version,currency,limit_micros,per_request_limit_micros,daily_limit_micros,monthly_limit_micros,session_limit_micros,provider_allowlist,model_allowlist,capability_allowlist,status,effective_from,effective_to,supersedes_id,created_by_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14::jsonb,'active',$15,$16,$17,$18) RETURNING *`,[crypto.randomUUID(),funding,companyId,ownerUserId,version,String(req.body.currency||"USD").toUpperCase(),...values.map(v=>String(req.body[v])),JSON.stringify(strings(req.body.providerAllowlist||[],"providerAllowlist")),JSON.stringify(strings(req.body.modelAllowlist||[],"modelAllowlist")),JSON.stringify(strings(req.body.capabilityAllowlist||[],"capabilityAllowlist")),date(req.body.effectiveFrom,"effectiveFrom"),req.body.effectiveTo?date(req.body.effectiveTo,"effectiveTo"):null,superseded.rows[0]?.id||null,a.userId]);await client.query("COMMIT");res.status(201).json(row.rows[0]);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}));
router.get("/ai-control/company-users",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const requestedCompanyId=parseCompanyScope(req.query.companyId);const companyId=a.isSuperAdmin?(requestedCompanyId??a.companyId):a.companyId;if(!a.isSuperAdmin)requireCompanyAdmin(a);const rows=await pool.query(`SELECT id,full_name,email FROM users WHERE company_id=$1 ORDER BY full_name,email`,[companyId]);res.json(rows.rows);}));
router.post("/ai-control/budgets/:id/allocations",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const budget=await pool.query(`SELECT * FROM company_ai_budgets WHERE id=$1`,[String(req.params.id)]);const b=budget.rows[0];if(!b)throw new AiControlError("BUDGET_NOT_FOUND","Budget not found.",404);if(b.funding_owner_type==="personal")throw new AiControlError("ALLOCATION_NOT_ALLOWED","Personal budgets cannot receive company allocations.",403);let targetCompanyId:number;if(b.funding_owner_type==="system"){requireSuper(a);targetCompanyId=parseCompanyScope(req.body.companyId)??(()=>{throw new AiControlError("TARGET_COMPANY_REQUIRED","System allocations require an explicit target company.",400);})();}else{if(!a.isSuperAdmin){requireCompanyAdmin(a);if(b.company_id!==a.companyId)throw new AiControlError("CROSS_COMPANY_FORBIDDEN","Company administrators may allocate only their own company budgets.",403);}targetCompanyId=b.company_id;}const target=Number(req.body.userId);if(!Number.isSafeInteger(target)||target<=0)throw new AiControlError("INPUT_INVALID","userId must be a positive integer.");const user=await pool.query(`SELECT id FROM users WHERE id=$1 AND company_id=$2`,[target,targetCompanyId]);if(!user.rows[0])throw new AiControlError("CROSS_COMPANY_FORBIDDEN","Allocation target must belong to the permitted company.",403);const caps=["limitMicros","dailyLimitMicros","monthlyLimitMicros","sessionLimitMicros"] as const;for(const v of caps)integerString(req.body[v],v);const row=await pool.query(`INSERT INTO user_ai_allocations(id,budget_id,company_id,user_id,limit_micros,daily_limit_micros,monthly_limit_micros,session_limit_micros,status,created_by_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'active',$9) ON CONFLICT(budget_id,user_id) DO UPDATE SET limit_micros=EXCLUDED.limit_micros,daily_limit_micros=EXCLUDED.daily_limit_micros,monthly_limit_micros=EXCLUDED.monthly_limit_micros,session_limit_micros=EXCLUDED.session_limit_micros,status='active',updated_at=now() RETURNING *`,[crypto.randomUUID(),b.id,targetCompanyId,target,...caps.map(v=>String(req.body[v])),a.userId]);res.status(201).json(row.rows[0]);}));

router.get("/ai-control/entitlements",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const rows=await pool.query(`SELECT * FROM entitlement_rules WHERE company_id=$1 OR (company_id IS NULL AND $2::boolean) ORDER BY capability,funding_type,version DESC`,[a.companyId,a.isSuperAdmin]);res.json(rows.rows);}));
router.post("/ai-control/entitlements",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);const funding=String(req.body.fundingType);if(!["personal","company","system"].includes(funding))throw new AiControlError("INPUT_INVALID","fundingType is invalid.");if(funding==="system")requireSuper(a);else requireCompanyAdmin(a);const version=Number(req.body.version);if(!Number.isSafeInteger(version)||version<=0)throw new AiControlError("INPUT_INVALID","version must be positive.");const companyId=funding==="system"?null:a.companyId,capability=String(req.body.capability||"assistant");const client=await pool.connect();try{await client.query("BEGIN");const superseded=await client.query(`UPDATE entitlement_rules SET enabled=false,effective_to=now() WHERE COALESCE(company_id,0)=COALESCE($1::int,0) AND capability=$2 AND funding_type=$3 AND enabled=true AND effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) RETURNING id`,[companyId,capability,funding]);const row=await client.query(`INSERT INTO entitlement_rules(id,version,company_id,capability,funding_type,provider_allowlist,model_allowlist,enabled,requires_file_confirmation,effective_from,effective_to,supersedes_id,created_by_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9,$10,$11,$12,$13) RETURNING *`,[crypto.randomUUID(),version,companyId,capability,funding,JSON.stringify(strings(req.body.providerAllowlist||[],"providerAllowlist")),JSON.stringify(strings(req.body.modelAllowlist||[],"modelAllowlist")),req.body.enabled!==false,req.body.requiresFileConfirmation!==false,date(req.body.effectiveFrom,"effectiveFrom"),req.body.effectiveTo?date(req.body.effectiveTo,"effectiveTo"):null,superseded.rows[0]?.id||null,a.userId]);await client.query("COMMIT");res.status(201).json(row.rows[0]);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}));
router.get("/ai-control/prices",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const rows=await pool.query(`SELECT * FROM ai_price_schedules ORDER BY provider,model,version DESC`);res.json(rows.rows);}));
router.post("/ai-control/prices",asyncRoute(async(req,res)=>{const a=await actorFor(req.user.userId);requireSuper(a);const provider=assertProvider(req.body.provider);const source=String(req.body.sourceUrl||"");const official=provider==="openai"?source==="https://openai.com/api/pricing/":source==="https://docs.anthropic.com/en/docs/about-claude/pricing";if(!official)throw new AiControlError("OFFICIAL_PRICE_SOURCE_REQUIRED","Use the exact approved official provider pricing URL.",400);const version=Number(req.body.version);if(!Number.isSafeInteger(version)||version<=0)throw new AiControlError("INPUT_INVALID","version must be positive.");const model=String(req.body.model||""),currency=String(req.body.currency||"USD").toUpperCase();const client=await pool.connect();try{await client.query("BEGIN");const superseded=await client.query(`UPDATE ai_price_schedules SET status='superseded',effective_to=now() WHERE provider=$1 AND model=$2 AND currency=$3 AND status='active' AND effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) RETURNING id`,[provider,model,currency]);const row=await client.query(`INSERT INTO ai_price_schedules(id,version,provider,model,currency,unit_basis,input_micros,output_micros,cached_input_micros,source_url,verified_by_id,verified_at,effective_from,effective_to,supersedes_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'active') RETURNING *`,[crypto.randomUUID(),version,provider,model,currency,Number(req.body.unitBasis||1000000),integerString(req.body.inputMicros,"inputMicros"),integerString(req.body.outputMicros,"outputMicros"),req.body.cachedInputMicros==null?null:integerString(req.body.cachedInputMicros,"cachedInputMicros"),source,a.userId,date(req.body.verifiedAt,"verifiedAt"),date(req.body.effectiveFrom,"effectiveFrom"),req.body.effectiveTo?date(req.body.effectiveTo,"effectiveTo"):null,superseded.rows[0]?.id||null]);await client.query("COMMIT");res.status(201).json(row.rows[0]);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}));

router.post("/ai-control/estimates",asyncRoute(async(req,res)=>{res.status(201).json(await createEstimate(await actorFor(req.user.userId),req.body));}));
router.post("/ai-control/estimates/:id/confirm",asyncRoute(async(req,res)=>{res.json(await confirmEstimate(await actorFor(req.user.userId),String(req.params.id),req.body));}));
router.post("/ai-control/estimates/:id/confirm-files",asyncRoute(async(req,res)=>{res.json(await confirmFileEstimate(await actorFor(req.user.userId),String(req.params.id),req.body));}));
router.post("/ai-control/runs/:id/reserve",asyncRoute(async(req,res)=>{res.json(await reserveRun(await actorFor(req.user.userId),String(req.params.id),req.body));}));
router.post("/ai-control/runs/:id/cancel",asyncRoute(async(req,res)=>{res.json(await cancelRun(await actorFor(req.user.userId),String(req.params.id)));}));
router.get("/ai-control/usage",asyncRoute(async(req,res)=>{res.json(await listUsage(await actorFor(req.user.userId)));}));

export default router;
