import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
const source=readFileSync(new URL("./commercial-workspace.ts",import.meta.url),"utf8");
assert.match(source,/router\.get\("\/commercial\/billing-identity",authMiddleware/);
assert.match(source,/router\.patch\("\/commercial\/billing-identity",authMiddleware/);
assert.equal((source.match(/requireCommercialBillingManager\(authority\)/g)??[]).length>=5,true);
assert.match(source,/parseCommercialBillingIdentityUpdate\(req\.body\)/);
assert.match(source,/where\(eq\(companiesTable\.id,actor\.companyId\)\)/);
assert.match(source,/BILLING_IDENTITY_INVALID/);
assert.match(source,/await client\.query\("BEGIN"\)/);
assert.match(source,/billing_identity_updated/);
assert.match(source,/JSON\.stringify\(\{fields:\["address","phone"\],status:identity\.status\}\)/);
assert.match(source,/await client\.query\("COMMIT"\)/);
assert.match(source,/await client\.query\("ROLLBACK"\)/);
console.log("LR032 billing-admin canonical identity route: PASS");
