import { Router, type Response } from "express";
import { authMiddleware, isSuperAdminMiddleware } from "../middlewares/auth";
import { resolveEffectiveEntitlement } from "../lib/feature-catalog-service";
import { bindProjectCompany, createCompanyPolicyGrant, createPolicyVersion, FeaturePolicyError, inspectPolicyAudit, listCompanyPolicyGrantMetadata, listCurrentUserPreferences, listEffectivePolicies, listProjectCompanyBindingMetadata, policyCapabilities, revokeCompanyPolicyGrant, type PolicyDecision } from "../lib/feature-policy-service";

const router=Router();
const fail=(res:Response,status:number,code:string,en:string,es:string)=>res.status(status).json({code,error:{en,es}});
const safe=(res:Response,error:unknown)=>error instanceof FeaturePolicyError?fail(res,error.status,error.code,error.message,error.messageEs):fail(res,500,"POLICY_UNAVAILABLE","Feature policy controls are temporarily unavailable.","Los controles de políticas de funciones no están disponibles temporalmente.");
const projectId=(value:unknown):number=>{const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<=0)throw new FeaturePolicyError(400,"PROJECT_CONTEXT_INVALID","projectId must be a positive integer.","projectId debe ser un entero positivo.");return parsed;};
const explanation=(body:Record<string,unknown>)=>({en:String((body.explanation as Record<string,unknown>|undefined)?.en??"").trim(),es:String((body.explanation as Record<string,unknown>|undefined)?.es??"").trim()});
const policyBody=(body:Record<string,unknown>)=>({decision:String(body.decision) as PolicyDecision,configuration:body.configuration??{},expectedVersion:body.expectedVersion===undefined?undefined:Number(body.expectedVersion),reasonCode:String(body.reasonCode??"").trim(),explanation:explanation(body),effectiveFrom:body.effectiveFrom,effectiveTo:body.effectiveTo});

router.get("/features/policies/capabilities",authMiddleware,async(req,res)=>{try{res.json(await policyCapabilities(req.user!.userId));}catch(error){safe(res,error);}});
router.get("/features/policies/company",authMiddleware,async(req,res)=>{try{const result=await listEffectivePolicies({scope:"company",userId:req.user!.userId});res.json({...result,readOnly:true});}catch(error){safe(res,error);}});
router.get("/features/policies/projects/:projectId",authMiddleware,async(req,res)=>{try{const result=await listEffectivePolicies({scope:"project",userId:req.user!.userId,projectId:projectId(req.params.projectId)});res.json({...result,readOnly:true});}catch(error){safe(res,error);}});
router.get("/features/preferences",authMiddleware,async(req,res)=>{try{res.json({preferences:await listCurrentUserPreferences(req.user!.userId),readOnly:true});}catch(error){safe(res,error);}});
router.get("/features/:featureKey/policy-resolution",authMiddleware,async(req,res)=>{try{const pid=req.query.projectId===undefined?undefined:projectId(req.query.projectId);const decision=await resolveEffectiveEntitlement({featureKey:String(req.params.featureKey),userId:req.user!.userId,companyId:req.user!.companyId,projectId:pid});res.json({featureKey:decision.featureKey,decision:decision.decision,state:decision.state,code:decision.code,explanation:decision.explanation,sources:decision.sources,policy:decision.policy,evaluation:decision.evaluation});}catch(error){safe(res,error);}});

router.post("/features/policies/company/:featureKey",authMiddleware,async(req,res)=>{try{const result=await createPolicyVersion({scope:"company",featureKey:String(req.params.featureKey),actorUserId:req.user!.userId,...policyBody(req.body??{})});res.status(201).json(result);}catch(error){safe(res,error);}});
router.post("/features/policies/projects/:projectId/:featureKey",authMiddleware,async(req,res)=>{try{const result=await createPolicyVersion({scope:"project",projectId:projectId(req.params.projectId),featureKey:String(req.params.featureKey),actorUserId:req.user!.userId,...policyBody(req.body??{})});res.status(201).json(result);}catch(error){safe(res,error);}});
router.put("/features/preferences/:featureKey",authMiddleware,async(req,res)=>{try{const body=req.body??{};const result=await createPolicyVersion({scope:"user",featureKey:String(req.params.featureKey),actorUserId:req.user!.userId,decision:String(body.decision) as PolicyDecision,configuration:{},expectedVersion:body.expectedVersion===undefined?undefined:Number(body.expectedVersion),reasonCode:"USER_PREFERENCE_CHANGED",explanation:{en:"User changed this optional feature preference.",es:"El usuario cambió esta preferencia opcional de función."}});res.status(201).json(result);}catch(error){safe(res,error);}});
router.get("/features/policies/audit/:scope",authMiddleware,async(req,res)=>{try{const scope=String(req.params.scope);if(scope!=="company"&&scope!=="project")return fail(res,400,"POLICY_SCOPE_INVALID","Policy scope is invalid.","El alcance de política no es válido.");const pid=scope==="project"?projectId(req.query.projectId):undefined;return res.json({versions:await inspectPolicyAudit({userId:req.user!.userId,scope,projectId:pid,featureKey:req.query.featureKey===undefined?undefined:String(req.query.featureKey)}),readOnly:true});}catch(error){return safe(res,error);}});

router.post("/admin/feature-policy-authority-grants",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{try{const body=req.body??{};const result=await createCompanyPolicyGrant({actorUserId:req.user!.userId,companyId:Number(body.companyId),userId:Number(body.userId),reasonCode:String(body.reasonCode??"").trim(),explanation:explanation(body),effectiveFrom:body.effectiveFrom,effectiveTo:body.effectiveTo});res.status(201).json(result);}catch(error){safe(res,error);}});
router.get("/admin/feature-policy-authority-grants",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{try{res.json({grants:await listCompanyPolicyGrantMetadata(req.user!.userId,Number(req.query.companyId)),metadataOnly:true});}catch(error){safe(res,error);}});
router.post("/admin/feature-policy-authority-grants/:grantId/revoke",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{try{const body=req.body??{};res.status(201).json(await revokeCompanyPolicyGrant({actorUserId:req.user!.userId,grantId:String(req.params.grantId),reasonCode:String(body.reasonCode??"").trim(),explanation:explanation(body)}));}catch(error){safe(res,error);}});
router.post("/admin/project-company-bindings",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{try{const body=req.body??{};res.status(201).json(await bindProjectCompany({actorUserId:req.user!.userId,projectId:projectId(body.projectId),companyId:Number(body.companyId),reasonCode:String(body.reasonCode??"").trim(),explanation:explanation(body)}));}catch(error){safe(res,error);}});
router.get("/admin/project-company-bindings/:projectId",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{try{res.json({bindings:await listProjectCompanyBindingMetadata(req.user!.userId,projectId(req.params.projectId)),metadataOnly:true});}catch(error){safe(res,error);}});

export default router;
