import { Router } from "express";
import { db } from "@workspace/db";
import {
  projectsTable, rfisTable, submittalsTable, filesTable,
  activityLogTable, transmittalsTable, changeOrdersTable,
  meetingMinutesTable, actionItemsTable, projectMembersTable, usersTable,
} from "@workspace/db/schema";
import { eq, and, inArray, desc, ne } from "drizzle-orm";
import { authMiddleware, requireProjectMember } from "../middlewares/auth";
import PDFDocument from "pdfkit";
import jwt from "jsonwebtoken";

async function verifyReportToken(req: any, res: any): Promise<number | null> {
  const token =
    req.headers.authorization?.split(" ")[1] ||
    (req.query.token as string);
  if (!token) {
    res.status(401).json({ error: "Authentication required" });
    return null;
  }
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET!) as any;
    return decoded.userId || decoded.id;
  } catch {
    res.status(401).json({ error: "Invalid token" });
    return null;
  }
}

const router: Router = Router();

function pdfHeader(doc: PDFKit.PDFDocument, project: { name: string; code: string }, title: string) {
  doc.fontSize(16).font("Helvetica-Bold").fillColor("#1D4ED8").text("BIMLog", 50, 45);
  doc.fontSize(10).font("Helvetica").fillColor("#000").text(`by IgniteSmart`, { continued: false });
  doc.moveDown(0.3);
  doc.fontSize(14).font("Helvetica-Bold").fillColor("#111").text(title, { align: "center" });
  doc.fontSize(10).font("Helvetica").fillColor("#666")
    .text(`Project: ${project.name} (${project.code})  |  Generated: ${new Date().toLocaleDateString()}`, { align: "center" });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#D1D5DB").stroke();
  doc.moveDown();
}

function pdfFooter(doc: PDFKit.PDFDocument) {
  doc.fontSize(7).font("Helvetica").fillColor("#9CA3AF")
    .text("Confidential — Generated by BIMLog by IgniteSmart. For authorized use only.", 50, doc.page.height - 40, { align: "center" });
}

function row(doc: PDFKit.PDFDocument, label: string, value: string, labelWidth = 160) {
  const y = doc.y;
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#374151").text(label, 50, y, { width: labelWidth });
  doc.fontSize(9).font("Helvetica").fillColor("#111").text(value, 50 + labelWidth, y, { width: doc.page.width - 50 - labelWidth - 50 });
  doc.moveDown(0.3);
}

async function getProject(projectId: number) {
  const [p] = await db.select().from(projectsTable).where(eq(projectsTable.id, projectId));
  return p;
}

// ── PROJECT HEALTH ─────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/project-health/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const [rfis, subs, files] = await Promise.all([
      db.select().from(rfisTable).where(eq(rfisTable.projectId, projectId)),
      db.select().from(submittalsTable).where(eq(submittalsTable.projectId, projectId)),
      db.select().from(filesTable).where(eq(filesTable.projectId, projectId)),
    ]);
    const now = Date.now();
    const openRfis = rfis.filter(r => r.status !== "closed");
    const overdueRfis = openRfis.filter(r => r.dueDate && new Date(r.dueDate).getTime() < now);
    const pendingSubs = subs.filter(s => ["pending", "under_review"].includes(s.status));
    const validFiles = files.filter(f => f.status === "valid");
    const compRate = files.length ? Math.round((validFiles.length / files.length) * 100) : 0;

    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="project-health-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Project Health Report");

    row(doc, "Project Name", project.name);
    row(doc, "Project Code", project.code);
    row(doc, "Status", project.status.toUpperCase());
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica-Bold").fillColor("#111").text("Summary Statistics");
    doc.moveDown(0.3);
    row(doc, "Total RFIs", String(rfis.length));
    row(doc, "Open RFIs", String(openRfis.length));
    row(doc, "Overdue RFIs", String(overdueRfis.length));
    row(doc, "Total Submittals", String(subs.length));
    row(doc, "Pending Submittals", String(pendingSubs.length));
    row(doc, "Total Files", String(files.length));
    row(doc, "Compliant Files", String(validFiles.length));
    row(doc, "Compliance Rate", `${compRate}%`);
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── COMPLIANCE ─────────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/compliance/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const files = await db.select().from(filesTable).where(eq(filesTable.projectId, projectId)).orderBy(desc(filesTable.createdAt));
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="compliance-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Naming Compliance Report");

    const valid = files.filter(f => f.status === "valid");
    const rejected = files.filter(f => f.status === "rejected");
    row(doc, "Total Files", String(files.length));
    row(doc, "Compliant", String(valid.length));
    row(doc, "Non-Compliant", String(rejected.length));
    row(doc, "Compliance Rate", files.length ? `${Math.round(valid.length / files.length * 100)}%` : "—");
    doc.moveDown();
    if (rejected.length) {
      doc.fontSize(10).font("Helvetica-Bold").text("Non-Compliant Files:");
      doc.moveDown(0.3);
      rejected.slice(0, 30).forEach(f => {
        doc.fontSize(8).font("Helvetica").fillColor("#DC2626").text(`✗ ${f.fileName}`, { indent: 10 });
      });
    }
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── RFI AGING ──────────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/rfi-aging/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const rfis = await db.select().from(rfisTable)
      .where(and(eq(rfisTable.projectId, projectId), ne(rfisTable.status, "closed")))
      .orderBy(rfisTable.createdAt);
    const now = Date.now();
    const doc = new PDFDocument({ size: "LETTER", margin: 50, layout: "landscape" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="rfi-aging-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "RFI Aging Report");

    rfis.forEach(rfi => {
      const ageDays = Math.floor((now - new Date(rfi.createdAt).getTime()) / 86400000);
      const overdue = rfi.dueDate && new Date(rfi.dueDate).getTime() < now;
      doc.fontSize(8).font(overdue ? "Helvetica-Bold" : "Helvetica")
        .fillColor(overdue ? "#DC2626" : "#111")
        .text(`${rfi.number} | ${rfi.subject} | ${rfi.status} | Age: ${ageDays}d${overdue ? " OVERDUE" : ""}`, { indent: 5 });
    });
    if (!rfis.length) doc.fontSize(10).fillColor("#666").text("No open RFIs.", { align: "center" });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── SUBMITTAL STATUS ───────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/submittal-status/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const subs = await db.select().from(submittalsTable).where(eq(submittalsTable.projectId, projectId)).orderBy(submittalsTable.number);
    const doc = new PDFDocument({ size: "LETTER", margin: 50, layout: "landscape" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="submittal-status-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Submittal Status Report");

    subs.forEach(s => {
      doc.fontSize(8).font("Helvetica").fillColor("#111")
        .text(`${s.number} | ${s.title} | ${s.status.replace(/_/g, " ")} | Ball in Court: ${s.ballInCourt ?? "—"}`, { indent: 5 });
    });
    if (!subs.length) doc.fontSize(10).fillColor("#666").text("No submittals found.", { align: "center" });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── PERFORMANCE ────────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/performance/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const [rfis, subs, files, members] = await Promise.all([
      db.select().from(rfisTable).where(eq(rfisTable.projectId, projectId)),
      db.select().from(submittalsTable).where(eq(submittalsTable.projectId, projectId)),
      db.select().from(filesTable).where(eq(filesTable.projectId, projectId)),
      db.select({ userId: projectMembersTable.userId }).from(projectMembersTable).where(eq(projectMembersTable.projectId, projectId)),
    ]);
    const now = Date.now();
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="performance-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Project Performance Report");

    row(doc, "Team Members", String(members.length));
    row(doc, "Total RFIs", String(rfis.length));
    row(doc, "Closed RFIs", String(rfis.filter(r => r.status === "closed").length));
    row(doc, "Total Submittals", String(subs.length));
    row(doc, "Approved Submittals", String(subs.filter(s => s.status === "approved").length));
    row(doc, "Total Files", String(files.length));
    row(doc, "Compliance Rate", files.length ? `${Math.round(files.filter(f => f.status === "valid").length / files.length * 100)}%` : "—");
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── DISPUTE REPORT ─────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/dispute/:module/:itemId/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  const module = req.params.module;
  const itemId = Number(req.params.itemId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const activity = await db.select().from(activityLogTable)
      .where(and(eq(activityLogTable.projectId, projectId), eq(activityLogTable.entityId, itemId)))
      .orderBy(activityLogTable.createdAt);

    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="dispute-${module}-${itemId}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, `Dispute Report — ${module.toUpperCase()} #${itemId}`);

    doc.fontSize(10).font("Helvetica-Bold").text("Full Audit Trail:");
    doc.moveDown(0.3);
    activity.forEach(a => {
      doc.fontSize(8).font("Helvetica").fillColor("#111")
        .text(`${new Date(a.createdAt).toLocaleString()} | ${a.userFullName} | ${a.actionType} | ${a.details ?? ""}`, { indent: 5 });
    });
    if (!activity.length) doc.fontSize(9).fillColor("#666").text("No activity recorded for this item.", { indent: 5 });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── AUDIT CERTIFICATE ──────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/audit-certificate/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const files = await db.select().from(filesTable).where(eq(filesTable.projectId, projectId));
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="audit-cert-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Document Audit Certificate");

    row(doc, "Certificate Date", new Date().toLocaleDateString());
    row(doc, "Total Documents", String(files.length));
    row(doc, "Verified Documents", String(files.filter(f => f.fileHash).length));
    doc.moveDown();
    doc.fontSize(9).font("Helvetica").fillColor("#374151")
      .text("This certificate confirms that all listed documents were processed through BIMLog's document control system with immutable activity logging, SHA-256 hash verification, and audit trail preservation.");
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── MEETING MINUTES ────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/meeting-minutes/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const meetings = await db.select().from(meetingMinutesTable)
      .where(eq(meetingMinutesTable.projectId, projectId)).orderBy(desc(meetingMinutesTable.meetingDate));
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="meeting-minutes-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Meeting Minutes Report");

    for (const m of meetings) {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#111").text(`${new Date(m.meetingDate).toLocaleDateString()} — ${m.title}`);
      if (m.location) doc.fontSize(8).font("Helvetica").fillColor("#666").text(`Location: ${m.location}`);
      if (m.notes) doc.fontSize(8).font("Helvetica").fillColor("#374151").text(m.notes, { indent: 10 });
      if (m.aiSummary) doc.fontSize(8).font("Helvetica-Oblique").fillColor("#2563EB").text(`AI Summary: ${m.aiSummary}`, { indent: 10 });
      doc.moveDown(0.5);
    }
    if (!meetings.length) doc.fontSize(10).fillColor("#666").text("No meetings recorded.", { align: "center" });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── CHANGE ORDER LOG ───────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/change-order-log/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const cos = await db.select().from(changeOrdersTable)
      .where(eq(changeOrdersTable.projectId, projectId)).orderBy(changeOrdersTable.number);
    const doc = new PDFDocument({ size: "LETTER", margin: 50, layout: "landscape" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="co-log-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Change Order Log");

    cos.forEach(co => {
      doc.fontSize(8).font("Helvetica").fillColor("#111")
        .text(`${co.number} | ${co.title} | ${co.status.replace(/_/g, " ")} | Impact: ${co.contractValueImpact ?? "—"} | Schedule: ${co.scheduleImpactDays ? co.scheduleImpactDays + "d" : "—"}`, { indent: 5 });
    });
    if (!cos.length) doc.fontSize(10).fillColor("#666").text("No change orders.", { align: "center" });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

// ── TRANSMITTAL LOG ────────────────────────────────────────────────────────────
router.get("/projects/:projectId/reports/transmittal-log/pdf", async (req, res) => {
  const userId = await verifyReportToken(req, res);
  if (!userId) return;
  const projectId = Number(req.params.projectId);
  try {
    const project = await getProject(projectId);
    if (!project) { res.status(404).json({ error: "Project not found" }); return; }
    const txs = await db.select().from(transmittalsTable)
      .where(eq(transmittalsTable.projectId, projectId)).orderBy(transmittalsTable.number);
    const doc = new PDFDocument({ size: "LETTER", margin: 50, layout: "landscape" });
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="transmittal-log-${project.code}.pdf"`);
    doc.pipe(res);
    pdfHeader(doc, project, "Transmittal Log");

    txs.forEach(tx => {
      doc.fontSize(8).font("Helvetica").fillColor("#111")
        .text(`${tx.number} | ${tx.title} | ${tx.status} | ${tx.sentAt ? new Date(tx.sentAt).toLocaleDateString() : "Draft"}`, { indent: 5 });
    });
    if (!txs.length) doc.fontSize(10).fillColor("#666").text("No transmittals.", { align: "center" });
    pdfFooter(doc);
    doc.end();
  } catch (err) {
    res.status(500).json({ error: err instanceof Error ? err.message : "Internal server error" });
  }
});

export default router;
