import {Router,type IRouter} from "express";import {and,count,desc,eq,ilike,inArray,isNull,lt,or,sql} from "drizzle-orm";import {db} from "@workspace/db";import {companiesTable,supportCasesTable,usersTable} from "@workspace/db/schema";import {authMiddleware,isSuperAdminMiddleware} from "../middlewares/auth";import {parseSupportCaseInput,supportCaseFingerprint} from "../lib/commercial-support-case";import {parseSupportCaseStatusChange,supportCaseWorkload} from "../lib/support-case-operations";import {supportResponseDueAt,supportResponseIsOverdue} from "../lib/support-case-accountability";import {canChangeSupportCaseAssignment,parseSupportCaseAssignment} from "../lib/support-case-assignment";import {alias} from "drizzle-orm/pg-core";import {parseSupportCaseListQuery} from "../lib/support-case-query";
const router:IRouter=Router();
const supportAssignee=alias(usersTable,"support_assignee");
const latestMessageAt=sql<Date|null>`(select max(message.created_at) from support_case_messages message where message.support_case_id = ${supportCasesTable.id})`;
const unreadCount=(actorId:number,authorRole:"customer"|"administrator")=>sql<number>`(select count(*)::int from support_case_messages message where message.support_case_id = ${supportCasesTable.id} and message.author_role = ${authorRole} and message.id > coalesce((select reads.last_read_message_id from support_conversation_reads reads where reads.support_case_id = ${supportCasesTable.id} and reads.user_id = ${actorId}),0))`;
router.get("/support/cases",authMiddleware,async(req,res)=>{const actor=req.user!;const items=await db.select({id:supportCasesTable.id,category:supportCasesTable.category,priority:supportCasesTable.priority,subject:supportCasesTable.subject,status:supportCasesTable.status,unreadCount:unreadCount(actor.userId,"administrator"),latestMessageAt,createdAt:supportCasesTable.createdAt,updatedAt:supportCasesTable.updatedAt}).from(supportCasesTable).where(and(eq(supportCasesTable.companyId,actor.companyId),eq(supportCasesTable.requesterUserId,actor.userId))).orderBy(desc(supportCasesTable.createdAt),desc(supportCasesTable.id)).limit(50);res.set("Cache-Control","private, no-store, max-age=0");res.json({items});});
router.post("/support/cases",authMiddleware,async(req,res)=>{let input;try{input=parseSupportCaseInput(req.body);}catch(error){res.status(400).json({code:"SUPPORT_CASE_INVALID",error:error instanceof Error?error.message:"Support request is invalid"});return;}const actor=req.user!,fingerprint=supportCaseFingerprint(input),openedAt=new Date();try{const [created]=await db.insert(supportCasesTable).values({...input,fingerprint,companyId:actor.companyId,requesterUserId:actor.userId,status:"open",responseDueAt:supportResponseDueAt(openedAt,input.priority),createdAt:openedAt,updatedAt:openedAt}).returning({id:supportCasesTable.id,status:supportCasesTable.status,createdAt:supportCasesTable.createdAt,updatedAt:supportCasesTable.updatedAt});res.status(201).json({...created,replayed:false});}catch(error){if((error as {code?:unknown})?.code!=="23505"){res.status(503).json({code:"SUPPORT_CASE_UNAVAILABLE"});return;}const [existing]=await db.select({id:supportCasesTable.id,status:supportCasesTable.status,fingerprint:supportCasesTable.fingerprint,createdAt:supportCasesTable.createdAt,updatedAt:supportCasesTable.updatedAt}).from(supportCasesTable).where(and(eq(supportCasesTable.requesterUserId,actor.userId),eq(supportCasesTable.requestKey,input.requestKey))).limit(1);if(!existing||existing.fingerprint!==fingerprint){res.status(409).json({code:"SUPPORT_CASE_REQUEST_CONFLICT"});return;}res.json({id:existing.id,status:existing.status,createdAt:existing.createdAt,updatedAt:existing.updatedAt,replayed:true});}});
router.get("/admin/support/cases",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{
 let query;try{query=parseSupportCaseListQuery(req.query);}catch(error){res.status(400).json({code:error instanceof Error?error.message:"SUPPORT_CASE_QUERY_INVALID"});return;}
 const actorId=req.user!.userId,active=inArray(supportCasesTable.status,["open","in_progress"]),conditions=[];
 if(query.search){const term=`%${query.search}%`;conditions.push(or(ilike(supportCasesTable.subject,term),ilike(supportCasesTable.description,term),ilike(companiesTable.name,term),ilike(usersTable.fullName,term),ilike(usersTable.email,term))!);}
 if(query.workload==="urgent")conditions.push(and(active,eq(supportCasesTable.priority,"urgent"))!);
 if(query.workload==="waiting")conditions.push(and(active,eq(supportCasesTable.priority,"normal"))!);
 if(query.workload==="resolved")conditions.push(inArray(supportCasesTable.status,["resolved","closed"]));
 if(query.assignment==="mine")conditions.push(eq(supportCasesTable.assignedToUserId,actorId));
 if(query.assignment==="unassigned")conditions.push(isNull(supportCasesTable.assignedToUserId));
 if(query.attention==="unread")conditions.push(sql`${unreadCount(actorId,"customer")} > 0`);
 if(query.overdue)conditions.push(and(active,lt(supportCasesTable.responseDueAt,new Date()))!);
 const where=conditions.length?and(...conditions):undefined;
 const base=()=>db.select({id:supportCasesTable.id,companyId:supportCasesTable.companyId,companyName:companiesTable.name,requesterUserId:supportCasesTable.requesterUserId,requesterName:usersTable.fullName,requesterEmail:usersTable.email,category:supportCasesTable.category,priority:supportCasesTable.priority,subject:supportCasesTable.subject,description:supportCasesTable.description,status:supportCasesTable.status,responseDueAt:supportCasesTable.responseDueAt,assignedToUserId:supportCasesTable.assignedToUserId,assignedToName:supportAssignee.fullName,assignedAt:supportCasesTable.assignedAt,unreadCount:unreadCount(actorId,"customer"),latestMessageAt,createdAt:supportCasesTable.createdAt,updatedAt:supportCasesTable.updatedAt}).from(supportCasesTable).innerJoin(companiesTable,eq(companiesTable.id,supportCasesTable.companyId)).innerJoin(usersTable,eq(usersTable.id,supportCasesTable.requesterUserId)).leftJoin(supportAssignee,eq(supportAssignee.id,supportCasesTable.assignedToUserId));
 const [rows,totalRows]=await Promise.all([base().where(where).orderBy(desc(supportCasesTable.createdAt),desc(supportCasesTable.id)).limit(query.limit).offset(query.offset),db.select({total:count()}).from(supportCasesTable).innerJoin(companiesTable,eq(companiesTable.id,supportCasesTable.companyId)).innerJoin(usersTable,eq(usersTable.id,supportCasesTable.requesterUserId)).where(where)]);
 res.set("Cache-Control","private, no-store, max-age=0");res.json({items:rows.map(row=>({...row,assignedToCurrentUser:row.assignedToUserId===actorId,overdue:supportResponseIsOverdue({status:row.status,responseDueAt:row.responseDueAt}),workload:supportCaseWorkload({status:row.status as "open"|"in_progress"|"resolved"|"closed",priority:row.priority as "normal"|"urgent"})})),limit:query.limit,offset:query.offset,total:totalRows[0]?.total??0});
});
router.patch("/admin/support/cases/:id/status",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<1){res.status(400).json({code:"SUPPORT_CASE_ID_INVALID"});return;}let input;try{input=parseSupportCaseStatusChange(req.body);}catch{res.status(400).json({code:"SUPPORT_CASE_TRANSITION_INVALID"});return;}const now=new Date();const [updated]=await db.update(supportCasesTable).set({status:input.status,updatedAt:now}).where(and(eq(supportCasesTable.id,id),eq(supportCasesTable.status,input.expectedStatus),eq(supportCasesTable.updatedAt,input.expectedUpdatedAt))).returning({id:supportCasesTable.id,status:supportCasesTable.status,updatedAt:supportCasesTable.updatedAt});if(!updated){res.status(409).json({code:"SUPPORT_CASE_STALE_OR_MISSING"});return;}res.set("Cache-Control","private, no-store, max-age=0");res.json(updated);});
router.patch("/admin/support/cases/:id/assignment",authMiddleware,isSuperAdminMiddleware,async(req,res)=>{const id=Number(req.params.id);if(!Number.isSafeInteger(id)||id<1){res.status(400).json({code:"SUPPORT_CASE_ID_INVALID"});return;}let input;try{input=parseSupportCaseAssignment(req.body);}catch{res.status(400).json({code:"SUPPORT_CASE_ASSIGNMENT_INVALID"});return;}const actorId=req.user!.userId,result=await db.transaction(async tx=>{const [current]=await tx.select({status:supportCasesTable.status,assignedToUserId:supportCasesTable.assignedToUserId,updatedAt:supportCasesTable.updatedAt}).from(supportCasesTable).where(eq(supportCasesTable.id,id)).for("update").limit(1);if(!current||current.updatedAt.getTime()!==input.expectedUpdatedAt.getTime())return "stale" as const;if(current.status==="resolved"||current.status==="closed")return "closed" as const;if(!canChangeSupportCaseAssignment(current.assignedToUserId,actorId,input.assigned))return "owned" as const;const now=new Date(),[updated]=await tx.update(supportCasesTable).set({assignedToUserId:input.assigned?actorId:null,assignedAt:input.assigned?now:null,updatedAt:now}).where(and(eq(supportCasesTable.id,id),eq(supportCasesTable.updatedAt,input.expectedUpdatedAt))).returning({id:supportCasesTable.id,assignedToUserId:supportCasesTable.assignedToUserId,assignedAt:supportCasesTable.assignedAt,updatedAt:supportCasesTable.updatedAt});return updated??"stale" as const;});if(result==="stale"){res.status(409).json({code:"SUPPORT_CASE_STALE_OR_MISSING"});return;}if(result==="closed"){res.status(409).json({code:"SUPPORT_CASE_CLOSED"});return;}if(result==="owned"){res.status(409).json({code:"SUPPORT_CASE_ALREADY_ASSIGNED"});return;}res.set("Cache-Control","private, no-store, max-age=0");res.json({...result,assignedToCurrentUser:result.assignedToUserId===actorId});});
export default router;
