import { useCallback, useEffect, useState } from "react";
import { CalendarDays, Download, Plus, Save, Send, Trash2 } from "lucide-react";

const API_BASE=(import.meta.env.VITE_API_URL as string|undefined)??"";
type Assignment={taskId:string;userId:number;plannedHours:number;startDate:string;endDate:string;category:string;reason:string;expectedTaskVersion:number};
type Workspace={canManage:boolean;project:{code:string};members:Array<{id:number;name:string;jobTitle:string;profile:any;crossProjectLoad:Array<{projectCode:string;remainingHours:string}>}>;tasks:Array<{id:string;nameEn:string;nameEs:string;plannedHours:string;progress:number;version:number;workItem:string}>;scenarios:any[];methodology:string};
type Props={projectId:number;token:string|null;lang:string;actorUserId:number};
const stamp=(offset=0)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10)};

export function ResourceSchedulingPanel({projectId,token,lang,actorUserId}:Props){
 const tt=(en:string,es:string)=>lang==="es"?es:en,base=`${API_BASE}/api/v1/projects/${projectId}/commercial/team-performance/resource-planning`;
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[name,setName]=useState(""),[startDate,setStartDate]=useState(stamp()),[endDate,setEndDate]=useState(stamp(28)),[rows,setRows]=useState<Assignment[]>([]),[evaluation,setEvaluation]=useState<any>(null),[reason,setReason]=useState("");
 const request=useCallback(async(path="",init?:RequestInit)=>{const response=await fetch(`${base}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(init?.headers??{})}}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||tt("Resource planning failed.","Falló la planificación de recursos."));return body},[base,token,lang]);
 const load=useCallback(async()=>{try{setData(await request());setError("")}catch(e){setError(e instanceof Error?e.message:String(e))}},[request]);useEffect(()=>{void load()},[load]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function add(){const task=data?.tasks[0],member=data?.members[0];if(task&&member)setRows(v=>[...v,{taskId:task.id,userId:member.id,plannedHours:Math.max(1,Number(task.plannedHours)*(1-task.progress/100)),startDate,endDate,category:task.workItem||"general",reason:tt("Proposed staffing scenario","Escenario propuesto de dotación"),expectedTaskVersion:task.version}])}
 const payload=()=>({name:name||tt("Draft staffing scenario","Escenario borrador"),startDate,endDate,assignments:rows});
 async function evaluate(){await run(async()=>{setEvaluation(await request("/evaluate",{method:"POST",body:JSON.stringify(payload())}));setNotice(tt("What-if evaluated; live assignments were not changed.","Escenario evaluado; no cambió asignaciones activas."))})}
 async function save(){await run(async()=>{const saved=await request("/scenarios",{method:"POST",body:JSON.stringify({...payload(),expectedVersion:0})});setEvaluation(saved.evaluation);setNotice(tt(`Scenario v${saved.version} saved.`,`Escenario v${saved.version} guardado.`));await load()})}
 async function apply(id:string){await run(async()=>{await request(`/scenarios/${id}/apply`,{method:"POST",body:JSON.stringify({eventKey:crypto.randomUUID(),reason})});setNotice(tt("Reviewed scenario applied to Job Operations.","Escenario revisado aplicado a Operaciones."));setReason("");await load()})}
 async function saveProfile(member:any){const existing=member.profile?.content??{timezone:"UTC",workingDays:[1,2,3,4,5],leave:[]};await run(async()=>{await request(`/profiles/${member.id}`,{method:"PUT",body:JSON.stringify({expectedVersion:member.profile?.version??0,profile:{...existing,weeklyCapacityHours:Number((document.getElementById(`cap-${member.id}`) as HTMLInputElement).value),internalHourlyRate:Number((document.getElementById(`int-${member.id}`) as HTMLInputElement).value),billingHourlyRate:Number((document.getElementById(`bill-${member.id}`) as HTMLInputElement).value)}})});setNotice(tt("Availability saved as a new version.","Disponibilidad guardada como nueva versión."));await load()})}
 function exportCsv(){if(!evaluation)return;const lines:unknown[][]=[["member","capacity","existing","scenario","utilization","internal cost","billing value","warnings"],...evaluation.people.map((p:any)=>[data?.members.find(m=>m.id===p.userId)?.name??p.userId,p.capacityHours,p.existingHours,p.scenarioHours,p.utilization,p.internalCost,p.billingValue,p.warnings.join(" | ")])];const a=document.createElement("a"),url=URL.createObjectURL(new Blob([lines.map((row:unknown[])=>row.map((value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`).join(",")).join("\r\n")],{type:"text/csv"}));a.href=url;a.download=`${data?.project.code??"project"}-staffing.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="rs"><style>{`.rs{display:grid;gap:14px}.rs-card{border:1px solid hsl(var(--border));background:hsl(var(--card));border-radius:13px;padding:16px}.rs h2,.rs h3{margin:0}.rs-head,.rs-actions,.rs-inline{display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap}.rs-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:12px}.rs label{display:grid;gap:5px;font-size:11px;font-weight:750}.rs input,.rs select,.rs textarea{border:1px solid hsl(var(--border));background:hsl(var(--background));color:hsl(var(--foreground));border-radius:8px;padding:8px}.rs button{display:inline-flex;align-items:center;gap:6px;border:1px solid hsl(var(--border));border-radius:8px;background:hsl(var(--card));color:hsl(var(--foreground));padding:8px 10px;font-weight:700}.rs button.primary{background:#1d4ed8;color:#fff}.rs button:disabled{opacity:.45}.rs-row{display:grid;grid-template-columns:1.4fr 1.2fr .6fr 1fr 1fr 1fr auto;gap:7px;align-items:end;border-top:1px solid hsl(var(--border));padding-top:10px;margin-top:10px}.rs-load{font-size:11px;color:hsl(var(--muted-foreground))}.rs-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.rs-kpis div{padding:10px;background:hsl(var(--muted));border-radius:9px}.rs-kpis strong{display:block;font-size:18px}.rs-table{width:100%;border-collapse:collapse;font-size:11px}.rs-table th,.rs-table td{padding:8px;border-bottom:1px solid hsl(var(--border));text-align:left}.rs-warning,.rs-error{color:#991b1b}.rs-error,.rs-notice{padding:11px;border-radius:9px;background:#fef2f2}.rs-notice{background:#eff6ff;color:#1e40af}@media(max-width:900px){.rs-grid,.rs-kpis{grid-template-columns:1fr}.rs-row{grid-template-columns:1fr 1fr}}@media print{.rs-actions,.rs-edit,.rs-builder button,.rs-builder textarea{display:none!important}.rs-card{break-inside:avoid}}`}</style>
 <section className="rs-card"><div className="rs-head"><div><h2><CalendarDays size={17}/> {tt("Resource Scheduling & Assignment Execution","Programación de Recursos y Ejecución de Asignaciones")}</h2><p>{tt("Model availability and workload, compare saved scenarios, then apply only after human review.","Modele disponibilidad y carga, compare escenarios guardados y aplique solo tras revisión humana.")}</p></div><div className="rs-actions"><button onClick={exportCsv} disabled={!evaluation}><Download size={14}/>CSV</button></div></div></section>
 {notice&&<div className="rs-notice">{notice}</div>}{error&&<div className="rs-error">{error}</div>}
 <section className="rs-card"><h3>{tt("Availability, leave, and authorized cross-project load","Disponibilidad, ausencias y carga autorizada entre proyectos")}</h3><p>{data?.methodology}</p><div className="rs-grid">{data?.members.map(member=>{const p=member.profile?.content??{weeklyCapacityHours:40,internalHourlyRate:0,billingHourlyRate:0};return <article key={member.id}><strong>{member.name}</strong><div>{member.jobTitle}</div><div className="rs-load">{member.crossProjectLoad.length?member.crossProjectLoad.map(load=><div key={load.projectCode}>{load.projectCode} · {Number(load.remainingHours).toFixed(2)}h</div>):tt("No visible cross-project commitments.","Sin compromisos visibles entre proyectos.")}</div>{member.id===actorUserId&&<div className="rs-edit"><label>{tt("Weekly capacity","Capacidad semanal")}<input id={`cap-${member.id}`} type="number" defaultValue={p.weeklyCapacityHours}/></label><label>{tt("Internal / billing hourly rate","Tarifa interna / facturación")}<span className="rs-inline"><input id={`int-${member.id}`} type="number" defaultValue={p.internalHourlyRate}/><input id={`bill-${member.id}`} type="number" defaultValue={p.billingHourlyRate}/></span></label><button disabled={busy} onClick={()=>void saveProfile(member)}><Save size={13}/>{tt("Save my profile","Guardar mi perfil")}</button></div>}</article>})}</div></section>
 <section className="rs-card rs-builder"><div className="rs-head"><h3>{tt("What-if staffing scenario","Escenario hipotético de dotación")}</h3><button onClick={add}><Plus size={14}/>{tt("Add assignment","Agregar asignación")}</button></div><div className="rs-grid"><label>{tt("Scenario name","Nombre")}<input value={name} onChange={e=>setName(e.target.value)}/></label><label>{tt("Start","Inicio")}<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>{tt("End","Fin")}<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>{rows.map((row,index)=><div className="rs-row" key={index}><label>{tt("Task","Tarea")}<select value={row.taskId} onChange={e=>{const task=data!.tasks.find(t=>t.id===e.target.value)!;setRows(v=>v.map((r,i)=>i===index?{...r,taskId:task.id,expectedTaskVersion:task.version,category:task.workItem}:r))}}>{data?.tasks.map(task=><option key={task.id} value={task.id}>{lang==="es"?task.nameEs:task.nameEn}</option>)}</select></label><label>{tt("Member","Miembro")}<select value={row.userId} onChange={e=>setRows(v=>v.map((r,i)=>i===index?{...r,userId:Number(e.target.value)}:r))}>{data?.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>{tt("Hours","Horas")}<input type="number" value={row.plannedHours} onChange={e=>setRows(v=>v.map((r,i)=>i===index?{...r,plannedHours:Number(e.target.value)}:r))}/></label><label>{tt("Start","Inicio")}<input type="date" value={row.startDate} onChange={e=>setRows(v=>v.map((r,i)=>i===index?{...r,startDate:e.target.value}:r))}/></label><label>{tt("End","Fin")}<input type="date" value={row.endDate} onChange={e=>setRows(v=>v.map((r,i)=>i===index?{...r,endDate:e.target.value}:r))}/></label><label>{tt("Category","Categoría")}<input value={row.category} onChange={e=>setRows(v=>v.map((r,i)=>i===index?{...r,category:e.target.value}:r))}/></label><button onClick={()=>setRows(v=>v.filter((_,i)=>i!==index))}><Trash2 size={14}/></button></div>)}<div className="rs-actions"><button disabled={busy||!rows.length} onClick={()=>void evaluate()}>{tt("Evaluate what-if","Evaluar")}</button><button className="primary" disabled={busy||!data?.canManage||!rows.length||name.trim().length<3} onClick={()=>void save()}><Save size={14}/>{tt("Save immutable version","Guardar versión inmutable")}</button></div></section>
 {evaluation&&<section className="rs-card"><h3>{tt("Scenario evidence and forecast","Evidencia y pronóstico")}</h3><div className="rs-kpis"><div><small>{tt("Scenario hours","Horas")}</small><strong>{evaluation.totals.scenarioHours}</strong></div><div><small>{tt("Internal cost","Costo interno")}</small><strong>{evaluation.totals.internalCost}</strong></div><div><small>{tt("Billing value","Valor facturable")}</small><strong>{evaluation.totals.billingValue}</strong></div></div><table className="rs-table"><thead><tr><th>{tt("Member","Miembro")}</th><th>{tt("Capacity","Capacidad")}</th><th>{tt("Existing","Existente")}</th><th>{tt("Scenario","Escenario")}</th><th>{tt("Utilization","Utilización")}</th><th>{tt("Warnings","Alertas")}</th></tr></thead><tbody>{evaluation.people.map((p:any)=><tr key={p.userId}><td>{data?.members.find(m=>m.id===p.userId)?.name}</td><td>{p.capacityHours}</td><td>{p.existingHours}</td><td>{p.scenarioHours}</td><td>{p.utilization==null?"—":`${(p.utilization*100).toFixed(1)}%`}</td><td className={p.warnings.length?"rs-warning":""}>{p.warnings.join(" · ")||tt("None","Ninguna")}</td></tr>)}</tbody></table></section>}
 {!!data?.scenarios.length&&<section className="rs-card"><h3>{tt("Saved scenarios","Escenarios guardados")}</h3>{data.scenarios.map(s=><article className="rs-head" key={s.id}><div><strong>{s.content.name} · v{s.version}</strong><div>{s.content.startDate} → {s.content.endDate}</div></div>{s.applied?<b>{tt("Applied","Aplicado")}</b>:data.canManage&&<div className="rs-inline"><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder={tt("Application reason","Motivo de aplicación")}/><button className="primary" disabled={busy||reason.trim().length<10} onClick={()=>void apply(s.id)}><Send size={14}/>{tt("Review & apply","Revisar y aplicar")}</button></div>}</article>)}</section>}
 </div>
}
