<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>BIMLogLensNext</AssemblyName>
    <RootNamespace>BIMLogLensNext</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Version>1.5.8.3</Version>
    <AssemblyVersion>1.5.8.3</AssemblyVersion>
    <FileVersion>1.5.8.3</FileVersion>
    <InformationalVersion>v1.05.N08-P03</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="native\**\*.cs" />
    <None Remove="tests\**\*" />
    <None Remove="native\**\*" />
  </ItemGroup>
</Project>
