export type CommercialWorkspaceActionDto={id:"complete_billing_identity"|"review_plans"|"contact_support";status:"available"|"complete"|"blocked";href:"/settings/company-profile"|"/pricing"|"/contact";blockers:string[]};
export type CommercialWorkspaceResponsibilitiesDto={customer:string[];bimlog:string[];customerReadiness:"action_required"|"ready";platformReadiness:"action_required"|"ready"};
export type CommercialPlatformServiceDto="subscription_catalog"|"payment_provider"|"payment_webhook"|"billing_portal"|"support_channel";
export type CommercialPlatformCheckDto={service:CommercialPlatformServiceDto;status:"ready"|"not_configured";code:string};
export type CommercialCatalogCoverageDto={slot:"professional.monthly"|"professional.annual"|"team.monthly"|"team.annual"|"business.monthly"|"business.annual";status:"ready"|"missing"|"invalid"|"duplicate_price"};
export type CommercialPreparedSubscriptionDto={subscriptionId:string;plan:"professional"|"team"|"business";billingCycle:"monthly"|"annual";seatQuantity:number};
export type CommercialCheckoutSummaryDto={checkoutId:string;orderId:string;status:"creating"|"open"|"completed"|"expired"|"canceled"|"failed";expiresAt:string;completedAt:string|null;updatedAt:string};
export type CommercialSubscriptionLifecycleDto={status:"pending"|"trialing"|"active"|"past_due"|"suspended"|"canceling"|"canceled"};
export type CommercialPortalEligibilityDto={ready:boolean;purpose:"manage"|"recover_payment"|"review_cancellation"|null;blockers:("billing_authority"|"subscription_state"|"provider_customer"|"portal_service")[]};
export type CommercialWorkspaceDto={companyId:number;companyName:string;memberCount:number;commercialAccess:boolean;preparedSubscription:CommercialPreparedSubscriptionDto|null;providerCustomerBound:boolean;latestCheckout:CommercialCheckoutSummaryDto|null;subscriptionLifecycle:CommercialSubscriptionLifecycleDto|null;portalEligibility:CommercialPortalEligibilityDto;billingAuthority:{canManageBilling:boolean;role:"billing_admin"|"viewer"};launchAuthorizationStatus:"current"|"missing"|"source_mismatch"|"expired"|"not_verified";launchAuthorizationReady:boolean;subscriptionStatus:"not_configured"|"pending"|"trialing"|"active"|"past_due"|"suspended"|"canceling";billingIdentityStatus:"incomplete"|"complete";paymentProviderStatus:"not_configured"|"ready";webhookStatus:"not_configured"|"ready";billingPortalStatus:"not_configured"|"ready";supportStatus:"not_configured"|"ready";providerMode:"test"|"live"|"unavailable";salesLaunchStatus:"ready"|"test_only"|"blocked";salesLaunchBlockers:("catalog"|"provider"|"live_mode"|"webhook"|"portal"|"support")[];readiness:"action_required"|"ready";blockers:string[];responsibilities:CommercialWorkspaceResponsibilitiesDto;platformChecks:CommercialPlatformCheckDto[];catalogCoverage:CommercialCatalogCoverageDto[];actions:CommercialWorkspaceActionDto[]};
const oneOf=<T extends string>(value:unknown,allowed:readonly T[],field:string):T=>{if(typeof value!=="string"||!allowed.includes(value as T))throw new Error(`Invalid commercial workspace ${field}`);return value as T;};
export function parseCommercialWorkspace(value:unknown):CommercialWorkspaceDto{
  if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial workspace response");
  const row=value as Record<string,unknown>;
  if(!Number.isSafeInteger(row.companyId)||Number(row.companyId)<1||typeof row.companyName!=="string"||!row.companyName.trim()||!Number.isSafeInteger(row.memberCount)||Number(row.memberCount)<0||typeof row.commercialAccess!=="boolean"||!Array.isArray(row.blockers)||row.blockers.some(item=>typeof item!=="string")||!Array.isArray(row.actions))throw new Error("Invalid commercial workspace identity");
  if(!row.billingAuthority||typeof row.billingAuthority!=="object"||Array.isArray(row.billingAuthority))throw new Error("Invalid commercial billing authority");
  const billingSource=row.billingAuthority as Record<string,unknown>,billingAuthority={canManageBilling:billingSource.canManageBilling===true,role:oneOf(billingSource.role,["billing_admin","viewer"],"billing role")};if(billingAuthority.canManageBilling!==(billingAuthority.role==="billing_admin"))throw new Error("Invalid commercial billing authority consistency");
  const launchAuthorizationStatus=oneOf(row.launchAuthorizationStatus,["current","missing","source_mismatch","expired","not_verified"],"launch authorization status"),launchAuthorizationReady=row.launchAuthorizationReady===true;
  if(launchAuthorizationReady!==(launchAuthorizationStatus==="current"))throw new Error("Invalid commercial launch authorization consistency");
  const actionHrefs={complete_billing_identity:"/settings/company-profile",review_plans:"/pricing",contact_support:"/contact"} as const;
  const actions=row.actions.map(value=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial workspace action");const action=value as Record<string,unknown>,id=oneOf(action.id,Object.keys(actionHrefs) as (keyof typeof actionHrefs)[],"action id"),href=oneOf(action.href,Object.values(actionHrefs),"action href");if(href!==actionHrefs[id]||!Array.isArray(action.blockers)||action.blockers.some(item=>typeof item!=="string"))throw new Error("Invalid commercial workspace action authority");return {id,status:oneOf(action.status,["available","complete","blocked"],"action status"),href,blockers:[...action.blockers] as string[]};});
  if(!row.responsibilities||typeof row.responsibilities!=="object"||Array.isArray(row.responsibilities))throw new Error("Invalid commercial workspace responsibilities");
  const source=row.responsibilities as Record<string,unknown>;
  if(!Array.isArray(source.customer)||!Array.isArray(source.bimlog)||[...source.customer,...source.bimlog].some(item=>typeof item!=="string"))throw new Error("Invalid commercial workspace responsibility lists");
  const customer=[...source.customer] as string[],bimlog=[...source.bimlog] as string[],partition=[...new Set([...customer,...bimlog])].sort(),blockers=[...row.blockers] as string[];
  if(customer.some(code=>code!=="BILLING_IDENTITY_INCOMPLETE")||bimlog.includes("BILLING_IDENTITY_INCOMPLETE")||JSON.stringify(partition)!==JSON.stringify([...new Set(blockers)].sort()))throw new Error("Invalid commercial workspace responsibility authority");
  const responsibilities={customer,bimlog,customerReadiness:oneOf(source.customerReadiness,["action_required","ready"],"customer readiness"),platformReadiness:oneOf(source.platformReadiness,["action_required","ready"],"platform readiness")};
  if((customer.length===0)!==(responsibilities.customerReadiness==="ready")||(bimlog.length===0)!==(responsibilities.platformReadiness==="ready"))throw new Error("Invalid commercial workspace responsibility readiness");
  const services=["subscription_catalog","payment_provider","payment_webhook","billing_portal","support_channel"] as const;
  if(!Array.isArray(row.platformChecks)||row.platformChecks.length!==services.length)throw new Error("Invalid commercial platform checks");
  const platformChecks=row.platformChecks.map(value=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial platform check");const item=value as Record<string,unknown>,service=oneOf(item.service,services,"platform service"),status=oneOf(item.status,["ready","not_configured"],"platform status");if(typeof item.code!=="string"||!/^[a-z_]{3,40}$/.test(item.code))throw new Error("Invalid commercial platform code");return {service,status,code:item.code};});
  if(new Set(platformChecks.map(item=>item.service)).size!==services.length)throw new Error("Invalid commercial platform partition");
  const subscriptionStatus=oneOf(row.subscriptionStatus,["not_configured","pending","trialing","active","past_due","suspended","canceling"],"subscription status"),billingIdentityStatus=oneOf(row.billingIdentityStatus,["incomplete","complete"],"billing identity status"),paymentProviderStatus=oneOf(row.paymentProviderStatus,["not_configured","ready"],"provider status"),webhookStatus=oneOf(row.webhookStatus,["not_configured","ready"],"webhook status"),billingPortalStatus=oneOf(row.billingPortalStatus,["not_configured","ready"],"portal status"),supportStatus=oneOf(row.supportStatus,["not_configured","ready"],"support status"),readiness=oneOf(row.readiness,["action_required","ready"],"readiness");
  let preparedSubscription:CommercialPreparedSubscriptionDto|null=null;
  if(row.preparedSubscription!==null){if(!row.preparedSubscription||typeof row.preparedSubscription!=="object"||Array.isArray(row.preparedSubscription))throw new Error("Invalid prepared subscription");const prepared=row.preparedSubscription as Record<string,unknown>;if(typeof prepared.subscriptionId!=="string"||!prepared.subscriptionId.trim()||!Number.isSafeInteger(prepared.seatQuantity)||Number(prepared.seatQuantity)<1)throw new Error("Invalid prepared subscription identity");preparedSubscription={subscriptionId:prepared.subscriptionId.trim(),plan:oneOf(prepared.plan,["professional","team","business"],"prepared plan"),billingCycle:oneOf(prepared.billingCycle,["monthly","annual"],"prepared billing cycle"),seatQuantity:Number(prepared.seatQuantity)};}
  if((subscriptionStatus==="not_configured")!==(preparedSubscription===null))throw new Error("Invalid prepared subscription consistency");
  let subscriptionLifecycle:CommercialSubscriptionLifecycleDto|null=null;if(row.subscriptionLifecycle!=null){if(typeof row.subscriptionLifecycle!=="object"||Array.isArray(row.subscriptionLifecycle))throw new Error("Invalid subscription lifecycle");subscriptionLifecycle={status:oneOf((row.subscriptionLifecycle as Record<string,unknown>).status,["pending","trialing","active","past_due","suspended","canceling","canceled"],"lifecycle status")};}
  if(!row.portalEligibility||typeof row.portalEligibility!=="object"||Array.isArray(row.portalEligibility))throw new Error("Invalid billing portal eligibility");
  const portalSource=row.portalEligibility as Record<string,unknown>,portalPurpose=portalSource.purpose===null?null:oneOf(portalSource.purpose,["manage","recover_payment","review_cancellation"],"portal purpose");
  if(typeof portalSource.ready!=="boolean"||!Array.isArray(portalSource.blockers))throw new Error("Invalid billing portal eligibility");
  const portalBlockers:CommercialPortalEligibilityDto["blockers"]=portalSource.blockers.map(value=>oneOf(value,["billing_authority","subscription_state","provider_customer","portal_service"] as const,"portal blocker"));
  const portalEligibility={ready:portalSource.ready,purpose:portalPurpose,blockers:portalBlockers};
  if(new Set(portalBlockers).size!==portalBlockers.length||portalEligibility.ready!==(portalBlockers.length===0&&portalPurpose!==null))throw new Error("Invalid billing portal eligibility consistency");
  let latestCheckout:CommercialCheckoutSummaryDto|null=null;
  if(row.latestCheckout!=null){if(typeof row.latestCheckout!=="object"||Array.isArray(row.latestCheckout))throw new Error("Invalid checkout summary");const checkout=row.latestCheckout as Record<string,unknown>;const checkoutId=typeof checkout.checkoutId==="string"?checkout.checkoutId.trim():"",orderId=typeof checkout.orderId==="string"?checkout.orderId.trim():"",expiresAt=typeof checkout.expiresAt==="string"?checkout.expiresAt:"",updatedAt=typeof checkout.updatedAt==="string"?checkout.updatedAt:"",completedAt=checkout.completedAt===null?null:typeof checkout.completedAt==="string"?checkout.completedAt:"";if(!checkoutId||!orderId||!Number.isFinite(Date.parse(expiresAt))||!Number.isFinite(Date.parse(updatedAt))||(completedAt!==null&&!Number.isFinite(Date.parse(completedAt))))throw new Error("Invalid checkout summary");const status=oneOf(checkout.status,["creating","open","completed","expired","canceled","failed"],"checkout status");if((status==="completed")!==(completedAt!==null))throw new Error("Invalid checkout completion evidence");latestCheckout={checkoutId,orderId,status,expiresAt,completedAt,updatedAt};}
  const catalogReady=platformChecks.find(item=>item.service==="subscription_catalog")?.status==="ready";
  const statuses=[catalogReady,paymentProviderStatus==="ready",webhookStatus==="ready",billingPortalStatus==="ready",supportStatus==="ready"];
  if(platformChecks.some((item,index)=>(item.status==="ready")!==statuses[index]))throw new Error("Invalid commercial platform consistency");
  const slots=["professional.monthly","professional.annual","team.monthly","team.annual","business.monthly","business.annual"] as const;
  if(!Array.isArray(row.catalogCoverage)||row.catalogCoverage.length!==slots.length)throw new Error("Invalid commercial catalog coverage");
  const catalogCoverage=row.catalogCoverage.map(value=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial catalog item");const item=value as Record<string,unknown>;return {slot:oneOf(item.slot,slots,"catalog slot"),status:oneOf(item.status,["ready","missing","invalid","duplicate_price"],"catalog status")};});
  if(new Set(catalogCoverage.map(item=>item.slot)).size!==slots.length||catalogReady!==catalogCoverage.every(item=>item.status==="ready"))throw new Error("Invalid commercial catalog consistency");
  const providerMode=oneOf(row.providerMode,["test","live","unavailable"],"provider mode"),salesLaunchStatus=oneOf(row.salesLaunchStatus,["ready","test_only","blocked"],"sales launch status");
  const launchBlockerValues=["catalog","provider","live_mode","webhook","portal","support"] as const;
  if(!Array.isArray(row.salesLaunchBlockers))throw new Error("Invalid commercial sales launch blockers");
  const salesLaunchBlockers=row.salesLaunchBlockers.map(value=>oneOf(value,launchBlockerValues,"sales launch blocker"));
  const expectedSalesStatus=salesLaunchBlockers.length===0?"ready":providerMode==="test"&&salesLaunchBlockers.every(blocker=>blocker==="live_mode")?"test_only":"blocked";
  if(new Set(salesLaunchBlockers).size!==salesLaunchBlockers.length||salesLaunchStatus!==expectedSalesStatus)throw new Error("Invalid commercial sales launch consistency");
  if(typeof row.providerCustomerBound!=="boolean")throw new Error("Invalid commercial provider customer binding");
  return {companyId:Number(row.companyId),companyName:row.companyName.trim(),memberCount:Number(row.memberCount),commercialAccess:row.commercialAccess,preparedSubscription,providerCustomerBound:row.providerCustomerBound,latestCheckout,subscriptionLifecycle,portalEligibility,billingAuthority,launchAuthorizationStatus,launchAuthorizationReady,subscriptionStatus,billingIdentityStatus,paymentProviderStatus,webhookStatus,billingPortalStatus,supportStatus,providerMode,salesLaunchStatus,salesLaunchBlockers,readiness,blockers,responsibilities,platformChecks,catalogCoverage,actions};
}

export type CommercialHostedDestination={url:string};
export const commercialHostedFailureCodes=["BILLING_AUTHORITY_REQUIRED","CHECKOUT_REQUEST_INVALID","CHECKOUT_AUTHORITY_CONFLICT","CHECKOUT_PLATFORM_NOT_READY","CHECKOUT_LIVE_VERIFICATION_REQUIRED","CHECKOUT_UNAVAILABLE","BILLING_PORTAL_UNAVAILABLE"] as const;
export type CommercialHostedFailureCode=typeof commercialHostedFailureCodes[number];
export class CommercialHostedDestinationError extends Error{
  readonly code:CommercialHostedFailureCode;readonly blockers:readonly string[];
  constructor(code:CommercialHostedFailureCode,blockers:readonly string[]=[]){super(code);this.name="CommercialHostedDestinationError";this.code=code;this.blockers=Object.freeze([...blockers]);}
}
export async function requestCommercialHostedDestination(input:{token:string;action:"checkout"|"billing-portal";plan?:"professional"|"team"|"business";cycle?:"monthly"|"annual";requestKey?:string;fetchImpl?:typeof fetch}):Promise<CommercialHostedDestination>{
  const fetchImpl=input.fetchImpl??fetch,base=(import.meta.env?.BASE_URL??"/").replace(/\/$/,"");
  const body=input.action==="checkout"?{plan:input.plan,cycle:input.cycle,requestKey:input.requestKey}:{};
  const response=await fetchImpl(`${base}/api/v1/commercial/${input.action}`,{method:"POST",headers:{Authorization:`Bearer ${input.token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});
  const payload=await response.json().catch(()=>({})) as Record<string,unknown>;
  if(!response.ok){const code=typeof payload.code==="string"&&commercialHostedFailureCodes.includes(payload.code as CommercialHostedFailureCode)?payload.code as CommercialHostedFailureCode:input.action==="checkout"?"CHECKOUT_UNAVAILABLE":"BILLING_PORTAL_UNAVAILABLE";const blockers=Array.isArray(payload.blockers)?payload.blockers.filter((value):value is string=>typeof value==="string"&&/^[a-z_]{3,50}$/.test(value)).slice(0,6):[];throw new CommercialHostedDestinationError(code,blockers);}
  if(typeof payload.url!=="string")throw new Error("Billing service returned an invalid destination.");
  const url=new URL(payload.url);const expected=input.action==="checkout"?"checkout.stripe.com":"billing.stripe.com";
  if(url.protocol!=="https:"||url.hostname!==expected)throw new Error("Billing service returned an untrusted destination.");
  return {url:url.toString()};
}

export async function requestCommercialSubscriptionSetup(input:{token:string;plan:"professional"|"team"|"business";cycle:"monthly"|"annual";requestKey:string;fetchImpl?:typeof fetch}){
  const response=await (input.fetchImpl??fetch)(`${import.meta.env.BASE_URL.replace(/\/$/,"")}/api/v1/commercial/subscription-setup`,{method:"POST",headers:{Authorization:`Bearer ${input.token}`,"Content-Type":"application/json"},body:JSON.stringify({plan:input.plan,cycle:input.cycle,requestKey:input.requestKey})});
  const payload=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(typeof payload.error==="string"?payload.error:"Subscription setup is unavailable.");
  if(typeof payload.subscriptionId!=="string"||typeof payload.providerBindingId!=="string"||payload.status!=="pending"||typeof payload.replayed!=="boolean"||!Number.isSafeInteger(payload.seatQuantity)||Number(payload.seatQuantity)<1)throw new Error("Subscription setup returned an invalid receipt.");
  return {subscriptionId:payload.subscriptionId,providerBindingId:payload.providerBindingId,status:"pending" as const,plan:oneOf(payload.plan,["professional","team","business"],"setup plan"),billingCycle:oneOf(payload.billingCycle,["monthly","annual"],"setup billing cycle"),seatQuantity:Number(payload.seatQuantity),replayed:payload.replayed};
}
