import assert from "node:assert/strict";
import {parseCommercialCheckoutReturn,parseCommercialPortalReturn} from "./commercial-checkout-return";
assert.equal(parseCommercialCheckoutReturn("?checkout=success&session_id=cs_test_redacted"),"success");
assert.equal(parseCommercialCheckoutReturn("?checkout=cancelled"),"cancelled");
assert.equal(parseCommercialCheckoutReturn("?checkout=complete"),null);
assert.equal(parseCommercialCheckoutReturn("?checkout=https%3A%2F%2Fevil.example"),null);
assert.equal(parseCommercialPortalReturn("?billing=returned"),true);
assert.equal(parseCommercialPortalReturn("?billing=success"),false);
assert.equal(parseCommercialPortalReturn("?billing=https%3A%2F%2Fevil.example"),false);
console.log("B075 bounded commercial checkout return feedback: PASS");
