export type CommercialLaunchStepDto={id:"catalog"|"provider"|"live_mode"|"webhook"|"portal"|"support";status:"ready"|"action_required";owner:"bimlog_platform";title:string;configurationKeys:string[]};
export type CommercialLaunchDto={status:"ready"|"test_only"|"blocked";providerMode:"test"|"live"|"unavailable";ready:boolean;steps:CommercialLaunchStepDto[];requiredActionCount:number;checkedAt:string};
export type CommercialVerificationEvidenceDto={schemaVersion:"bimlog-commercial-verification-v1";sourceCommit:string;status:"configuration_blocked"|"verified"|"failed";verified:boolean;checkedAt:string;validUntil:string;checkCount:number;failedCheckIds:string[];evidenceSha256:string};
export type CommercialLiveVerificationDto={status:"configuration_blocked"|"verified"|"failed";verified:boolean;checks:{id:string;status:"verified"|"failed";code:string}[];checkedAt:string;evidence:CommercialVerificationEvidenceDto|null};
export type CommercialEvidenceDecision={status:"current"|"missing"|"source_mismatch"|"expired"|"not_verified";ready:boolean};
const ids=["catalog","provider","live_mode","webhook","portal","support"] as const;
const allowedKeys=new Set(["BIMLOG_STRIPE_PRICE_IDS","BIMLOG_COMMERCIAL_MODE","STRIPE_SECRET_KEY","BIMLOG_APP_ORIGIN","STRIPE_WEBHOOK_SECRET","STRIPE_PORTAL_CONFIGURATION_ID","SENDGRID_API_KEY","BIMLOG_SUPPORT_FROM_EMAIL","BIMLOG_SUPPORT_INBOX_EMAIL"]);
export function parseCommercialLaunch(value:unknown):CommercialLaunchDto{
  if(!value||typeof value!=="object")throw new Error("Commercial launch status is invalid.");
  const item=value as Record<string,unknown>,steps=item.steps;
  if(!["ready","test_only","blocked"].includes(String(item.status))||!["test","live","unavailable"].includes(String(item.providerMode))||typeof item.ready!=="boolean"||!Array.isArray(steps)||steps.length!==ids.length||!Number.isInteger(item.requiredActionCount)||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt)))throw new Error("Commercial launch status is invalid.");
  const parsed=steps.map((raw,index)=>{if(!raw||typeof raw!=="object")throw new Error("Commercial launch step is invalid.");const step=raw as Record<string,unknown>;if(step.id!==ids[index]||!["ready","action_required"].includes(String(step.status))||step.owner!=="bimlog_platform"||typeof step.title!=="string"||!step.title.trim()||!Array.isArray(step.configurationKeys)||step.configurationKeys.some(key=>typeof key!=="string"||!allowedKeys.has(key)))throw new Error("Commercial launch step is invalid.");return step as unknown as CommercialLaunchStepDto;});
  const required=parsed.filter(step=>step.status==="action_required").length;
  if(required!==item.requiredActionCount||item.ready!==(item.status==="ready")||(item.status==="ready"&&required!==0))throw new Error("Commercial launch status is contradictory.");
  return {...item,steps:parsed,requiredActionCount:required} as CommercialLaunchDto;
}
export function parseCommercialLiveVerification(value:unknown):CommercialLiveVerificationDto{if(!value||typeof value!=="object")throw new Error("Live verification result is invalid.");const item=value as Record<string,unknown>;if(!["configuration_blocked","verified","failed"].includes(String(item.status))||typeof item.verified!=="boolean"||!Array.isArray(item.checks)||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt)))throw new Error("Live verification result is invalid.");const checks=item.checks.map(raw=>{if(!raw||typeof raw!=="object")throw new Error("Live verification check is invalid.");const check=raw as Record<string,unknown>;if(typeof check.id!=="string"||!check.id||!["verified","failed"].includes(String(check.status))||typeof check.code!=="string"||!check.code)throw new Error("Live verification check is invalid.");return check as {id:string;status:"verified"|"failed";code:string};});const rawEvidence=item.evidence;let evidence:CommercialVerificationEvidenceDto|null=null;if(rawEvidence!==null){if(!rawEvidence||typeof rawEvidence!=="object")throw new Error("Live verification evidence is invalid.");const e=rawEvidence as Record<string,unknown>;if(e.schemaVersion!=="bimlog-commercial-verification-v1"||typeof e.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(e.sourceCommit)||e.status!==item.status||e.verified!==item.verified||e.checkedAt!==item.checkedAt||typeof e.validUntil!=="string"||!Number.isFinite(Date.parse(e.validUntil))||!Number.isInteger(e.checkCount)||e.checkCount!==checks.length||!Array.isArray(e.failedCheckIds)||e.failedCheckIds.some(id=>typeof id!=="string"||!id)||typeof e.evidenceSha256!=="string"||!/^[0-9a-f]{64}$/.test(e.evidenceSha256))throw new Error("Live verification evidence is invalid.");evidence=e as unknown as CommercialVerificationEvidenceDto;}if(item.verified!==(item.status==="verified")||(item.status==="verified"&&checks.some(check=>check.status!=="verified"))||(item.status==="configuration_blocked"&&checks.length))throw new Error("Live verification result is contradictory.");return {...item,checks,evidence} as CommercialLiveVerificationDto;}
export function evaluateCommercialVerificationEvidence(live:CommercialLiveVerificationDto,expectedSourceCommit:string,now=new Date()):CommercialEvidenceDecision{
  if(!/^[0-9a-f]{40}$/.test(expectedSourceCommit))throw new Error("Expected source commit is invalid.");
  if(!live.evidence)return {status:"missing",ready:false};
  if(live.evidence.sourceCommit!==expectedSourceCommit)return {status:"source_mismatch",ready:false};
  if(!live.verified||!live.evidence.verified)return {status:"not_verified",ready:false};
  const checkedAt=Date.parse(live.evidence.checkedAt),validUntil=Date.parse(live.evidence.validUntil),at=now.getTime();
  if(!Number.isFinite(at)||checkedAt>at||validUntil<=at||validUntil<=checkedAt)return {status:"expired",ready:false};
  return {status:"current",ready:true};
}
