export type BillingCycle = "monthly" | "annual";
export type CommercialJourney = "self_service" | "sales_assisted";
export type CommercialOffer = { id: "free" | "professional" | "team" | "business" | "enterprise"; name: string; audience: string; monthlyUsd: number | null; annualUsd: number | null; projectLimit: number | null; memberLimit: number | null; journey: CommercialJourney; availability: string; included: readonly string[] };
export const COMMERCIAL_OFFERS: readonly CommercialOffer[] = [
  { id:"free",name:"Free",audience:"One team evaluating BIMLog on one active project",monthlyUsd:0,annualUsd:0,projectLimit:1,memberLimit:5,journey:"self_service",availability:"Account creation is available without a credit card.",included:["Core project coordination","RFI and Submittal registers","Naming Convention Builder","Bilingual English and Spanish"] },
  { id:"professional",name:"Professional",audience:"Independent coordinators and small coordination firms",monthlyUsd:149,annualUsd:1490,projectLimit:3,memberLimit:25,journey:"sales_assisted",availability:"Contact BIMLog to confirm entitlement and onboarding.",included:["Free capabilities","Document integrity and audit records","Configured AI assistance","Governed exports and reporting"] },
  { id:"team",name:"Team",audience:"Teams coordinating several active projects",monthlyUsd:249,annualUsd:2490,projectLimit:5,memberLimit:null,journey:"sales_assisted",availability:"Contact BIMLog to confirm entitlement and onboarding.",included:["Professional capabilities","Drawing and change registers","Daily Reports","Team coordination workflows"] },
  { id:"business",name:"Business",audience:"BIM management firms and general contractors",monthlyUsd:399,annualUsd:3990,projectLimit:10,memberLimit:null,journey:"sales_assisted",availability:"Contact BIMLog for a scoped proposal and connector review.",included:["Team capabilities","Transmittals and Meeting Minutes","Coordination reporting","Approved connectors only when configured and validated"] },
  { id:"enterprise",name:"Enterprise",audience:"Organizations requiring portfolio scale or contracted configuration",monthlyUsd:null,annualUsd:null,projectLimit:null,memberLimit:null,journey:"sales_assisted",availability:"Pricing, service levels, retention, integrations and onboarding are defined in the customer agreement.",included:["Business capabilities","Portfolio and branding options","Supported authenticated API workflows","Windows desktop app available as a separate installation when configured"] },
] as const;
export const FOUNDING_OFFER={availability:"Application and eligibility review required",terms:"Any designation, price lock, duration or service commitment is valid only when stated in the signed customer agreement."} as const;
export function offerPrice(offer:CommercialOffer,cycle:BillingCycle){const amount=cycle==="annual"?offer.annualUsd:offer.monthlyUsd;if(amount==null)return "Custom proposal";if(amount===0)return "$0";return `$${amount.toLocaleString("en-US")} / ${cycle==="annual"?"year":"month"}`;}
export function commercialDestination(offer:CommercialOffer,cycle:BillingCycle,useCase=""){const query=new URLSearchParams({plan:offer.id,billing:cycle});if(useCase.trim())query.set("useCase",useCase.trim().slice(0,120));return `${offer.journey==="self_service"?"/register":"/contact"}?${query}`;}
export function foundingDestination(cycle:BillingCycle,useCase=""){const query=new URLSearchParams({plan:"founding",billing:cycle});if(useCase.trim())query.set("useCase",useCase.trim().slice(0,120));return `/contact?${query}`;}
export function journeyAction(offer:CommercialOffer){return offer.journey==="self_service"?{label:"Create free account",detail:"Create your company account now; no sales conversation or payment method is required."}:{label:"Request plan consultation",detail:"Send your team and use-case context. BIMLog will confirm entitlement, onboarding and any contracted terms before access changes."};}
