export type CommercialLaunchStepDto={id:"catalog"|"provider"|"live_mode"|"webhook"|"portal"|"support";status:"ready"|"action_required";owner:"bimlog_platform";title:string;configurationKeys:string[]};
export type CommercialLaunchDto={status:"ready"|"test_only"|"blocked";providerMode:"test"|"live"|"unavailable";ready:boolean;steps:CommercialLaunchStepDto[];requiredActionCount:number;checkedAt:string};
export type CommercialVerificationEvidenceDto={schemaVersion:"bimlog-commercial-verification-v1";sourceCommit:string;status:"configuration_blocked"|"verified"|"failed";verified:boolean;checkedAt:string;validUntil:string;checkCount:number;failedCheckIds:string[];evidenceSha256:string};
export type CommercialLiveVerificationDto={status:"configuration_blocked"|"verified"|"failed";verified:boolean;checks:{id:string;status:"verified"|"failed";code:string}[];checkedAt:string;evidence:CommercialVerificationEvidenceDto|null};
export type CommercialEvidenceDecision={status:"current"|"missing"|"source_mismatch"|"expired"|"not_verified";ready:boolean};
export type CommercialHealthIdentityDto={status:"ok";release:string;sourceCommit:string;assetManifestSha256:string;packageId:string;databaseMigrationLevel:string;identityFingerprint:string;identityBound:true};
export type CommercialVerificationHistoryItem={id:string;actorUserId:number;sourceCommit:string;status:"configuration_blocked"|"verified"|"failed";verified:boolean;checkedAt:string;validUntil:string;checkCount:number;failedCheckIds:string[];checks:{id:string;status:"verified"|"failed";code:string}[];evidenceSha256:string;recordedAt:string};
export type CommercialLaunchAuthorizationDto={status:"current"|"missing"|"source_mismatch"|"expired"|"not_verified";ready:boolean;sourceCommit:string;receipt:CommercialVerificationHistoryItem|null;evaluatedAt:string};
export type CommercialLaunchDossierDto={schemaVersion:"bimlog-commercial-launch-dossier-v1";status:"ready"|"blocked";ready:boolean;sourceCommit:string;sections:{id:"supplier_identity"|"commercial_services"|"current_verification";status:"ready"|"action_required";owner:"bimlog_platform";blockerCount:number}[];blockerCount:number;evaluatedAt:string;profile:{status:"complete"|"incomplete";complete:boolean;supplierName:string|null;registrationNumber:string|null;taxIdentifier:string|null;billingEmail:string|null;supportEmail:string|null;registeredAddress:string|null;invoiceJurisdiction:string|null;missingFields:string[];checkedAt:string};missingConfigurationKeys:string[];services:{status:"ready"|"test_only"|"blocked";providerMode:"test"|"live"|"unavailable";requiredActionCount:number};authorization:{status:"current"|"missing"|"source_mismatch"|"expired"|"not_verified";ready:boolean}};
const ids=["catalog","provider","live_mode","webhook","portal","support"] as const;
const allowedKeys=new Set(["BIMLOG_STRIPE_PRICE_IDS","BIMLOG_COMMERCIAL_MODE","STRIPE_SECRET_KEY","BIMLOG_APP_ORIGIN","STRIPE_WEBHOOK_SECRET","STRIPE_PORTAL_CONFIGURATION_ID","SENDGRID_API_KEY","BIMLOG_SUPPORT_FROM_EMAIL","BIMLOG_SUPPORT_INBOX_EMAIL"]);
export function parseCommercialLaunch(value:unknown):CommercialLaunchDto{
  if(!value||typeof value!=="object")throw new Error("Commercial launch status is invalid.");
  const item=value as Record<string,unknown>,steps=item.steps;
  if(!["ready","test_only","blocked"].includes(String(item.status))||!["test","live","unavailable"].includes(String(item.providerMode))||typeof item.ready!=="boolean"||!Array.isArray(steps)||steps.length!==ids.length||!Number.isInteger(item.requiredActionCount)||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt)))throw new Error("Commercial launch status is invalid.");
  const parsed=steps.map((raw,index)=>{if(!raw||typeof raw!=="object")throw new Error("Commercial launch step is invalid.");const step=raw as Record<string,unknown>;if(step.id!==ids[index]||!["ready","action_required"].includes(String(step.status))||step.owner!=="bimlog_platform"||typeof step.title!=="string"||!step.title.trim()||!Array.isArray(step.configurationKeys)||step.configurationKeys.some(key=>typeof key!=="string"||!allowedKeys.has(key)))throw new Error("Commercial launch step is invalid.");return step as unknown as CommercialLaunchStepDto;});
  const required=parsed.filter(step=>step.status==="action_required").length;
  if(required!==item.requiredActionCount||item.ready!==(item.status==="ready")||(item.status==="ready"&&required!==0))throw new Error("Commercial launch status is contradictory.");
  return {...item,steps:parsed,requiredActionCount:required} as CommercialLaunchDto;
}
export function parseCommercialLiveVerification(value:unknown):CommercialLiveVerificationDto{if(!value||typeof value!=="object")throw new Error("Live verification result is invalid.");const item=value as Record<string,unknown>;if(!["configuration_blocked","verified","failed"].includes(String(item.status))||typeof item.verified!=="boolean"||!Array.isArray(item.checks)||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt)))throw new Error("Live verification result is invalid.");const checks=item.checks.map(raw=>{if(!raw||typeof raw!=="object")throw new Error("Live verification check is invalid.");const check=raw as Record<string,unknown>;if(typeof check.id!=="string"||!check.id||!["verified","failed"].includes(String(check.status))||typeof check.code!=="string"||!check.code)throw new Error("Live verification check is invalid.");return check as {id:string;status:"verified"|"failed";code:string};});const rawEvidence=item.evidence;let evidence:CommercialVerificationEvidenceDto|null=null;if(rawEvidence!==null){if(!rawEvidence||typeof rawEvidence!=="object")throw new Error("Live verification evidence is invalid.");const e=rawEvidence as Record<string,unknown>;if(e.schemaVersion!=="bimlog-commercial-verification-v1"||typeof e.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(e.sourceCommit)||e.status!==item.status||e.verified!==item.verified||e.checkedAt!==item.checkedAt||typeof e.validUntil!=="string"||!Number.isFinite(Date.parse(e.validUntil))||!Number.isInteger(e.checkCount)||e.checkCount!==checks.length||!Array.isArray(e.failedCheckIds)||e.failedCheckIds.some(id=>typeof id!=="string"||!id)||typeof e.evidenceSha256!=="string"||!/^[0-9a-f]{64}$/.test(e.evidenceSha256))throw new Error("Live verification evidence is invalid.");evidence=e as unknown as CommercialVerificationEvidenceDto;}if(item.verified!==(item.status==="verified")||(item.status==="verified"&&checks.some(check=>check.status!=="verified"))||(item.status==="configuration_blocked"&&checks.length))throw new Error("Live verification result is contradictory.");return {...item,checks,evidence} as CommercialLiveVerificationDto;}
export function evaluateCommercialVerificationEvidence(live:CommercialLiveVerificationDto,expectedSourceCommit:string,now=new Date()):CommercialEvidenceDecision{
  if(!/^[0-9a-f]{40}$/.test(expectedSourceCommit))throw new Error("Expected source commit is invalid.");
  if(!live.evidence)return {status:"missing",ready:false};
  if(live.evidence.sourceCommit!==expectedSourceCommit)return {status:"source_mismatch",ready:false};
  if(!live.verified||!live.evidence.verified)return {status:"not_verified",ready:false};
  const checkedAt=Date.parse(live.evidence.checkedAt),validUntil=Date.parse(live.evidence.validUntil),at=now.getTime();
  if(!Number.isFinite(at)||checkedAt>at||validUntil<=at||validUntil<=checkedAt)return {status:"expired",ready:false};
  return {status:"current",ready:true};
}
export function parseCommercialHealthIdentity(value:unknown):CommercialHealthIdentityDto{
  if(!value||typeof value!=="object")throw new Error("Live release identity is invalid.");
  const item=value as Record<string,unknown>;
  if(item.status!=="ok"||typeof item.release!=="string"||!item.release||typeof item.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(item.sourceCommit)||typeof item.assetManifestSha256!=="string"||!/^[0-9a-f]{64}$/.test(item.assetManifestSha256)||typeof item.packageId!=="string"||!item.packageId||typeof item.databaseMigrationLevel!=="string"||!item.databaseMigrationLevel||typeof item.identityFingerprint!=="string"||!/^[0-9a-f]{64}$/.test(item.identityFingerprint)||item.identityBound!==true)throw new Error("Live release identity is invalid.");
  return item as CommercialHealthIdentityDto;
}
export function parseCommercialVerificationHistory(value:unknown):CommercialVerificationHistoryItem[]{
  if(!value||typeof value!=="object"||!Array.isArray((value as {items?:unknown}).items))throw new Error("Commercial verification history is invalid.");
  return (value as {items:unknown[]}).items.map(raw=>{if(!raw||typeof raw!=="object")throw new Error("Commercial verification history is invalid.");const item=raw as Record<string,unknown>;
    if(typeof item.id!=="string"||!item.id||!Number.isInteger(item.actorUserId)||Number(item.actorUserId)<=0||typeof item.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(item.sourceCommit)||!["configuration_blocked","verified","failed"].includes(String(item.status))||typeof item.verified!=="boolean"||typeof item.checkedAt!=="string"||!Number.isFinite(Date.parse(item.checkedAt))||typeof item.validUntil!=="string"||!Number.isFinite(Date.parse(item.validUntil))||typeof item.recordedAt!=="string"||!Number.isFinite(Date.parse(item.recordedAt))||!Number.isInteger(item.checkCount)||Number(item.checkCount)<0||!Array.isArray(item.failedCheckIds)||item.failedCheckIds.some(id=>typeof id!=="string"||!id)||!Array.isArray(item.checks)||item.checks.length!==item.checkCount||typeof item.evidenceSha256!=="string"||!/^[0-9a-f]{64}$/.test(item.evidenceSha256))throw new Error("Commercial verification history is invalid.");
    const checks=item.checks.map(check=>{if(!check||typeof check!=="object")throw new Error("Commercial verification history is invalid.");const entry=check as Record<string,unknown>;if(typeof entry.id!=="string"||!entry.id||!["verified","failed"].includes(String(entry.status))||typeof entry.code!=="string"||!entry.code)throw new Error("Commercial verification history is invalid.");return entry as {id:string;status:"verified"|"failed";code:string};});
    if(item.verified!==(item.status==="verified")||item.failedCheckIds.length!==checks.filter(check=>check.status==="failed").length)return (()=>{throw new Error("Commercial verification history is contradictory.");})();
    return {...item,checks} as CommercialVerificationHistoryItem;});
}
export function parseCommercialLaunchAuthorization(value:unknown):CommercialLaunchAuthorizationDto{
  if(!value||typeof value!=="object")throw new Error("Commercial launch authorization is invalid.");
  const item=value as Record<string,unknown>,status=String(item.status);
  if(!["current","missing","source_mismatch","expired","not_verified"].includes(status)||typeof item.ready!=="boolean"||item.ready!==(status==="current")||typeof item.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(item.sourceCommit)||typeof item.evaluatedAt!=="string"||!Number.isFinite(Date.parse(item.evaluatedAt)))throw new Error("Commercial launch authorization is invalid.");
  let receipt:CommercialVerificationHistoryItem|null=null;
  if(item.receipt!==null){const parsed=parseCommercialVerificationHistory({items:[item.receipt]});receipt=parsed[0];}
  if((status==="missing")!==(receipt===null)||(status==="current"&&receipt?.sourceCommit!==item.sourceCommit))throw new Error("Commercial launch authorization is contradictory.");
  return {...item,status,receipt} as CommercialLaunchAuthorizationDto;
}

export function parseCommercialLaunchDossier(value:unknown):CommercialLaunchDossierDto{
  if(!value||typeof value!=="object")throw new Error("Commercial launch dossier is invalid.");
  const item=value as Record<string,unknown>,sections=item.sections,profile=item.profile as Record<string,unknown>|undefined,services=item.services as Record<string,unknown>|undefined,authorization=item.authorization as Record<string,unknown>|undefined;
  const sectionIds=["supplier_identity","commercial_services","current_verification"] as const,profileFields=["supplierName","registrationNumber","taxIdentifier","billingEmail","supportEmail","registeredAddress","invoiceJurisdiction"];
  if(item.schemaVersion!=="bimlog-commercial-launch-dossier-v1"||!["ready","blocked"].includes(String(item.status))||typeof item.ready!=="boolean"||item.ready!==(item.status==="ready")||typeof item.sourceCommit!=="string"||!/^[0-9a-f]{40}$/.test(item.sourceCommit)||!Array.isArray(sections)||sections.length!==3||!Number.isInteger(item.blockerCount)||Number(item.blockerCount)<0||typeof item.evaluatedAt!=="string"||!Number.isFinite(Date.parse(item.evaluatedAt)))throw new Error("Commercial launch dossier is invalid.");
  const parsedSections=sections.map((raw,index)=>{if(!raw||typeof raw!=="object")throw new Error("Commercial launch dossier section is invalid.");const section=raw as Record<string,unknown>;if(section.id!==sectionIds[index]||!["ready","action_required"].includes(String(section.status))||section.owner!=="bimlog_platform"||!Number.isInteger(section.blockerCount)||Number(section.blockerCount)<0||(section.status==="ready")!==(section.blockerCount===0))throw new Error("Commercial launch dossier section is invalid.");return section;});
  if(parsedSections.reduce((sum,section)=>sum+Number(section.blockerCount),0)!==item.blockerCount||item.ready!==(item.blockerCount===0)||!profile||!["complete","incomplete"].includes(String(profile.status))||typeof profile.complete!=="boolean"||profile.complete!==(profile.status==="complete")||!Array.isArray(profile.missingFields)||!Array.isArray(item.missingConfigurationKeys)||!services||!["ready","test_only","blocked"].includes(String(services.status))||!["test","live","unavailable"].includes(String(services.providerMode))||!Number.isInteger(services.requiredActionCount)||!authorization||!["current","missing","source_mismatch","expired","not_verified"].includes(String(authorization.status))||typeof authorization.ready!=="boolean"||authorization.ready!==(authorization.status==="current"))throw new Error("Commercial launch dossier is contradictory.");
  for(const field of profileFields)if(profile[field]!==null&&typeof profile[field]!=="string")throw new Error("Commercial launch supplier profile is invalid.");
  if(profile.missingFields.some(field=>!profileFields.includes(String(field)))||item.missingConfigurationKeys.some(key=>typeof key!=="string"||!/^[A-Z0-9_]+$/.test(key as string)))throw new Error("Commercial launch supplier profile is invalid.");
  return item as unknown as CommercialLaunchDossierDto;
}
