export type CommercialWorkspaceActionDto={id:"complete_billing_identity"|"review_plans"|"contact_support";status:"available"|"complete"|"blocked";href:"/settings/company-profile"|"/pricing"|"/contact";blockers:string[]};
export type CommercialWorkspaceDto={companyId:number;companyName:string;memberCount:number;commercialAccess:boolean;subscriptionStatus:"not_configured"|"active";billingIdentityStatus:"incomplete"|"complete";paymentProviderStatus:"not_configured"|"ready";webhookStatus:"not_configured"|"ready";billingPortalStatus:"not_configured"|"ready";supportStatus:"not_configured"|"ready";readiness:"action_required"|"ready";blockers:string[];actions:CommercialWorkspaceActionDto[]};
const oneOf=<T extends string>(value:unknown,allowed:readonly T[],field:string):T=>{if(typeof value!=="string"||!allowed.includes(value as T))throw new Error(`Invalid commercial workspace ${field}`);return value as T;};
export function parseCommercialWorkspace(value:unknown):CommercialWorkspaceDto{
  if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial workspace response");
  const row=value as Record<string,unknown>;
  if(!Number.isSafeInteger(row.companyId)||Number(row.companyId)<1||typeof row.companyName!=="string"||!row.companyName.trim()||!Number.isSafeInteger(row.memberCount)||Number(row.memberCount)<0||typeof row.commercialAccess!=="boolean"||!Array.isArray(row.blockers)||row.blockers.some(item=>typeof item!=="string")||!Array.isArray(row.actions))throw new Error("Invalid commercial workspace identity");
  const actionHrefs={complete_billing_identity:"/settings/company-profile",review_plans:"/pricing",contact_support:"/contact"} as const;
  const actions=row.actions.map(value=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Invalid commercial workspace action");const action=value as Record<string,unknown>,id=oneOf(action.id,Object.keys(actionHrefs) as (keyof typeof actionHrefs)[],"action id"),href=oneOf(action.href,Object.values(actionHrefs),"action href");if(href!==actionHrefs[id]||!Array.isArray(action.blockers)||action.blockers.some(item=>typeof item!=="string"))throw new Error("Invalid commercial workspace action authority");return {id,status:oneOf(action.status,["available","complete","blocked"],"action status"),href,blockers:[...action.blockers] as string[]};});
  return {companyId:Number(row.companyId),companyName:row.companyName.trim(),memberCount:Number(row.memberCount),commercialAccess:row.commercialAccess,subscriptionStatus:oneOf(row.subscriptionStatus,["not_configured","active"],"subscription status"),billingIdentityStatus:oneOf(row.billingIdentityStatus,["incomplete","complete"],"billing identity status"),paymentProviderStatus:oneOf(row.paymentProviderStatus,["not_configured","ready"],"provider status"),webhookStatus:oneOf(row.webhookStatus,["not_configured","ready"],"webhook status"),billingPortalStatus:oneOf(row.billingPortalStatus,["not_configured","ready"],"portal status"),supportStatus:oneOf(row.supportStatus,["not_configured","ready"],"support status"),readiness:oneOf(row.readiness,["action_required","ready"],"readiness"),blockers:[...row.blockers] as string[],actions};
}
