import assert from "node:assert/strict";
import { applyAssignmentApuRate, applyAssignmentRole, governedApuRateChoices, rateForApuProfile } from "./job-intake-apu-rates.ts";
const draft = { scopeItems: [{ id: "scope-1", billingHourlyRate: "30.00" }], team: { assignments: [{ scopeItemId: "scope-1", role: "Pending", internalHourlyRate: "5.10" }] }, review: { pricingConfirmed: true } };
const assigned = applyAssignmentRole(draft, 0, "BIM Coordinator");
assert.equal(assigned.scopeItems[0].billingHourlyRate, "30.00");
assert.equal(assigned.team.assignments[0].role, "BIM Coordinator");
assert.equal(assigned.team.assignments[0].internalHourlyRate, "5.10");
assert.equal(applyAssignmentApuRate(draft, 0, "37.99", "Drafting").scopeItems[0].billingHourlyRate, "30.00");
assert.equal(rateForApuProfile("drafting"), null);
assert.equal(governedApuRateChoices([{ id: "apu-30", label: "$30 BIM", unitRate: "30.00", currency: "USD", apuPlanVersion: 4 }])[0].unitRate, "30.00");
console.log("job-intake-apu-rates.behavior: PASS");
