import assert from "node:assert/strict";
import fs from "node:fs";

const source=fs.readFileSync(new URL("./FeedbackWidget.tsx",import.meta.url),"utf8");
const editor=fs.readFileSync(new URL("./FeedbackMarkupEditor.tsx",import.meta.url),"utf8");
const assertions:Array<[string,RegExp]>=[
  ["dialog is viewport bounded",/maxHeight: "calc\(100dvh - 24px\)"/],
  ["dialog scrolls",/overflowY: "auto"/],
  ["background becomes inert",/sibling\.inert = true/],
  ["focus trap includes links",/a\[href\]/],
  ["focus trap includes summaries",/summary/],
  ["errors are alerts",/role="alert" aria-live="assertive"/],
  ["scope loss clears caches",/clearReviewScope\(\)/],
  ["discard revokes consent",/revokeCaptureConsents/],
  ["successful send clears consent",/setCaptureConsents\(\{\}\)/],
  ["file identity survives removal",/WeakMap<File,string>/],
  ["per-file state is durable",/setUploadResults/],
  ["failed files are retryable",/Retry this file/],
  ["retry targets one file",/retryFile\(file\)/],
  ["imported audio uses inspected media",/file\.type\.startsWith\("audio\/"\)/],
  ["imported audio has explicit non-capture origin",/addFiles\(Array\.from\(event\.target\.files \|\| \[\]\),"user-file-import"\)/],
  ["origin is not inferred from filename",/fileOriginsRef\.current\.get\(file\)/],
  ["revocation failure remains visible",/Consent revocation failed/],
  ["error receives focus",/errorRef\.current\?\.focus\(\)/],
  ["identical-byte replay is explicit",/Identical evidence already linked/],
  ["relay lifecycle is localized",/receipt-verified.*cleanup-pending.*manual-review/s],
  ["per-evidence relay history is visible",/item\.relays\.map.*Evidence relay.*Retransmisión de evidencia/s],
  ["customer relay reasons are localized",/awaiting-delivery.*Esperando entrega segura.*retention-ended.*Finalizó el período de retención/s],
  ["raw relay reason is never rendered",/relayReasonLabel\(relay\.reason\).*relayReasonLabel\(event\.reason\)/s],
  ["customer can request transcription",/Request transcription.*Solicitar transcripción/s],
  ["customer transcription reason is localized",/provider-unavailable.*El proveedor de transcripción aún no está disponible/s],
  ["imported transcription obtains processing consent",/captureKind:"transcription"/],
  ["blocked transcription retries as explicit successor",/retryOfJobId.*transcription-successor/s],
  ["customer can review transcription",/reviewTranscription\(item\.id,item\.transcription!\.id/],
  ["attachment download is authenticated",/fetch\(`\$\{API_BASE\}\$\{asset\.downloadUrl\}`.*Authorization: `Bearer \$\{token\}`/s],
  ["download object URLs are released",/URL\.revokeObjectURL\(url\)/],
  ["completed files are skipped",/state==="success"\)continue/],
  ["feedback states are translated",/stateLabel\(item\.status\)/],
  ["history events are translated",/eventLabel\(event\.eventType\)/],
  ["scan states are translated",/stateLabel\(asset\.scanState\)/],
  ["recording states are translated",/stateLabel\(recordingState\)/],
  ["capture reserves two atomic evidence slots",/files\.length > 8.*two linked slots/s],
  ["capture keeps original and marked evidence",/\[\.\.\.current, original, rendered\]/],
  ["capture bundle has stable linkage",/captureBundleId.*evidenceRole: "original".*evidenceRole: "marked"/s],
  ["capture bundle identity reaches server",/form\.append\("captureBundleId".*form\.append\("captureRole"/s],
  ["visual markup editor replaces numeric crop",/FeedbackMarkupEditor/],
  ["plain feedback route opens a new submission",/location !== "\/feedback".*setOpen\(true\).*else setReviewing\(false\)/s],
  ["feedback notification route reads the reactive query and opens customer history",/useSearch\(\).*new URLSearchParams\(search\).*view.*mine.*loadMine\(\)/s],
  ["report download requires an explicit positive asset id",/requestedAsset = params\.get\("downloadAsset"\).*if \(!requestedAsset\).*assetId < 1/s],
  ["floating feedback button always opens a new submission",/onClick=\{\(\) => \{ setReviewing\(false\); setOpen\(true\); \}\}/],
  ["customer sees automatic snapshot state",/Automatic PDF\/JSON snapshot.*Instantánea PDF\/JSON automática/s],
  ["customer downloads retained automatic PDF",/package-snapshot\.\$\{format\}.*Automatic PDF/s],
  ["customer downloads retained automatic JSON",/package-snapshot\.\$\{format\}.*Automatic JSON/s],
];
for(const [name,pattern] of assertions)assert.match(source,pattern,name);
for(const [name,pattern] of [
  ["editor exposes required drawing tools",/"crop".*"pen".*"pencil".*"highlight".*"line".*"arrow".*"rectangle".*"square".*"circle".*"text"/s],
  ["editor supports undo and redo",/const undo =.*const redoOne =/s],
  ["editor persists operation provenance",/toolVersion: "bimlog-cutting-markup-v1".*operationCount: operations\.length.*operations/s],
  ["editor preserves original statement",/untouched capture.*marked version remain linked/s],
] as Array<[string,RegExp]>) assert.match(editor,pattern,name);
console.log(`FeedbackWidget source assertions: ${assertions.length}/${assertions.length} passed`);
