import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { useAuthStore } from "@/store/auth";
import { useI18n } from "@/lib/i18n";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertCircle, Building2, Check, ChevronLeft, Mail, Settings2, UserRound, X } from "lucide-react";
import { clearCommercialIntent, intentLabel, postOnboardingCommercialDestination, readCommercialIntent } from "@/lib/commercial-intent";

const STORAGE_KEY="bimlog-onboarding-dismissed-v2";
const API=(import.meta.env.BASE_URL||"").replace(/\/$/,"")+"/api/v1";
const roles=[["bim_coordinator","BIM coordinator","Coordinador BIM"],["project_admin","Project administrator","Administrador de proyecto"],["document_controller","Document controller","Controlador documental"],["designer","Designer / detailer","Diseñador / dibujante"],["field_team","Field team","Equipo de campo"],["executive","Executive / owner","Ejecutivo / propietario"]] as const;
const allDisciplines=["Architecture","Structural","Mechanical","Electrical","Plumbing","Fire Protection","Civil"];
const allDocuments=["Shop Drawings","Coordination Drawings","Clash Reports","RFIs","Submittals"];
type State={email:string;companyName:string;emailVerifiedAt:string|null;workProfile:string|null;preferredDisciplines:string[];preferredDocumentTypes:string[];completedSteps:string[];completedAt:string|null;projectCount:number};

export function OnboardingFlow({onDone}:{onDone:()=>void}){
  const {lang}=useI18n(),token=useAuthStore(s=>s.token),tl=(en:string,es:string)=>lang==="es"?es:en;
  const [,navigate]=useLocation();
  const [state,setState]=useState<State|null>(null),[step,setStep]=useState(0),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [commercialIntent]=useState(()=>readCommercialIntent());
  const [role,setRole]=useState(""),[disciplines,setDisciplines]=useState<string[]>(["Architecture"]),[documents,setDocuments]=useState<string[]>(["Shop Drawings"]);
  const [project,setProject]=useState({name:"",code:"",description:""});
  const [createdProjectId,setCreatedProjectId]=useState<number|null>(null);
  const headers=useMemo(()=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"}),[token]);
  const load=async()=>{setError("");const response=await fetch(`${API}/onboarding`,{headers});if(!response.ok)throw new Error(tl("Setup could not be loaded.","No se pudo cargar la configuración."));const data=await response.json() as State;setState(data);setRole(data.workProfile||"");setDisciplines(data.preferredDisciplines.length?data.preferredDisciplines:["Architecture"]);setDocuments(data.preferredDocumentTypes.length?data.preferredDocumentTypes:["Shop Drawings"]);if(data.completedAt||data.projectCount>0){localStorage.setItem(STORAGE_KEY,"1");onDone();}};
  useEffect(()=>{void load().catch(e=>setError(e.message));},[token]);
  const request=async(path:string,init:RequestInit={})=>{setBusy(true);setError("");setNotice("");try{const response=await fetch(`${API}${path}`,{...init,headers:{...headers,...init.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||tl("The step could not be saved.","No se pudo guardar el paso."));return body;}finally{setBusy(false);}};
  const toggle=(value:string,current:string[],set:(v:string[])=>void)=>set(current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const saveProfile=async()=>{if(!role)throw new Error(tl("Choose the work profile that best matches your day-to-day work.","Elija el perfil que mejor represente su trabajo diario."));await request("/onboarding",{method:"PATCH",body:JSON.stringify({workProfile:role})});setStep(3);};
  const createProject=async()=>{const body={...project,code:project.code.trim().toUpperCase()};if(!body.name.trim()||!body.code)throw new Error(tl("Project name and code are required.","Se requieren el nombre y código del proyecto."));const created=await request("/projects",{method:"POST",body:JSON.stringify(body)});setCreatedProjectId(Number(created.id));setState(current=>current?{...current,projectCount:current.projectCount+1}:current);setStep(4);};
  const finish=async()=>{await request("/onboarding",{method:"PATCH",body:JSON.stringify({preferredDisciplines:disciplines,preferredDocumentTypes:documents})});await request("/onboarding/complete",{method:"POST"});const destination=postOnboardingCommercialDestination(commercialIntent,createdProjectId?`/projects/${createdProjectId}/intake`:"/dashboard");clearCommercialIntent();localStorage.setItem(STORAGE_KEY,"1");onDone();navigate(destination);};
  if(!state&&!error)return <Overlay><p className="rounded-xl bg-white p-8">{tl("Loading your setup…","Cargando su configuración…")}</p></Overlay>;
  const titles=[["Verify your email","Verifique su correo"],["Confirm your company","Confirme su empresa"],["Choose your work profile","Elija su perfil de trabajo"],["Create your first project","Cree su primer proyecto"],["Set useful defaults","Configure valores útiles"]];
  return <Overlay><div role="dialog" aria-modal="true" aria-labelledby="onboarding-title" className="w-[720px] max-w-[94vw] max-h-[92vh] overflow-auto rounded-2xl bg-white shadow-2xl">
    <div className="h-1 bg-slate-200"><div className="h-full bg-blue-600 transition-all" style={{width:`${(step+1)*20}%`}}/></div>
    <div className="flex items-center justify-between border-b px-6 py-4"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">{tl(`Setup ${step+1} of 5`,`Configuración ${step+1} de 5`)}</p><h2 id="onboarding-title" className="text-xl font-bold">{tl(titles[step][0],titles[step][1])}</h2></div><button aria-label={tl("Close setup","Cerrar configuración")} onClick={()=>{localStorage.setItem(STORAGE_KEY,"1");onDone();}}><X/></button></div>
    <div className="p-6">{commercialIntent&&<div role="status" className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900"><strong>{tl("Selected offer","Oferta seleccionada")}:</strong> {intentLabel(commercialIntent)}{commercialIntent.useCase?` · ${commercialIntent.useCase}`:""}. {commercialIntent.plan==="free"?tl("Your free account requires no payment method.","Su cuenta gratuita no requiere un método de pago."):tl("This selection preserves your request context; it does not grant paid access or replace a confirmed agreement.","Esta selección conserva el contexto de su solicitud; no otorga acceso de pago ni reemplaza un acuerdo confirmado.")}</div>}{error&&<div role="alert" className="mb-4 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800"><AlertCircle className="h-5 w-5"/>{error}</div>}{notice&&<div role="status" className="mb-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{notice}</div>}
      {step===0&&<Step icon={<Mail/>} text={tl(`We will verify ${state?.email}. This protects invitations and account recovery.`,`Verificaremos ${state?.email}. Esto protege las invitaciones y la recuperación de la cuenta.`)}>{state?.emailVerifiedAt?<Done text={tl("Email verified","Correo verificado")}/>:<Button disabled={busy} onClick={()=>void request("/onboarding/email-verification",{method:"POST"}).then(()=>setNotice(tl("Verification email sent. Open its secure link, then return and refresh this step.","Correo de verificación enviado. Abra su enlace seguro, luego regrese y actualice este paso."))).catch(e=>setError(e.message))}>{tl("Send verification email","Enviar correo de verificación")}</Button>}<Button variant="outline" disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>{tl("Refresh status","Actualizar estado")}</Button></Step>}
      {step===1&&<Step icon={<Building2/>} text={tl("Your company workspace is the boundary for catalogs, pricing and people. Joining another company requires its secure invitation.","El espacio de su empresa es el límite para catálogos, precios y personas. Unirse a otra empresa requiere su invitación segura.")}><div className="rounded-lg border bg-slate-50 p-4"><strong>{state?.companyName}</strong><p className="text-sm text-slate-600">{tl("Current authenticated company","Empresa autenticada actual")}</p></div></Step>}
      {step===2&&<Step icon={<UserRound/>} text={tl("This personalizes guidance only. It never grants permissions or changes your project role.","Esto solo personaliza la guía. Nunca otorga permisos ni cambia su rol del proyecto.")}><div className="grid gap-2 sm:grid-cols-2">{roles.map(item=><Choice key={item[0]} active={role===item[0]} onClick={()=>setRole(item[0])}>{tl(item[1],item[2])}</Choice>)}</div></Step>}
      {step===3&&<Step icon={<Building2/>} text={state?.projectCount?tl("You already have project access. Continue with that project or create another from Headquarters.","Ya tiene acceso a un proyecto. Continúe con ese proyecto o cree otro desde la Sede."):tl("Create the project shell now. BIMLog will take you directly to full Job Intake; team assignments can remain pending.","Cree ahora la base del proyecto. BIMLog lo llevará directamente al Intake completo; las asignaciones del equipo pueden quedar pendientes.")}>{!state?.projectCount&&<div className="grid gap-3"><Input aria-label={tl("Project name","Nombre del proyecto")} placeholder={tl("Project name","Nombre del proyecto")} value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/><Input aria-label={tl("Project code","Código del proyecto")} placeholder="PROJ-001" value={project.code} onChange={e=>setProject({...project,code:e.target.value.replace(/[^a-zA-Z0-9-]/g,"")})}/><Input aria-label={tl("Description","Descripción")} placeholder={tl("Optional description","Descripción opcional")} value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/></div>}</Step>}
      {step===4&&<Step icon={<Settings2/>} text={tl("Start with the choices you use most. Shop Drawings remain first for BIM coordination; you can search the full governed catalogs in Intake.","Comience con las opciones que más usa. Shop Drawings permanece primero para coordinación BIM; puede buscar los catálogos controlados completos en Intake.")}><Label text={tl("Frequent disciplines","Disciplinas frecuentes")}>{allDisciplines.map(value=><Choice key={value} active={disciplines.includes(value)} onClick={()=>toggle(value,disciplines,setDisciplines)}>{value}</Choice>)}</Label><Label text={tl("Frequent deliverables","Entregables frecuentes")}>{allDocuments.map(value=><Choice key={value} active={documents.includes(value)} onClick={()=>toggle(value,documents,setDocuments)}>{value}</Choice>)}</Label></Step>}
    </div>
    <div className="flex justify-between border-t px-6 py-4"><Button variant="outline" disabled={step===0||busy} onClick={()=>setStep(step-1)}><ChevronLeft className="mr-1 h-4 w-4"/>{tl("Back","Atrás")}</Button>{step===0?<Button disabled={!state?.emailVerifiedAt} onClick={()=>setStep(1)}>{tl("Continue","Continuar")}</Button>:step===1?<Button onClick={()=>setStep(2)}>{tl("This is my company","Esta es mi empresa")}</Button>:step===2?<Button disabled={busy} onClick={()=>void saveProfile().catch(e=>setError(e.message))}>{tl("Save and continue","Guardar y continuar")}</Button>:step===3?<Button disabled={busy} onClick={()=>state?.projectCount?setStep(4):void createProject().catch(e=>setError(e.message))}>{state?.projectCount?tl("Continue","Continuar"):tl("Create project","Crear proyecto")}</Button>:<Button disabled={busy||!disciplines.length||!documents.length} onClick={()=>void finish().catch(e=>setError(e.message))}>{commercialIntent&&["professional","team","business"].includes(commercialIntent.plan)?tl("Save and review billing","Guardar y revisar facturación"):tl("Save and open full Intake","Guardar y abrir Intake completo")}</Button>}</div>
  </div></Overlay>;
}

function Overlay({children}:{children:React.ReactNode}){return <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-slate-950/60 p-3">{children}</div>}
function Step({icon,text,children}:{icon:React.ReactNode;text:string;children:React.ReactNode}){return <div><div className="mb-5 flex gap-3"><div className="rounded-lg bg-blue-50 p-3 text-blue-700">{icon}</div><p className="text-sm leading-6 text-slate-600">{text}</p></div><div className="space-y-3">{children}</div></div>}
function Done({text}:{text:string}){return <div className="flex items-center gap-2 rounded-lg bg-emerald-50 p-3 font-semibold text-emerald-800"><Check className="h-5 w-5"/>{text}</div>}
function Choice({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" aria-pressed={active} onClick={onClick} className={`rounded-lg border px-3 py-2 text-left text-sm ${active?"border-blue-600 bg-blue-50 font-semibold text-blue-800":"border-slate-200 hover:border-slate-400"}`}>{children}</button>}
function Label({text,children}:{text:string;children:React.ReactNode}){return <div><p className="mb-2 mt-4 text-sm font-semibold">{text}</p><div className="flex flex-wrap gap-2">{children}</div></div>}
export function useOnboarding(){const {token}=useAuthStore();return{shouldShow:!!token&&!localStorage.getItem(STORAGE_KEY),markDone:()=>localStorage.setItem(STORAGE_KEY,"1")};}
