DatabaseMirror database.clamav.net
DatabaseDirectory /tmp/bimlog-feedback-clamav/database
DNSDatabaseInfo current.cvd.clamav.net
Checks 6
ConnectTimeout 30
ReceiveTimeout 60
MaxAttempts 3
ScriptedUpdates yes
CompressLocalDatabase no
SafeBrowsing no
Bytecode yes
