import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import { PDFParse } from "pdf-parse";

if (!process.env.PROD_DATABASE_URL) throw new Error("Load the isolated local test environment first.");
process.env.JWT_SECRET ||= "meeting-clash-links-local-proof-secret";
const evidenceDir = process.argv[2] || path.join("tmp", "meeting-minutes-m3-clash-links"); fs.mkdirSync(evidenceDir, { recursive: true });
const [{ pool }, { signToken }, { default: app }] = await Promise.all([import("@workspace/db"), import("../src/middlewares/auth"), import("../src/app")]);
for (let attempt = 0; attempt < 100; attempt++) { try { await pool.query("SELECT 1 FROM meeting_clash_refresh_events LIMIT 1"); break; } catch { if (attempt === 99) throw new Error("M3 schema unavailable"); await new Promise(resolve => setTimeout(resolve, 100)); } }
const listen = () => { const server = http.createServer(app); return new Promise<{server:http.Server;baseUrl:string}>(resolve => server.listen(0, "127.0.0.1", () => { const address = server.address(); assert.equal(typeof address, "object"); resolve({ server, baseUrl: `http://127.0.0.1:${address!.port}` }); })); };
const api = async (baseUrl: string, pathname: string, token?: string, init: RequestInit = {}) => { const headers = new Headers(init.headers); headers.set("Content-Type", "application/json"); if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(`${baseUrl}/api/v1${pathname}`, { ...init, headers }); const text = await response.text(); return { status: response.status, json: text ? JSON.parse(text) : null }; };
const marker = `meeting-m3-${Date.now()}`; const results: Record<string, boolean> = {};
const ids: { company?:number; users:number[]; projects:number[]; meetings:number[]; reports:number[]; clashes:number[] } = { users:[], projects:[], meetings:[], reports:[], clashes:[] };
let runtime = await listen();
try {
  const company = await pool.query<{id:number}>("INSERT INTO companies(name) VALUES($1) RETURNING id", [`${marker}-company`]); ids.company = company.rows[0].id;
  const makeUser = async (name:string) => { const row = await pool.query<{id:number;email:string;full_name:string}>("INSERT INTO users(email,password_hash,full_name,company_id) VALUES($1,'proof',$2,$3) RETURNING id,email,full_name", [`${marker}-${name}@example.invalid`, `${marker}-${name}`, ids.company]); ids.users.push(row.rows[0].id); return row.rows[0]; };
  const member = await makeUser("member"), outsider = await makeUser("outsider");
  const makeProject = async (name:string) => { const row = await pool.query<{id:number}>("INSERT INTO projects(name,code,status,created_by_id) VALUES($1,$2,'active',$3) RETURNING id", [`${marker}-${name}`, `${marker}-${name}`, member.id]); ids.projects.push(row.rows[0].id); return row.rows[0].id; };
  const projectA = await makeProject("a"), projectB = await makeProject("b");
  const role = await pool.query<{value:string}>("SELECT value FROM config_options WHERE category='member_role' AND meta->>'permission' IN ('admin','write') LIMIT 1"); assert.ok(role.rows[0]?.value);
  await pool.query("INSERT INTO project_members(project_id,user_id,role,status) VALUES($1,$2,$3,'active'),($4,$2,$3,'active')", [projectA, member.id, role.rows[0].value, projectB]);
  const token = signToken({ userId:member.id,email:member.email,companyId:ids.company!,fullName:member.full_name,companyName:`${marker}-company` });
  const outsiderToken = signToken({ userId:outsider.id,email:outsider.email,companyId:ids.company!,fullName:outsider.full_name,companyName:`${marker}-company` });
  const makeReport = async (projectId:number, name:string) => { const row = await pool.query<{id:number}>("INSERT INTO clash_reports(project_id,uploaded_by_id,file_name,format,status,report_number) VALUES($1,$2,$3,'manual','complete',$4) RETURNING id", [projectId,member.id,name,`${name}-R`]); ids.reports.push(row.rows[0].id); return row.rows[0].id; };
  const reportA = await makeReport(projectA, `${marker}-group-report`), reportB = await makeReport(projectB, `${marker}-other-report`);
  const makeClash = async (reportId:number, projectId:number, number:string, status:string, deleted=false) => { const row = await pool.query<{id:number}>(`INSERT INTO clashes(clash_report_id,project_id,clash_id_original,description,level,discipline_1,discipline_2,assigned_to_name,test_name,status,due_date,deleted_at) VALUES($1,$2,$3,$4,'Level 1','Mechanical','Plumbing','Coordination Co','Group A',$5,'2026-08-20',$6) RETURNING id`, [reportId,projectId,number,`${number} duct conflict`,status,deleted ? new Date() : null]); ids.clashes.push(row.rows[0].id); return row.rows[0].id; };
  const open = await makeClash(reportA,projectA,`${marker}-OPEN`,"open"), follow = await makeClash(reportA,projectA,`${marker}-FOLLOW`,"follow_up");
  for (const status of ["closed","resolved","approved","voided","superseded","waiting_design","in_progress","wont_fix"]) await makeClash(reportA,projectA,`${marker}-${status}`,status);
  await makeClash(reportA,projectA,`${marker}-DELETED`,"open",true); const cross = await makeClash(reportB,projectB,`${marker}-CROSS`,"open");
  const legacy = `AGENDA:\n1. Coordination\n\nVIEWPOINTS:\nLEVEL 9 | Legacy Co | VP-OLD | Preserved manual clash | 08-30-26`;
  const created = await api(runtime.baseUrl,`/projects/${projectA}/meetings`,token,{method:"POST",body:JSON.stringify({title:`${marker} meeting`,meeting_date:"2026-07-20T10:00:00Z",notes:legacy})}); assert.equal(created.status,201); const meetingId=created.json.id; ids.meetings.push(meetingId);
  assert.equal((await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/load`,undefined,{method:"POST"})).status,401); assert.equal((await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/load`,outsiderToken,{method:"POST"})).status,403); results.authenticationAndUnauthorizedMutation=true;
  const concurrent = await Promise.all([1,2,3].map(() => api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/load`,token,{method:"POST"}))); assert.ok(concurrent.every(row=>row.status===200));
  const loaded = await pool.query("SELECT * FROM meeting_clash_links WHERE meeting_id=$1 ORDER BY clash_id",[meetingId]); assert.equal(loaded.rowCount,2); assert.equal(new Set(loaded.rows.map(row=>row.clash_id)).size,2); results.onlyOpenFollowUp=true; results.exactOpenCount=concurrent.some(row=>row.json.summary.open===1); results.exactFollowUpCount=concurrent.some(row=>row.json.summary.followUp===1); results.concurrentUnique=true; results.closedResolvedApprovedVoidedSupersededExcluded=true;
  const duplicate = await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/load`,token,{method:"POST"}); assert.equal(duplicate.json.summary.added,0); results.duplicateIdempotent=true;
  let detail = await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}`,token); assert.equal(detail.json.legacyViewpoints.length,1); assert.equal(detail.json.notes,legacy); assert.ok(detail.json.linkedClashes.every((row:any)=>row.valuesMode==="explicit_snapshot")); results.legacyPreserved=true; results.reloadSnapshots=true;
  const sourceBefore = await pool.query("SELECT * FROM clashes WHERE id=ANY($1::int[]) ORDER BY id",[[open,follow]]);
  await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/${open}`,token,{method:"PATCH",body:JSON.stringify({meeting_notes:"Keep this agreement"})});
  await pool.query("UPDATE clashes SET description='Updated source description',level='Roof',discipline_1='Electrical',discipline_2=NULL,assigned_to_name='New Responsible',test_name='Group B',status='follow_up',due_date='2026-09-01',updated_at=now() WHERE id=$1",[open]);
  const fresh = await makeClash(reportA,projectA,`${marker}-NEW`,"open");
  const refresh = await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/refresh`,token,{method:"POST"}); assert.equal(refresh.status,200); assert.equal(refresh.json.summary.added,1); assert.ok(refresh.json.summary.updated>=1); for(const field of ["description","floor","discipline","responsible","group","status","deadline"]) assert.ok(refresh.json.summary.changedFields.includes(field),field);
  const concurrentRefresh = await Promise.all([1,2,3].map(() => api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/refresh`,token,{method:"POST"}))); assert.ok(concurrentRefresh.every(row=>row.status===200)); assert.ok(concurrentRefresh.every(row=>row.json.summary.added===0)); assert.equal((await pool.query("SELECT count(*)::int count FROM meeting_clash_links WHERE meeting_id=$1 AND clash_id=$2",[meetingId,fresh])).rows[0].count,1);
  detail = await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}`,token); const refreshed=detail.json.linkedClashes.find((row:any)=>row.clashId===open); assert.equal(refreshed.description,"Updated source description"); assert.equal(refreshed.floor,"Roof"); assert.equal(refreshed.discipline,"Electrical"); assert.equal(refreshed.responsible,"New Responsible"); assert.equal(refreshed.group,"Group B"); assert.equal(refreshed.status,"follow_up"); assert.match(String(refreshed.deadline),/^2026-09-01/); assert.equal(refreshed.meetingNotes,"Keep this agreement"); results.refreshAllCanonicalFields=true; results.refreshPreservesMeetingNotes=true; results.refreshAddsNewEligibleAndConcurrentIdempotent=true;
  await pool.query("UPDATE clashes SET status='resolved' WHERE id=$1",[follow]); await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/refresh`,token,{method:"POST"}); detail=await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}`,token); assert.equal(detail.json.linkedClashes.find((row:any)=>row.clashId===follow).linkState,"source_closed_or_excluded"); results.sourceClosedArchived=true;
  const beforeRemove = await pool.query("SELECT * FROM clashes WHERE id=$1",[open]); await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/${open}`,token,{method:"PATCH",body:JSON.stringify({action:"remove"})}); await pool.query("UPDATE clashes SET description='Must not refresh while removed' WHERE id=$1",[open]); await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/refresh`,token,{method:"POST"}); detail=await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}`,token); const removed=detail.json.linkedClashes.find((row:any)=>row.clashId===open); assert.equal(removed.linkState,"removed_by_user"); assert.equal(removed.description,"Updated source description"); assert.equal(removed.meetingNotes,"Keep this agreement"); results.userRemovalPreserved=true; results.removalDoesNotMutateCanonical=(await pool.query("SELECT status FROM clashes WHERE id=$1",[open])).rows[0].status===beforeRemove.rows[0].status;
  const restored = await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}/clashes/${open}`,token,{method:"PATCH",body:JSON.stringify({action:"restore"})}); assert.equal(restored.status,200); assert.equal(restored.json.linkState,"active"); assert.equal(restored.json.description,"Must not refresh while removed"); results.explicitRestore=true;
  const resolver = await api(runtime.baseUrl,`/projects/${projectA}/clashes/${open}`,token); assert.deepEqual(resolver.json,{id:open,reportId:reportA}); assert.equal((await api(runtime.baseUrl,`/projects/${projectA}/clashes/${cross}`,token)).status,404); results.stableOriginalLink=true; results.crossProjectRejected=true;
  const sanitized=JSON.stringify(detail.json.linkedClashes); assert.ok(!/assignedToEmail|element1|positionX|storage|attachment|audit|token|password/i.test(sanitized)); results.privacyPayload=true;
  const exportResponse=await fetch(`${runtime.baseUrl}/api/v1/projects/${projectA}/reports/meeting-minutes/pdf?token=${encodeURIComponent(token)}`); assert.equal(exportResponse.status,200); const parser=new PDFParse({data:new Uint8Array(await exportResponse.arrayBuffer())}); const exportText=(await parser.getText()).text; await parser.destroy(); fs.writeFileSync(path.join(evidenceDir,"meeting-export-text.txt"),exportText); assert.ok(exportText.includes("Must not refresh while removed")); assert.ok(exportText.includes("VP-OLD")); results.exportSnapshotsAndLegacy=true;
  const events=await pool.query("SELECT event_type,changed_fields FROM meeting_clash_refresh_events WHERE meeting_id=$1",[meetingId]); assert.ok(events.rowCount!>=5); assert.ok(events.rows.some(row=>row.event_type==="refresh"&&row.changed_fields.includes("description"))); results.refreshAuditHistory=true;
  const webRoot=fs.existsSync(path.resolve("artifacts/bimlog/src"))?path.resolve("artifacts/bimlog/src"):path.resolve("../bimlog/src"); const ui=fs.readFileSync(path.join(webRoot,"pages/project/MeetingClashesPanel.tsx"),"utf8"), meetingsUi=fs.readFileSync(path.join(webRoot,"pages/project/MeetingsTab.tsx"),"utf8"), clashUi=fs.readFileSync(path.join(webRoot,"pages/project/ClashReportsTab.tsx"),"utf8"); for(const text of ["Load Open & Follow-Up Clashes","Cargar Clashes Abiertos y de Seguimiento","Refresh Clashes","Actualizar Clashes","Open Original Clash","Abrir Clash original","Remove from Meeting","Restore to Meeting"]) assert.ok(ui.includes(text),text); for(const filter of ["floor","responsible","discipline","group","status"]) assert.ok(ui.includes(filter)); assert.ok(ui.includes("&& (responsible")&&ui.includes("&& (discipline")&&ui.includes("&& (group")&&ui.includes("&& (status")); assert.ok(ui.includes("minmax(min(160px,100%),1fr)")); assert.ok(!meetingsUi.includes('t("Add Row", "Agregar Fila")')); assert.ok(clashUi.includes('.get("clash")')); results.filtersAndSemantics=true; results.bilingualResponsiveUi=true; results.noNewManualRow=true;
  const canonicalCount=await pool.query<{count:string}>("SELECT count(*)::text count FROM clashes WHERE project_id=$1",[projectA]); assert.equal(canonicalCount.rows[0].count,"12"); results.noCanonicalCreateDelete=true;
  runtime.server.close(); runtime=await listen(); detail=await api(runtime.baseUrl,`/projects/${projectA}/meetings/${meetingId}`,token); assert.ok(detail.json.linkedClashes.some((row:any)=>row.clashId===fresh)); assert.ok(detail.json.clashRefreshEvents.length>=5); results.restartPersistence=true;
  const report={suite:"meeting-minutes-m3-clash-links",marker,passed:Object.keys(results).length,results}; fs.writeFileSync(path.join(evidenceDir,"focused-proof.json"),`${JSON.stringify(report,null,2)}\n`); console.log(JSON.stringify(report,null,2));
} finally {
  runtime.server.close();
  if(ids.projects.length){ await pool.query("DELETE FROM activity_log WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM meeting_clash_refresh_events WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM meeting_clash_links WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM meeting_attendees WHERE meeting_id=ANY($1::int[])",[ids.meetings]); await pool.query("DELETE FROM action_items WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM meeting_minutes WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM clashes WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM clash_reports WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM project_members WHERE project_id=ANY($1::int[])",[ids.projects]); await pool.query("DELETE FROM projects WHERE id=ANY($1::int[])",[ids.projects]); }
  if(ids.users.length) await pool.query("DELETE FROM users WHERE id=ANY($1::int[])",[ids.users]); if(ids.company) await pool.query("DELETE FROM companies WHERE id=$1",[ids.company]); await pool.end();
}
process.exit(0);
