import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import { randomUUID,X509Certificate,createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { EventEmitter } from "node:events";
import { NativeHttpsRelayTransport } from "./transport.js";
import { sha256 } from "./protocol.js";

const proofRoot=process.env.BIMLOG_FEEDBACK_TLS_TEST_ROOT;if(!proofRoot||!path.isAbsolute(proofRoot))throw new Error("BIMLOG_FEEDBACK_TLS_TEST_ROOT must bind an absolute disposable test root");const disposable=path.join(proofRoot,randomUUID());fs.mkdirSync(disposable,{recursive:true});const keyPath=path.join(disposable,"localhost.key"),certPath=path.join(disposable,"localhost.crt");
const openssl=process.env.BIMLOG_TEST_OPENSSL||"openssl";const generated=spawnSync(openssl,["req","-x509","-newkey","rsa:2048","-nodes","-keyout",keyPath,"-out",certPath,"-days","1","-subj","/CN=localhost","-addext","subjectAltName=DNS:localhost"],{stdio:"ignore"});if(generated.status!==0)throw new Error("Configured OpenSSL could not generate the disposable local TLS fixture");
const key=fs.readFileSync(keyPath),cert=fs.readFileSync(certPath),x509=new X509Certificate(cert);const pins={leafSha256:createHash("sha256").update(x509.raw).digest("hex"),spkiSha256:`sha256-${createHash("sha256").update(x509.publicKey.export({type:"spki",format:"der"})).digest("base64")}`};
let received=0;const server=https.createServer({key,cert},(req,res)=>{if(req.url==="/redirect"){res.writeHead(302,{location:"/ok"});res.end();return;}if(req.url==="/idle")return;if(req.url==="/idle-body"){res.writeHead(200);res.flushHeaders();return;}const chunks:Buffer[]=[];req.on("data",chunk=>chunks.push(Buffer.from(chunk)));req.on("end",()=>{received=Buffer.concat(chunks).length;if(req.url==="/large")res.end(Buffer.alloc(128));else res.end("ok");});});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error("Loopback server address missing");const origin=`https://localhost:${address.port}`;
let passed=0;const check=async(name:string,fn:()=>unknown|Promise<unknown>)=>{await fn();passed++;console.log(`PASS ${passed}: ${name}`);};const rejects=async(code:string,fn:()=>unknown|Promise<unknown>)=>assert.rejects(async()=>fn(),(e:unknown)=>Boolean(e&&typeof e==="object"&&"code" in e&&e.code===code));
try{
await check("native TLS validates CA hostname leaf and SPKI pins",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);const response=await transport.request({method:"POST",path:"/ok",body:Buffer.from("body"),maxResponseBytes:2,expectedResponseSha256:sha256("ok"),expectedGeneration:"generation-1"});assert.equal(response.status,200);assert.equal(received,4);transport.close();});
await check("hostname validation remains mandatory",async()=>{const transport=new NativeHttpsRelayTransport(`https://127.0.0.1:${address.port}`,pins,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_TRANSPORT_FAILED",()=>transport.request({method:"GET",path:"/ok",contentLength:0,maxResponseBytes:2}));transport.close();});
await check("leaf and SPKI mutations fail native handshake",async()=>{for(const bad of [{...pins,leafSha256:"0".repeat(64)},{...pins,spkiSha256:`sha256-${Buffer.alloc(32).toString("base64")}`}]){const transport=new NativeHttpsRelayTransport(origin,bad,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_TRANSPORT_FAILED",()=>transport.request({method:"GET",path:"/ok",contentLength:0,maxResponseBytes:2}));transport.close();}});
await check("native redirect is refused",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_REDIRECT_DENIED",()=>transport.request({method:"GET",path:"/redirect",contentLength:0,maxResponseBytes:10}));transport.close();});
await check("native bounded response destroys oversized socket",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_RESPONSE_TOO_LARGE",()=>transport.request({method:"GET",path:"/large",contentLength:0,maxResponseBytes:16}));transport.close();});
await check("async request streaming preserves exact byte count",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);async function* body(){for(let i=0;i<32;i++)yield Buffer.alloc(4096,i);}await transport.request({method:"PUT",path:"/ok",body:body(),contentLength:131072,maxResponseBytes:2});assert.equal(received,131072);await rejects("FEEDBACK_RELAY_REQUEST_BYTES_MISMATCH",()=>transport.request({method:"PUT",path:"/ok",body:body(),contentLength:1,maxResponseBytes:2}));transport.close();});
await check("slow upload has a distinct bounded request-write deadline",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);async function* slow(){yield Buffer.from("a");await new Promise(resolve=>setTimeout(resolve,100));yield Buffer.from("b");}await rejects("FEEDBACK_RELAY_REQUEST_WRITE_TIMEOUT",()=>transport.request({method:"PUT",path:"/ok",body:slow(),contentLength:2,maxResponseBytes:2,deadlines:{connectMs:1000,requestWriteMs:20,headersMs:1000,idleMs:1000,totalMs:2000}}));transport.close();});
await check("slow connect does not consume request-write budget",async()=>{const factory=(_url:URL,_options:unknown,onResponse:(r:any)=>void)=>{const req=new EventEmitter() as any;req.write=()=>true;req.destroy=()=>undefined;req.end=()=>{const response=new EventEmitter() as any;response.statusCode=200;response.headers={};response.destroy=()=>undefined;queueMicrotask(()=>{onResponse(response);response.emit("data",Buffer.from("ok"));response.emit("end");});};setTimeout(()=>req.emit("socket",{connecting:false}),50);return req;};const transport=new NativeHttpsRelayTransport("https://receiver.test",{leafSha256:"a".repeat(64)},"slow-connect",factory as any);assert.equal((await transport.request({method:"PUT",path:"/ok",body:Buffer.from("x"),maxResponseBytes:2,deadlines:{connectMs:200,requestWriteMs:20,headersMs:200,idleMs:200,totalMs:500}})).status,200);transport.close();});
await check("AbortSignal deterministically cancels idle socket",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);const controller=new AbortController();const pending=transport.request({method:"GET",path:"/idle",contentLength:0,maxResponseBytes:2,signal:controller.signal,deadlines:{headersMs:1000,totalMs:2000,idleMs:1000,connectMs:1000}});controller.abort();await rejects("FEEDBACK_RELAY_ABORTED",()=>pending);transport.close();});
await check("header deadline is distinct and fail closed",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_HEADERS_TIMEOUT",()=>transport.request({method:"GET",path:"/idle",contentLength:0,maxResponseBytes:2,deadlines:{headersMs:20,totalMs:1000,idleMs:1000,connectMs:1000}}));transport.close();});
await check("response idle and total deadlines are distinct",async()=>{const transport=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert);await rejects("FEEDBACK_RELAY_IDLE_TIMEOUT",()=>transport.request({method:"GET",path:"/idle-body",contentLength:0,maxResponseBytes:2,deadlines:{headersMs:1000,totalMs:1000,idleMs:20,connectMs:1000}}));await rejects("FEEDBACK_RELAY_TOTAL_TIMEOUT",()=>transport.request({method:"GET",path:"/idle",contentLength:0,maxResponseBytes:2,deadlines:{headersMs:1000,totalMs:20,idleMs:1000,connectMs:1000}}));transport.close();});
await check("pin rotation closes old Agent and binds new generation",async()=>{const old=new NativeHttpsRelayTransport(origin,pins,"generation-1",https.request,cert),next=old.rotate({pins,generation:"generation-2",ca:cert});await rejects("FEEDBACK_RELAY_TRANSPORT_CLOSED",()=>old.request({method:"GET",path:"/ok",contentLength:0,maxResponseBytes:2}));await rejects("FEEDBACK_RELAY_GENERATION_STALE",()=>next.request({method:"GET",path:"/ok",contentLength:0,maxResponseBytes:2,expectedGeneration:"generation-1"}));assert.equal((await next.request({method:"GET",path:"/ok",contentLength:0,maxResponseBytes:2,expectedGeneration:"generation-2"})).status,200);next.close();});
console.log(`feedback relay native TLS transport behavior: ${passed}/${passed}`);
}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));fs.rmSync(disposable,{recursive:true,force:true});}
