import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { RelayProtocolError, canonicalRequest, canonicalReceipt, sha256, signReadback, signReceipt, signRequest, verifyRequest, type NonceAuthority, type ReadbackContract, type ReceiptContract, type RelayKeyRing, type RequestContract, type Signed } from "./protocol.js";

export type ReceiverRootAuthority={canonicalRoot:string;rootFingerprintSha256:string;destinationId:string};
export type ReceiverMediaKind="screenshot"|"audio"|"document"|"transcript"|"original";
export type ScannerInspection={verdict:"clean";scannerAdapter:string;inspectedAt:string;inspectedMediaType:string;mediaKind:ReceiverMediaKind;byteCount:number;sha256:string};
export type StoredDelivery={requestHash:string;objectRelativePath:string;inspection:ScannerInspection;receipt:Signed<ReceiptContract>};
export type PurgeAuthority={policySha256:string;approvedBy:string;approvedAt:string;hold:boolean};
export type DeletionReceipt={deletedAt:string;objectSha256:string;byteCount:number;policySha256:string;approvedBy:string;absenceVerified:true;signed:Signed<RequestContract>};
export type BackupInventory={createdAt:string;sourceRootFingerprintSha256:string;objects:readonly {relativePath:string;byteCount:number;sha256:string}[];inventorySha256:string};

const HEX64=/^[a-f0-9]{64}$/;
const fail=(code:string,message:string):never=>{throw new RelayProtocolError(code,message);};
const canonicalRoot=(value:string)=>path.resolve(value);
const rootFingerprint=(root:string)=>sha256(`bimlog-feedback-receiver-root-v1\n${root.replaceAll("\\","/").toLowerCase()}`);
function contained(root:string,target:string){const relative=path.relative(root,target);return relative===""||(!relative.startsWith(`..${path.sep}`)&&relative!==".."&&!path.isAbsolute(relative));}
function assertNoLinks(root:string,target:string){if(!contained(root,target))fail("FEEDBACK_RECEIVER_CONTAINMENT_DENIED","Receiver path escaped its authorized root");let current=root;for(const part of path.relative(root,target).split(path.sep).filter(Boolean)){current=path.join(current,part);if(!fs.existsSync(current))break;const stat=fs.lstatSync(current);if(stat.isSymbolicLink())fail("FEEDBACK_RECEIVER_REPARSE_DENIED","Receiver custody contains a link or reparse point");}}
function assertTreeNoLinks(root:string,dir=root){assertNoLinks(root,dir);for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const target=path.join(dir,entry.name);const stat=fs.lstatSync(target);if(stat.isSymbolicLink())fail("FEEDBACK_RECEIVER_REPARSE_DENIED","Receiver custody contains a link or reparse point");if(stat.isDirectory())assertTreeNoLinks(root,target);}}
function mkdirSafe(root:string,target:string){assertNoLinks(root,target);fs.mkdirSync(target,{recursive:true});assertNoLinks(root,target);}
function atomicWrite(root:string,target:string,bytes:Buffer){mkdirSafe(root,path.dirname(target));const staging=path.join(root,"99-System","staging");const temporary=fs.existsSync(staging)&&!contained(staging,target)?path.join(staging,`.stage-${randomUUID()}`):path.join(path.dirname(target),`.stage-${randomUUID()}`);const fd=fs.openSync(temporary,"wx",0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}try{fs.renameSync(temporary,target);}catch(error){try{fs.unlinkSync(temporary);}catch{}throw error;}}
function atomicJson(root:string,target:string,value:unknown){atomicWrite(root,target,Buffer.from(JSON.stringify(value),"utf8"));}
function readJson<T>(file:string):T{return JSON.parse(fs.readFileSync(file,"utf8")) as T;}
const MEDIA_KIND:Readonly<Record<string,ReceiverMediaKind>>={"image/png":"screenshot","image/jpeg":"screenshot","audio/mpeg":"audio","audio/wav":"audio","audio/webm":"audio","application/pdf":"document","text/plain":"transcript","application/octet-stream":"original"};
function verifiedInspection(input:ScannerInspection,request:RequestContract,clientDeclared?:{mediaType:string;mediaKind:ReceiverMediaKind}){if(input.verdict!=="clean")fail("FEEDBACK_RECEIVER_SCANNER_CLEAN_REQUIRED","Only scanner-clean bytes may enter receiver custody");if(!/^[A-Za-z0-9._-]{1,80}$/.test(input.scannerAdapter)||/precheck|evidence.?contract/i.test(input.scannerAdapter))fail("FEEDBACK_RECEIVER_SCANNER_AUTHORITY_INVALID","A governed malware scanner adapter is required");const inspectedAt=new Date(input.inspectedAt);if(Number.isNaN(inspectedAt.getTime())||inspectedAt.toISOString()!==input.inspectedAt||input.byteCount!==request.byteCount||input.sha256!==request.sha256)fail("FEEDBACK_RECEIVER_INSPECTION_MISMATCH","Scanner inspection does not bind the signed bytes");const mediaType=input.inspectedMediaType.trim().toLowerCase();if(MEDIA_KIND[mediaType]!==input.mediaKind)fail("FEEDBACK_RECEIVER_MEDIA_KIND_MISMATCH","Inspected media type and media kind are inconsistent");if(clientDeclared&&(clientDeclared.mediaType.trim().toLowerCase()!==mediaType||clientDeclared.mediaKind!==input.mediaKind))fail("FEEDBACK_RECEIVER_CLIENT_MEDIA_MISMATCH","Client-declared media identity differs from scanner inspection");return{...input,inspectedMediaType:mediaType};}

export class FeedbackReceiverCustodyService{
  readonly root:string;private readonly system:string;private readonly objects:string;
  constructor(private readonly authority:ReceiverRootAuthority,private readonly senderKeys:RelayKeyRing,private readonly receiverKeys:RelayKeyRing,private readonly nonces:NonceAuthority,private readonly maxSkewMs:number){
    this.root=canonicalRoot(authority.canonicalRoot);if(!fs.existsSync(this.root)||!fs.statSync(this.root).isDirectory())fail("FEEDBACK_RECEIVER_ROOT_REQUIRED","Authorized receiver root must already exist");
    const physical=fs.realpathSync.native(this.root);if(canonicalRoot(physical)!==this.root)fail("FEEDBACK_RECEIVER_ROOT_IDENTITY_MISMATCH","Receiver root physical identity differs from authority");
    if(!HEX64.test(authority.rootFingerprintSha256)||rootFingerprint(this.root)!==authority.rootFingerprintSha256)fail("FEEDBACK_RECEIVER_ROOT_IDENTITY_MISMATCH","Receiver root fingerprint differs from authority");
    assertTreeNoLinks(this.root);this.system=path.join(this.root,"99-System");this.objects=path.join(this.root,"01-Active");mkdirSafe(this.root,this.system);mkdirSafe(this.root,this.objects);mkdirSafe(this.root,path.join(this.system,"requests"));mkdirSafe(this.root,path.join(this.system,"locks"));mkdirSafe(this.root,path.join(this.system,"deletions"));mkdirSafe(this.root,path.join(this.system,"staging"));
  }
  static fingerprintRoot(root:string){return rootFingerprint(canonicalRoot(root));}
  private indexPath(requestId:string){return path.join(this.system,"requests",`${sha256(requestId)}.json`);}
  private objectPath(request:RequestContract){return path.join(this.objects,sha256(request.companyId).slice(0,16),sha256(request.projectId).slice(0,16),sha256(request.feedbackId).slice(0,16),sha256(request.objectId).slice(0,16),request.sha256);}
  private async lock<T>(identity:string,work:()=>Promise<T>):Promise<T>{const lock=path.join(this.system,"locks",sha256(identity));for(let attempt=0;attempt<200;attempt++){try{fs.mkdirSync(lock);fs.writeFileSync(path.join(lock,"owner.json"),JSON.stringify({pid:process.pid,acquiredAt:new Date().toISOString()}),{flag:"wx",mode:0o600});try{return await work();}finally{fs.rmSync(lock,{recursive:true,force:false});} }catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;await new Promise(resolve=>setTimeout(resolve,2));}}return fail("FEEDBACK_RECEIVER_LOCK_TIMEOUT","Receiver request is already being processed");}
  async deliver(input:{signedRequest:Signed<RequestContract>;bytes:Buffer;inspection:ScannerInspection;clientDeclared?:{mediaType:string;mediaKind:ReceiverMediaKind};now?:Date}):Promise<Signed<ReceiptContract>>{
    const requestId=input.signedRequest.payload.requestId,inspection=verifiedInspection(input.inspection,input.signedRequest.payload,input.clientDeclared),requestHash=sha256(`${canonicalRequest(input.signedRequest.payload)}\ninspection:${sha256(JSON.stringify(inspection))}`);return this.lock(requestId,async()=>{const index=this.indexPath(requestId);if(fs.existsSync(index)){const stored=readJson<StoredDelivery>(index);if(stored.requestHash!==requestHash)fail("FEEDBACK_RECEIVER_REQUEST_CONFLICT","Request identity was reused with divergent content");return stored.receipt;}
      const now=input.now??new Date();const request=await verifyRequest(input.signedRequest,this.senderKeys,this.nonces,{now,maxSkewMs:this.maxSkewMs});if(input.bytes.length!==request.byteCount||sha256(input.bytes)!==request.sha256||request.bodySha256!==request.sha256)fail("FEEDBACK_RECEIVER_OBJECT_MISMATCH","Delivered bytes do not match the signed request");
      const object=this.objectPath(request);assertNoLinks(this.root,object);if(fs.existsSync(object)){const existing=fs.readFileSync(object);if(existing.length!==request.byteCount||sha256(existing)!==request.sha256)fail("FEEDBACK_RECEIVER_OBJECT_CONFLICT","Existing custody object differs from request");}else atomicWrite(this.root,object,input.bytes);
      const receipt=signReceipt({version:"1",requestId:request.requestId,companyId:request.companyId,projectId:request.projectId,feedbackId:request.feedbackId,objectId:request.objectId,byteCount:request.byteCount,sha256:request.sha256,destinationId:this.authority.destinationId,receivedAt:now.toISOString(),requestNonce:request.nonce,receiverKeyId:this.receiverKeys.activeKeyId},this.receiverKeys,now);
      atomicJson(this.root,index,{requestHash,objectRelativePath:path.relative(this.root,object),inspection,receipt} satisfies StoredDelivery);return receipt;});
  }
  readback(requestId:string,now=new Date()):Signed<ReadbackContract>{const stored=readJson<StoredDelivery>(this.indexPath(requestId));const object=path.join(this.root,stored.objectRelativePath);assertNoLinks(this.root,object);const bytes=fs.readFileSync(object);if(bytes.length!==stored.receipt.payload.byteCount||sha256(bytes)!==stored.receipt.payload.sha256)fail("FEEDBACK_RECEIVER_READBACK_MISMATCH","Custody bytes no longer match their receipt");return signReadback({version:"1",requestId:stored.receipt.payload.requestId,companyId:stored.receipt.payload.companyId,projectId:stored.receipt.payload.projectId,feedbackId:stored.receipt.payload.feedbackId,objectId:stored.receipt.payload.objectId,byteCount:bytes.length,sha256:sha256(bytes),destinationId:this.authority.destinationId,verifiedAt:now.toISOString(),receiptSha256:sha256(canonicalReceipt(stored.receipt.payload)),receiverKeyId:this.receiverKeys.activeKeyId},this.receiverKeys,now);}
  recover():{removedStages:number;removedStaleLocks:number}{const staging=path.join(this.system,"staging");assertNoLinks(this.root,staging);let removedStages=0,removedStaleLocks=0;for(const entry of fs.readdirSync(staging)){const target=path.join(staging,entry);assertNoLinks(this.root,target);if(fs.lstatSync(target).isFile()){fs.unlinkSync(target);removedStages++;}}const locks=path.join(this.system,"locks");for(const entry of fs.readdirSync(locks)){const target=path.join(locks,entry),ownerPath=path.join(target,"owner.json");assertNoLinks(this.root,target);if(!fs.lstatSync(target).isDirectory()||!fs.existsSync(ownerPath))continue;const owner=readJson<{pid:number}>(ownerPath);let alive=true;try{process.kill(owner.pid,0);}catch(error){if((error as NodeJS.ErrnoException).code==="ESRCH")alive=false;}if(!alive){fs.rmSync(target,{recursive:true,force:false});removedStaleLocks++;}}return{removedStages,removedStaleLocks};}
  purge(requestId:string,authority:PurgeAuthority,now=new Date()):DeletionReceipt{if(authority.hold)fail("FEEDBACK_RECEIVER_HOLD_ACTIVE","Held custody cannot be purged");if(!HEX64.test(authority.policySha256)||!authority.approvedBy.trim()||new Date(authority.approvedAt).toISOString()!==authority.approvedAt)fail("FEEDBACK_RECEIVER_PURGE_AUTHORITY_INVALID","Purge authority is invalid");const deletionPath=path.join(this.system,"deletions",`${sha256(requestId)}.json`);if(fs.existsSync(deletionPath)){const existing=readJson<DeletionReceipt>(deletionPath);if(existing.policySha256!==authority.policySha256||existing.approvedBy!==authority.approvedBy)fail("FEEDBACK_RECEIVER_PURGE_CONFLICT","Purge receipt authority differs from immutable history");return existing;}const stored=readJson<StoredDelivery>(this.indexPath(requestId));const object=path.join(this.root,stored.objectRelativePath);assertNoLinks(this.root,object);const bytes=fs.readFileSync(object);if(sha256(bytes)!==stored.receipt.payload.sha256)fail("FEEDBACK_RECEIVER_READBACK_MISMATCH","Custody bytes changed before purge");fs.unlinkSync(object);if(fs.existsSync(object))fail("FEEDBACK_RECEIVER_ABSENCE_UNPROVEN","Purged object absence could not be verified");const signed=signRequest({version:"1",method:"DELETE",path:`/v1/objects/${stored.receipt.payload.objectId}`,query:"",audience:this.authority.destinationId,keyId:this.receiverKeys.activeKeyId,timestamp:now.toISOString(),nonce:`purge-${sha256(requestId).slice(0,24)}`,requestId:`purge-${requestId}`,companyId:stored.receipt.payload.companyId,projectId:stored.receipt.payload.projectId,feedbackId:stored.receipt.payload.feedbackId,objectId:stored.receipt.payload.objectId,byteCount:bytes.length,sha256:sha256(bytes),bodySha256:authority.policySha256},this.receiverKeys,now);const result:DeletionReceipt={deletedAt:now.toISOString(),objectSha256:sha256(bytes),byteCount:bytes.length,policySha256:authority.policySha256,approvedBy:authority.approvedBy,absenceVerified:true,signed};atomicJson(this.root,deletionPath,result);return result;}
  health(){try{assertTreeNoLinks(this.root);fs.accessSync(this.root,fs.constants.R_OK|fs.constants.W_OK);return{status:"ok" as const,destinationId:this.authority.destinationId,rootFingerprintSha256:this.authority.rootFingerprintSha256};}catch{return{status:"unavailable" as const,destinationId:this.authority.destinationId};}}
}

function inventoryObjects(root:string){const result:{relativePath:string;byteCount:number;sha256:string}[]=[];const walk=(dir:string)=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const target=path.join(dir,entry.name);assertNoLinks(root,target);if(entry.isDirectory())walk(target);else if(entry.isFile()){const bytes=fs.readFileSync(target);result.push({relativePath:path.relative(root,target).replaceAll("\\","/"),byteCount:bytes.length,sha256:sha256(bytes)});}}};const active=path.join(root,"01-Active");if(fs.existsSync(active))walk(active);return result.sort((a,b)=>a.relativePath.localeCompare(b.relativePath));}
export function createReceiverBackup(sourceRoot:string,backupRoot:string,createdAt=new Date()):BackupInventory{const source=canonicalRoot(sourceRoot),backup=canonicalRoot(backupRoot);if(!fs.existsSync(backup)||fs.readdirSync(backup).length)fail("FEEDBACK_RECEIVER_BACKUP_ROOT_NOT_EMPTY","Backup root must exist and be empty");assertNoLinks(source,source);const objects=inventoryObjects(source);for(const item of objects){const from=path.join(source,item.relativePath),to=path.join(backup,item.relativePath);mkdirSafe(backup,path.dirname(to));fs.copyFileSync(from,to,fs.constants.COPYFILE_EXCL);if(sha256(fs.readFileSync(to))!==item.sha256)fail("FEEDBACK_RECEIVER_BACKUP_MISMATCH","Backup object verification failed");}const base={createdAt:createdAt.toISOString(),sourceRootFingerprintSha256:rootFingerprint(source),objects};const inventory={...base,inventorySha256:sha256(JSON.stringify(base))};atomicJson(backup,path.join(backup,"backup-inventory.json"),inventory);return inventory;}
export function restoreReceiverBackup(backupRoot:string,isolatedRestoreRoot:string):BackupInventory{const backup=canonicalRoot(backupRoot),restore=canonicalRoot(isolatedRestoreRoot);if(!fs.existsSync(restore)||fs.readdirSync(restore).length)fail("FEEDBACK_RECEIVER_RESTORE_ROOT_NOT_EMPTY","Restore root must exist and be empty");const inventory=readJson<BackupInventory>(path.join(backup,"backup-inventory.json"));const base={createdAt:inventory.createdAt,sourceRootFingerprintSha256:inventory.sourceRootFingerprintSha256,objects:inventory.objects};if(sha256(JSON.stringify(base))!==inventory.inventorySha256)fail("FEEDBACK_RECEIVER_BACKUP_INVENTORY_INVALID","Backup inventory digest is invalid");for(const item of inventory.objects){const from=path.join(backup,item.relativePath),to=path.join(restore,item.relativePath);assertNoLinks(backup,from);mkdirSafe(restore,path.dirname(to));fs.copyFileSync(from,to,fs.constants.COPYFILE_EXCL);const bytes=fs.readFileSync(to);if(bytes.length!==item.byteCount||sha256(bytes)!==item.sha256)fail("FEEDBACK_RECEIVER_RESTORE_MISMATCH","Restored object verification failed");}return inventory;}
