import https from "node:https";
import tls from "node:tls";
import { X509Certificate, createHash, timingSafeEqual } from "node:crypto";
import { once } from "node:events";
import type { IncomingMessage } from "node:http";
import { RelayProtocolError, sha256 } from "./protocol.js";
export type TransportPins={leafSha256?:string;spkiSha256?:string};
export type TransportResponse={status:number;headers:Readonly<Record<string,string|string[]|undefined>>;body:Buffer;sha256:string};
export type TransportDeadlines={connectMs:number;requestWriteMs:number;headersMs:number;idleMs:number;totalMs:number};
export type RequestFactory=(url:URL,options:https.RequestOptions,onResponse:(response:IncomingMessage)=>void)=>ReturnType<typeof https.request>;
const DEFAULT_DEADLINES:TransportDeadlines={connectMs:10_000,requestWriteMs:30_000,headersMs:20_000,idleMs:15_000,totalMs:60_000};
const safeEqual=(a:Buffer,b:Buffer)=>a.length===b.length&&timingSafeEqual(a,b);
const pinBytes=(value:string,kind:"leaf"|"spki")=>kind==="leaf"?Buffer.from(value,"hex"):Buffer.from(value.slice(7),"base64");
export function assertCertificatePins(actual:{leafSha256:string;spkiSha256:string},pins:TransportPins){const leafOk=!pins.leafSha256||safeEqual(pinBytes(actual.leafSha256,"leaf"),pinBytes(pins.leafSha256,"leaf"));const spkiOk=!pins.spkiSha256||safeEqual(pinBytes(actual.spkiSha256,"spki"),pinBytes(pins.spkiSha256,"spki"));return leafOk&&spkiOk?undefined:new Error("FEEDBACK_RELAY_CERTIFICATE_PIN_MISMATCH");}
export function pinnedServerIdentity(hostname:string,cert:tls.PeerCertificate,pins:TransportPins){const normal=tls.checkServerIdentity(hostname,cert);if(normal)return normal;if(!cert.raw)return new Error("FEEDBACK_RELAY_CERTIFICATE_MISSING");const leaf=createHash("sha256").update(cert.raw).digest("hex");const spki=createHash("sha256").update(new X509Certificate(cert.raw).publicKey.export({type:"spki",format:"der"})).digest("base64");return assertCertificatePins({leafSha256:leaf,spkiSha256:`sha256-${spki}`},pins);}
function validatePins(pins:TransportPins){if(!pins.leafSha256&&!pins.spkiSha256)throw new RelayProtocolError("FEEDBACK_RELAY_PIN_REQUIRED","A leaf or SPKI pin is required");if(pins.leafSha256&&!/^[a-f0-9]{64}$/.test(pins.leafSha256))throw new RelayProtocolError("FEEDBACK_RELAY_PIN_INVALID","Leaf pin is invalid");if(pins.spkiSha256&&!/^sha256-[A-Za-z0-9+/]{43}=$/.test(pins.spkiSha256))throw new RelayProtocolError("FEEDBACK_RELAY_PIN_INVALID","SPKI pin is invalid");}
function validateDeadlines(value:TransportDeadlines){for(const [name,ms] of Object.entries(value))if(!Number.isSafeInteger(ms)||ms<1||ms>300_000)throw new RelayProtocolError("FEEDBACK_RELAY_DEADLINE_INVALID",`Invalid ${name}`);}
export class NativeHttpsRelayTransport{
  private readonly origin:string;private readonly agent:https.Agent;private closed=false;
  constructor(origin:string,private readonly pins:TransportPins,readonly generation="1",private readonly requestFactory:RequestFactory=https.request,private readonly ca?:string|Buffer){const url=new URL(origin);if(url.protocol!=="https:"||url.username||url.password||url.search||url.hash||url.pathname!=="/")throw new RelayProtocolError("FEEDBACK_RELAY_ORIGIN_INVALID","Relay origin must be a credential-free HTTPS origin");validatePins(pins);if(!/^[A-Za-z0-9._-]{1,64}$/.test(generation))throw new RelayProtocolError("FEEDBACK_RELAY_GENERATION_INVALID","Transport generation is invalid");this.origin=url.origin;this.agent=new https.Agent({keepAlive:true,maxSockets:8,ca});}
  close(){if(!this.closed){this.closed=true;this.agent.destroy();}}
  rotate(input:{pins:TransportPins;generation:string;ca?:string|Buffer}){this.close();return new NativeHttpsRelayTransport(this.origin,input.pins,input.generation,this.requestFactory,input.ca);}
  async request(input:{method:string;path:string;headers?:Record<string,string>;body?:Buffer|AsyncIterable<Uint8Array>;contentLength?:number;expectedResponseSha256?:string;maxResponseBytes:number;deadlines?:Partial<TransportDeadlines>;signal?:AbortSignal;expectedGeneration?:string}):Promise<TransportResponse>{
    if(this.closed)throw new RelayProtocolError("FEEDBACK_RELAY_TRANSPORT_CLOSED","Transport generation is closed");if(input.expectedGeneration&&input.expectedGeneration!==this.generation)throw new RelayProtocolError("FEEDBACK_RELAY_GENERATION_STALE","Transport pin generation changed");const url=new URL(input.path,this.origin);if(url.origin!==this.origin||url.protocol!=="https:"||url.username||url.password||url.hash)throw new RelayProtocolError("FEEDBACK_RELAY_DESTINATION_DENIED","Relay destination escaped its pinned origin");if(!Number.isSafeInteger(input.maxResponseBytes)||input.maxResponseBytes<0)throw new RelayProtocolError("FEEDBACK_RELAY_RESPONSE_LIMIT_INVALID","Response byte limit is invalid");
    const deadlines={...DEFAULT_DEADLINES,...input.deadlines};validateDeadlines(deadlines);const bufferBody=Buffer.isBuffer(input.body)?input.body:undefined;const streamBody=bufferBody?undefined:input.body as AsyncIterable<Uint8Array>|undefined;const contentLength=input.contentLength??bufferBody?.length;if(contentLength===undefined||!Number.isSafeInteger(contentLength)||contentLength<0)throw new RelayProtocolError("FEEDBACK_RELAY_CONTENT_LENGTH_REQUIRED","Exact content length is required");
    return await new Promise<TransportResponse>((resolve,reject)=>{let settled=false,response:IncomingMessage|undefined,idleTimer:NodeJS.Timeout|undefined,request:ReturnType<typeof https.request>;const timers=new Set<NodeJS.Timeout>();const timer=(ms:number,code:string)=>{const value=setTimeout(()=>fail(new RelayProtocolError(code,"Feedback relay transport deadline exceeded")),ms);timers.add(value);return value;};const cleanup=()=>{for(const value of timers)clearTimeout(value);if(idleTimer)clearTimeout(idleTimer);input.signal?.removeEventListener("abort",abort);};const fail=(error:unknown)=>{if(settled)return;settled=true;cleanup();response?.destroy();request?.destroy();reject(error instanceof RelayProtocolError?error:new RelayProtocolError("FEEDBACK_RELAY_TRANSPORT_FAILED","Feedback relay transport failed"));};const abort=()=>fail(new RelayProtocolError("FEEDBACK_RELAY_ABORTED","Feedback relay request was aborted"));if(input.signal?.aborted){reject(new RelayProtocolError("FEEDBACK_RELAY_ABORTED","Feedback relay request was aborted"));return;}input.signal?.addEventListener("abort",abort,{once:true});
      timer(deadlines.totalMs,"FEEDBACK_RELAY_TOTAL_TIMEOUT");const connect=timer(deadlines.connectMs,"FEEDBACK_RELAY_CONNECT_TIMEOUT"),requestWrite=timer(deadlines.requestWriteMs,"FEEDBACK_RELAY_REQUEST_WRITE_TIMEOUT");let headers:NodeJS.Timeout|undefined;const connected=()=>clearTimeout(connect);request=this.requestFactory(url,{method:input.method,headers:{...input.headers,"content-length":String(contentLength)},rejectUnauthorized:true,ca:this.ca,agent:this.agent,checkServerIdentity:(host,cert)=>pinnedServerIdentity(host,cert,this.pins)},incoming=>{response=incoming;if(headers)clearTimeout(headers);if(incoming.statusCode&&incoming.statusCode>=300&&incoming.statusCode<400){fail(new RelayProtocolError("FEEDBACK_RELAY_REDIRECT_DENIED","Feedback relay redirects are forbidden"));incoming.resume();return;}const chunks:Buffer[]=[];let count=0;const resetIdle=()=>{if(idleTimer)clearTimeout(idleTimer);idleTimer=setTimeout(()=>fail(new RelayProtocolError("FEEDBACK_RELAY_IDLE_TIMEOUT","Feedback relay response became idle")),deadlines.idleMs);};resetIdle();incoming.on("data",chunk=>{resetIdle();const bytes=Buffer.from(chunk);count+=bytes.length;if(count>input.maxResponseBytes){fail(new RelayProtocolError("FEEDBACK_RELAY_RESPONSE_TOO_LARGE","Feedback relay response exceeded its byte limit"));return;}chunks.push(bytes);});incoming.on("error",fail);incoming.on("end",()=>{if(settled)return;const body=Buffer.concat(chunks);const digest=sha256(body);if(input.expectedResponseSha256&&digest!==input.expectedResponseSha256){fail(new RelayProtocolError("FEEDBACK_RELAY_RESPONSE_HASH_MISMATCH","Feedback relay response hash did not match"));return;}settled=true;cleanup();resolve({status:incoming.statusCode??0,headers:incoming.headers,body,sha256:digest});});});request.on("socket",socket=>{const secure=socket as tls.TLSSocket;if(secure.connecting)secure.once("secureConnect",connected);else connected();});request.on("error",fail);
      void(async()=>{try{let written=0;if(bufferBody){written=bufferBody.length;if(!request.write(bufferBody))await once(request,"drain");}else if(streamBody){for await(const chunk of streamBody){if(input.signal?.aborted)throw new RelayProtocolError("FEEDBACK_RELAY_ABORTED","Feedback relay request was aborted");written+=chunk.byteLength;if(written>contentLength)throw new RelayProtocolError("FEEDBACK_RELAY_REQUEST_BYTES_MISMATCH","Request exceeded declared content length");if(!request.write(chunk))await once(request,"drain");}}if(written!==contentLength)throw new RelayProtocolError("FEEDBACK_RELAY_REQUEST_BYTES_MISMATCH","Request did not match declared content length");request.end();clearTimeout(requestWrite);headers=timer(deadlines.headersMs,"FEEDBACK_RELAY_HEADERS_TIMEOUT");}catch(error){fail(error);}})();
    });
  }
}
