import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { FolderWizardRequestLifetime } from "./folder-wizard-request-lifetime";
const lifetime = new FolderWizardRequestLifetime();
const first = lifetime.begin();
assert.equal(first(), true);
const second = lifetime.begin();
assert.equal(first(), false);
assert.equal(second(), true);
lifetime.invalidate();
assert.equal(second(), false);
const third = lifetime.begin();
assert.equal(first(), false);
assert.equal(third(), true);
let complete!: () => void;
const pending = new Promise<void>((resolve) => { complete = resolve; });
const applies = lifetime.begin();
let updates = 0;
const delayed = pending.then(() => { if (applies()) updates += 1; });
lifetime.invalidate();
complete(); await delayed;
assert.equal(updates, 0);
// Structural binding checks supplement the helper behavior; these are not browser acceptance.
const importer = readFileSync(new URL("./FolderWizardImportPanel.tsx", import.meta.url), "utf8");
assert.match(importer, /revision === scopeRevision.current/);
assert.match(importer, /const text = await file.text\(\);\s+if \(!active\(\)\) return/);
assert.match(importer, /await refreshAfterConfirmedFolderWizardMutation\(\(\) => reload\(\)\);\s+if \(!active\(\)\) return/);
assert.match(importer, /if \(saveInFlight.current \|\| !token \|\| !sourceText\) return/);
console.log("Folder Wizard async request invalidation: PASS");
const routing = readFileSync(new URL("./FolderWizardRoutingPanel.tsx", import.meta.url), "utf8");
assert.match(routing, /if \(!active\(\)\) return;\s+setLoaded\(data\)/);
assert.match(routing, /if \(!canEdit \|\| inFlight.current\) return/);
assert.match(routing, /<fieldset disabled=\{busy\}/);
assert.match(routing, /return \(\) => \{ lifetime.current.invalidate\(\); \}/);
assert.match(routing, /await onChanged\(\);/);
assert.match(importer, /setRoutingRevision\(\(value\) => value \+ 1\); setReadiness\(null\); await reload\(\);/);
assert.match(importer, /FolderWizardPublishPanel key=\{`\$\{projectId\}:\$\{current.sha256\}:\$\{routingRevision\}`\}/);
