import { useState } from "react";
import { ExternalLink, RefreshCw } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { useAuthStore } from "@/store/auth";

const API = "/api/v1";

export interface MeetingClashLink {
  id: number; clashId: number; clashReportId: number; number?: string | null; description?: string | null;
  floor?: string | null; discipline?: string | null; responsible?: string | null; group?: string | null;
  status: string; deadline?: string | null; meetingNotes?: string | null;
  linkState: "active" | "removed_by_user" | "source_closed_or_excluded";
}

interface SyncSummary { reviewed: number; added: number; updated: number; unchanged: number; sourceExcluded: number; userExcluded: number; failures: number; open: number; followUp: number; }
const label = (value?: string | null) => value ? value.replace(/[_-]+/g, " ").replace(/\b\w/g, character => character.toUpperCase()) : "—";

export function MeetingClashesPanel({ projectId, meetingId, links, canWrite, reload }: { projectId: number; meetingId: number; links: MeetingClashLink[]; canWrite: boolean; reload: () => Promise<void> }) {
  const { lang } = useI18n(); const { token } = useAuthStore(); const t = (en: string, es: string) => lang === "es" ? es : en;
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [floor, setFloor] = useState("all"), [responsible, setResponsible] = useState("all"), [discipline, setDiscipline] = useState("all"), [group, setGroup] = useState("all"), [status, setStatus] = useState("all");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };
  const active = links.filter(link => link.linkState === "active"), history = links.filter(link => link.linkState !== "active");
  const values = (key: "floor" | "responsible" | "discipline" | "group" | "status") => [...new Set(active.map(link => link[key]).filter(Boolean) as string[])].sort((a, b) => a.localeCompare(b));
  const visible = active.filter(link => (floor === "all" || link.floor === floor) && (responsible === "all" || link.responsible === responsible) && (discipline === "all" || link.discipline === discipline) && (group === "all" || link.group === group) && (status === "all" || link.status === status));
  const summaryText = (s: SyncSummary) => lang === "es" ? `${s.reviewed} revisados: ${s.added} nuevos, ${s.updated} actualizados, ${s.unchanged} sin cambios, ${s.sourceExcluded} cerrados/excluidos, ${s.userExcluded} exclusiones del usuario conservadas, ${s.failures} fallos. ${s.open} Abiertos y ${s.followUp} de Seguimiento.` : `${s.reviewed} reviewed: ${s.added} new, ${s.updated} updated, ${s.unchanged} unchanged, ${s.sourceExcluded} closed/excluded, ${s.userExcluded} user exclusions preserved, ${s.failures} failures. ${s.open} Open and ${s.followUp} Follow Up.`;
  const sync = async (mode: "load" | "refresh") => { setBusy(true); setError(""); setMessage(""); try { const response = await fetch(`${API}/projects/${projectId}/meetings/${meetingId}/clashes/${mode}`, { method: "POST", headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(); setMessage(summaryText(body.summary)); await reload(); } catch { setError(t("Could not update Meeting clashes. Retry.", "No se pudieron actualizar los Clashes de la reunión. Reintentar.")); } finally { setBusy(false); } };
  const update = async (link: MeetingClashLink, body: object) => { setError(""); const response = await fetch(`${API}/projects/${projectId}/meetings/${meetingId}/clashes/${link.clashId}`, { method: "PATCH", headers, body: JSON.stringify(body) }); if (!response.ok) { setError(t("The Meeting link could not be changed.", "No se pudo cambiar el enlace de la reunión.")); return; } await reload(); };
  const openOriginal = async (link: MeetingClashLink) => { setError(""); const response = await fetch(`${API}/projects/${projectId}/clashes/${link.clashId}`, { headers }); if (!response.ok) { setError(t("The original Clash is deleted or no longer accessible.", "El Clash original fue eliminado o ya no es accesible.")); return; } const original = await response.json(); window.location.assign(`/projects/${projectId}/clash-reports?report=${original.reportId}&clash=${original.id}`); };
  const filters = [[t("All floors / areas", "Todos los pisos / áreas"), floor, setFloor, values("floor")], [t("All responsible parties", "Todos los responsables"), responsible, setResponsible, values("responsible")], [t("All disciplines / trades", "Todas las disciplinas / oficios"), discipline, setDiscipline, values("discipline")], [t("All clash groups", "Todos los grupos de Clashes"), group, setGroup, values("group")], [t("All statuses", "Todos los estados"), status, setStatus, values("status")]] as const;
  return <div style={{ flexBasis: "100%", border: "1px solid #BFDBFE", borderRadius: 9, padding: 12, minWidth: 0 }}>
    <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}><strong style={{ marginRight: "auto" }}>{t("Canonical Clash Log", "Registro canónico de Clashes")}</strong>{canWrite && <button className="btn btn-sm btn-outline" disabled={busy} onClick={() => void sync("load")}>{t("Load Open & Follow-Up Clashes", "Cargar Clashes Abiertos y de Seguimiento")}</button>}{canWrite && <button className="btn btn-sm btn-outline" disabled={busy} onClick={() => void sync("refresh")}><RefreshCw size={12} style={{ marginRight: 4 }} />{t("Refresh Clashes", "Actualizar Clashes")}</button>}</div>
    {message && <div role="status" style={{ marginTop: 9, padding: 8, background: "#EFF6FF", color: "#1E40AF", borderRadius: 6, fontSize: 12 }}>{message}</div>}{error && <div role="alert" style={{ marginTop: 9, color: "#B91C1C", fontSize: 12 }}>{error}</div>}
    {active.length > 0 && <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(min(160px,100%),1fr))", gap: 7, marginTop: 10 }}>{filters.map(([name, value, setter, options]) => <select key={name} aria-label={name} value={value} onChange={event => setter(event.target.value)} style={{ minWidth: 0, width: "100%", padding: 7, border: "1px solid #D1D5DB", borderRadius: 6 }}><option value="all">{name}</option>{options.map(option => <option key={option} value={option}>{label(option)}</option>)}</select>)}</div>}
    {!busy && active.length === 0 && <div style={{ color: "#6B7280", fontSize: 12, marginTop: 10 }}>{t("No active linked Clashes. Load the current Open and Follow Up Clash Log.", "No hay Clashes enlazados activos. Cargue el Registro actual de Clashes Abiertos y de Seguimiento.")}</div>}{active.length > 0 && visible.length === 0 && <div style={{ color: "#6B7280", fontSize: 12, padding: 16, textAlign: "center" }}>{t("No active Clashes match all selected filters.", "Ningún Clash activo coincide con todos los filtros seleccionados.")}</div>}
    <div style={{ display: "grid", gap: 8, marginTop: 10 }}>{visible.map(link => <div key={link.clashId} style={{ border: "1px solid #E5E7EB", borderRadius: 7, padding: 9, minWidth: 0 }}><div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}><strong>{link.number || `Clash ${link.clashId}`}</strong><span style={{ fontSize: 11, background: "#F3F4F6", padding: "2px 6px", borderRadius: 10 }}>{label(link.status)}</span><span style={{ flex: "1 1 100%", overflowWrap: "anywhere" }}>{link.description || t("No description", "Sin descripción")}</span><div style={{ color: "#6B7280", fontSize: 11, flex: "1 1 100%" }}>{[link.floor, link.discipline, link.responsible, link.group, link.deadline ? new Date(link.deadline).toLocaleDateString() : null].filter(Boolean).join(" · ")}</div><button className="btn btn-sm btn-outline" onClick={() => void openOriginal(link)}><ExternalLink size={12} style={{ marginRight: 4 }} />{t("Open Original Clash", "Abrir Clash original")}</button>{canWrite && <button className="btn btn-sm btn-outline" onClick={() => void update(link, { action: "remove" })}>{t("Remove from Meeting", "Quitar de la reunión")}</button>}</div><textarea defaultValue={link.meetingNotes || ""} disabled={!canWrite} onBlur={event => { if (event.target.value !== (link.meetingNotes || "")) void update(link, { meeting_notes: event.target.value }); }} placeholder={t("Meeting notes / agreements", "Notas / acuerdos de la reunión")} style={{ width: "100%", marginTop: 8, minHeight: 48, resize: "vertical", boxSizing: "border-box" }} /></div>)}</div>
    {history.length > 0 && <details style={{ marginTop: 10 }}><summary style={{ cursor: "pointer", fontSize: 12, fontWeight: 700 }}>{t(`Removed / excluded history (${history.length})`, `Historial eliminado / excluido (${history.length})`)}</summary><div style={{ display: "grid", gap: 6, marginTop: 7 }}>{history.map(link => <div key={link.clashId} style={{ padding: 8, border: "1px dashed #D1D5DB", borderRadius: 6, fontSize: 12 }}><strong>{link.number || `Clash ${link.clashId}`}</strong> · {link.description || "—"} · {label(link.linkState)} {canWrite && link.linkState === "removed_by_user" && <button className="btn btn-sm btn-outline" onClick={() => void update(link, { action: "restore" })} style={{ marginLeft: 8 }}>{t("Restore to Meeting", "Restaurar a la reunión")}</button>}</div>)}</div></details>}
  </div>;
}
