import{useEffect,useState}from"react";import{sharePointConnectionHealth,type SharePointConnectionHealth}from"./sharepoint-connection-health";import{readFolderWizardDestination}from"./folder-wizard-destination-response";
export function SharePointEnrollmentStatus({projectId,token,lang}:{projectId:number;token:string|null;lang:string}){
 const tr=(en:string,es:string)=>lang==="es"?es:en;const[state,setState]=useState<SharePointConnectionHealth>("temporarily_unavailable");const[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);if(!token){setState("temporarily_unavailable");setLoading(false);return()=>controller.abort();}
  void Promise.all([fetch(`/api/v1/projects/${projectId}/coordination-hub/credential-lifecycle`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}),fetch(`/api/v1/projects/${projectId}/integrations/folder-wizard/destination`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal})]).then(async([lifecycleResponse,destinationResponse])=>{
   if(lifecycleResponse.status===403){setState("administrator_required");return;}if(!lifecycleResponse.ok||!destinationResponse.ok){setState("temporarily_unavailable");return;}
   const lifecycle=await lifecycleResponse.json() as{credentials?:Array<{state?:string}>};const destination=readFolderWizardDestination(await destinationResponse.json());setState(sharePointConnectionHealth({httpStatus:200,credentialStates:(lifecycle.credentials??[]).map(item=>String(item.state??"")),destinationState:destination.current?.state??null,providerUnavailable:false}));
  }).catch(error=>{if((error as Error).name!=="AbortError")setState("temporarily_unavailable");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[projectId,token]);
 const labels:Record<SharePointConnectionHealth,[string,string]>={connected:["Connected — selected site and destination are ready","Conectado — el sitio seleccionado y el destino están listos"],setup_incomplete:["Setup incomplete — resume the administrator steps","Configuración incompleta — reanude los pasos de administrador"],disconnected:["Disconnected — publishing remains unavailable","Desconectado — la publicación no está disponible"],temporarily_unavailable:["Connection health unavailable — no publishing is enabled","Estado de conexión no disponible — no se habilita la publicación"],administrator_required:["A project administrator can view and resume Microsoft setup","Un administrador del proyecto puede ver y reanudar la configuración de Microsoft"]};
 return <section aria-label={tr("SharePoint connection health","Estado de conexión SharePoint")}><h3>{tr("SharePoint connection","Conexión SharePoint")}</h3><p role="status">{loading?tr("Checking connection…","Comprobando conexión…"):labels[state][lang==="es"?1:0]}</p><p>{tr("Microsoft consent is completed by an authorized Microsoft administrator. Ordinary users never handle tokens or Entra configuration.","El consentimiento de Microsoft lo completa un administrador autorizado de Microsoft. Los usuarios normales nunca manejan tokens ni configuración de Entra.")}</p></section>;
}
