import React from "react";
import type { LensNextKnowledgeContext } from "./lens-next-types";

type KnowledgeDetail={kind:"conflict"}|{kind:"rule";id:string}|{kind:"method";id:string}|{kind:"cases"}|null;
const readDetail=():KnowledgeDetail=>{if(typeof window==="undefined")return null;const url=new URL(window.location.href),kind=url.searchParams.get("lensKnowledge"),id=url.searchParams.get("lensKnowledgeId");return kind==="conflict"?{kind}:kind==="cases"?{kind}:kind==="rule"&&id?{kind,id}:kind==="method"&&id?{kind,id}:null;};

export function LensNextKnowledgePanel({context,error,onRetry,onClassify,activeIssueKey}:{context:LensNextKnowledgeContext|"loading"|null;error:string|null;onRetry():void;onClassify?(revisionId:string|null,expected:string|null):void;activeIssueKey:string}) {
  const [expanded,setExpanded]=React.useState(true);
  const [suggestionsVisible,setSuggestionsVisible]=React.useState(true);
  const [detail,setDetail]=React.useState<KnowledgeDetail>(()=>readDetail());
  React.useEffect(()=>{setDetail(null);setSuggestionsVisible(true);},[activeIssueKey]);
  React.useEffect(()=>{const onPop=()=>setDetail(readDetail());window.addEventListener("popstate",onPop);return()=>window.removeEventListener("popstate",onPop);},[]);
  const navigate=(next:Exclude<KnowledgeDetail,null>)=>{const url=new URL(window.location.href);url.searchParams.set("lensKnowledge",next.kind);if("id" in next)url.searchParams.set("lensKnowledgeId",next.id);else url.searchParams.delete("lensKnowledgeId");window.history.pushState({lensKnowledge:true,activeIssueKey},"",url);setDetail(next);};
  const returnToIssue=()=>{const url=new URL(window.location.href);url.searchParams.delete("lensKnowledge");url.searchParams.delete("lensKnowledgeId");window.history.pushState({lensKnowledge:false,activeIssueKey},"",url);setDetail(null);};
  if(context&&context!=="loading"&&detail){const rule=detail.kind==="rule"?context.rules.find(item=>item.revisionId===detail.id):null,method=detail.kind==="method"?context.methods.find(item=>item.revisionId===detail.id):null;return <section className="lens-next-knowledge" aria-label="Coordination Knowledge detail"><header><div><strong>Coordination Knowledge</strong><small>Lens issue {activeIssueKey} remains active.</small></div><button type="button" onClick={returnToIssue}>Return to active issue</button></header><div className="lens-next-knowledge__body">{detail.kind==="conflict"&&context.conflictType&&<article><h3>{context.conflictType.name}</h3><p>{context.conflictType.description}</p><dl><div><dt>Code</dt><dd>{context.conflictType.code}</dd></div><div><dt>Disciplines</dt><dd>{context.conflictType.disciplineA} / {context.conflictType.disciplineB}</dd></div><div><dt>Elements</dt><dd>{context.conflictType.elementTypeA} / {context.conflictType.elementTypeB}</dd></div><div><dt>Category</dt><dd>{context.conflictType.category}</dd></div><div><dt>Approved revision</dt><dd>{context.conflictType.revision}</dd></div></dl></article>}{rule&&<article><h3>{rule.title}</h3><p>{rule.guidance}</p><p>{rule.code} · approved revision {rule.revision}</p></article>}{method&&<article><h3>{method.name}</h3><p>{method.description}</p><p>Responsible trade: {method.responsibleTrade??"Not specified"}</p><p>RFI: {method.rfiRequirement}</p><p>Approvals: {method.requiredApprovals.join(", ")||"None recorded"}</p><p>Constraints: {method.constraints.join("; ")||"None recorded"}</p></article>}{detail.kind==="cases"&&<article><h3>Similar BIMLog Cases</h3>{context.previousCases.map(item=><section key={item.id}><strong>{item.projectName} · {item.location??"Location not recorded"}</strong><p>{item.actualResolution}</p><p>Why similar: {item.similarityReasons.join("; ")}</p></section>)}</article>}</div></section>;}
  return <section className="lens-next-knowledge" aria-label="Coordination Knowledge"><header><div><strong>Coordination Knowledge</strong><small>Approved guidance and permitted precedent for this exact issue.</small></div><button type="button" onClick={()=>setExpanded(value=>!value)} aria-expanded={expanded}>{expanded?"Collapse":"Expand"}</button></header>{expanded&&<div className="lens-next-knowledge__body">
    {context==="loading"&&<p role="status">Loading approved coordination knowledge…</p>}{error&&<div role="alert"><p>{error}</p><button type="button" onClick={onRetry}>Retry</button></div>}
    {context&&context!=="loading"&&!context.conflictType&&<div className="lens-next-knowledge__empty"><strong>No conflict type classified</strong><p>Issue work remains available. Classification is optional and no guidance will be invented.</p>{suggestionsVisible&&context.classificationSuggestions.length>0&&<div><strong>Possible matches</strong><p>Based only on approved structured fields. BIMLog will never apply a match automatically.</p>{context.classificationSuggestions.map(item=><div key={item.conflictType.revisionId}><span>{item.conflictType.code} · {item.conflictType.name}</span><small>{item.reasons.join("; ")} · Source: {item.matchingSource}</small>{context.canClassify&&<button type="button" onClick={()=>onClassify?.(item.conflictType.revisionId,null)}>Use this classification</button>}</div>)}<button type="button" onClick={()=>setSuggestionsVisible(false)}>Reject suggestions</button></div>}{context.canClassify&&<label>Optional classification<select value="" onChange={event=>{if(event.target.value)onClassify?.(event.target.value,null);}}><option value="">Select an approved Conflict Type</option>{context.availableConflictTypes.map(item=><option key={item.revisionId} value={item.revisionId}>{item.code} · {item.name}</option>)}</select></label>}</div>}
    {context&&context!=="loading"&&context.conflictType&&<div className="lens-next-knowledge__conflict"><div className="lens-next-knowledge__eyebrow"><span>Conflict Type · {context.conflictType.code}</span><span className="lens-next-knowledge__approved">Approved · revision {context.conflictType.revision}</span></div><h3>{context.conflictType.name}</h3><p>{context.conflictType.disciplineA} / {context.conflictType.disciplineB} · {context.conflictType.elementTypeA} vs {context.conflictType.elementTypeB}</p><p>{context.conflictType.category}</p><p>{context.conflictType.description}</p><div className="lens-next-knowledge__links"><button type="button" onClick={()=>navigate({kind:"conflict"})}>View Full Conflict Type</button>{context.canClassify?<label>Change classification<select value={context.conflictType.revisionId} onChange={event=>onClassify?.(event.target.value||null,context.conflictType?.revisionId??null)}><option value="">Remove classification</option>{context.availableConflictTypes.map(item=><option key={item.revisionId} value={item.revisionId}>{item.code} · {item.name}</option>)}</select></label>:<span title="Your project role cannot classify issues.">Classification change unavailable</span>}</div></div>}
    {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section"><h3>Key Coordination Guidance</h3>{context.rules.length?<ul>{context.rules.map(rule=><li key={rule.revisionId}><div><strong>{rule.title}</strong><small>{rule.code} · approved revision {rule.revision}</small></div><p>{rule.guidance}</p><button type="button" onClick={()=>navigate({kind:"rule",id:rule.revisionId})}>View rule details</button></li>)}</ul>:<p>No approved guidance is applicable to this classification.</p>}</section>}
    {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section"><h3>Known Resolution Methods</h3><p className="lens-next-knowledge__disclaimer">BIMLog does not select or execute a resolution.</p>{context.methods.length?<ol className="lens-next-knowledge__methods">{context.methods.map(method=><li key={method.revisionId}><details><summary><span>{method.name}</span>{method.preferred&&<em>Approved preferred</em>}</summary><div><p>{method.description}</p><button type="button" onClick={()=>navigate({kind:"method",id:method.revisionId})}>View method details</button></div></details></li>)}</ol>:<p>No approved resolution method is linked to this classification.</p>}</section>}
    {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section"><div className="lens-next-knowledge__section-title"><h3>Previous BIMLog Cases</h3><button type="button" onClick={()=>navigate({kind:"cases"})}>View Similar Cases</button></div><p className="lens-next-knowledge__disclaimer">Previous cases are permitted precedent, not an automatic recommendation.</p>{context.previousCases.length?<div className="lens-next-knowledge__case-scroll"><table><thead><tr><th>Project</th><th>Level / location</th><th>Resolution used</th><th>Why similar</th><th>RFI</th><th>Status</th></tr></thead><tbody>{context.previousCases.map(item=><tr key={item.id}><td>{item.projectName}</td><td>{item.location??"Not recorded"}</td><td>{item.actualResolution}</td><td>{item.similarityReasons.join("; ")}</td><td>{item.rfiState}</td><td>{item.status}</td></tr>)}</tbody></table></div>:<p>No permitted resolved precedent is available for this classification.</p>}</section>}
  </div>}</section>;
}
