import React from "react";
import type { LensNextKnowledgeContext } from "./lens-next-types";

export function LensNextKnowledgePanel({context,error,onRetry,onClassify}:{context:LensNextKnowledgeContext|"loading"|null;error:string|null;onRetry():void;onClassify?(revisionId:string|null,expected:string|null):void}) {
  const [expanded,setExpanded]=React.useState(true);
  const [suggestionsVisible,setSuggestionsVisible]=React.useState(true);
  return <section className="lens-next-knowledge" aria-label="Coordination Knowledge">
    <header><div><strong>Coordination Knowledge</strong><small>Approved guidance and permitted precedent for this exact issue.</small></div><button type="button" onClick={()=>setExpanded(value=>!value)} aria-expanded={expanded}>{expanded?"Collapse":"Expand"}</button></header>
    {expanded&&<div className="lens-next-knowledge__body">
      {context==="loading"&&<p role="status">Loading approved coordination knowledge…</p>}
      {error&&<div role="alert"><p>{error}</p><button type="button" onClick={onRetry}>Retry</button></div>}
      {context&&context!=="loading"&&!context.conflictType&&<div className="lens-next-knowledge__empty"><strong>No conflict type classified</strong><p>Issue work remains available. Classification is optional and no guidance will be invented.</p>{suggestionsVisible&&context.classificationSuggestions.length>0&&<div><strong>Possible matches</strong><p>Based only on approved structured fields. BIMLog will never apply a match automatically.</p>{context.classificationSuggestions.map(item=><div key={item.conflictType.revisionId}><span>{item.conflictType.code} · {item.conflictType.name}</span><small>{item.reasons.join("; ")} · Source: {item.matchingSource}</small>{context.canClassify&&<button type="button" onClick={()=>onClassify?.(item.conflictType.revisionId,null)}>Use this classification</button>}</div>)}<button type="button" onClick={()=>setSuggestionsVisible(false)}>Reject suggestions</button></div>}{context.canClassify&&<label>Optional classification<select value="" onChange={event=>{if(event.target.value)onClassify?.(event.target.value,null);}}><option value="">Select an approved Conflict Type</option>{context.availableConflictTypes.map(item=><option key={item.revisionId} value={item.revisionId}>{item.code} · {item.name}</option>)}</select></label>}</div>}
      {context&&context!=="loading"&&context.conflictType&&<div className="lens-next-knowledge__conflict">
        <div className="lens-next-knowledge__eyebrow"><span>Conflict Type · {context.conflictType.code}</span><span className="lens-next-knowledge__approved">Approved · revision {context.conflictType.revision}</span></div>
        <h3>{context.conflictType.name}</h3>
        <p>{context.conflictType.disciplineA} / {context.conflictType.disciplineB} · {context.conflictType.elementTypeA} vs {context.conflictType.elementTypeB}</p>
        <p>{context.conflictType.category}</p><p>{context.conflictType.description}</p>
        <div className="lens-next-knowledge__links"><a href={`/knowledge?section=conflict-types&conflictTypeId=${encodeURIComponent(context.conflictType.id)}`}>View Full Conflict Type</a>{context.canClassify?<label>Change classification<select value={context.conflictType.revisionId} onChange={event=>onClassify?.(event.target.value||null,context.conflictType?.revisionId??null)}><option value="">Remove classification</option>{context.availableConflictTypes.map(item=><option key={item.revisionId} value={item.revisionId}>{item.code} · {item.name}</option>)}</select></label>:<span title="Your project role cannot classify issues.">Classification change unavailable</span>}</div>
      </div>}
      {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section" aria-labelledby="knowledge-guidance-title"><h3 id="knowledge-guidance-title">Key Coordination Guidance</h3>{context.rules.length?<ul>{context.rules.map(rule=><li key={rule.revisionId}><div><strong>{rule.title}</strong><small>{rule.code} · approved revision {rule.revision}</small></div><p>{rule.guidance}</p></li>)}</ul>:<p className="lens-next-knowledge__empty-copy">No approved guidance is applicable to this classification. Continue issue work using project controls.</p>}</section>}
      {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section" aria-labelledby="knowledge-methods-title"><h3 id="knowledge-methods-title">Known Resolution Methods</h3><p className="lens-next-knowledge__disclaimer">Options are ordered by governed applicability. BIMLog does not select or execute a resolution.</p>{context.methods.length?<ol className="lens-next-knowledge__methods">{context.methods.map(method=><li key={method.revisionId}><details><summary><span>{method.name}</span>{method.preferred&&<em>Approved preferred</em>}</summary><div><p>{method.description}</p><dl><div><dt>Responsible trade</dt><dd>{method.responsibleTrade??"Not specified"}</dd></div><div><dt>RFI</dt><dd>{method.rfiRequirement}</dd></div><div><dt>Approvals</dt><dd>{method.requiredApprovals.length?method.requiredApprovals.join(", "):"None recorded"}</dd></div><div><dt>Constraints</dt><dd>{method.constraints.length?method.constraints.join("; "):"None recorded"}</dd></div><div><dt>Revision</dt><dd>{method.revision} (approved)</dd></div></dl><a href={`/knowledge?section=resolution-methods&methodId=${encodeURIComponent(method.id)}`}>View method details</a></div></details></li>)}</ol>:<p className="lens-next-knowledge__empty-copy">No approved resolution method is linked to this classification.</p>}</section>}
      {context&&context!=="loading"&&context.conflictType&&<section className="lens-next-knowledge__section" aria-labelledby="knowledge-cases-title"><div className="lens-next-knowledge__section-title"><h3 id="knowledge-cases-title">Previous BIMLog Cases</h3><a href={`/knowledge?section=cases&conflictTypeId=${encodeURIComponent(context.conflictType.id)}`}>View Similar Cases</a></div><p className="lens-next-knowledge__disclaimer">Previous cases are permitted precedent, not an organizational standard or an automatic recommendation.</p>{context.previousCases.length?<div className="lens-next-knowledge__case-scroll"><table><thead><tr><th>Project</th><th>Level / location</th><th>Resolution used</th><th>Why similar</th><th>RFI</th><th>Status</th></tr></thead><tbody>{context.previousCases.map(item=><tr key={item.id}><td>{item.projectName}</td><td>{item.location??"Not recorded"}</td><td>{item.actualResolution}</td><td>{item.similarityReasons.join("; ")}</td><td>{item.rfiState}</td><td>{item.status}</td></tr>)}</tbody></table></div>:<p className="lens-next-knowledge__empty-copy">No permitted resolved precedent is available for this classification.</p>}</section>}
    </div>}
  </section>;
}
