import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const css = readFileSync(new URL("./lens-next-panel.css", import.meta.url), "utf8");
const view = readFileSync(new URL("./LensNextPanelView.tsx", import.meta.url), "utf8");
const narrow = css.match(/@media \(max-width: 420px\) \{([\s\S]*?)\n\}/)?.[1] ?? "";
assert.match(narrow, /overflow-x:\s*hidden/);
assert.match(narrow, /min-height:\s*44px/);
assert.match(narrow, /grid-template-columns:\s*minmax\(0, 1fr\)/);
assert.match(narrow, /overflow-x:\s*auto/);
assert.match(narrow, /lens-next__sync-recovery/);
assert.match(css, /:focus-visible/);
assert.match(css, /prefers-reduced-motion:reduce/);
assert.match(view, /Skip to issues/);
assert.match(view, /aria-describedby="lens-next-sync-readiness"/);
assert.match(view, /aria-atomic="true"/);
assert.match(view, /const IssueCard = React\.memo/);
assert.match(view, /const IssueTable = React\.memo/);
assert.match(css, /content-visibility:auto/);
assert.match(css, /contain-intrinsic-block-size:72px/);
console.log("Lens Next exact-390 responsive contract: PASS");
