import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const shell = readFileSync(new URL("../../../lens-next-acceptance-mobile.html", import.meta.url), "utf8");
const productionHtml = readFileSync(new URL("../../../index.html", import.meta.url), "utf8");
const css = readFileSync(new URL("./lens-next-panel.css", import.meta.url), "utf8");
const view = readFileSync(new URL("./LensNextPanelView.tsx", import.meta.url), "utf8");
const evidence = JSON.parse(readFileSync(new URL("../../../evidence/lens-next-build33-exact-390-acceptance.json", import.meta.url), "utf8"));
assert.match(shell, /width:\s*390px/);
assert.match(shell, /height:\s*844px/);
assert.match(shell, /src="\/lens-next-acceptance-harness\.html\?acceptanceMobile=390"/);
assert.match(shell, /lens-next-mobile-acceptance/);
assert.doesNotMatch(productionHtml, /lens-next-acceptance-mobile/);
assert.match(css, /@media \(max-width: 420px\)/);
assert.match(css, /\.lens-next \{ width: 100%; min-width: 0; overflow-x: hidden; \}/);
assert.match(css, /\.lens-next__header button[\s\S]*width: 100%/);
assert.match(css, /\.lens-next__filters,[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(css, /:has\(> \.lens-next__details:not\(\.lens-next__details--empty\)\) > \.lens-next__browser[\s\S]*display:\s*none/);
assert.match(css, /\.lens-next__browser,[\s\S]*\.lens-next__body > \.lens-next__details[\s\S]*max-height:\s*none/);
assert.match(css, /\.lens-next__details > header \{ order: 1; \}/);
assert.match(css, /\.lens-next__details > \.lens-next__actions \{ order: 2; \}/);
assert.match(css, /\.lens-next__details > \.lens-next__detail-section \{ order: 3; \}/);
assert.match(view, /matchMedia\("\(max-width: 760px\)"\)/);
assert.match(view, /selectedIssueRef\.current\?\.scrollIntoView\(\{ block: "start", behavior: "auto" \}\)/);
assert.equal(evidence.checks.viewportWidth, 390);
assert.equal(evidence.checks.horizontalOverflow, false);
assert.equal(evidence.checks.issueBrowserHiddenWhileDetailSelected, true);
assert.ok(evidence.checks.detailHeaderTop - evidence.checks.detailsTop < 20);
assert.deepEqual(evidence.checks.spanishActions, ["Abrir vista de trabajo", "Ver historial", "Vincular elemento BIMLog"]);
console.log("BUILD33_EXACT_390_CONTRACT=PASS fixture_viewport=390x844 production_component=true");
