import assert from "node:assert/strict";
import { filterLensNextIssues } from "./lens-next-model";
import { LENS_NEXT_DEFAULT_FILTERS, type LensNextIssue } from "./lens-next-types";
const issue={identity:{serverId:7,projectId:1,viewpointId:"VIEW-Á01",revisionNumber:1,lifecycleStatus:"active",supersedesId:null},displayId:"CL-007",note:"Duct conflict",openItems:null,trade:"HVAC",floor:"Level 02",responsibleCompany:"BIMTech",reportType:"Coordination",status:"open",priority:1,capturedAt:"2026-09-16T14:00:00Z",screenshotUrl:"/api/v1/images/7"} as unknown as LensNextIssue;
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,search:"duct hvac level 02"}).length,1);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,search:"view a01"}).length,1);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,search:"duct plumbing"}).length,0);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,responsibleCompany:"BIMTech",reportType:"Coordination",capturedFrom:"2026-09-16",capturedTo:"2026-09-16",screenshot:"captured"}).length,1);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,responsibleCompany:"Other"}).length,0);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,reportType:"Shop Drawing"}).length,0);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,capturedFrom:"2026-09-17"}).length,0);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,capturedTo:"2026-09-15"}).length,0);
assert.equal(filterLensNextIssues([issue],{...LENS_NEXT_DEFAULT_FILTERS,screenshot:"missing"}).length,0);
const missing={...issue,identity:{...issue.identity,serverId:8},capturedAt:null,screenshotUrl:null};
assert.equal(filterLensNextIssues([missing],{...LENS_NEXT_DEFAULT_FILTERS,screenshot:"missing"}).length,1);
assert.equal(filterLensNextIssues([missing],{...LENS_NEXT_DEFAULT_FILTERS,capturedFrom:"2026-09-01"}).length,0);
assert.equal(filterLensNextIssues([issue,missing],{...LENS_NEXT_DEFAULT_FILTERS,search:"duct",screenshot:"captured"}).length,1);
console.log("Lens Next discovery search: PASS");
