import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const view = readFileSync(new URL("./LensNextPanelView.tsx", import.meta.url), "utf8");
const panel = readFileSync(new URL("./LensNextPanel.tsx", import.meta.url), "utf8");
const client = readFileSync(new URL("./lens-next-client.ts", import.meta.url), "utf8");
const model = readFileSync(new URL("./lens-next-model.ts", import.meta.url), "utf8");
const styles = readFileSync(new URL("./lens-next-panel.css", import.meta.url), "utf8");
const checks: string[] = [];
const check = (condition: unknown, label: string) => { assert.ok(condition, label); checks.push(label); };

check(view.includes("BIMLog · Controlled publishing"), "truthful M8 workspace label");
check(view.includes('{filteredIssues.length === 1 ? "issue" : "issues"}') && view.includes('{synchronizationPlan.items.length === 1 ? "item" : "items"}'), "issue and synchronization-plan counts use correct singular grammar");
check(!view.includes("<h2>Lens Next"), "redundant Lens Next version heading is absent from the embedded workspace");
check(!view.includes("v1.0.08-Pro · M8"), "obsolete internal milestone is absent from the customer-facing workspace");
check(view.includes("Your current project role is read-only"), "read-only role has fail-closed explanation");
check(view.includes("Review publication") && view.includes("Confirm publish") && view.includes("Cancel"), "explicit review and confirmation step");
check(view.includes("immutable BIMLog audit receipt"), "confirmation explains immutable audit consequence");
check(view.includes('type: "status"') && view.includes('type: "comment"') && view.includes('type: "assignment"'), "only three controlled actions are exposed");
check(panel.includes("publishAttempt") && panel.includes("idempotencyKey"), "retry retains actor-scoped idempotency identity");
check(panel.includes("mutationVersion: result.issue.mutationVersion"), "verified server version replaces local version");
check(client.includes('contractVersion: "lens-next-publish.v1"'), "client pins exact publishing contract");
check(client.includes('method: "POST"') && client.includes("Authorization: `Bearer ${token}`"), "authenticated POST transport");
check(model.includes("publishing.allowed === true"), "server capability controls publisher visibility");
check(model.includes("mutationVersion"), "pull adapter retains concurrency version");
check(styles.includes(".lens-next-workspace--embedded {") && styles.includes("overflow: hidden"), "embedded viewport stays fixed beneath native window chrome");
check(styles.includes("Header chrome stays visible") && styles.includes("scroll independently"), "two-pane scrollbar ownership is explicit");
check(styles.includes(".lens-next-workspace--embedded .lens-next__browser,") && styles.includes("overflow-y: auto"), "issue browser and selected details scroll independently");
check(styles.includes("grid-template-columns: clamp(380px, 42vw, 520px) minmax(360px, 1fr)"), "embedded workspace keeps stable readable list and detail columns");
check(styles.includes("@media (max-width: 760px)") && styles.includes("grid-template-columns: minmax(0, 1fr)"), "narrow embedded windows stack without compressed controls");
check(styles.includes(".lens-next h2 small") && styles.includes("font-size: 0.6em"), "customer-facing version is visually subordinate");
console.log(JSON.stringify({ status: "PASS", checks: checks.length, details: checks }));
