import assert from "node:assert/strict";
import fs from "node:fs";
const view=fs.readFileSync(new URL("./LensNextPanelView.tsx",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("./lens-next-panel.css",import.meta.url),"utf8");
const panel=fs.readFileSync(new URL("./LensNextPanel.tsx",import.meta.url),"utf8");
assert.match(view,/lens-next__browser-grid/);
assert.match(view,/lens-next__filter-pane/);
assert.match(view,/Filter pane width/);
assert.match(view,/Issue list width/);
assert.match(view,/filtersCollapsed/);
assert.match(view,/listCollapsed/);
assert.match(view,/scrollIntoView\(\{block:"nearest",inline:"nearest"\}\)/);
assert.match(css,/grid-template-columns:\s*var\(--lens-next-filter-width/);
assert.match(css,/lens-next__filter-pane--collapsed/);
assert.match(css,/lens-next__body--list-collapsed/);
assert.match(css,/\.lens-next__list-heading\s*\{\s*display:\s*grid;/);
assert.match(css,/\.lens-next-workspace--embedded \.lens-next__browser \.lens-next__issue-list\s*\{[^}]*min-height:\s*0;/);
assert.match(css,/@media \(max-width: 760px\)[\s\S]*lens-next__browser-grid[\s\S]*flex-direction:\s*column/);
assert.doesNotMatch(view,/applyPlatformWorkingView[\s\S]{0,500}workspaceLayout/);
assert.match(panel,/findIndex\(issue=>issue\.identity\.serverId===selectedServerId\)/);
assert.match(panel,/Math\.floor\(index\/issuePageSize\)\+1/);
assert.match(view,/aria-label="Issue list pages"/);
assert.match(view,/aria-label=\{tt\("Sort issues", "Ordenar incidencias"\)\}/);
assert.match(view,/onFiltersChange\(\{\.\.\.LENS_NEXT_DEFAULT_FILTERS\}\)/);
console.log("Lens Next modern three-pane workspace: PASS");
