import { sql } from "drizzle-orm";
import { boolean, check, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { projectsTable } from "./projects";
import { companiesTable, usersTable } from "./users";

const money = (name: string) => numeric(name, { precision: 30, scale: 0 });
const utc = (name: string) => timestamp(name, { withTimezone: true });

export const companyAiAdministratorsTable = pgTable("company_ai_administrators", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), userId: integer("user_id").notNull().references(() => usersTable.id),
  status: text("status").notNull().default("active"), grantedById: integer("granted_by_id").notNull().references(() => usersTable.id), grantedAt: utc("granted_at").defaultNow().notNull(), revokedById: integer("revoked_by_id").references(() => usersTable.id), revokedAt: utc("revoked_at"), auditEvidence: jsonb("audit_evidence").notNull().default({}),
}, (t) => [uniqueIndex("company_ai_administrators_active_uidx").on(t.companyId, t.userId).where(sql`${t.status} = 'active'`), index("company_ai_administrators_user_idx").on(t.userId, t.status), check("company_ai_administrators_status_chk", sql`${t.status} in ('active','revoked')`)]);

export const providerConnectionsTable = pgTable("provider_connections", {
  id: text("id").primaryKey(), ownerType: text("owner_type").notNull(), userId: integer("user_id").references(() => usersTable.id), companyId: integer("company_id").references(() => companiesTable.id), provider: text("provider").notNull(), status: text("status").notNull().default("pending_validation"), label: text("label").notNull(), allowedModels: jsonb("allowed_models").notNull().default([]),
  secretCiphertext: text("secret_ciphertext"), secretIv: text("secret_iv"), secretTag: text("secret_tag"), wrappedDataKey: text("wrapped_data_key"), wrapIv: text("wrap_iv"), wrapTag: text("wrap_tag"), keyVersion: text("key_version").notNull(), validatedAt: utc("validated_at"), rotatedAt: utc("rotated_at"), revokedAt: utc("revoked_at"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(), updatedAt: utc("updated_at").defaultNow().notNull(),
}, (t) => [
  check("provider_connections_owner_chk", sql`(${t.ownerType}='personal' and ${t.userId} is not null and ${t.companyId} is not null) or (${t.ownerType}='company' and ${t.userId} is null and ${t.companyId} is not null) or (${t.ownerType}='system' and ${t.userId} is null and ${t.companyId} is null)`),
  check("provider_connections_provider_chk", sql`${t.provider} in ('openai','anthropic')`), check("provider_connections_status_chk", sql`${t.status} in ('pending_validation','active','disabled','revoked')`),
  uniqueIndex("provider_connections_active_personal_uidx").on(t.userId, t.provider).where(sql`${t.ownerType}='personal' and ${t.status}='active'`), uniqueIndex("provider_connections_active_company_uidx").on(t.companyId, t.provider).where(sql`${t.ownerType}='company' and ${t.status}='active'`), uniqueIndex("provider_connections_active_system_uidx").on(t.provider).where(sql`${t.ownerType}='system' and ${t.status}='active'`),
]);

export const companyAiBudgetsTable = pgTable("company_ai_budgets", {
  id: text("id").primaryKey(), fundingOwnerType: text("funding_owner_type").notNull(), companyId: integer("company_id").references(() => companiesTable.id), ownerUserId: integer("owner_user_id").references(() => usersTable.id), version: integer("version").notNull(), currency: text("currency").notNull(),
  limitMicros: money("limit_micros").notNull(), reservedMicros: money("reserved_micros").notNull().default("0"), settledMicros: money("settled_micros").notNull().default("0"), perRequestLimitMicros: money("per_request_limit_micros").notNull(), dailyLimitMicros: money("daily_limit_micros").notNull(), monthlyLimitMicros: money("monthly_limit_micros").notNull(), sessionLimitMicros: money("session_limit_micros").notNull(),
  providerAllowlist: jsonb("provider_allowlist").notNull().default([]), modelAllowlist: jsonb("model_allowlist").notNull().default([]), capabilityAllowlist: jsonb("capability_allowlist").notNull().default([]), status: text("status").notNull().default("active"), effectiveFrom: utc("effective_from").notNull(), effectiveTo: utc("effective_to"), supersedesId: text("supersedes_id"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [
  check("company_ai_budgets_owner_chk", sql`(${t.fundingOwnerType}='personal' and ${t.ownerUserId} is not null and ${t.companyId} is not null) or (${t.fundingOwnerType}='company' and ${t.ownerUserId} is null and ${t.companyId} is not null) or (${t.fundingOwnerType}='system' and ${t.ownerUserId} is null and ${t.companyId} is null)`), check("company_ai_budgets_status_chk", sql`${t.status} in ('active','disabled','superseded')`), check("company_ai_budgets_currency_chk", sql`${t.currency} ~ '^[A-Z]{3}$'`),
  uniqueIndex("company_ai_budgets_scope_version_uidx").on(t.fundingOwnerType, sql`coalesce(${t.companyId},0)`, sql`coalesce(${t.ownerUserId},0)`, t.version),
  uniqueIndex("company_ai_budgets_active_scope_uidx").on(t.fundingOwnerType, sql`coalesce(${t.companyId},0)`, sql`coalesce(${t.ownerUserId},0)`).where(sql`${t.status}='active' and ${t.effectiveTo} is null`),
  index("company_ai_budgets_effective_idx").on(t.fundingOwnerType, t.companyId, t.ownerUserId, t.status),
]);

export const userAiAllocationsTable = pgTable("user_ai_allocations", {
  id: text("id").primaryKey(), budgetId: text("budget_id").notNull().references(() => companyAiBudgetsTable.id), companyId: integer("company_id").notNull().references(() => companiesTable.id), userId: integer("user_id").notNull().references(() => usersTable.id),
  limitMicros: money("limit_micros").notNull(), reservedMicros: money("reserved_micros").notNull().default("0"), settledMicros: money("settled_micros").notNull().default("0"), dailyLimitMicros: money("daily_limit_micros").notNull(), monthlyLimitMicros: money("monthly_limit_micros").notNull(), sessionLimitMicros: money("session_limit_micros").notNull(), status: text("status").notNull().default("active"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(), updatedAt: utc("updated_at").defaultNow().notNull(),
}, (t) => [uniqueIndex("user_ai_allocations_budget_user_uidx").on(t.budgetId, t.userId), check("user_ai_allocations_status_chk", sql`${t.status} in ('active','disabled')`)]);

export const aiPriceSchedulesTable = pgTable("ai_price_schedules", {
  id: text("id").primaryKey(), version: integer("version").notNull(), provider: text("provider").notNull(), model: text("model").notNull(), currency: text("currency").notNull(), unitBasis: integer("unit_basis").notNull(), inputMicros: money("input_micros").notNull(), outputMicros: money("output_micros").notNull(), cachedInputMicros: money("cached_input_micros"), sourceUrl: text("source_url").notNull(), verifiedById: integer("verified_by_id").notNull().references(() => usersTable.id), verifiedAt: utc("verified_at").notNull(), effectiveFrom: utc("effective_from").notNull(), effectiveTo: utc("effective_to"), supersedesId: text("supersedes_id"), status: text("status").notNull().default("active"), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [
  uniqueIndex("ai_price_schedules_provider_model_version_uidx").on(t.provider, t.model, t.version),
  uniqueIndex("ai_price_schedules_active_scope_uidx").on(t.provider, t.model, t.currency).where(sql`${t.status}='active' and ${t.effectiveTo} is null`),
  check("ai_price_schedules_provider_chk", sql`${t.provider} in ('openai','anthropic')`), check("ai_price_schedules_status_chk", sql`${t.status} in ('active','superseded')`), check("ai_price_schedules_unit_chk", sql`${t.unitBasis}>0`)
]);

export const entitlementRulesTable = pgTable("entitlement_rules", {
  id: text("id").primaryKey(), version: integer("version").notNull(), companyId: integer("company_id").references(() => companiesTable.id), capability: text("capability").notNull(), fundingType: text("funding_type").notNull(), providerAllowlist: jsonb("provider_allowlist").notNull().default([]), modelAllowlist: jsonb("model_allowlist").notNull().default([]), enabled: boolean("enabled").notNull().default(true), requiresFileConfirmation: boolean("requires_file_confirmation").notNull().default(true), effectiveFrom: utc("effective_from").notNull(), effectiveTo: utc("effective_to"), supersedesId: text("supersedes_id"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [
  uniqueIndex("entitlement_rules_scope_version_uidx").on(sql`coalesce(${t.companyId},0)`, t.capability, t.fundingType, t.version),
  uniqueIndex("entitlement_rules_active_scope_uidx").on(sql`coalesce(${t.companyId},0)`, t.capability, t.fundingType).where(sql`${t.enabled}=true and ${t.effectiveTo} is null`),
  check("entitlement_rules_funding_chk", sql`${t.fundingType} in ('personal','company','system')`)
]);

export const aiRunsTable = pgTable("ai_runs", {
  id: text("id").primaryKey(), userId: integer("user_id").notNull().references(() => usersTable.id), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").references(() => projectsTable.id), sessionId: text("session_id").notNull(), capability: text("capability").notNull(), purpose: text("purpose").notNull(), provider: text("provider").notNull(), model: text("model").notNull(), connectionId: text("connection_id").notNull().references(() => providerConnectionsTable.id), creditOwnerType: text("credit_owner_type").notNull(),
  contextManifestHash: text("context_manifest_hash").notNull(), contextCategories: jsonb("context_categories").notNull(), fileManifestHash: text("file_manifest_hash"), filesWillBeTransmitted: boolean("files_will_be_transmitted").notNull().default(false), fileCount: integer("file_count").notNull().default(0), fileTypes: jsonb("file_types").notNull().default([]), fileTotalBytes: money("file_total_bytes").notNull().default("0"), pageImageEstimate: integer("page_image_estimate").notNull().default(0), transmissionScope: text("transmission_scope"), fileAdditionalInputTokensMax: integer("file_additional_input_tokens_max").notNull().default(0), fileAdditionalCostMicros: money("file_additional_cost_micros").notNull().default("0"),
  priceScheduleId: text("price_schedule_id").notNull().references(() => aiPriceSchedulesTable.id), entitlementRuleId: text("entitlement_rule_id").notNull().references(() => entitlementRulesTable.id), budgetId: text("budget_id").notNull().references(() => companyAiBudgetsTable.id), allocationId: text("allocation_id").references(() => userAiAllocationsTable.id), inputTokenMin: integer("input_token_min").notNull(), inputTokenMax: integer("input_token_max").notNull(), outputTokenMax: integer("output_token_max").notNull(), estimatedMinMicros: money("estimated_min_micros").notNull(), estimatedMaxMicros: money("estimated_max_micros").notNull(), currency: text("currency").notNull(), requestFingerprint: text("request_fingerprint").notNull(), estimateFingerprint: text("estimate_fingerprint").notNull(), estimateExpiresAt: utc("estimate_expires_at").notNull(), confirmationId: text("confirmation_id"), confirmedAt: utc("confirmed_at"), fileConfirmationId: text("file_confirmation_id"), fileConfirmedAt: utc("file_confirmed_at"), fileConfirmationExpiresAt: utc("file_confirmation_expires_at"), status: text("status").notNull().default("estimated"), idempotencyKey: text("idempotency_key").notNull(), reservedMicros: money("reserved_micros").notNull().default("0"), actualMicros: money("actual_micros"), providerRequestId: text("provider_request_id"), inputTokensActual: integer("input_tokens_actual"), outputTokensActual: integer("output_tokens_actual"), createdAt: utc("created_at").defaultNow().notNull(), updatedAt: utc("updated_at").defaultNow().notNull(),
}, (t) => [uniqueIndex("ai_runs_user_idempotency_uidx").on(t.userId, t.idempotencyKey), index("ai_runs_budget_status_idx").on(t.budgetId, t.status, t.createdAt), check("ai_runs_status_chk", sql`${t.status} in ('estimated','confirmed','file_confirmed','reserved','settled','cancelled','failed')`)]);

// The startup migration adds a database trigger that rejects UPDATE and DELETE.
export const aiUsageCostsTable = pgTable("ai_usage_costs", {
  id: text("id").primaryKey(), runId: text("run_id").notNull().references(() => aiRunsTable.id), entryType: text("entry_type").notNull(), amountMicros: money("amount_micros").notNull(), currency: text("currency").notNull(), inputTokens: integer("input_tokens"), outputTokens: integer("output_tokens"), providerRequestId: text("provider_request_id"), priceScheduleId: text("price_schedule_id").references(() => aiPriceSchedulesTable.id), correctionOfId: text("correction_of_id"), reason: text("reason"), actorUserId: integer("actor_user_id").references(() => usersTable.id), idempotencyKey: text("idempotency_key").notNull(), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [uniqueIndex("ai_usage_costs_run_entry_idempotency_uidx").on(t.runId, t.idempotencyKey), index("ai_usage_costs_run_created_idx").on(t.runId, t.createdAt), check("ai_usage_costs_entry_chk", sql`${t.entryType} in ('reservation','settlement','release','correction','failure')`)]);
