import { sql } from "drizzle-orm";
import { check, foreignKey, index, integer, jsonb, pgTable, text, timestamp, unique, uniqueIndex } from "drizzle-orm/pg-core";
import { enterpriseTradesTable } from "./enterprise-identity";
import { filesTable } from "./files";
import { projectsTable } from "./projects";
import { companiesTable, usersTable } from "./users";

const utc = (name: string) => timestamp(name, { withTimezone: true });

export const connectorCredentialsTable = pgTable("connector_credentials", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), provider: text("provider").notNull(), label: text("label").notNull(), state: text("state").notNull().default("pending_validation"),
  secretCiphertext: text("secret_ciphertext").notNull(), secretIv: text("secret_iv").notNull(), secretTag: text("secret_tag").notNull(), wrappedDataKey: text("wrapped_data_key").notNull(), wrapIv: text("wrap_iv").notNull(), wrapTag: text("wrap_tag").notNull(), keyVersion: integer("key_version").notNull(),
  createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(), rotatedAt: utc("rotated_at"), revokedAt: utc("revoked_at"),
}, (t) => [
  uniqueIndex("connector_credentials_active_scope_uq").on(t.companyId, t.provider, t.label).where(sql`${t.state}='active'`),
  check("connector_credentials_provider_chk", sql`${t.provider} ~ '^[a-z][a-z0-9_-]{1,63}$'`), check("connector_credentials_state_chk", sql`${t.state} IN ('pending_validation','active','disabled','revoked')`), check("connector_credentials_key_version_chk", sql`${t.keyVersion}>0`),
  check("connector_credentials_revocation_chk", sql`(${t.state}='revoked')=(${t.revokedAt} IS NOT NULL)`),
]);

export const connectorJobsTable = pgTable("connector_jobs", {
  id: text("id").primaryKey(), credentialId: text("credential_id").notNull().references(() => connectorCredentialsTable.id), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), provider: text("provider").notNull(), jobType: text("job_type").notNull(), state: text("state").notNull().default("queued"),
  idempotencyKey: text("idempotency_key").notNull(), requestDigest: text("request_digest").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull().default({}), attempts: integer("attempts").notNull().default(0), maxAttempts: integer("max_attempts").notNull().default(5), nextAttemptAt: utc("next_attempt_at").defaultNow().notNull(),
  leaseOwner: text("lease_owner"), leaseToken: text("lease_token"), leaseExpiresAt: utc("lease_expires_at"), fencingToken: integer("fencing_token").notNull().default(0), lastErrorCode: text("last_error_code"), replayOfJobId: text("replay_of_job_id"),
  createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(), updatedAt: utc("updated_at").defaultNow().notNull(), completedAt: utc("completed_at"), deadLetteredAt: utc("dead_lettered_at"),
}, (t) => [
  foreignKey({ columns: [t.replayOfJobId], foreignColumns: [t.id], name: "connector_jobs_replay_of_fk" }), unique("connector_jobs_id_company_project_uq").on(t.id, t.companyId, t.projectId), unique("connector_jobs_idempotency_uq").on(t.companyId, t.projectId, t.provider, t.jobType, t.idempotencyKey),
  index("connector_jobs_claim_idx").on(t.state, t.nextAttemptAt, t.leaseExpiresAt), check("connector_jobs_state_chk", sql`${t.state} IN ('queued','leased','retry','completed','dead_letter','cancelled')`), check("connector_jobs_attempts_chk", sql`${t.attempts}>=0 AND ${t.maxAttempts}>0 AND ${t.attempts}<=${t.maxAttempts}`), check("connector_jobs_digest_chk", sql`${t.requestDigest} ~ '^[a-f0-9]{64}$'`),
  check("connector_jobs_lease_chk", sql`(${t.state}='leased' AND ${t.leaseOwner} IS NOT NULL AND ${t.leaseToken} IS NOT NULL AND ${t.leaseExpiresAt} IS NOT NULL) OR (${t.state}<>'leased' AND ${t.leaseOwner} IS NULL AND ${t.leaseToken} IS NULL AND ${t.leaseExpiresAt} IS NULL)`), check("connector_jobs_terminal_chk", sql`(${t.state}='completed')=(${t.completedAt} IS NOT NULL) AND (${t.state}='dead_letter')=(${t.deadLetteredAt} IS NOT NULL)`),
]);

export const connectorJobEventsTable = pgTable("connector_job_events", {
  id: text("id").primaryKey(), jobId: text("job_id").notNull(), companyId: integer("company_id").notNull(), projectId: integer("project_id").notNull(), sequence: integer("sequence").notNull(), eventType: text("event_type").notNull(), fromState: text("from_state"), toState: text("to_state").notNull(), fencingToken: integer("fencing_token").notNull(), actorType: text("actor_type").notNull(), actorId: text("actor_id"), reasonCode: text("reason_code").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), occurredAt: utc("occurred_at").defaultNow().notNull(),
}, (t) => [foreignKey({ columns: [t.jobId, t.companyId, t.projectId], foreignColumns: [connectorJobsTable.id, connectorJobsTable.companyId, connectorJobsTable.projectId], name: "connector_job_events_job_scope_fk" }), unique("connector_job_events_job_sequence_uq").on(t.jobId, t.sequence), check("connector_job_events_sequence_chk", sql`${t.sequence}>0`), check("connector_job_events_fencing_chk", sql`${t.fencingToken}>=0`)]);

export const coordinationFilesTable = pgTable("coordination_files", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), tradeId: integer("trade_id").references(() => enterpriseTradesTable.id), category: text("category").notNull(), stableKey: text("stable_key").notNull(), state: text("state").notNull().default("active"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(), retiredAt: utc("retired_at"),
}, (t) => [unique("coordination_files_id_project_uq").on(t.id, t.projectId), unique("coordination_files_project_stable_key_uq").on(t.projectId, t.stableKey), check("coordination_files_state_chk", sql`${t.state} IN ('active','retired')`)]);

export const coordinationFileRevisionsTable = pgTable("coordination_file_revisions", {
  id: text("id").primaryKey(), coordinationFileId: text("coordination_file_id").notNull(), projectId: integer("project_id").notNull(), revisionNumber: integer("revision_number").notNull(), sourceFileId: integer("source_file_id").references(() => filesTable.id), provider: text("provider").notNull(), providerItemId: text("provider_item_id").notNull(), providerVersionId: text("provider_version_id").notNull(), contentSha256: text("content_sha256").notNull(), byteSize: integer("byte_size").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [foreignKey({ columns: [t.coordinationFileId, t.projectId], foreignColumns: [coordinationFilesTable.id, coordinationFilesTable.projectId], name: "coordination_file_revisions_file_project_fk" }), unique("coordination_file_revisions_id_file_uq").on(t.id, t.coordinationFileId), unique("coordination_file_revisions_number_uq").on(t.coordinationFileId, t.revisionNumber), unique("coordination_file_revisions_provider_version_uq").on(t.provider, t.providerItemId, t.providerVersionId), check("coordination_file_revisions_number_chk", sql`${t.revisionNumber}>0`), check("coordination_file_revisions_digest_chk", sql`${t.contentSha256} ~ '^[a-f0-9]{64}$' AND ${t.byteSize}>=0`)]);

export const coordinationFileCurrentRevisionsTable = pgTable("coordination_file_current_revisions", {
  coordinationFileId: text("coordination_file_id").primaryKey(), revisionId: text("revision_id").notNull().unique(), designatedById: integer("designated_by_id").notNull().references(() => usersTable.id), designatedAt: utc("designated_at").defaultNow().notNull(),
}, (t) => [foreignKey({ columns: [t.revisionId, t.coordinationFileId], foreignColumns: [coordinationFileRevisionsTable.id, coordinationFileRevisionsTable.coordinationFileId], name: "coordination_file_current_revision_fk" })]);

export const sharePointProjectMappingsTable = pgTable("sharepoint_project_mappings", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), credentialId: text("credential_id").notNull().references(() => connectorCredentialsTable.id), siteId: text("site_id").notNull(), libraryId: text("library_id").notNull(), state: text("state").notNull().default("active"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [unique("sharepoint_project_mappings_project_uq").on(t.projectId), unique("sharepoint_project_mappings_scope_uq").on(t.id, t.companyId, t.projectId), check("sharepoint_project_mappings_state_chk", sql`${t.state} IN ('active','disabled','mismatch')`)]);

export const sharePointFolderMappingsTable = pgTable("sharepoint_folder_mappings", {
  id: text("id").primaryKey(), projectMappingId: text("project_mapping_id").notNull(), companyId: integer("company_id").notNull(), projectId: integer("project_id").notNull(), tradeId: integer("trade_id").references(() => enterpriseTradesTable.id), category: text("category").notNull(), folderId: text("folder_id").notNull(), folderPath: text("folder_path").notNull(), state: text("state").notNull().default("active"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: utc("created_at").defaultNow().notNull(),
}, (t) => [foreignKey({ columns: [t.projectMappingId, t.companyId, t.projectId], foreignColumns: [sharePointProjectMappingsTable.id, sharePointProjectMappingsTable.companyId, sharePointProjectMappingsTable.projectId], name: "sharepoint_folder_mappings_project_scope_fk" }), unique("sharepoint_folder_mappings_category_trade_uq").on(t.projectMappingId, t.category, t.tradeId), check("sharepoint_folder_mappings_state_chk", sql`${t.state} IN ('active','disabled','mismatch')`)]);

export const sharePointSyncStatesTable = pgTable("sharepoint_sync_states", {
  id: text("id").primaryKey(), folderMappingId: text("folder_mapping_id").notNull().references(() => sharePointFolderMappingsTable.id), syncStatus: text("sync_status").notNull().default("never_synced"), cursorCiphertext: text("cursor_ciphertext"), cursorIv: text("cursor_iv"), cursorTag: text("cursor_tag"), wrappedDataKey: text("wrapped_data_key"), wrapIv: text("wrap_iv"), wrapTag: text("wrap_tag"), keyVersion: integer("key_version"), lastSyncAt: utc("last_sync_at"), mismatchCode: text("mismatch_code"), updatedAt: utc("updated_at").defaultNow().notNull(),
}, (t) => [unique("sharepoint_sync_states_folder_uq").on(t.folderMappingId), check("sharepoint_sync_states_status_chk", sql`${t.syncStatus} IN ('never_synced','queued','syncing','current','retry','mismatch','disabled')`), check("sharepoint_sync_states_cursor_envelope_chk", sql`(${t.cursorCiphertext} IS NULL AND ${t.cursorIv} IS NULL AND ${t.cursorTag} IS NULL AND ${t.wrappedDataKey} IS NULL AND ${t.wrapIv} IS NULL AND ${t.wrapTag} IS NULL AND ${t.keyVersion} IS NULL) OR (${t.cursorCiphertext} IS NOT NULL AND ${t.cursorIv} IS NOT NULL AND ${t.cursorTag} IS NOT NULL AND ${t.wrappedDataKey} IS NOT NULL AND ${t.wrapIv} IS NOT NULL AND ${t.wrapTag} IS NOT NULL AND ${t.keyVersion}>0)`), check("sharepoint_sync_states_mismatch_chk", sql`(${t.syncStatus}='mismatch')=(${t.mismatchCode} IS NOT NULL)`)]);
