import {
  boolean,
  check,
  date,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { companiesTable, usersTable } from "./users";
import { projectsTable } from "./projects";
import { filesTable } from "./files";

export const companyCostLibraryVersionsTable = pgTable(
  "company_cost_library_versions",
  {
    id: text("id").primaryKey(),
    libraryId: text("library_id").notNull(),
    companyId: integer("company_id").references(() => companiesTable.id).notNull(),
    version: integer("version").notNull(),
    effectiveDate: date("effective_date").notNull(),
    status: text("status").notNull(),
    reason: text("reason").notNull(),
    contentFingerprint: text("content_fingerprint").notNull(),
    supersedesId: text("supersedes_id"),
    createdById: integer("created_by_id").references(() => usersTable.id).notNull(),
    reviewedById: integer("reviewed_by_id").references(() => usersTable.id),
    approvedById: integer("approved_by_id").references(() => usersTable.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
  },
  (table) => [
    uniqueIndex("company_cost_library_version_uidx").on(table.libraryId, table.version),
    check("company_cost_library_status_chk", sql`${table.status} IN ('draft','submitted','under_review','approved','rejected','deprecated')`),
  ],
);

export const companyCostNodesTable = pgTable(
  "company_cost_nodes",
  {
    id: text("id").primaryKey(),
    libraryVersionId: text("library_version_id").references(() => companyCostLibraryVersionsTable.id).notNull(),
    stableNodeId: text("stable_node_id").notNull(),
    parentStableNodeId: text("parent_stable_node_id"),
    hierarchicalPath: text("hierarchical_path").notNull(),
    companyCode: text("company_code").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    active: boolean("active").default(true).notNull(),
    sortOrder: integer("sort_order").notNull(),
    wbsMapping: text("wbs_mapping"),
    csiMapping: text("csi_mapping"),
    scheduleActivityMapping: text("schedule_activity_mapping"),
    externalMappingProfileRef: text("external_mapping_profile_ref"),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"),
    deprecationReason: text("deprecation_reason"),
  },
  (table) => [uniqueIndex("company_cost_node_stable_uidx").on(table.libraryVersionId, table.stableNodeId)],
);

export const projectCostStructureVersionsTable = pgTable(
  "project_cost_structure_versions",
  {
    id: text("id").primaryKey(),
    structureId: text("structure_id").notNull(),
    projectId: integer("project_id").references(() => projectsTable.id).notNull(),
    companyId: integer("company_id").references(() => companiesTable.id).notNull(),
    libraryVersionId: text("library_version_id").references(() => companyCostLibraryVersionsTable.id).notNull(),
    version: integer("version").notNull(),
    status: text("status").notNull(),
    reason: text("reason").notNull(),
    validationFingerprint: text("validation_fingerprint").notNull(),
    contentFingerprint: text("content_fingerprint").notNull(),
    supersedesId: text("supersedes_id"),
    createdById: integer("created_by_id").references(() => usersTable.id).notNull(),
    reviewedById: integer("reviewed_by_id").references(() => usersTable.id),
    approvedById: integer("approved_by_id").references(() => usersTable.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
  },
  (table) => [
    uniqueIndex("project_cost_structure_version_uidx").on(table.structureId, table.version),
    check("project_cost_structure_status_chk", sql`${table.status} IN ('draft','submitted','under_review','approved','rejected','deprecated')`),
  ],
);

export const projectCostNodesTable = pgTable(
  "project_cost_nodes",
  {
    id: text("id").primaryKey(),
    structureVersionId: text("structure_version_id").references(() => projectCostStructureVersionsTable.id).notNull(),
    stableProjectNodeId: text("stable_project_node_id").notNull(),
    companyStableNodeId: text("company_stable_node_id").notNull(),
    companyLibraryVersionId: text("company_library_version_id").references(() => companyCostLibraryVersionsTable.id).notNull(),
    parentProjectNodeId: text("parent_project_node_id"),
    projectCode: text("project_code").notNull(),
    projectName: text("project_name").notNull(),
    description: text("description"),
    wbsMapping: text("wbs_mapping"),
    scheduleActivityRef: text("schedule_activity_ref"),
    csiMapping: text("csi_mapping"),
    active: boolean("active").default(true).notNull(),
    sortOrder: integer("sort_order").notNull(),
    effectiveFrom: date("effective_from").notNull(),
    effectiveTo: date("effective_to"),
    mappingProvenance: text("mapping_provenance").notNull(),
  },
  (table) => [uniqueIndex("project_cost_node_stable_uidx").on(table.structureVersionId, table.stableProjectNodeId)],
);

export const projectBudgetVersionsTable = pgTable(
  "project_budget_versions",
  {
    id: text("id").primaryKey(),
    budgetId: text("budget_id").notNull(),
    projectId: integer("project_id").references(() => projectsTable.id).notNull(),
    companyId: integer("company_id").references(() => companiesTable.id).notNull(),
    structureVersionId: text("structure_version_id").references(() => projectCostStructureVersionsTable.id).notNull(),
    version: integer("version").notNull(),
    currency: text("currency").notNull(),
    status: text("status").notNull(),
    purpose: text("purpose").notNull(),
    preparedById: integer("prepared_by_id").references(() => usersTable.id).notNull(),
    submittedById: integer("submitted_by_id").references(() => usersTable.id),
    reviewedById: integer("reviewed_by_id").references(() => usersTable.id),
    approvedById: integer("approved_by_id").references(() => usersTable.id),
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    outcomeReason: text("outcome_reason"),
    previousApprovedId: text("previous_approved_id"),
    contentFingerprint: text("content_fingerprint").notNull(),
    calculatedTotal: numeric("calculated_total", { precision: 30, scale: 6 }).notNull(),
    approvedSnapshotId: text("approved_snapshot_id"),
    sourceFileId: integer("source_file_id").references(() => filesTable.id),
    revision: integer("revision").default(1).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("project_budget_version_uidx").on(table.budgetId, table.version),
    check("project_budget_currency_chk", sql`${table.currency} ~ '^[A-Z]{3}$'`),
    check("project_budget_status_chk", sql`${table.status} IN ('draft','submitted','under_review','approved','returned','rejected','withdrawn','superseded','voided')`),
  ],
);

export const projectBudgetLinesTable = pgTable(
  "project_budget_lines",
  {
    id: text("id").primaryKey(),
    budgetVersionId: text("budget_version_id").references(() => projectBudgetVersionsTable.id).notNull(),
    stableLineId: text("stable_line_id").notNull(),
    projectCostNodeId: text("project_cost_node_id").references(() => projectCostNodesTable.id).notNull(),
    description: text("description").notNull(),
    amount: numeric("amount", { precision: 30, scale: 6 }).notNull(),
    quantity: numeric("quantity", { precision: 30, scale: 6 }),
    unit: text("unit"),
    unitRate: numeric("unit_rate", { precision: 30, scale: 6 }),
    notes: text("notes"),
    provenance: text("provenance"),
    sortOrder: integer("sort_order").notNull(),
  },
  (table) => [uniqueIndex("project_budget_line_stable_uidx").on(table.budgetVersionId, table.stableLineId)],
);

export const approvedBudgetSnapshotsTable = pgTable(
  "approved_budget_snapshots",
  {
    id: text("id").primaryKey(),
    budgetVersionId: text("budget_version_id").references(() => projectBudgetVersionsTable.id).notNull().unique(),
    budgetId: text("budget_id").notNull(),
    budgetVersion: integer("budget_version").notNull(),
    projectId: integer("project_id").references(() => projectsTable.id).notNull(),
    companyId: integer("company_id").references(() => companiesTable.id).notNull(),
    structureVersionId: text("structure_version_id").references(() => projectCostStructureVersionsTable.id).notNull(),
    currency: text("currency").notNull(),
    total: numeric("total", { precision: 30, scale: 6 }).notNull(),
    originalTotal: numeric("original_total", { precision: 30, scale: 6 }).notNull(),
    currentTotal: numeric("current_total", { precision: 30, scale: 6 }).notNull(),
    differenceFromOriginal: numeric("difference_from_original", { precision: 30, scale: 6 }).notNull(),
    approvedById: integer("approved_by_id").references(() => usersTable.id).notNull(),
    approvedAt: timestamp("approved_at", { withTimezone: true }).notNull(),
    approvalPolicyId: text("approval_policy_id").notNull(),
    approvalLimit: numeric("approval_limit", { precision: 30, scale: 6 }).notNull(),
    contentFingerprint: text("content_fingerprint").notNull(),
    snapshotFingerprint: text("snapshot_fingerprint").notNull().unique(),
    previousSnapshotId: text("previous_snapshot_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
);

export const approvedBudgetSnapshotLinesTable = pgTable(
  "approved_budget_snapshot_lines",
  {
    id: text("id").primaryKey(),
    snapshotId: text("snapshot_id").references(() => approvedBudgetSnapshotsTable.id).notNull(),
    stableLineId: text("stable_line_id").notNull(),
    projectCostNodeId: text("project_cost_node_id").references(() => projectCostNodesTable.id).notNull(),
    projectCode: text("project_code").notNull(),
    projectName: text("project_name").notNull(),
    hierarchicalPath: text("hierarchical_path").notNull(),
    description: text("description").notNull(),
    amount: numeric("amount", { precision: 30, scale: 6 }).notNull(),
    quantity: numeric("quantity", { precision: 30, scale: 6 }),
    unit: text("unit"),
    unitRate: numeric("unit_rate", { precision: 30, scale: 6 }),
    notes: text("notes"),
    sortOrder: integer("sort_order").notNull(),
  },
  (table) => [uniqueIndex("approved_snapshot_line_stable_uidx").on(table.snapshotId, table.stableLineId)],
);

export const budgetImportSessionsTable = pgTable(
  "budget_import_sessions",
  {
    id: text("id").primaryKey(),
    projectId: integer("project_id").references(() => projectsTable.id).notNull(),
    companyId: integer("company_id").references(() => companiesTable.id).notNull(),
    actorUserId: integer("actor_user_id").references(() => usersTable.id).notNull(),
    sourceFileId: integer("source_file_id").references(() => filesTable.id).notNull(),
    fileHash: text("file_hash").notNull(),
    parsedFingerprint: text("parsed_fingerprint").notNull(),
    currency: text("currency").notNull(),
    total: numeric("total", { precision: 30, scale: 6 }).notNull(),
    acceptedCount: integer("accepted_count").notNull(),
    rejectedCount: integer("rejected_count").notNull(),
    preview: jsonb("preview").notNull(),
    confirmedBudgetVersionId: text("confirmed_budget_version_id").references(() => projectBudgetVersionsTable.id).unique(),
    idempotencyKey: text("idempotency_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
  },
  (table) => [uniqueIndex("budget_import_project_key_uidx").on(table.projectId, table.idempotencyKey)],
);
