import { sql } from "drizzle-orm";
import { check, date, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { companiesTable, usersTable } from "./users";

export const companyInternalCostPolicyVersionsTable = pgTable("company_internal_cost_policy_versions", {
  id:text("id").primaryKey(), companyId:integer("company_id").notNull(), version:integer("version").notNull(), roleRates:jsonb("role_rates").notNull(), effectiveFrom:date("effective_from").notNull(), status:text("status").notNull(), proposedById:integer("proposed_by_id").notNull(), approvedById:integer("approved_by_id"), reason:text("reason").notNull(), contentFingerprint:text("content_fingerprint").notNull(), supersedesId:text("supersedes_id"), proposedAt:timestamp("proposed_at",{withTimezone:true}).notNull().defaultNow(), decidedAt:timestamp("decided_at",{withTimezone:true}),
}, table => [
  uniqueIndex("company_internal_cost_policy_version_uidx").on(table.companyId,table.version), index("company_internal_cost_policy_effective_idx").on(table.companyId,table.effectiveFrom.desc().nullsFirst(),table.version.desc().nullsFirst()).where(sql`${table.status}='approved'`), foreignKey({name:"company_internal_cost_policy_versions_company_id_fkey",columns:[table.companyId],foreignColumns:[companiesTable.id]}), foreignKey({name:"company_internal_cost_policy_versions_proposed_by_id_fkey",columns:[table.proposedById],foreignColumns:[usersTable.id]}), foreignKey({name:"company_internal_cost_policy_versions_approved_by_id_fkey",columns:[table.approvedById],foreignColumns:[usersTable.id]}), foreignKey({name:"company_internal_cost_policy_versions_supersedes_id_fkey",columns:[table.supersedesId],foreignColumns:[table.id]}), check("company_internal_cost_policy_version_positive_chk",sql`${table.version}>0`), check("company_internal_cost_policy_status_chk",sql`${table.status} IN('proposed','approved','rejected')`), check("company_internal_cost_policy_rates_object_chk",sql`jsonb_typeof(${table.roleRates})='object'`), check("company_internal_cost_policy_reason_chk",sql`length(${table.reason}) BETWEEN 10 AND 1000`), check("company_internal_cost_policy_approval_chk",sql`(${table.status}='approved' AND ${table.approvedById} IS NOT NULL AND ${table.decidedAt} IS NOT NULL) OR ${table.status}<>'approved'`),
]);

export const memberInternalCostProfileVersionsTable = pgTable("member_internal_cost_profile_versions", {
  id:text("id").primaryKey(), companyId:integer("company_id").notNull(), userId:integer("user_id").notNull(), version:integer("version").notNull(), policyVersionId:text("policy_version_id").notNull(), costRole:text("cost_role").notNull(), hourlyRate:numeric("hourly_rate",{precision:18,scale:6}).notNull(), effectiveFrom:date("effective_from").notNull(), effectiveTo:date("effective_to"), status:text("status").notNull(), proposedById:integer("proposed_by_id").notNull(), approvedById:integer("approved_by_id"), reason:text("reason").notNull(), contentFingerprint:text("content_fingerprint").notNull(), supersedesId:text("supersedes_id"), proposedAt:timestamp("proposed_at",{withTimezone:true}).notNull().defaultNow(), decidedAt:timestamp("decided_at",{withTimezone:true}),
}, table => [
  uniqueIndex("member_internal_cost_profile_version_uidx").on(table.companyId,table.userId,table.version), index("member_internal_cost_profile_effective_idx").on(table.companyId,table.userId,table.effectiveFrom.desc().nullsFirst(),table.version.desc().nullsFirst()).where(sql`${table.status}='approved'`), foreignKey({name:"member_internal_cost_profile_versions_company_id_fkey",columns:[table.companyId],foreignColumns:[companiesTable.id]}), foreignKey({name:"member_internal_cost_profile_versions_user_id_fkey",columns:[table.userId],foreignColumns:[usersTable.id]}), foreignKey({name:"member_internal_cost_profile_versions_policy_version_id_fkey",columns:[table.policyVersionId],foreignColumns:[companyInternalCostPolicyVersionsTable.id]}), foreignKey({name:"member_internal_cost_profile_versions_proposed_by_id_fkey",columns:[table.proposedById],foreignColumns:[usersTable.id]}), foreignKey({name:"member_internal_cost_profile_versions_approved_by_id_fkey",columns:[table.approvedById],foreignColumns:[usersTable.id]}), foreignKey({name:"member_internal_cost_profile_versions_supersedes_id_fkey",columns:[table.supersedesId],foreignColumns:[table.id]}), check("member_internal_cost_profile_version_positive_chk",sql`${table.version}>0`), check("member_internal_cost_profile_role_chk",sql`${table.costRole} IN('drafter','coordinator')`), check("member_internal_cost_profile_rate_chk",sql`${table.hourlyRate}>=0`), check("member_internal_cost_profile_range_chk",sql`${table.effectiveTo} IS NULL OR ${table.effectiveTo}>=${table.effectiveFrom}`), check("member_internal_cost_profile_status_chk",sql`${table.status} IN('proposed','approved','rejected')`), check("member_internal_cost_profile_reason_chk",sql`length(${table.reason}) BETWEEN 10 AND 1000`), check("member_internal_cost_profile_approval_chk",sql`(${table.status}='approved' AND ${table.approvedById} IS NOT NULL AND ${table.decidedAt} IS NOT NULL) OR ${table.status}<>'approved'`),
]);
