import { boolean, check, date, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, type AnyPgColumn } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { companiesTable, usersTable } from "./users";
import { projectsTable } from "./projects";
import { filesTable } from "./files";
import { financialContractsTable, financialContractVersionsTable } from "./financial-contracts";
import { projectCostNodesTable } from "./financial-budgets";

export const jobIntakesTable = pgTable("job_intakes", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id),
  status: text("status").notNull().default("draft"), revision: integer("revision").notNull().default(1), data: jsonb("data").$type<Record<string, unknown>>().notNull().default({}), completion: jsonb("completion").$type<Record<string, unknown>>().notNull().default({}),
  activatedContractId: text("activated_contract_id").references(() => financialContractsTable.id), activationMode: text("activation_mode"), activationSummary: jsonb("activation_summary").$type<Record<string, unknown>>().notNull().default({}), createdById: integer("created_by_id").notNull().references(() => usersTable.id), updatedById: integer("updated_by_id").notNull().references(() => usersTable.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(), activatedAt: timestamp("activated_at", { withTimezone: true }),
}, (table) => [uniqueIndex("job_intake_project_uidx").on(table.projectId), index("job_intake_company_status_idx").on(table.companyId, table.status, table.updatedAt), check("job_intake_status_chk", sql`${table.status} IN ('draft','ready','activated')`), check("job_intake_revision_positive_chk", sql`${table.revision} > 0`)]);

export const jobIntakeDocumentsTable = pgTable("job_intake_documents", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), fileId: integer("file_id").notNull().references(() => filesTable.id),
  category: text("category").notNull(), revisionLabel: text("revision_label"), sourceHash: text("source_hash").notNull(), extractionStatus: text("extraction_status").notNull(), extractionSummary: jsonb("extraction_summary").$type<Record<string, unknown>>().notNull().default({}),
  uploadedById: integer("uploaded_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), removedAt: timestamp("removed_at", { withTimezone: true }), removedById: integer("removed_by_id").references(() => usersTable.id),
}, (table) => [uniqueIndex("job_intake_document_uidx").on(table.intakeId, table.fileId), index("job_intake_document_active_idx").on(table.intakeId, table.createdAt), check("job_intake_document_category_chk", sql`${table.category} IN ('quotation','proposal','takeoff','estimate','contract','supporting')`), check("job_intake_document_extraction_chk", sql`${table.extractionStatus} IN ('structured_preview','text_preview','manual_review_required')`)]);

export const jobIntakeEventsTable = pgTable("job_intake_events", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), actorUserId: integer("actor_user_id").notNull().references(() => usersTable.id), eventType: text("event_type").notNull(), beforeRevision: integer("before_revision"), afterRevision: integer("after_revision"), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("job_intake_event_idx").on(table.intakeId, table.createdAt, table.id)]);

export const jobActivationWorkItemsTable = pgTable("job_activation_work_items", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), stableScopeItemId: text("stable_scope_item_id").notNull(),
  edtNodeId: text("edt_node_id").references((): AnyPgColumn => jobActivationEdtNodesTable.id), locationIdentity: text("location_identity"), locationSnapshot: jsonb("location_snapshot").$type<Record<string, unknown>>(), tradeIdentity: text("trade_identity"), tradeSnapshot: jsonb("trade_snapshot").$type<Record<string, unknown>>(), deliverableTypeIdentity: text("deliverable_type_identity"), deliverableTypeSnapshot: jsonb("deliverable_type_snapshot").$type<Record<string, unknown>>(), displayCode: text("display_code"), revisionNumber: integer("revision_number").notNull().default(0), issuanceVersion: integer("issuance_version").notNull().default(0), splitFromWorkItemId: text("split_from_work_item_id").references((): AnyPgColumn => jobActivationWorkItemsTable.id), groupedLocationEvidence: jsonb("grouped_location_evidence").$type<Record<string, unknown>>(), identityFingerprint: text("identity_fingerprint"), economicPlanFingerprint: text("economic_plan_fingerprint"),
  name: text("name").notNull(), description: text("description").notNull().default(""), unit: text("unit").notNull(), plannedHours: numeric("planned_hours", { precision: 30, scale: 6 }).notNull(), workflowTemplate: text("workflow_template").notNull(), status: text("status").notNull().default("active"),
  billingHourlyRate: numeric("billing_hourly_rate", { precision: 30, scale: 6 }), plannedBillableValue: numeric("planned_billable_value", { precision: 30, scale: 6 }), apuPlanVersion: integer("apu_plan_version"), budgetSnapshotLineId: text("budget_snapshot_line_id"), projectCostNodeId: text("project_cost_node_id"),
  contractId: text("contract_id").references(() => financialContractsTable.id), contractVersionId: text("contract_version_id").references(() => financialContractVersionsTable.id), commercialCapabilities: jsonb("commercial_capabilities").$type<Record<string, unknown>>().notNull().default({}), createdById: integer("created_by_id").notNull().references(() => usersTable.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_item_uidx").on(table.intakeId, table.stableScopeItemId), uniqueIndex("job_activation_work_item_display_code_uidx").on(table.projectId, table.displayCode).where(sql`${table.displayCode} IS NOT NULL AND ${table.status} <> 'cancelled'`), index("job_activation_work_item_project_idx").on(table.projectId, table.status, table.createdAt), check("job_activation_work_item_status_chk", sql`${table.status} IN ('active','completed','cancelled')`), check("job_activation_work_item_hours_chk", sql`${table.plannedHours} > 0`), check("job_activation_work_item_rv_chk", sql`${table.revisionNumber} >= 0 AND ${table.issuanceVersion} >= 0`), check("job_activation_work_item_identity_fingerprint_chk", sql`${table.identityFingerprint} IS NULL OR ${table.identityFingerprint} ~ '^[a-f0-9]{64}$'`), check("job_activation_work_item_economic_fingerprint_chk", sql`${table.economicPlanFingerprint} IS NULL OR ${table.economicPlanFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationEdtNodesTable = pgTable("job_activation_edt_nodes", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), parentId: text("parent_id").references((): AnyPgColumn => jobActivationEdtNodesTable.id), nodeKind: text("node_kind").notNull(), sourceIdentity: text("source_identity").notNull(), code: text("code").notNull(), name: text("name").notNull(), sequence: integer("sequence").notNull(), active: boolean("active").notNull().default(true), sourceSnapshot: jsonb("source_snapshot").$type<Record<string, unknown>>().notNull(), sourceFingerprint: text("source_fingerprint").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_edt_node_source_uidx").on(table.intakeId, table.nodeKind, table.sourceIdentity), uniqueIndex("job_activation_edt_node_sibling_sequence_uidx").on(table.intakeId, table.parentId, table.sequence), index("job_activation_edt_node_project_idx").on(table.projectId, table.nodeKind, table.sequence), check("job_activation_edt_node_kind_chk", sql`${table.nodeKind} IN ('project','contract','deliverable','location')`), check("job_activation_edt_node_sequence_chk", sql`${table.sequence} > 0`), check("job_activation_edt_node_fingerprint_chk", sql`${table.sourceFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationWorkItemCodeAliasesTable = pgTable("job_activation_work_item_code_aliases", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), aliasCode: text("alias_code").notNull(), validFrom: timestamp("valid_from", { withTimezone: true }).notNull().defaultNow(), validTo: timestamp("valid_to", { withTimezone: true }), changeRequestId: text("change_request_id"), decisionId: text("decision_id"), reason: text("reason").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_item_active_alias_uidx").on(table.projectId, table.aliasCode).where(sql`${table.validTo} IS NULL`), index("job_activation_work_item_alias_lookup_idx").on(table.projectId, table.aliasCode, table.validFrom), check("job_activation_work_item_alias_period_chk", sql`${table.validTo} IS NULL OR ${table.validTo} > ${table.validFrom}`)]);

export const jobActivationRequestsTable = pgTable("job_activation_requests", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), intakeRevision: integer("intake_revision").notNull(), governanceVersionId: text("governance_version_id").notNull(), pricingVersionId: text("pricing_version_id").notNull(), workflowVersionIds: jsonb("workflow_version_ids").$type<string[]>().notNull(), requestFingerprint: text("request_fingerprint").notNull(), state: text("state").notNull().default("pending"), optimisticVersion: integer("optimistic_version").notNull().default(1), idempotencyKey: text("idempotency_key").notNull(), requestedById: integer("requested_by_id").notNull().references(() => usersTable.id), eligibleRole: text("eligible_role").notNull(), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), decidedAt: timestamp("decided_at", { withTimezone: true }),
}, (table) => [uniqueIndex("job_activation_request_idempotency_uidx").on(table.intakeId, table.idempotencyKey), uniqueIndex("job_activation_request_open_uidx").on(table.intakeId).where(sql`${table.state} = 'pending'`), index("job_activation_request_project_idx").on(table.projectId, table.state, table.createdAt), check("job_activation_request_state_chk", sql`${table.state} IN ('pending','approved','rejected','cancelled')`), check("job_activation_request_revision_chk", sql`${table.intakeRevision} > 0 AND ${table.optimisticVersion} > 0`), check("job_activation_request_fingerprint_chk", sql`${table.requestFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationDecisionsTable = pgTable("job_activation_decisions", {
  id: text("id").primaryKey(), requestId: text("request_id").notNull().references(() => jobActivationRequestsTable.id), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), outcome: text("outcome").notNull(), requestFingerprint: text("request_fingerprint").notNull(), decidedById: integer("decided_by_id").notNull().references(() => usersTable.id), eligibleRole: text("eligible_role").notNull(), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_decision_request_uidx").on(table.requestId), index("job_activation_decision_project_idx").on(table.projectId, table.createdAt), check("job_activation_decision_outcome_chk", sql`${table.outcome} IN ('approved','rejected')`), check("job_activation_decision_fingerprint_chk", sql`${table.requestFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const edtOperationsDirectorGrantsTable = pgTable("edt_operations_director_grants", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id),
  projectId: integer("project_id").notNull().references(() => projectsTable.id),
  userId: integer("user_id").notNull().references(() => usersTable.id),
  grantedById: integer("granted_by_id").notNull().references(() => usersTable.id),
  reason: text("reason").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("edt_operations_director_grant_scope_idx").on(table.companyId, table.projectId, table.userId)]);

export const edtOperationsDirectorRevocationsTable = pgTable("edt_operations_director_revocations", {
  grantId: text("grant_id").primaryKey().references(() => edtOperationsDirectorGrantsTable.id),
  revokedById: integer("revoked_by_id").notNull().references(() => usersTable.id),
  reason: text("reason").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const jobGovernedChangeRequestsTable = pgTable("job_governed_change_requests", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").references(() => jobActivationWorkItemsTable.id), actionType: text("action_type").notNull(), targetVersion: integer("target_version").notNull(), beforeState: jsonb("before_state").$type<Record<string, unknown>>().notNull(), afterState: jsonb("after_state").$type<Record<string, unknown>>().notNull(), requestFingerprint: text("request_fingerprint").notNull(), state: text("state").notNull().default("pending"), optimisticVersion: integer("optimistic_version").notNull().default(1), idempotencyKey: text("idempotency_key").notNull(), requestedById: integer("requested_by_id").notNull().references(() => usersTable.id), eligibleRole: text("eligible_role").notNull(), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), decidedAt: timestamp("decided_at", { withTimezone: true }),
}, (table) => [uniqueIndex("job_governed_change_request_idempotency_uidx").on(table.projectId, table.idempotencyKey), uniqueIndex("job_governed_change_request_open_uidx").on(table.projectId, table.actionType, table.workItemId).where(sql`${table.state} = 'pending'`), index("job_governed_change_request_project_idx").on(table.projectId, table.state, table.createdAt), check("job_governed_change_request_action_chk", sql`${table.actionType} IN ('redistribute_work_item','redistribute_contract','extra_hours','code_correction','split_work_item','reopen_work_item')`), check("job_governed_change_request_state_chk", sql`${table.state} IN ('pending','approved','rejected','cancelled')`), check("job_governed_change_request_version_chk", sql`${table.targetVersion} > 0 AND ${table.optimisticVersion} > 0`), check("job_governed_change_request_fingerprint_chk", sql`${table.requestFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobGovernedChangeDecisionsTable = pgTable("job_governed_change_decisions", {
  id: text("id").primaryKey(), requestId: text("request_id").notNull().references(() => jobGovernedChangeRequestsTable.id), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), outcome: text("outcome").notNull(), requestFingerprint: text("request_fingerprint").notNull(), decidedById: integer("decided_by_id").notNull().references(() => usersTable.id), eligibleRole: text("eligible_role").notNull(), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_governed_change_decision_request_uidx").on(table.requestId), index("job_governed_change_decision_project_idx").on(table.projectId, table.createdAt), check("job_governed_change_decision_outcome_chk", sql`${table.outcome} IN ('approved','rejected')`), check("job_governed_change_decision_fingerprint_chk", sql`${table.requestFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationWorkItemEconomicPlansTable = pgTable("job_activation_work_item_economic_plans", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), contractId: text("contract_id").notNull().references(() => financialContractsTable.id), contractVersionId: text("contract_version_id").notNull().references(() => financialContractVersionsTable.id), pricingTemplateVersionId: text("pricing_template_version_id").notNull(), deliveryWorkflowVersionId: text("delivery_workflow_version_id").notNull(), currency: text("currency").notNull(), directProductionAmount: numeric("direct_production_amount", { precision: 30, scale: 6 }).notNull(), projectAdministrativeAmount: numeric("project_administrative_amount", { precision: 30, scale: 6 }).notNull(), incentiveReserveAmount: numeric("incentive_reserve_amount", { precision: 30, scale: 6 }).notNull(), taskEarningsAmount: numeric("task_earnings_amount", { precision: 30, scale: 6 }).notNull(), projectEarningsAmount: numeric("project_earnings_amount", { precision: 30, scale: 6 }).notNull(), resolvedAllocation: jsonb("resolved_allocation").$type<Record<string, unknown>>().notNull(), sourceFingerprint: text("source_fingerprint").notNull(), planFingerprint: text("plan_fingerprint").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_item_economic_plan_uidx").on(table.workItemId), index("job_activation_economic_plan_project_idx").on(table.projectId, table.contractId), check("job_activation_economic_plan_currency_chk", sql`${table.currency} ~ '^[A-Z]{3}$'`), check("job_activation_economic_plan_amounts_chk", sql`${table.directProductionAmount} >= 0 AND ${table.projectAdministrativeAmount} >= 0 AND ${table.incentiveReserveAmount} >= 0 AND ${table.taskEarningsAmount} >= 0 AND ${table.projectEarningsAmount} >= 0`), check("job_activation_economic_plan_fingerprints_chk", sql`${table.sourceFingerprint} ~ '^[a-f0-9]{64}$' AND ${table.planFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationBudgetLedgerEntriesTable = pgTable("job_activation_budget_ledger_entries", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), budgetAccountId: text("budget_account_id").notNull().references(() => jobActivationBudgetAccountsTable.id), workItemId: text("work_item_id").references(() => jobActivationWorkItemsTable.id), taskId: text("task_id").references(() => jobActivationTasksTable.id), assignmentId: text("assignment_id").references(() => jobActivationResourceAssignmentsTable.id), timeEntryId: text("time_entry_id").references(() => jobActivationTimeEntriesTable.id), pool: text("pool").notNull(), ledgerState: text("ledger_state").notNull(), amountDelta: numeric("amount_delta", { precision: 30, scale: 6 }).notNull().default("0"), hoursDelta: numeric("hours_delta", { precision: 30, scale: 6 }).notNull().default("0"), idempotencyKey: text("idempotency_key").notNull(), sourceVersion: integer("source_version").notNull(), sourceFingerprint: text("source_fingerprint").notNull(), actorUserId: integer("actor_user_id").notNull().references(() => usersTable.id), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_budget_ledger_idempotency_uidx").on(table.projectId, table.idempotencyKey), index("job_activation_budget_ledger_account_idx").on(table.budgetAccountId, table.pool, table.createdAt), index("job_activation_budget_ledger_work_item_idx").on(table.workItemId, table.createdAt), check("job_activation_budget_ledger_pool_chk", sql`${table.pool} IN ('direct_production','project_administrative','incentive_reserve','task_earnings','project_earnings')`), check("job_activation_budget_ledger_state_chk", sql`${table.ledgerState} IN ('budgeted','committed_pending','approved_consumed','released','corrected')`), check("job_activation_budget_ledger_delta_chk", sql`${table.amountDelta} <> 0 OR ${table.hoursDelta} <> 0`), check("job_activation_budget_ledger_source_chk", sql`${table.sourceVersion} > 0 AND ${table.sourceFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationWorkItemIssuancesTable = pgTable("job_activation_work_item_issuances", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), revisionNumber: integer("revision_number").notNull().default(0), issuanceVersion: integer("issuance_version").notNull().default(0), issuanceKind: text("issuance_kind").notNull(), state: text("state").notNull().default("prepared"), packageSnapshot: jsonb("package_snapshot").$type<Record<string, unknown>>().notNull(), evidenceFileId: integer("evidence_file_id").references(() => filesTable.id), sourceEvidence: jsonb("source_evidence").$type<Record<string, unknown>>().notNull().default({}), issuanceFingerprint: text("issuance_fingerprint").notNull(), optimisticVersion: integer("optimistic_version").notNull().default(1), preparedById: integer("prepared_by_id").notNull().references(() => usersTable.id), submittedById: integer("submitted_by_id").references(() => usersTable.id), submittedAt: timestamp("submitted_at", { withTimezone: true }), closedAt: timestamp("closed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_item_issuance_rv_uidx").on(table.workItemId, table.revisionNumber, table.issuanceVersion), index("job_activation_work_item_issuance_project_idx").on(table.projectId, table.state, table.createdAt), check("job_activation_work_item_issuance_rv_chk", sql`${table.revisionNumber} >= 0 AND ${table.issuanceVersion} >= 0`), check("job_activation_work_item_issuance_kind_chk", sql`${table.issuanceKind} IN ('initial','internal_issuance','external_revision','corrected_resubmittal','reopen')`), check("job_activation_work_item_issuance_state_chk", sql`${table.state} IN ('prepared','submitted','approved','rejected','superseded','reopened')`), check("job_activation_work_item_issuance_version_chk", sql`${table.optimisticVersion} > 0`), check("job_activation_work_item_issuance_fingerprint_chk", sql`${table.issuanceFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationQcDecisionsTable = pgTable("job_activation_qc_decisions", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), issuanceId: text("issuance_id").notNull().references(() => jobActivationWorkItemIssuancesTable.id), decisionKind: text("decision_kind").notNull(), outcome: text("outcome").notNull(), reviewerUserId: integer("reviewer_user_id").notNull().references(() => usersTable.id), eligibleRole: text("eligible_role").notNull(), conflictEvaluation: jsonb("conflict_evaluation").$type<Record<string, unknown>>().notNull(), reason: text("reason").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), issuanceFingerprint: text("issuance_fingerprint").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_qc_decision_step_uidx").on(table.issuanceId, table.decisionKind), index("job_activation_qc_decision_project_idx").on(table.projectId, table.createdAt), check("job_activation_qc_decision_kind_chk", sql`${table.decisionKind} IN ('review','final_approval','reopen_approval')`), check("job_activation_qc_decision_outcome_chk", sql`${table.outcome} IN ('approved','rejected')`), check("job_activation_qc_decision_fingerprint_chk", sql`${table.issuanceFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobIntakeImportBatchesTable = pgTable("job_intake_import_batches", {
  id: text("id").primaryKey(), companyId: integer("company_id").notNull().references(() => companiesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), intakeRevision: integer("intake_revision").notNull(), fileId: integer("file_id").notNull().references(() => filesTable.id), fileSha256: text("file_sha256").notNull(), worksheetName: text("worksheet_name").notNull().default("Result"), parserVersion: text("parser_version").notNull(), structuralRange: text("structural_range").notNull(), previewFingerprint: text("preview_fingerprint").notNull(), status: text("status").notNull().default("previewed"), requestedById: integer("requested_by_id").notNull().references(() => usersTable.id), reviewedById: integer("reviewed_by_id").references(() => usersTable.id), activatedById: integer("activated_by_id").references(() => usersTable.id), reviewedAt: timestamp("reviewed_at", { withTimezone: true }), activatedAt: timestamp("activated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_intake_import_batch_repeat_uidx").on(table.intakeId, table.intakeRevision, table.fileSha256, table.parserVersion), index("job_intake_import_batch_project_idx").on(table.projectId, table.status, table.createdAt), check("job_intake_import_batch_revision_chk", sql`${table.intakeRevision} > 0`), check("job_intake_import_batch_hashes_chk", sql`${table.fileSha256} ~ '^[a-f0-9]{64}$' AND ${table.previewFingerprint} ~ '^[a-f0-9]{64}$'`), check("job_intake_import_batch_sheet_chk", sql`${table.worksheetName} = 'Result'`), check("job_intake_import_batch_status_chk", sql`${table.status} IN ('previewed','invalid','validated','reviewed','activated','rejected')`)]);

export const jobIntakeImportRowsTable = pgTable("job_intake_import_rows", {
  id: text("id").primaryKey(), batchId: text("batch_id").notNull().references(() => jobIntakeImportBatchesTable.id), rowNumber: integer("row_number").notNull(), rawFields: jsonb("raw_fields").$type<Record<string, unknown>>().notNull(), normalizedFields: jsonb("normalized_fields").$type<Record<string, unknown>>().notNull(), validationState: text("validation_state").notNull(), validationErrors: jsonb("validation_errors").$type<string[]>().notNull().default([]), mappedIdentities: jsonb("mapped_identities").$type<Record<string, unknown>>().notNull().default({}), rowFingerprint: text("row_fingerprint").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_intake_import_row_number_uidx").on(table.batchId, table.rowNumber), index("job_intake_import_row_validation_idx").on(table.batchId, table.validationState, table.rowNumber), check("job_intake_import_row_number_chk", sql`${table.rowNumber} > 1`), check("job_intake_import_row_state_chk", sql`${table.validationState} IN ('valid','invalid','unsupported','duplicate')`), check("job_intake_import_row_fingerprint_chk", sql`${table.rowFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationTasksTable = pgTable("job_activation_tasks", {
  id: text("id").primaryKey(), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), taskKey: text("task_key").notNull(), nameEn: text("name_en").notNull(), nameEs: text("name_es").notNull(), sequence: integer("sequence").notNull().default(1), status: text("status").notNull().default("not_started"), version: integer("version").notNull().default(1), progressPercent: integer("progress_percent").notNull().default(0),
  plannedHours: numeric("planned_hours", { precision: 30, scale: 6 }).notNull(), assigneeUserId: integer("assignee_user_id").references(() => usersTable.id), startDate: date("start_date"), dueDate: date("due_date"), predecessorTaskIds: text("predecessor_task_ids").array().notNull().default(sql`'{}'::text[]`), disciplineId: text("discipline_id"), disciplineCode: text("discipline_code"), disciplineName: text("discipline_name"), serviceId: text("service_id"), serviceCode: text("service_code"), serviceName: text("service_name"), phaseId: text("phase_id"), phaseCode: text("phase_code"), phaseName: text("phase_name"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_task_uidx").on(table.workItemId, table.taskKey), index("job_activation_task_work_item_idx").on(table.workItemId, table.sequence), check("job_activation_task_status_chk", sql`${table.status} IN ('not_started','in_progress','blocked','complete','cancelled')`), check("job_activation_task_hours_chk", sql`${table.plannedHours} > 0`), check("job_activation_task_version_chk", sql`${table.version} > 0`), check("job_activation_task_progress_chk", sql`${table.progressPercent} >= 0 AND ${table.progressPercent} <= 100`), check("job_activation_task_dates_chk", sql`${table.startDate} IS NULL OR ${table.dueDate} IS NULL OR ${table.startDate} <= ${table.dueDate}`)]);

export const jobActivationResourceAssignmentsTable = pgTable("job_activation_resource_assignments", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), taskId: text("task_id").notNull().references(() => jobActivationTasksTable.id), sourceAssignmentId: text("source_assignment_id").notNull(),
  userId: integer("user_id").references(() => usersTable.id), personName: text("person_name").notNull(), role: text("role").notNull(), employmentType: text("employment_type").notNull(), plannedHours: numeric("planned_hours", { precision: 30, scale: 6 }).notNull(), internalHourlyRate: numeric("internal_hourly_rate", { precision: 30, scale: 6 }), billingHourlyRate: numeric("billing_hourly_rate", { precision: 30, scale: 6 }), plannedInternalCost: numeric("planned_internal_cost", { precision: 30, scale: 6 }), plannedBillableValue: numeric("planned_billable_value", { precision: 30, scale: 6 }), version: integer("version").notNull().default(1),
  createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_resource_uidx").on(table.intakeId, table.sourceAssignmentId), index("job_activation_resource_work_item_idx").on(table.workItemId, table.userId), check("job_activation_resource_hours_chk", sql`${table.plannedHours} > 0`), check("job_activation_resource_version_chk", sql`${table.version} > 0`)]);

export const jobActivationTimeEntriesTable = pgTable("job_activation_time_entries", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), taskId: text("task_id").notNull().references(() => jobActivationTasksTable.id), assignmentId: text("assignment_id").references(() => jobActivationResourceAssignmentsTable.id),
  userId: integer("user_id").notNull().references(() => usersTable.id), workDate: date("work_date").notNull(), hours: numeric("hours", { precision: 30, scale: 6 }).notNull(), note: text("note").notNull().default(""), status: text("status").notNull().default("legacy_recorded"), optimisticVersion: integer("optimistic_version").notNull().default(1), submittedById: integer("submitted_by_id").references(() => usersTable.id), submittedAt: timestamp("submitted_at", { withTimezone: true }), decidedById: integer("decided_by_id").references(() => usersTable.id), decidedAt: timestamp("decided_at", { withTimezone: true }), decisionReason: text("decision_reason"), correctsEntryId: text("corrects_entry_id").references((): AnyPgColumn => jobActivationTimeEntriesTable.id), supersededByEntryId: text("superseded_by_entry_id").references((): AnyPgColumn => jobActivationTimeEntriesTable.id), sourceFingerprint: text("source_fingerprint"), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("job_activation_time_task_idx").on(table.taskId, table.workDate, table.createdAt), index("job_activation_time_user_idx").on(table.projectId, table.userId, table.workDate), index("job_activation_time_status_idx").on(table.projectId, table.status, table.workDate), check("job_activation_time_hours_chk", sql`${table.hours} > 0 AND ${table.hours} <= 24`), check("job_activation_time_status_chk", sql`${table.status} IN ('legacy_recorded','draft','submitted','approved','rejected','corrected','superseded')`), check("job_activation_time_version_chk", sql`${table.optimisticVersion} > 0`), check("job_activation_time_fingerprint_chk", sql`${table.sourceFingerprint} IS NULL OR ${table.sourceFingerprint} ~ '^[a-f0-9]{64}$'`)]);

export const jobActivationTaskDeliverablesTable = pgTable("job_activation_task_deliverables", {
  id: text("id").primaryKey(), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id), taskId: text("task_id").notNull().references(() => jobActivationTasksTable.id), fileId: integer("file_id").notNull().references(() => filesTable.id), deliverableType: text("deliverable_type").notNull(), note: text("note").notNull().default(""), linkedById: integer("linked_by_id").notNull().references(() => usersTable.id), linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_task_deliverable_uidx").on(table.taskId, table.fileId, table.deliverableType), index("job_activation_deliverable_task_idx").on(table.taskId, table.linkedAt), check("job_activation_deliverable_type_chk", sql`${table.deliverableType} IN ('shop_drawing','submittal','deliverable','supporting')`)]);

export const jobActivationWorkPackagesTable = pgTable("job_activation_work_packages", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").notNull().references(() => jobActivationWorkItemsTable.id),
  packageCode: text("package_code").notNull(), title: text("title").notNull(), description: text("description").notNull().default(""), packageType: text("package_type").notNull(), status: text("status").notNull().default("draft"), responsibleUserId: integer("responsible_user_id").references(() => usersTable.id), dueDate: date("due_date"), version: integer("version").notNull().default(1), disciplineId: text("discipline_id"), disciplineCode: text("discipline_code"), disciplineName: text("discipline_name"), serviceId: text("service_id"), serviceCode: text("service_code"), serviceName: text("service_name"), phaseId: text("phase_id"), phaseCode: text("phase_code"), phaseName: text("phase_name"),
  createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_package_code_uidx").on(table.projectId, table.packageCode), index("job_activation_work_package_project_idx").on(table.projectId, table.status, table.dueDate, table.updatedAt), index("job_activation_work_package_item_idx").on(table.workItemId, table.createdAt, table.id), check("job_activation_work_package_type_chk", sql`${table.packageType} IN ('shop_drawing','submittal','mixed','deliverable')`), check("job_activation_work_package_status_chk", sql`${table.status} IN ('draft','internal_review','submitted','returned','approved','cancelled')`), check("job_activation_work_package_version_chk", sql`${table.version} > 0`)]);

export const jobActivationWorkPackageTasksTable = pgTable("job_activation_work_package_tasks", {
  packageId: text("package_id").notNull().references(() => jobActivationWorkPackagesTable.id), taskId: text("task_id").notNull().references(() => jobActivationTasksTable.id), linkedById: integer("linked_by_id").notNull().references(() => usersTable.id), linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_work_package_task_uidx").on(table.packageId, table.taskId), index("job_activation_work_package_task_idx").on(table.taskId, table.packageId)]);

export const jobActivationWorkPackageCountersTable = pgTable("job_activation_work_package_counters", {
  projectId: integer("project_id").primaryKey().references(() => projectsTable.id),
  nextValue: integer("next_value").notNull().default(1),
}, (table) => [check("job_activation_work_package_counter_positive_chk", sql`${table.nextValue} > 0`)]);

export const jobActivationDocumentConnectionsTable = pgTable("job_activation_document_connections", {
  id: text("id").primaryKey(),
  projectId: integer("project_id").notNull(),
  targetType: text("target_type").notNull(),
  targetId: text("target_id").notNull(),
  entityType: text("entity_type").notNull(),
  entityId: integer("entity_id").notNull(),
  note: text("note").notNull().default(""),
  linkedById: integer("linked_by_id").notNull(),
  linkedAt: timestamp("linked_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  foreignKey({ name: "job_activation_document_connections_project_id_fkey", columns: [table.projectId], foreignColumns: [projectsTable.id] }),
  foreignKey({ name: "job_activation_document_connections_linked_by_id_fkey", columns: [table.linkedById], foreignColumns: [usersTable.id] }),
  uniqueIndex("job_activation_document_connection_target_entity_uidx").on(table.projectId, table.targetType, table.targetId, table.entityType, table.entityId),
  index("job_activation_document_connection_project_target_idx").on(table.projectId, table.targetType, table.targetId, table.linkedAt),
  check("job_activation_document_connection_id_chk", sql`${table.id} ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'`),
  check("job_activation_document_connection_target_type_chk", sql`${table.targetType} IN ('task','work_package')`),
  check("job_activation_document_connection_entity_type_chk", sql`${table.entityType} IN ('rfi','file_revision','transmittal')`),
  check("job_activation_document_connection_target_id_chk", sql`octet_length(${table.targetId}) BETWEEN 8 AND 64`),
  check("job_activation_document_connection_entity_id_chk", sql`${table.entityId} > 0`),
  check("job_activation_document_connection_note_chk", sql`octet_length(${table.note}) <= 500`),
]);

export const jobActivationBudgetBaselinesTable = pgTable("job_activation_budget_baselines", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), version: integer("version").notNull(), supersedesId: text("supersedes_id").references((): AnyPgColumn => jobActivationBudgetBaselinesTable.id), content: jsonb("content").$type<Record<string, unknown>>().notNull(), contentFingerprint: text("content_fingerprint").notNull(), revisionReason: text("revision_reason").notNull().default(""), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_budget_baseline_project_version_uidx").on(table.projectId, table.version), index("job_activation_budget_baseline_fingerprint_idx").on(table.projectId, table.contentFingerprint), index("job_activation_budget_baseline_project_idx").on(table.projectId, table.version), check("job_activation_budget_baseline_version_chk", sql`${table.version} > 0`)]);

export const jobActivationBudgetVarianceReviewsTable = pgTable("job_activation_budget_variance_reviews", {
  id: text("id").primaryKey(), baselineId: text("baseline_id").notNull().references(() => jobActivationBudgetBaselinesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").references(() => jobActivationWorkItemsTable.id), metric: text("metric").notNull(), plannedValue: numeric("planned_value", { precision: 30, scale: 6 }).notNull(), actualValue: numeric("actual_value", { precision: 30, scale: 6 }).notNull(), varianceValue: numeric("variance_value", { precision: 30, scale: 6 }).notNull(), reason: text("reason").notNull(), correctiveAction: text("corrective_action").notNull(), status: text("status").notNull().default("open"), version: integer("version").notNull().default(1), createdById: integer("created_by_id").notNull().references(() => usersTable.id), reviewedById: integer("reviewed_by_id").references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
}, (table) => [index("job_activation_budget_variance_project_idx").on(table.projectId, table.status, table.createdAt), check("job_activation_budget_variance_metric_chk", sql`${table.metric} IN ('hours','internal_cost','billable_value')`), check("job_activation_budget_variance_status_chk", sql`${table.status} IN ('open','acknowledged','resolved','rejected')`), check("job_activation_budget_variance_positive_chk", sql`${table.varianceValue} > 0`), check("job_activation_budget_variance_version_chk", sql`${table.version} > 0`)]);

export const jobActivationBudgetAccountsTable = pgTable("job_activation_budget_accounts", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), projectCostNodeId: text("project_cost_node_id").notNull().references(() => projectCostNodesTable.id), currency: text("currency").notNull(), amount: numeric("amount", { precision: 30, scale: 6 }).notNull(), contractIds: jsonb("contract_ids").$type<string[]>().notNull(), contractItemIds: jsonb("contract_item_ids").$type<string[]>().notNull(), contentFingerprint: text("content_fingerprint").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_budget_account_uidx").on(table.intakeId, table.projectCostNodeId), index("job_activation_budget_account_project_idx").on(table.projectId, table.projectCostNodeId), check("job_activation_budget_account_amount_chk", sql`${table.amount} >= 0`), check("job_activation_budget_account_currency_chk", sql`${table.currency} ~ '^[A-Z]{3}$'`)]);

export const jobActivationContractItemBaselinesTable = pgTable("job_activation_contract_item_baselines", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), contractId: text("contract_id").notNull().references(() => financialContractsTable.id), contractVersionId: text("contract_version_id").notNull().references(() => financialContractVersionsTable.id), stableLineId: text("stable_line_id").notNull(), budgetAccountId: text("budget_account_id").notNull().references(() => jobActivationBudgetAccountsTable.id), pricingSnapshot: jsonb("pricing_snapshot").$type<Record<string, unknown>>().notNull(), snapshotFingerprint: text("snapshot_fingerprint").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_contract_item_baseline_uidx").on(table.contractVersionId, table.stableLineId), index("job_activation_contract_item_baseline_project_idx").on(table.projectId, table.contractId)]);

export const jobActivationExecutionBaselinesTable = pgTable("job_activation_execution_baselines", {
  id: text("id").primaryKey(), intakeId: text("intake_id").notNull().references(() => jobIntakesTable.id), projectId: integer("project_id").notNull().references(() => projectsTable.id), content: jsonb("content").$type<Record<string, unknown>>().notNull(), contentFingerprint: text("content_fingerprint").notNull(), createdById: integer("created_by_id").notNull().references(() => usersTable.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex("job_activation_execution_baseline_intake_uidx").on(table.intakeId), index("job_activation_execution_baseline_project_idx").on(table.projectId, table.createdAt)]);

export const jobActivationOperationEventsTable = pgTable("job_activation_operation_events", {
  id: text("id").primaryKey(), projectId: integer("project_id").notNull().references(() => projectsTable.id), workItemId: text("work_item_id").references(() => jobActivationWorkItemsTable.id), taskId: text("task_id").references(() => jobActivationTasksTable.id), assignmentId: text("assignment_id").references(() => jobActivationResourceAssignmentsTable.id), packageId: text("package_id").references(() => jobActivationWorkPackagesTable.id), actorUserId: integer("actor_user_id").notNull().references(() => usersTable.id), eventType: text("event_type").notNull(), evidence: jsonb("evidence").$type<Record<string, unknown>>().notNull().default({}), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [index("job_activation_operation_event_idx").on(table.projectId, table.createdAt, table.id)]);
