import assert from "node:assert/strict";import fs from "node:fs";
const source=fs.readFileSync(new URL("./CommercialWorkspace.tsx",import.meta.url),"utf8");
for(const token of ["Billing & Support","Facturación y Soporte","/api/v1/commercial/workspace","Loading commercial status","Status unavailable","Action required","What happens next"])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
for(const token of ["Next steps","Próximos pasos","Complete billing identity","Review plans","Contact support","Unavailable until setup is complete"])assert.match(source,new RegExp(token));
for(const token of ["What happens next","Qué sucede ahora","Your company","You do not need to configure them","data.responsibilities.customer","data.responsibilities.bimlog"])assert.match(source,new RegExp(token));
for(const token of ["Ready to sell live subscriptions","Subscriptions are not ready for sale","Checkout is in test mode","Customers do not need to enter provider settings","salesLaunchBlockers.map"])assert.match(source,new RegExp(token));
assert.doesNotMatch(source,/price_[A-Za-z0-9_]+/);
for(const token of ["parseCommercialCheckoutReturn","Checkout submitted — verification pending","Checkout cancelled","signed payment confirmation","No subscription change was claimed"])assert.match(source,new RegExp(token));
for(const token of ["Billing self-service","Autoservicio de facturación","Start secure checkout","Manage billing","requestCommercialHostedDestination","data.billingAuthority.canManageBilling"])assert.match(source,new RegExp(token));
for(const token of ["Checkout submitted — verification pending","Pago enviado — verificación pendiente","signed payment confirmation","confirmación firmada del pago"])assert.match(source,new RegExp(token));
for(const token of ["deriveCommercialCheckoutEligibility","readCommercialIntent","Prepare subscription","Preparar suscripción","requestCommercialSubscriptionSetup","providerCustomerBound","Before checkout:","checkoutBlockerLabels","checkoutEligibility?.blockers.map"])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
for(const token of ["Prepared offer","Oferta preparada","data.preparedSubscription.seatQuantity","Boolean(data.preparedSubscription)"])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
assert.match(source,/checkoutEligibility\?\.ready\?<Button/);assert.match(source,/data\.subscriptionStatus!=="active"/);
assert.match(source,/data\.actions\.map/);assert.match(source,/action\.status==="blocked"/);assert.match(source,/Button disabled/);
assert.match(source,/minmax\(min\(240px,100%\),1fr\)/);assert.match(source,/Waiting for:/);assert.match(source,/action\.blockers\.map/);assert.doesNotMatch(source,/Ready \/ Listo|Setup required \/ Requiere configuración/);
assert.match(source,/AbortController/);assert.match(source,/parseCommercialWorkspace/);assert.doesNotMatch(source,/stripe.*secret/i);
assert.match(source,/complete_billing_identity.*from=billing/s);assert.match(source,/<a href=\{href\}>/);
console.log("B069 bilingual Billing & Support workspace: PASS");
const app=fs.readFileSync(new URL("../App.tsx",import.meta.url),"utf8"),sidebar=fs.readFileSync(new URL("../components/layout/MasterSidebar.tsx",import.meta.url),"utf8");
assert.match(app,/settings\/billing-support/);assert.match(app,/ProtectedRoute component=\{CommercialWorkspace\}/);assert.match(sidebar,/Billing & Support/);assert.match(sidebar,/Facturación y Soporte/);
console.log("B070 discoverable protected commercial workspace acceptance: PASS");
