import {useEffect,useState} from "react";
import {Link} from "wouter";
import {CreditCard,Headphones,RefreshCw,ShieldCheck} from "lucide-react";
import {MasterSidebar} from "@/components/layout/MasterSidebar";
import {Button} from "@/components/ui/button";
import {useAuthStore} from "@/store/auth";
import {useI18n} from "@/lib/i18n";
import {parseCommercialWorkspace,type CommercialWorkspaceDto} from "@/lib/commercial-workspace-client";
const API_BASE=import.meta.env.BASE_URL.replace(/\/$/,"");

export function CommercialWorkspace(){
  const token=useAuthStore(state=>state.token),{tt}=useI18n();
  const [data,setData]=useState<CommercialWorkspaceDto|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[nonce,setNonce]=useState(0);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");fetch(`${API_BASE}/api/v1/commercial/workspace`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:tt("Commercial workspace could not be loaded.","No se pudo cargar el espacio comercial."));return parseCommercialWorkspace(body);}).then(setData).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,nonce,tt]);
  const labels:Record<string,[string,string]>={SUBSCRIPTION_NOT_CONFIGURED:["Subscription setup","Configuración de suscripción"],BILLING_IDENTITY_INCOMPLETE:["Billing identity","Identidad de facturación"],PAYMENT_PROVIDER_NOT_CONFIGURED:["Payment provider","Proveedor de pagos"],WEBHOOK_NOT_CONFIGURED:["Payment confirmation webhook","Webhook de confirmación de pago"],BILLING_PORTAL_NOT_CONFIGURED:["Billing portal","Portal de facturación"],SUPPORT_CHANNEL_NOT_CONFIGURED:["Customer support channel","Canal de servicio al cliente"],COMMERCIAL_ACCESS_DISABLED:["Commercial access","Acceso comercial"]};
  return <div className="app-shell commercial-workspace-page"><MasterSidebar/><div className="main-area"><main className="page-content" style={{padding:"24px clamp(14px,3vw,36px) 64px",maxWidth:1100,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap",marginBottom:20}}><div><h1 style={{fontSize:26,fontWeight:800,margin:0}}>{tt("Billing & Support","Facturación y Soporte")}</h1><p style={{color:"#64748B",margin:"6px 0 0"}}>{tt("Your company’s subscription, payment readiness, seats and support setup in one place.","La suscripción, preparación de pagos, cupos y soporte de su empresa en un solo lugar.")}</p></div><Button variant="outline" onClick={()=>setNonce(value=>value+1)}><RefreshCw style={{width:15,marginRight:6}}/>{tt("Refresh status","Actualizar estado")}</Button></header>
    {loading&&<div role="status" style={{padding:24,border:"1px solid #E2E8F0",borderRadius:12}}>{tt("Loading commercial status…","Cargando estado comercial…")}</div>}
    {error&&<div role="alert" style={{padding:18,border:"1px solid #FCA5A5",background:"#FEF2F2",borderRadius:12}}><strong>{tt("Status unavailable","Estado no disponible")}</strong><p>{error}</p><Button onClick={()=>setNonce(value=>value+1)}>{tt("Try again","Intentar de nuevo")}</Button></div>}
    {data&&<><section style={{padding:20,border:"1px solid #CBD5E1",borderRadius:14,background:"white",marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{data.companyName}</strong><div style={{color:"#64748B",fontSize:13}}>{tt(`${data.memberCount} company members`,`${data.memberCount} miembros de la empresa`)}</div></div><span style={{fontWeight:700,color:data.readiness==="ready"?"#047857":"#B45309"}}>{data.readiness==="ready"?tt("Ready","Listo"):tt("Action required","Acción requerida")}</span></div></section>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}><StatusCard icon={<CreditCard/>} title={tt("Subscription & billing","Suscripción y facturación")} ready={data.subscriptionStatus==="active"&&data.billingIdentityStatus==="complete"}/><StatusCard icon={<ShieldCheck/>} title={tt("Payment processing","Procesamiento de pagos")} ready={data.paymentProviderStatus==="ready"&&data.webhookStatus==="ready"&&data.billingPortalStatus==="ready"}/><StatusCard icon={<Headphones/>} title={tt("Customer support","Servicio al cliente")} ready={data.supportStatus==="ready"}/></div>
    {data.blockers.length>0&&<section style={{marginTop:18,padding:20,border:"1px solid #FDE68A",background:"#FFFBEB",borderRadius:14}}><h2 style={{fontSize:17,marginTop:0}}>{tt("Complete these items before selling subscriptions","Complete estos puntos antes de vender suscripciones")}</h2><ul>{data.blockers.map(code=><li key={code}>{tt(...(labels[code]??[code,code]))}</li>)}</ul><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><Button asChild variant="outline"><Link href="/settings/company-profile">{tt("Complete company profile","Completar perfil de empresa")}</Link></Button><Button asChild variant="outline"><Link href="/contact">{tt("Contact BIMLog support","Contactar soporte BIMLog")}</Link></Button></div></section>}</>}
  </main></div></div>;
}
function StatusCard({icon,title,ready}:{icon:React.ReactNode;title:string;ready:boolean}){return <section style={{padding:18,border:"1px solid #E2E8F0",borderRadius:12,background:"white"}}><div style={{color:"#2563EB",marginBottom:10}}>{icon}</div><strong>{title}</strong><div style={{marginTop:7,color:ready?"#047857":"#B45309",fontSize:13,fontWeight:700}}>{ready?"Ready / Listo":"Setup required / Requiere configuración"}</div></section>}
