import {useEffect,useState} from "react";
import {Link} from "wouter";
import {CheckCircle2,CreditCard,Headphones,RefreshCw,ShieldCheck} from "lucide-react";
import {MasterSidebar} from "@/components/layout/MasterSidebar";
import {Button} from "@/components/ui/button";
import {useAuthStore} from "@/store/auth";
import {useI18n} from "@/lib/i18n";
import {parseCommercialWorkspace,requestCommercialHostedDestination,type CommercialWorkspaceDto} from "@/lib/commercial-workspace-client";
import {parseCommercialCheckoutReturn} from "@/lib/commercial-checkout-return";
import {SupportCasesPanel} from "@/components/commercial/SupportCasesPanel";
import {BillingHistoryPanel} from "@/components/commercial/BillingHistoryPanel";
const API_BASE=import.meta.env.BASE_URL.replace(/\/$/,"");

export function CommercialWorkspace(){
  const token=useAuthStore(state=>state.token),{tt}=useI18n();
  const [data,setData]=useState<CommercialWorkspaceDto|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[nonce,setNonce]=useState(0),[plan,setPlan]=useState<"professional"|"team"|"business">("professional"),[cycle,setCycle]=useState<"monthly"|"annual">("monthly"),[billingBusy,setBillingBusy]=useState(false),[billingError,setBillingError]=useState("");
  const checkoutReturn=parseCommercialCheckoutReturn(window.location.search);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");fetch(`${API_BASE}/api/v1/commercial/workspace`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal}).then(async response=>{const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof body.error==="string"?body.error:tt("Commercial workspace could not be loaded.","No se pudo cargar el espacio comercial."));return parseCommercialWorkspace(body);}).then(setData).catch(reason=>{if(reason?.name!=="AbortError")setError(reason instanceof Error?reason.message:String(reason));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,nonce,tt]);
  const labels:Record<string,[string,string]>={SUBSCRIPTION_NOT_CONFIGURED:["Subscription setup","Configuración de suscripción"],BILLING_IDENTITY_INCOMPLETE:["Billing identity","Identidad de facturación"],PAYMENT_PROVIDER_NOT_CONFIGURED:["Payment provider","Proveedor de pagos"],WEBHOOK_NOT_CONFIGURED:["Payment confirmation webhook","Webhook de confirmación de pago"],BILLING_PORTAL_NOT_CONFIGURED:["Billing portal","Portal de facturación"],SUPPORT_CHANNEL_NOT_CONFIGURED:["Customer support channel","Canal de servicio al cliente"],COMMERCIAL_ACCESS_DISABLED:["Commercial access","Acceso comercial"]};
  const serviceLabels:Record<string,[string,string]>={subscription_catalog:["Plans and pricing","Planes y precios"],payment_provider:["Secure payment service","Servicio de pago seguro"],payment_webhook:["Payment confirmation","Confirmación de pago"],billing_portal:["Billing self-service","Autoservicio de facturación"],support_channel:["Customer support delivery","Atención al cliente"]};
  const planLabels:Record<string,[string,string]>={professional:["Professional","Profesional"],team:["Team","Equipo"],business:["Business","Negocios"]};
  const catalogStatusLabels:Record<string,[string,string]>={ready:["Available","Disponible"],missing:["BIMLog setup pending","Configuración BIMLog pendiente"],invalid:["BIMLog review required","Revisión de BIMLog requerida"],duplicate_price:["BIMLog correction required","Corrección de BIMLog requerida"]};
  const salesBlockerLabels:Record<string,[string,string]>={catalog:["Complete plan pricing","Completar precios de planes"],provider:["Configure secure payments","Configurar pagos seguros"],live_mode:["Switch payments from test to live mode","Cambiar pagos de prueba a modo real"],webhook:["Configure payment confirmation","Configurar confirmación de pago"],portal:["Configure billing self-service","Configurar autoservicio de facturación"],support:["Configure customer support delivery","Configurar atención al cliente"]};
  return <div className="app-shell commercial-workspace-page"><MasterSidebar/><div className="main-area"><main className="page-content" style={{padding:"24px clamp(14px,3vw,36px) 64px",maxWidth:1100,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap",marginBottom:20}}><div><h1 style={{fontSize:26,fontWeight:800,margin:0}}>{tt("Billing & Support","Facturación y Soporte")}</h1><p style={{color:"#64748B",margin:"6px 0 0"}}>{tt("Your company’s subscription, payment readiness, seats and support setup in one place.","La suscripción, preparación de pagos, cupos y soporte de su empresa en un solo lugar.")}</p></div><Button variant="outline" onClick={()=>setNonce(value=>value+1)}><RefreshCw style={{width:15,marginRight:6}}/>{tt("Refresh status","Actualizar estado")}</Button></header>
    {checkoutReturn&&<div role="status" style={{padding:16,marginBottom:16,border:`1px solid ${checkoutReturn==="success"?"#86EFAC":"#FDE68A"}`,background:checkoutReturn==="success"?"#F0FDF4":"#FFFBEB",borderRadius:12}}><strong>{checkoutReturn==="success"?tt("Checkout received","Pago recibido"):tt("Checkout cancelled","Pago cancelado")}</strong><p style={{margin:"6px 0 0"}}>{checkoutReturn==="success"?tt("BIMLog is verifying the provider confirmation. Refresh status before relying on access.","BIMLog está verificando la confirmación del proveedor. Actualice el estado antes de depender del acceso."):tt("No subscription change was claimed. You can review the plans and try again.","No se registró ningún cambio de suscripción. Puede revisar los planes e intentarlo de nuevo.")}</p></div>}
    {loading&&<div role="status" style={{padding:24,border:"1px solid #E2E8F0",borderRadius:12}}>{tt("Loading commercial status…","Cargando estado comercial…")}</div>}
    {error&&<div role="alert" style={{padding:18,border:"1px solid #FCA5A5",background:"#FEF2F2",borderRadius:12}}><strong>{tt("Status unavailable","Estado no disponible")}</strong><p>{error}</p><Button onClick={()=>setNonce(value=>value+1)}>{tt("Try again","Intentar de nuevo")}</Button></div>}
    {data&&<><section style={{padding:20,border:"1px solid #CBD5E1",borderRadius:14,background:"white",marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{data.companyName}</strong><div style={{color:"#64748B",fontSize:13}}>{tt(`${data.memberCount} company members`,`${data.memberCount} miembros de la empresa`)}</div></div><span style={{fontWeight:700,color:data.readiness==="ready"?"#047857":"#B45309"}}>{data.readiness==="ready"?tt("Ready","Listo"):tt("Action required","Acción requerida")}</span></div></section>
    <section aria-labelledby="sales-launch-status" style={{padding:18,border:`1px solid ${data.salesLaunchStatus==="ready"?"#86EFAC":"#FDE68A"}`,background:data.salesLaunchStatus==="ready"?"#F0FDF4":"#FFFBEB",borderRadius:12,marginBottom:16}}><h2 id="sales-launch-status" style={{fontSize:19,margin:"0 0 6px"}}>{data.salesLaunchStatus==="ready"?tt("Ready to sell live subscriptions","Listo para vender suscripciones reales"):data.salesLaunchStatus==="test_only"?tt("Checkout is in test mode","El pago está en modo de prueba"):tt("Subscriptions are not ready for sale","Las suscripciones no están listas para venta")}</h2><p style={{margin:"0 0 8px",color:"#475569"}}>{data.salesLaunchStatus==="ready"?tt("All BIMLog-managed commercial services required for live checkout are ready.","Todos los servicios comerciales administrados por BIMLog requeridos para pagos reales están listos."):tt("This is a BIMLog platform status. Customers do not need to enter provider settings.","Este es un estado de la plataforma BIMLog. Los clientes no necesitan ingresar configuraciones del proveedor.")}</p>{data.salesLaunchBlockers.length>0&&<ul style={{marginBottom:0}}>{data.salesLaunchBlockers.map(code=><li key={code}>{tt(...(salesBlockerLabels[code]??[code,code]))}</li>)}</ul>}</section>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(230px,100%),1fr))",gap:14}}><StatusCard icon={<CreditCard/>} title={tt("Subscription & billing","Suscripción y facturación")} ready={data.subscriptionStatus==="active"&&data.billingIdentityStatus==="complete"} tt={tt}/><StatusCard icon={<ShieldCheck/>} title={tt("Payment processing","Procesamiento de pagos")} ready={data.paymentProviderStatus==="ready"&&data.webhookStatus==="ready"&&data.billingPortalStatus==="ready"} tt={tt}/><StatusCard icon={<Headphones/>} title={tt("Customer support","Servicio al cliente")} ready={data.supportStatus==="ready"} tt={tt}/></div>
    <section aria-labelledby="commercial-service-checks" style={{marginTop:18,padding:18,border:"1px solid #E2E8F0",borderRadius:12,background:"white"}}><h2 id="commercial-service-checks" style={{fontSize:19,marginTop:0}}>{tt("BIMLog service readiness","Preparación de servicios BIMLog")}</h2><p style={{color:"#64748B"}}>{tt("These services are managed by BIMLog. Your company does not need to enter technical settings.","BIMLog administra estos servicios. Su empresa no necesita ingresar configuraciones técnicas.")}</p><ul style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(220px,100%),1fr))",gap:10,listStyle:"none",padding:0,marginBottom:0}}>{data.platformChecks.map(item=><li key={item.service} style={{padding:12,border:"1px solid #E2E8F0",borderRadius:10,display:"flex",justifyContent:"space-between",gap:10}}><span>{tt(...serviceLabels[item.service])}</span><strong style={{color:item.status==="ready"?"#047857":"#B45309"}}>{item.status==="ready"?tt("Ready","Listo"):tt("BIMLog setup pending","Configuración BIMLog pendiente")}</strong></li>)}</ul><h3 style={{fontSize:16,margin:"18px 0 8px"}}>{tt("Plan checkout coverage","Cobertura de pago por plan")}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(220px,100%),1fr))",gap:10}}>{data.catalogCoverage.map(item=>{const [plan,cycle]=item.slot.split(".");return <div key={item.slot} style={{padding:12,border:"1px solid #E2E8F0",borderRadius:10}}><strong>{tt(...planLabels[plan])}</strong><div style={{fontSize:13,color:"#64748B"}}>{cycle==="monthly"?tt("Monthly billing","Facturación mensual"):tt("Annual billing","Facturación anual")}</div><div style={{fontSize:13,fontWeight:700,color:item.status==="ready"?"#047857":"#B45309"}}>{tt(...catalogStatusLabels[item.status])}</div></div>})}</div></section>
    {data.blockers.length>0&&<section aria-labelledby="commercial-readiness-owners" style={{marginTop:18}}><h2 id="commercial-readiness-owners" style={{fontSize:19}}>{tt("What happens next","Qué sucede ahora")}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(260px,100%),1fr))",gap:12}}><ResponsibilityCard title={tt("Your company","Su empresa")} ready={data.responsibilities.customerReadiness==="ready"} readyText={tt("Nothing else is required from your company.","Su empresa no necesita completar nada más.")} pendingText={tt("Complete these details to continue:","Complete estos datos para continuar:")} blockers={data.responsibilities.customer} labels={labels} tt={tt}/><ResponsibilityCard title="BIMLog" ready={data.responsibilities.platformReadiness==="ready"} readyText={tt("The BIMLog commercial services are configured.","Los servicios comerciales de BIMLog están configurados.")} pendingText={tt("BIMLog must finish these platform services. You do not need to configure them:","BIMLog debe completar estos servicios de plataforma. Usted no necesita configurarlos:")} blockers={data.responsibilities.bimlog} labels={labels} tt={tt}/></div></section>}
    {data.billingAuthority.canManageBilling&&<section aria-labelledby="billing-self-service" style={{marginTop:18,padding:18,border:"1px solid #CBD5E1",borderRadius:12,background:"white"}}><h2 id="billing-self-service" style={{fontSize:19,marginTop:0}}>{tt("Billing self-service","Autoservicio de facturación")}</h2><p style={{color:"#64748B"}}>{tt("Choose the subscription already prepared for your company, or open Stripe to manage an active account.","Elija la suscripción ya preparada para su empresa o abra Stripe para administrar una cuenta activa.")}</p><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><label>{tt("Plan","Plan")}<select value={plan} onChange={event=>setPlan(event.target.value as typeof plan)} disabled={billingBusy} style={{display:"block",padding:8,marginTop:4}}><option value="professional">Professional</option><option value="team">Team</option><option value="business">Business</option></select></label><label>{tt("Billing cycle","Ciclo de facturación")}<select value={cycle} onChange={event=>setCycle(event.target.value as typeof cycle)} disabled={billingBusy} style={{display:"block",padding:8,marginTop:4}}><option value="monthly">{tt("Monthly","Mensual")}</option><option value="annual">{tt("Annual","Anual")}</option></select></label><Button disabled={billingBusy||data.paymentProviderStatus!=="ready"} onClick={async()=>{setBillingBusy(true);setBillingError("");try{const destination=await requestCommercialHostedDestination({token:token??"",action:"checkout",plan,cycle,requestKey:crypto.randomUUID()});window.location.assign(destination.url);}catch(reason){setBillingError(reason instanceof Error?reason.message:String(reason));setBillingBusy(false);}}}>{tt("Start secure checkout","Iniciar pago seguro")}</Button><Button variant="outline" disabled={billingBusy||data.billingPortalStatus!=="ready"} onClick={async()=>{setBillingBusy(true);setBillingError("");try{const destination=await requestCommercialHostedDestination({token:token??"",action:"billing-portal"});window.location.assign(destination.url);}catch(reason){setBillingError(reason instanceof Error?reason.message:String(reason));setBillingBusy(false);}}}>{tt("Manage billing","Administrar facturación")}</Button></div>{billingError&&<p role="alert" style={{color:"#B91C1C",marginBottom:0}}>{billingError}</p>}</section>}
    {data.billingAuthority.canManageBilling&&<BillingHistoryPanel token={token??""}/>}
    <section aria-labelledby="commercial-next-steps" style={{marginTop:18}}><h2 id="commercial-next-steps" style={{fontSize:19}}>{tt("Next steps","Próximos pasos")}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(240px,100%),1fr))",gap:12}}>{data.actions.map(action=><ActionCard key={action.id} action={action} labels={labels} tt={tt}/>)}</div></section><SupportCasesPanel/></>}
  </main></div></div>;
}
function StatusCard({icon,title,ready,tt}:{icon:React.ReactNode;title:string;ready:boolean;tt:(en:string,es:string)=>string}){return <section style={{padding:18,border:"1px solid #E2E8F0",borderRadius:12,background:"white"}}><div style={{color:"#2563EB",marginBottom:10}}>{icon}</div><strong>{title}</strong><div style={{marginTop:7,color:ready?"#047857":"#B45309",fontSize:13,fontWeight:700}}>{ready?tt("Ready","Listo"):tt("Setup required","Requiere configuración")}</div></section>}
function ResponsibilityCard({title,ready,readyText,pendingText,blockers,labels,tt}:{title:string;ready:boolean;readyText:string;pendingText:string;blockers:string[];labels:Record<string,[string,string]>;tt:(en:string,es:string)=>string}){return <article style={{padding:18,border:`1px solid ${ready?"#A7F3D0":"#FDE68A"}`,background:ready?"#F0FDF4":"#FFFBEB",borderRadius:12}}><strong>{title}</strong><p style={{margin:"7px 0",color:"#475569"}}>{ready?readyText:pendingText}</p>{blockers.length>0&&<ul style={{marginBottom:0}}>{blockers.map(code=><li key={code}>{tt(...(labels[code]??[code,code]))}</li>)}</ul>}</article>}
function ActionCard({action,labels,tt}:{action:CommercialWorkspaceDto["actions"][number];labels:Record<string,[string,string]>;tt:(en:string,es:string)=>string}){const copy={complete_billing_identity:["Complete billing identity","Completar identidad de facturación","Add the company details required for invoices.","Agregue los datos de la empresa requeridos para facturas."],review_plans:["Review plans","Revisar planes","Compare the available BIMLog plans and features.","Compare los planes y funciones disponibles de BIMLog."],contact_support:["Contact support","Contactar soporte","Ask BIMLog for help with billing or account setup.","Solicite ayuda de BIMLog con facturación o configuración de cuenta."]}[action.id];return <article style={{padding:18,border:"1px solid #E2E8F0",borderRadius:12,background:"white",display:"flex",flexDirection:"column",gap:10,minWidth:0}}><strong>{tt(copy[0],copy[1])}</strong><p style={{margin:0,color:"#64748B",fontSize:14}}>{tt(copy[2],copy[3])}</p>{action.status==="complete"?<span style={{display:"inline-flex",alignItems:"center",gap:6,color:"#047857",fontWeight:700}}><CheckCircle2 aria-hidden="true" size={16}/>{tt("Complete","Completado")}</span>:action.status==="blocked"?<Button disabled aria-describedby={`blocked-${action.id}`}>{tt("Unavailable until setup is complete","No disponible hasta completar la configuración")}</Button>:<Button asChild><Link href={action.href}>{tt("Continue","Continuar")}</Link></Button>}{action.status==="blocked"&&<div id={`blocked-${action.id}`} style={{color:"#92400E",fontSize:12}}><span>{tt("Waiting for:","En espera de:")}</span><ul style={{margin:"4px 0 0",paddingLeft:18}}>{action.blockers.map(code=><li key={code}>{tt(...(labels[code]??[code,code]))}</li>)}</ul></div>}</article>}
