import assert from "node:assert/strict";import fs from "node:fs";
const source=fs.readFileSync(new URL("./CommercialWorkspace.tsx",import.meta.url),"utf8");
for(const token of ["Billing & Support","Facturación y Soporte","/api/v1/commercial/workspace","Loading commercial status","Status unavailable","Action required","What happens next"])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));
for(const token of ["Next steps","Próximos pasos","Complete billing identity","Review plans","Contact support","Unavailable until setup is complete"])assert.match(source,new RegExp(token));
for(const token of ["What happens next","Qué sucede ahora","Your company","You do not need to configure them","data.responsibilities.customer","data.responsibilities.bimlog"])assert.match(source,new RegExp(token));
for(const token of ["parseCommercialCheckoutReturn","Checkout received","Checkout cancelled","verifying the provider confirmation","No subscription change was claimed"])assert.match(source,new RegExp(token));
assert.match(source,/data\.actions\.map/);assert.match(source,/action\.status==="blocked"/);assert.match(source,/Button disabled/);
assert.match(source,/AbortController/);assert.match(source,/parseCommercialWorkspace/);assert.doesNotMatch(source,/stripe.*secret/i);
console.log("B069 bilingual Billing & Support workspace: PASS");
const app=fs.readFileSync(new URL("../App.tsx",import.meta.url),"utf8"),sidebar=fs.readFileSync(new URL("../components/layout/MasterSidebar.tsx",import.meta.url),"utf8");
assert.match(app,/settings\/billing-support/);assert.match(app,/ProtectedRoute component=\{CommercialWorkspace\}/);assert.match(sidebar,/Billing & Support/);assert.match(sidebar,/Facturación y Soporte/);
console.log("B070 discoverable protected commercial workspace acceptance: PASS");
