import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const read = (path: string) => readFileSync(fileURLToPath(new URL(path, import.meta.url)), "utf8");
const app = read("../App.tsx"), page = read("./CoordinationKnowledgeLibrary.tsx"), css = read("./CoordinationKnowledgeLibrary.css");
const sidebar = read("../components/layout/MasterSidebar.tsx"), accessibility = read("../components/layout/RouteAccessibility.tsx");

assert.match(app, /Route path="\/knowledge"/);
assert.match(app, /ProtectedRoute component=\{CoordinationKnowledgeLibrary\}/);
assert.match(sidebar, /Coordination Knowledge/);
assert.match(accessibility, /"\/knowledge": "Coordination Knowledge Library"/);
for (const section of ["conflict-types", "rules", "methods", "lessons"]) assert.ok(page.includes(`id: "${section}"`));
assert.match(page, /role="tablist"/); assert.match(page, /role="tab"/); assert.match(page, /role="tabpanel"/);
assert.match(page, /ArrowRight/); assert.match(page, /ArrowLeft/); assert.match(page, /Home/); assert.match(page, /End/);
assert.match(css, /@media \(max-width: 720px\)/); assert.doesNotMatch(page, /BIMLens/);
assert.match(page, /coordination-knowledge\/capabilities/);
assert.match(page, /coordination-knowledge\/conflict-types/);
for (const filter of ["discipline", "element", "category", "status", "tag"]) assert.match(page, new RegExp(filter));
assert.match(css, /knowledge-status-approved/); assert.match(css, /knowledge-status-retired/);
assert.match(page, /role="alert"/); assert.match(page, /Try again/); assert.match(page, /No Conflict Types yet/);
assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(page, /coordination-knowledge\/rules/); assert.match(page, /\/history/);
for (const field of ["guidance", "applicability", "approved_by_id", "references", "conflictTypeIds"]) assert.match(page, new RegExp(field));
assert.match(page, /Only approved guidance is visible in this role/);
assert.match(page, /View revision history/); assert.match(page, /History is unavailable/);
assert.match(page, /coordination-knowledge\/resolution-methods/);
for (const field of ["conflict_type_ids", "responsible_trade", "rfi_requirement", "required_approvals", "rule_revision_ids", "previousCases"]) assert.match(page, new RegExp(field));
assert.match(page, /Options, not instructions/); assert.match(page, /Historical reference only/); assert.match(page, /cannot be selected for a new resolution/);
const repository = read("../../../api-server/src/lib/coordination-knowledge-repository.ts");
assert.match(repository, /listResolutionMethods[\s\S]+conflict_type_ids[\s\S]+rule_revision_ids/);
for (const queueState of ["proposed", "under_review", "approved", "rejected", "merged"]) assert.match(page, new RegExp(queueState));
for (const capability of ["propose_lesson", "review", "promote_approved_lesson"]) assert.match(page, new RegExp(capability));
assert.match(page, /Source issue/); assert.match(page, /Supporting evidence/);
assert.match(page, /No automatic approval is performed/); assert.match(page, /Submission never approves or changes company knowledge automatically/);
assert.match(page, /Separate controlled action/); assert.match(css, /knowledge-lesson-contract/);
console.log("Coordination Knowledge Build 236 workspace shell: navigation, responsive layout and keyboard tabs passed");
console.log("Coordination Knowledge Build 237 Conflict Type catalog: permission scope, filters, revision/status semantics and loading/empty/error states passed");
console.log("Coordination Knowledge Build 238 Rules catalog: applicability/status filters, approval distinction, references and authorized revision history passed");
console.log("Coordination Knowledge Build 239 Resolution Methods catalog: governed filters, related rules/cases, optional semantics and retired-selection protection passed");
console.log("Coordination Knowledge Build 240 Lessons Learned queue shell: lifecycle states, permission boundaries, source evidence and no-auto-approval semantics passed");
