import { Link } from "wouter";
import { useI18n } from "@/lib/i18n";
import { Footer } from "@/components/layout/Footer";
import { ChevronLeft } from "lucide-react";

const CONTENT = {
  en: {
    title: "Platform Disclaimer",
    effectiveDate: "March 21, 2026",
    intro: "Important Notice Regarding the Use of BIMLog Data and Reports\n\nBIMLog is a data recording, tracking, and reporting platform operated by BIMCapital Partners INC through its IgniteSmart technology division. The following disclaimer applies to all data, reports, audit certificates, delay attribution analyses, compliance summaries, and any other outputs generated by the BIMLog platform.",
    sections: [
      {
        heading: "1. BIMLog Is Not a Legal Authority",
        body: "BIMLog records, organizes, and presents project data provided by platform users and connected third-party systems. BIMLog does not provide legal advice, legal determinations, or legal conclusions of any kind. Nothing on the BIMLog platform constitutes legal advice or creates an attorney-client relationship.",
      },
      {
        heading: "2. Informational Records Only",
        body: "All reports, audit trails, delay attribution analyses, audit certificates, compliance summaries, and all other outputs generated by BIMLog constitute informational records based on data submitted to and processed by the platform. They do not constitute legal findings, binding determinations of liability, fault, or contractual responsibility, and they do not constitute admissions by any party.",
      },
      {
        heading: "3. Timestamp Integrity",
        body: "All timestamps recorded by BIMLog reflect the actual date and time of each recorded event as registered by BIMLog servers in Coordinated Universal Time (UTC). Timestamps are recorded server-side and cannot be modified by users. BIMLog certifies that all audit trail entries are append-only and cannot be altered after recording.",
      },
      {
        heading: "4. SHA-256 Document Integrity",
        body: "File integrity is verified by SHA-256 cryptographic hash where technically applicable. For Revit, Navisworks, and other proprietary BIM file formats, file identity is verified by hash of the submitted file. Content comparison is not available without the originating software license. The SHA-256 hash proves that a specific file was submitted at a specific time by a specific user but does not verify the accuracy or completeness of the file's content.",
      },
      {
        heading: "5. User Responsibility",
        body: "Users are solely responsible for the accuracy, completeness, and appropriateness of all data submitted to BIMLog. BIMCapital Partners INC makes no representation that BIMLog outputs are accurate, complete, or suitable for use in legal proceedings, arbitration, or contract dispute resolution without independent verification by qualified professionals.",
      },
      {
        heading: "6. Use in Legal Proceedings",
        body: "Any use of BIMLog data, reports, Audit Certificates, or any other platform output in legal proceedings, arbitration, contract administration, dispute resolution, backcharge proceedings, or any other legal or quasi-legal context is undertaken solely at the user's risk. BIMCapital Partners INC expressly disclaims all liability arising from such use. Users are advised to consult qualified legal counsel before using any BIMLog output in any legal or contractual proceeding.",
      },
      {
        heading: "7. Contact",
        body: "info@ignitesmart.ai\nBIMCapital Partners INC\n7901 4th Street North STE 300\nSt. Petersburg FL 33702",
      },
    ],
  },
  es: {
    title: "Aviso Legal de la Plataforma",
    effectiveDate: "21 de marzo de 2026",
    intro: "Aviso Importante Sobre el Uso de Datos e Informes de BIMLog\n\nBIMLog es una plataforma de registro, seguimiento e informes de datos operada por BIMCapital Partners INC a través de su división tecnológica IgniteSmart. El siguiente aviso aplica a todos los datos, informes, certificados de auditoría, análisis de atribución de retrasos, resúmenes de cumplimiento y cualquier otro resultado generado por la plataforma BIMLog.",
    sections: [
      {
        heading: "1. BIMLog No Es una Autoridad Legal",
        body: "BIMLog registra, organiza y presenta datos de proyectos proporcionados por usuarios de la plataforma y sistemas de terceros conectados. BIMLog no proporciona asesoramiento legal, determinaciones legales ni conclusiones legales de ningún tipo. Nada en la plataforma BIMLog constituye asesoramiento legal ni crea una relación abogado-cliente.",
      },
      {
        heading: "2. Solo Registros Informativos",
        body: "Todos los informes, registros de auditoría, análisis de atribución de retrasos, certificados de auditoría, resúmenes de cumplimiento y todos los demás resultados generados por BIMLog constituyen registros informativos basados en datos enviados y procesados por la plataforma. No constituyen hallazgos legales, determinaciones vinculantes de responsabilidad, culpa o responsabilidad contractual, y no constituyen admisiones de ninguna parte.",
      },
      {
        heading: "3. Integridad de las Marcas de Tiempo",
        body: "Todas las marcas de tiempo registradas por BIMLog reflejan la fecha y hora reales de cada evento registrado tal como lo registran los servidores de BIMLog en Tiempo Universal Coordinado (UTC). Las marcas de tiempo se registran del lado del servidor y no pueden ser modificadas por los usuarios. BIMLog certifica que todas las entradas del registro de auditoría son de solo anexión y no pueden ser alteradas después del registro.",
      },
      {
        heading: "4. Integridad de Documentos SHA-256",
        body: "La integridad de los archivos se verifica mediante hash criptográfico SHA-256 donde sea técnicamente aplicable. Para Revit, Navisworks y otros formatos de archivo BIM propietarios, la identidad del archivo se verifica por hash del archivo enviado. La comparación de contenido no está disponible sin la licencia de software de origen. El hash SHA-256 demuestra que un archivo específico fue enviado en un momento específico por un usuario específico, pero no verifica la exactitud o completitud del contenido del archivo.",
      },
      {
        heading: "5. Responsabilidad del Usuario",
        body: "Los usuarios son los únicos responsables de la exactitud, completitud y adecuación de todos los datos enviados a BIMLog. BIMCapital Partners INC no hace ninguna representación de que los resultados de BIMLog sean exactos, completos o adecuados para su uso en procedimientos legales, arbitraje o resolución de disputas contractuales sin verificación independiente por profesionales calificados.",
      },
      {
        heading: "6. Uso en Procedimientos Legales",
        body: "Cualquier uso de datos, informes, Certificados de Auditoría u otros resultados de la plataforma de BIMLog en procedimientos legales, arbitraje, administración contractual, resolución de disputas, procedimientos de contracargo o cualquier otro contexto legal o cuasi-legal se realiza únicamente bajo el riesgo del usuario. BIMCapital Partners INC renuncia expresamente a toda responsabilidad derivada de dicho uso. Se aconseja a los usuarios consultar con un asesor legal calificado antes de usar cualquier resultado de BIMLog en cualquier procedimiento legal o contractual.",
      },
      {
        heading: "7. Contacto",
        body: "info@ignitesmart.ai\nBIMCapital Partners INC\n7901 4th Street North STE 300\nSt. Petersburg FL 33702",
      },
    ],
  },
};

export function Disclaimer() {
  const { language, t } = useI18n();
  const content = language === "es" ? CONTENT.es : CONTENT.en;

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 24px", flex: 1 }}>
        <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 4, fontSize: 13, color: "hsl(var(--muted-foreground))", textDecoration: "none", marginBottom: 32 }}>
          <ChevronLeft style={{ width: 14, height: 14 }} />
          {t("legal.backToHome")}
        </Link>

        <div style={{ marginBottom: 8 }}>
          <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "hsl(var(--primary))", background: "hsl(var(--primary)/0.08)", padding: "3px 10px", borderRadius: 4 }}>Legal</span>
        </div>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: "hsl(var(--foreground))", marginBottom: 8, fontFamily: "var(--font-display)" }}>{content.title}</h1>
        <div style={{ fontSize: 13, color: "hsl(var(--muted-foreground))", marginBottom: 32 }}>
          {t("legal.effectiveDate")}: {content.effectiveDate} · BIMCapital Partners INC · info@ignitesmart.ai
        </div>

        <div style={{ background: "hsl(var(--muted)/0.4)", border: "1px solid hsl(var(--border))", borderRadius: 8, padding: "16px 20px", marginBottom: 32 }}>
          {content.intro.split("\n\n").map((para, i) => (
            <p key={i} style={{ fontSize: 14, color: "hsl(var(--foreground))", lineHeight: 1.7, marginBottom: i < 1 ? 8 : 0, fontWeight: i === 0 ? 600 : 400 }}>{para}</p>
          ))}
        </div>

        <div style={{ borderTop: "1px solid hsl(var(--border))", paddingTop: 32 }}>
          {content.sections.map((sec, i) => (
            <div key={i} style={{ marginBottom: 32 }}>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: "hsl(var(--foreground))", marginBottom: 10, fontFamily: "var(--font-display)" }}>{sec.heading}</h2>
              {sec.body.split("\n\n").map((para, j) => (
                <p key={j} style={{ fontSize: 14, color: "hsl(var(--muted-foreground))", lineHeight: 1.7, marginBottom: 10, whiteSpace: "pre-line" }}>{para}</p>
              ))}
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}
