import { Link } from "wouter";
import { ArrowRight, CheckCircle2, ChevronLeft, LockKeyhole } from "lucide-react";
import { Footer } from "@/components/layout/Footer";
import { useI18n } from "@/lib/i18n";

export const VERIFIED_CAPABILITIES = [
  { role: ["BIM Coordinator", "Coordinador BIM"], title: ["Coordinate daily delivery", "Coordinar la entrega diaria"], description: ["Open project workspaces for files, RFIs, submittals, meetings, clashes, viewpoints, and Job Operations.", "Abra espacios del proyecto para archivos, RFIs, submittals, reuniones, interferencias, puntos de vista y Operaciones."], availability: ["Project membership required", "Requiere membresía del proyecto"], prerequisite: ["An administrator creates the project and grants access.", "Un administrador crea el proyecto y concede acceso."], href: "/help?topic=command-center" },
  { role: ["BIM Manager", "Gerente BIM"], title: ["Set up governed project work", "Configurar trabajo de proyecto controlado"], description: ["Use full Job Intake to define scope, contracts, delivery workflows, disciplines, levels, resources, and the activation review.", "Use el Ingreso completo para definir alcance, contratos, flujos, disciplinas, niveles, recursos y revisión de activación."], availability: ["Authorized project roles", "Roles de proyecto autorizados"], prerequisite: ["Company catalogs and financial authorities can limit available choices.", "Los catálogos y autoridades financieras pueden limitar las opciones."], href: "/help?topic=job-intake" },
  { role: ["Project Administrator", "Administrador de Proyecto"], title: ["Control access and conventions", "Controlar acceso y convenciones"], description: ["Manage project membership, naming conventions, integrations, and approved workflow configuration.", "Administre membresía, convenciones, integraciones y configuración aprobada."], availability: ["Administrative permission required", "Requiere permiso administrativo"], prerequisite: ["External providers work only after their connector is configured and validated.", "Los proveedores externos funcionan después de configurar y validar su conector."], href: "/help?topic=directory-administration" },
  { role: ["Commercial / Operations", "Comercial / Operaciones"], title: ["Connect planned and actual work", "Conectar trabajo planificado y real"], description: ["Review contract items, governed APU versions, planned resources, actual hours, progress, deliverables, and forecasts.", "Revise partidas, versiones APU controladas, recursos planificados, horas reales, avance, entregables y pronósticos."], availability: ["Entitlement and project authority required", "Requiere habilitación y autoridad del proyecto"], prerequisite: ["Financial values remain hidden when the signed-in role lacks access.", "Los valores financieros permanecen ocultos sin acceso del rol."], href: "/help?topic=job-operations" },
] as const;

export function Features() {
  const { lang, tt } = useI18n(); const i = lang === "es" ? 1 : 0;
  return <div className="min-h-screen bg-background flex flex-col"><main className="flex-1 max-w-6xl mx-auto w-full px-6 py-12">
    <Link href="/" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground mb-10"><ChevronLeft size={16}/>{tt("Back to home", "Volver al inicio")}</Link>
    <div className="max-w-3xl mb-12"><p className="text-xs font-bold uppercase tracking-widest text-primary mb-3">{tt("Verified product capabilities", "Capacidades verificadas")}</p><h1 className="font-display text-4xl md:text-5xl font-bold mb-5">{tt("Start with your role and the job you need to complete", "Comience con su rol y el trabajo que necesita completar")}</h1><p className="text-lg text-muted-foreground leading-relaxed">{tt("Each capability below identifies who uses it, what must exist first, and where to review the released workflow. Availability still depends on the signed-in account, project membership, role, and enabled package.", "Cada capacidad identifica quién la usa, qué debe existir primero y dónde revisar el flujo publicado. La disponibilidad depende de la cuenta, membresía, rol y paquete habilitado.")}</p></div>
    <div className="grid md:grid-cols-2 gap-5">{VERIFIED_CAPABILITIES.map((item)=><article key={item.title[0]} className="card p-6 flex flex-col"><span className="text-xs font-bold text-primary uppercase tracking-wide">{item.role[i]}</span><h2 className="font-display text-xl font-bold mt-2 mb-3">{item.title[i]}</h2><p className="text-sm text-muted-foreground leading-relaxed mb-5">{item.description[i]}</p><div className="space-y-3 mb-6"><div className="flex gap-2 text-sm"><CheckCircle2 className="w-4 h-4 mt-0.5 text-emerald-600 shrink-0"/><span>{item.availability[i]}</span></div><div className="flex gap-2 text-sm text-muted-foreground"><LockKeyhole className="w-4 h-4 mt-0.5 shrink-0"/><span>{item.prerequisite[i]}</span></div></div><Link href={item.href} className="mt-auto inline-flex min-h-11 items-center gap-2 font-semibold text-primary hover:underline">{tt("Review the task guide", "Revisar la guía de trabajo")}<ArrowRight size={16}/></Link></article>)}</div>
    <div className="surface rounded-2xl p-6 mt-8"><h2 className="font-display text-xl font-bold mb-2">{tt("Need to verify your exact access?", "¿Necesita verificar su acceso exacto?")}</h2><p className="text-sm text-muted-foreground mb-4">{tt("Sign in and open the project. BIMLog shows unavailable actions with their required role, configuration, or entitlement.", "Inicie sesión y abra el proyecto. BIMLog muestra las acciones no disponibles con el rol, configuración o habilitación requerida.")}</p><Link href="/login" className="inline-flex items-center gap-2 font-semibold text-primary">{tt("Sign in", "Iniciar sesión")}<ArrowRight size={16}/></Link></div>
  </main><Footer/></div>;
}
