import { useCallback, useEffect, useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { BriefcaseBusiness, Clock3, FileCheck2, RefreshCw, Save, Trash2, UserRoundCheck } from "lucide-react";
import { FinancialProjectShell } from "@/components/layout/FinancialProjectShell";
import { useAuthStore } from "@/store/auth";
import { useI18n } from "@/lib/i18n";

const API_BASE = (import.meta.env.VITE_API_URL as string | undefined) ?? "";
const css = `
.jo{max-width:1240px;margin:0 auto;padding:24px 0 80px}.jo *{box-sizing:border-box}.jo-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.jo h1{font-size:30px;margin:4px 0}.jo h2{font-size:20px;margin:0}.jo h3{font-size:16px;margin:0}.jo p{color:#536174}.jo button,.jo select,.jo input,.jo textarea{border:1px solid #cbd5e1;border-radius:8px;padding:9px;background:#fff;color:#0f172a}.jo button{cursor:pointer}.jo button.primary{background:#1d4ed8;border-color:#1d4ed8;color:#fff;font-weight:700}.jo button.danger{color:#b42318}.jo button:disabled{opacity:.5;cursor:not-allowed}.jo-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:10px;margin-bottom:18px}.jo-stat,.jo-card{background:#fff;border:1px solid #d9e1ec;border-radius:14px}.jo-stat{padding:14px}.jo-stat strong{display:block;font-size:22px}.jo-stat span{font-size:12px;color:#64748b}.jo-card{padding:18px;margin-bottom:16px}.jo-item-head{display:flex;justify-content:space-between;gap:12px;align-items:start;margin-bottom:12px}.jo-chip{display:inline-flex;padding:3px 8px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:11px;font-weight:800}.jo-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.jo-task{border:1px solid #e2e8f0;border-radius:12px;padding:14px;margin-top:12px}.jo-task-head{display:flex;justify-content:space-between;gap:10px}.jo label{display:grid;gap:5px;font-size:12px;font-weight:700;color:#475569}.jo-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.jo-progress{height:8px;background:#e8edf5;border-radius:99px;overflow:hidden;margin-top:8px}.jo-progress span{display:block;height:100%;background:#2563eb}.jo-sub{margin-top:12px;padding-top:12px;border-top:1px solid #e2e8f0}.jo-sub h4{margin:0 0 8px}.jo-table{width:100%;border-collapse:collapse;font-size:13px}.jo-table th,.jo-table td{text-align:left;padding:8px;border-bottom:1px solid #e2e8f0}.jo-empty,.jo-error,.jo-ok{padding:16px;border-radius:12px;margin-bottom:14px}.jo-empty{background:#eff6ff}.jo-error{background:#fff1f2;color:#9f1239}.jo-ok{background:#ecfdf5;color:#166534}.jo-muted{font-size:12px;color:#64748b}.jo-financial{background:#f0fdf4}.jo-forms{display:grid;grid-template-columns:1fr 1fr;gap:12px}.jo-form{border:1px solid #dbe4f0;border-radius:12px;padding:12px}.jo-form .jo-grid{grid-template-columns:2fr 1fr 1fr}.jo-file{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-bottom:1px solid #e2e8f0}.jo textarea{min-height:40px;resize:vertical}.jo input[type=range]{padding:0}.jo-refresh{display:flex;align-items:center;gap:6px}@media(max-width:900px){.jo-grid,.jo-form .jo-grid{grid-template-columns:1fr 1fr}.jo-forms{grid-template-columns:1fr}.jo-head,.jo-item-head{display:block}.jo-table{display:block;overflow:auto}}@media(max-width:560px){.jo-grid,.jo-form .jo-grid{grid-template-columns:1fr}}
`;

const n = (value: unknown) => Number(value ?? 0);
const money = (value: unknown) => n(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const today = () => new Date().toISOString().slice(0, 10);

export function JobOperationsWorkspace() {
  const { token } = useAuthStore();
  const { language, tt } = useI18n();
  const [, route] = useRoute("/projects/:id/operations");
  const projectId = Number(route?.id);
  const [data, setData] = useState<any>(null);
  const [drafts, setDrafts] = useState<Record<string, any>>({});
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const headers = useMemo(() => ({ Authorization: `Bearer ${token}` }), [token]);
  const api = useCallback(async (path: string, init?: RequestInit) => {
    const response = await fetch(`${API_BASE}/api/v1${path}`, { ...init, headers: { ...headers, ...(init?.headers ?? {}) } });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error((language === "es" ? payload?.error?.es : payload?.error?.en) || payload?.error?.en || tt("The request failed.", "La solicitud falló."));
    return payload;
  }, [headers, language, tt]);
  const load = useCallback(async () => {
    if (!projectId) return;
    setBusy(true); setError("");
    try {
      const result = await api(`/projects/${projectId}/operations`);
      setData(result);
      setDrafts(Object.fromEntries((result.tasks ?? []).map((task: any) => [task.id, { status: task.status, progressPercent: task.progressPercent, assigneeUserId: task.assigneeUserId ?? "" }])));
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); }
    finally { setBusy(false); }
  }, [api, projectId]);
  useEffect(() => { void load(); }, [load]);

  const mutate = async (path: string, init: RequestInit, message: string) => {
    setBusy(true); setError(""); setNotice("");
    try { await api(path, init); setNotice(message); await load(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); setBusy(false); }
  };
  const json = (body: unknown): RequestInit => ({ method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const tasksFor = (id: string) => data?.tasks?.filter((task: any) => task.workItemId === id) ?? [];
  const assignmentsFor = (id: string) => data?.assignments?.filter((assignment: any) => assignment.workItemId === id) ?? [];
  const taskAssignments = (id: string) => data?.assignments?.filter((assignment: any) => assignment.taskId === id) ?? [];
  const taskDeliverables = (id: string) => data?.deliverables?.filter((item: any) => item.taskId === id) ?? [];
  const statusLabel = (value: string) => ({ not_started: tt("Not started", "No iniciada"), in_progress: tt("In progress", "En progreso"), blocked: tt("Blocked", "Bloqueada"), complete: tt("Complete", "Completada"), cancelled: tt("Cancelled", "Cancelada") } as Record<string, string>)[value] ?? value;
  const deliverableLabel = (value: string) => ({ shop_drawing: tt("Shop drawing", "Plano de taller"), submittal: tt("Submittal", "Submittal"), deliverable: tt("Deliverable", "Entregable"), supporting: tt("Supporting file", "Archivo de apoyo") } as Record<string, string>)[value] ?? value;

  if (!data) return <FinancialProjectShell projectId={projectId} activeTab="operations"><style>{css}</style><main className="jo"><p>{busy ? tt("Loading job operations…", "Cargando operaciones del trabajo…") : error}</p></main></FinancialProjectShell>;
  const total = data.totals ?? {};
  const remaining = Math.max(0, n(total.plannedHours) - n(total.actualHours));
  const progress = data.tasks?.length ? Math.round(data.tasks.reduce((sum: number, task: any) => sum + n(task.progressPercent), 0) / data.tasks.length) : 0;
  return <FinancialProjectShell projectId={projectId} activeTab="operations"><style>{css}</style><main className="jo">
    <header className="jo-head"><div><span className="jo-chip">{tt("COMMAND", "COMANDO")}</span><h1>{tt("Job Operations", "Operaciones del Trabajo")}</h1><p>{tt("Run activated work, assign people, record actual hours, and connect project deliverables.", "Ejecute el trabajo activado, asigne personas, registre horas reales y conecte los entregables del proyecto.")}</p></div><button className="jo-refresh" disabled={busy} onClick={() => void load()}><RefreshCw size={15}/>{tt("Refresh", "Actualizar")}</button></header>
    {error && <div className="jo-error" role="alert">{error}</div>}{notice && <div className="jo-ok">{notice}</div>}
    {!data.available && <div className="jo-empty"><BriefcaseBusiness size={22}/><h2>{tt("Activate Job Intake first", "Primero active el Ingreso del Trabajo")}</h2><p>{tt("Job Operations begins with the work items, tasks, and assignments created by an activated Intake.", "Operaciones del Trabajo comienza con las partidas, tareas y asignaciones creadas por un Ingreso activado.")}</p><Link href={`/projects/${projectId}/intake`}>{tt("Open Job Intake & Setup", "Abrir Ingreso y Configuración del Trabajo")}</Link></div>}
    {data.available && <>
      <section className="jo-summary"><div className="jo-stat"><strong>{money(total.plannedHours)}h</strong><span>{tt("Planned hours", "Horas planificadas")}</span></div><div className="jo-stat"><strong>{money(total.actualHours)}h</strong><span>{tt("Actual hours", "Horas reales")}</span></div><div className="jo-stat"><strong>{money(remaining)}h</strong><span>{tt("Remaining", "Restantes")}</span></div><div className="jo-stat"><strong>{progress}%</strong><span>{tt("Task progress", "Progreso de tareas")}</span></div>{data.capabilities?.budget && <><div className="jo-stat jo-financial"><strong>{money(total.plannedInternalCost)}</strong><span>{tt("Planned internal cost", "Costo interno planificado")}</span></div><div className="jo-stat jo-financial"><strong>{money(total.actualInternalCost)}</strong><span>{tt("Actual internal cost", "Costo interno real")}</span></div></>}{data.capabilities?.cost_value_planner && <><div className="jo-stat jo-financial"><strong>{money(total.plannedBillableValue)}</strong><span>{tt("Planned billable value", "Valor facturable planificado")}</span></div><div className="jo-stat jo-financial"><strong>{money(total.earnedBillableValue)}</strong><span>{tt("Earned billable value", "Valor facturable ganado")}</span></div></>}</section>
      {data.workItems.map((item: any) => <section className="jo-card" key={item.id}><div className="jo-item-head"><div><h2>{item.name}</h2><p>{item.description || tt("Activated scope item", "Partida de alcance activada")}</p></div><div><span className="jo-chip">{money(item.plannedHours)}h</span>{data.capabilities?.cost_value_planner && <span className="jo-chip">{money(item.plannedBillableValue)}</span>}</div></div>
        {assignmentsFor(item.id).length > 0 && <div className="jo-sub"><h4>{tt("Resource plan", "Plan de recursos")}</h4><div style={{overflow:"auto"}}><table className="jo-table"><thead><tr><th>{tt("Person", "Persona")}</th><th>{tt("Role", "Rol")}</th><th>{tt("Planned", "Planificadas")}</th><th>{tt("Actual", "Reales")}</th>{data.capabilities?.budget && <th>{tt("Internal cost", "Costo interno")}</th>}{data.canManage && <th>{tt("Reassign", "Reasignar")}</th>}</tr></thead><tbody>{assignmentsFor(item.id).map((assignment: any) => <tr key={assignment.id}><td>{assignment.personName || "—"}</td><td>{assignment.role}</td><td>{money(assignment.plannedHours)}h</td><td>{money(assignment.actualHours)}h</td>{data.capabilities?.budget && <td>{money(assignment.plannedInternalCost)}</td>}{data.canManage && <td><select aria-label={tt("Reassign resource", "Reasignar recurso")} value={assignment.userId ?? ""} onChange={(event) => void mutate(`/projects/${projectId}/operations/assignments/${assignment.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedVersion: assignment.version, userId: Number(event.target.value) }) }, tt("Resource reassigned.", "Recurso reasignado."))}>{data.members.map((member: any) => <option key={member.id} value={member.id}>{member.fullName || member.email}</option>)}</select></td>}</tr>)}</tbody></table></div></div>}
        {tasksFor(item.id).map((task: any) => { const draft = drafts[task.id] ?? task; return <article className="jo-task" key={task.id}><div className="jo-task-head"><div><h3>{language === "es" ? task.nameEs : task.nameEn}</h3><span className="jo-muted">{statusLabel(task.status)} · {money(task.actualHours)} / {money(task.plannedHours)}h · {task.deliverableCount} {tt("files", "archivos")}</span></div><strong>{task.progressPercent}%</strong></div><div className="jo-progress"><span style={{width:`${task.progressPercent}%`}}/></div>
          <div className="jo-grid" style={{marginTop:10}}><label>{tt("Status", "Estado")}<select disabled={!task.canControl} value={draft.status} onChange={(e)=>setDrafts(old=>({...old,[task.id]:{...draft,status:e.target.value}}))}>{["not_started","in_progress","blocked","complete","cancelled"].map(value=><option key={value} value={value}>{statusLabel(value)}</option>)}</select></label><label>{tt("Progress", "Progreso")}<input disabled={!task.canControl} type="number" min="0" max="100" step="1" value={draft.progressPercent} onChange={(e)=>setDrafts(old=>({...old,[task.id]:{...draft,progressPercent:Number(e.target.value)}}))}/></label><label>{tt("Assignee", "Responsable")}<select disabled={!data.canManage} value={draft.assigneeUserId ?? ""} onChange={(e)=>setDrafts(old=>({...old,[task.id]:{...draft,assigneeUserId:e.target.value}}))}><option value="">{tt("Unassigned", "Sin asignar")}</option>{data.members.map((member:any)=><option key={member.id} value={member.id}>{member.fullName || member.email}</option>)}</select></label><div className="jo-actions"><button className="primary" disabled={busy || !task.canControl} onClick={()=>void mutate(`/projects/${projectId}/operations/tasks/${task.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({expectedVersion:task.version,status:draft.status,progressPercent:draft.progressPercent,assigneeUserId:draft.assigneeUserId?Number(draft.assigneeUserId):null})},tt("Task updated.","Tarea actualizada."))}><Save size={14}/>{tt("Save task", "Guardar tarea")}</button></div></div>
          <div className="jo-forms"><form className="jo-form" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate(`/projects/${projectId}/operations/time`,json({entryId:crypto.randomUUID(),taskId:task.id,assignmentId:form.get("assignmentId")||null,workDate:form.get("workDate"),hours:form.get("hours"),note:form.get("note")}),tt("Actual hours recorded.","Horas reales registradas."));}}><h4><Clock3 size={15}/> {tt("Record actual hours", "Registrar horas reales")}</h4><div className="jo-grid"><label>{tt("Assignment", "Asignación")}<select disabled={!task.canControl} name="assignmentId"><option value="">{tt("Task assignee", "Responsable de la tarea")}</option>{taskAssignments(task.id).map((a:any)=><option key={a.id} value={a.id}>{a.personName}</option>)}</select></label><label>{tt("Date", "Fecha")}<input disabled={!task.canControl} required name="workDate" type="date" defaultValue={today()}/></label><label>{tt("Hours", "Horas")}<input disabled={!task.canControl} required name="hours" type="number" min="0.01" max="24" step="0.01"/></label></div><label>{tt("Work note", "Nota del trabajo")}<textarea disabled={!task.canControl} name="note" maxLength={500}/></label><button className="primary" disabled={busy || !task.canControl}>{tt("Add time", "Agregar horas")}</button></form>
          <form className="jo-form" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate(`/projects/${projectId}/operations/deliverables`,json({linkId:crypto.randomUUID(),taskId:task.id,fileId:Number(form.get("fileId")),deliverableType:form.get("deliverableType"),note:form.get("note")}),tt("Project file linked.","Archivo del proyecto vinculado."));}}><h4><FileCheck2 size={15}/> {tt("Connect deliverable", "Conectar entregable")}</h4><div className="jo-grid"><label>{tt("Project file", "Archivo del proyecto")}<select disabled={!task.canControl} required name="fileId"><option value="">{tt("Choose file", "Seleccione un archivo")}</option>{data.files.map((file:any)=><option key={file.id} value={file.id}>{file.fileName}</option>)}</select></label><label>{tt("Type", "Tipo")}<select disabled={!task.canControl} name="deliverableType">{["shop_drawing","submittal","deliverable","supporting"].map(value=><option key={value} value={value}>{deliverableLabel(value)}</option>)}</select></label></div><label>{tt("Link note", "Nota del vínculo")}<textarea disabled={!task.canControl} name="note" maxLength={500}/></label><button className="primary" disabled={busy || !task.canControl}>{tt("Link file", "Vincular archivo")}</button>{taskDeliverables(task.id).map((link:any)=><div className="jo-file" key={link.id}><span><UserRoundCheck size={13}/> {link.fileName} · {deliverableLabel(link.deliverableType)}</span>{link.canRemove && <button type="button" className="danger" aria-label={tt("Remove link", "Eliminar vínculo")} onClick={()=>void mutate(`/projects/${projectId}/operations/deliverables/${link.id}`,{method:"DELETE"},tt("Link removed.","Vínculo eliminado."))}><Trash2 size={13}/></button>}</div>)}</form></div>
        </article>; })}
      </section>)}
    </>}
  </main></FinancialProjectShell>;
}
