import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Check, ChevronLeft, Star } from "lucide-react";
import { Footer } from "@/components/layout/Footer";
import { useI18n } from "@/lib/i18n";
import { COMMERCIAL_OFFERS, FOUNDING_OFFER, commercialDestination, foundingDestination, journeyAction, offerPrice, type BillingCycle } from "@/lib/commercial-offers";
import { calculateRoiIllustration, ROI_METHOD } from "@/lib/roi-illustration";
import { recordConversionEvent } from "@/lib/conversion-funnel";
import { ConversionBaseline } from "@/components/ConversionBaseline";
export function Pricing(){
 const {tt}=useI18n(); const [billing,setBilling]=useState<BillingCycle>("monthly"); const [useCase,setUseCase]=useState(""); const [roi,setRoi]=useState({events:120,hoursPerEvent:1,hourlyCost:65,annualSoftwareCost:1490}); const illustration=calculateRoiIllustration(roi); const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
 useEffect(()=>{recordConversionEvent("pricing_viewed");},[]);
 return <div style={{minHeight:"100vh",display:"flex",flexDirection:"column"}}><main style={{maxWidth:1180,margin:"0 auto",padding:"40px 24px 72px",width:"100%",flex:1}}>
 <Link href="/" style={{display:"inline-flex",alignItems:"center",gap:4,color:"hsl(var(--muted-foreground))",textDecoration:"none",marginBottom:32}}><ChevronLeft size={15}/>{tt("Back to home","Volver al inicio")}</Link>
 <header style={{maxWidth:760,marginBottom:28}}><span style={{fontWeight:800,color:"hsl(var(--primary))"}}>{tt("PRICING","PRECIOS")}</span><h1 style={{fontSize:38,margin:"8px 0"}}>{tt("Choose the next step that fits your team","Elija el siguiente paso para su equipo")}</h1><p>{tt("Compare the current public offers. Paid access, limits and services become authoritative only in your BIMLog entitlement or signed customer agreement.","Compare las ofertas públicas actuales. El acceso pagado, los límites y los servicios son vinculantes solo en su habilitación de BIMLog o acuerdo firmado.")}</p></header>
 <section aria-label={tt("Offer preferences","Preferencias de oferta")} style={{display:"flex",gap:16,flexWrap:"wrap",alignItems:"end",padding:18,border:"1px solid hsl(var(--border))",borderRadius:12,marginBottom:24}}><div><strong>{tt("Billing illustration","Ilustración de facturación")}</strong><div style={{display:"flex",gap:6,marginTop:8}}>{(["monthly","annual"] as const).map(value=><button key={value} aria-pressed={billing===value} onClick={()=>setBilling(value)}>{tt(value==="monthly"?"Monthly":"Annual",value==="monthly"?"Mensual":"Anual")}</button>)}</div></div><label style={{flex:1,minWidth:240}}>{tt("Primary use case (optional)","Caso de uso principal (opcional)")}<input value={useCase} maxLength={120} onChange={e=>setUseCase(e.target.value)} placeholder={tt("Example: shop drawing coordination","Ejemplo: coordinación de planos de taller")} style={{display:"block",width:"100%",padding:9,marginTop:6}}/></label></section>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14}}>{COMMERCIAL_OFFERS.map(offer=>{const action=journeyAction(offer);return <article key={offer.id} data-journey={offer.journey} style={{display:"flex",flexDirection:"column",border:"1px solid hsl(var(--border))",borderRadius:14,padding:20,background:"hsl(var(--card))"}}><h2 style={{margin:0}}>{offer.name}</h2><p style={{minHeight:54}}>{offer.audience}</p><strong style={{fontSize:22}}>{offerPrice(offer,billing)}</strong><small style={{margin:"6px 0 14px"}}>{billing==="annual"&&offer.annualUsd?tt("Annual total; equivalent to 10 listed monthly payments.","Total anual; equivale a 10 pagos mensuales publicados."):tt("Public price illustration in USD.","Ilustración de precio público en USD.")}</small><p><b>{tt("Limits","Límites")}:</b> {offer.projectLimit==null?tt("Defined by agreement","Definidos por acuerdo"):`${offer.projectLimit} ${tt("active projects","proyectos activos")}`} · {offer.memberLimit==null?tt("Members defined by entitlement","Miembros definidos por habilitación"):`${offer.memberLimit} ${tt("members per project","miembros por proyecto")}`}</p><ul style={{paddingLeft:18,flex:1}}>{offer.included.map(item=><li key={item} style={{marginBottom:8}}><Check size={13} style={{display:"inline",marginRight:6}}/>{item}</li>)}</ul><small>{offer.availability}</small><small style={{minHeight:64,marginTop:8}}><b>{offer.journey==="self_service"?tt("Self-service","Autoservicio"):tt("Sales-assisted","Asistido por ventas")}:</b> {action.detail}</small><a onClick={()=>recordConversionEvent("offer_selected")} href={commercialDestination(offer,billing,useCase)} style={{marginTop:14,padding:10,textAlign:"center",background:"hsl(var(--primary))",color:"white",borderRadius:8,textDecoration:"none",fontWeight:700}}>{tt(action.label,offer.journey==="self_service"?"Crear cuenta gratis":"Solicitar consulta del plan")}</a></article>})}</div>
 <section style={{marginTop:28,padding:24,border:"1px solid #D97706",borderRadius:12}}><Star size={20}/><h2>{tt("Founding Partner interest","Interés en Socio Fundador")}</h2><p><b>{FOUNDING_OFFER.availability}.</b> {FOUNDING_OFFER.terms}</p><a onClick={()=>recordConversionEvent("offer_selected")} href={foundingDestination(billing,useCase)}>{tt("Discuss eligibility","Conversar sobre elegibilidad")}</a></section>
 <section style={{marginTop:32,padding:24,border:"1px solid hsl(var(--border))",borderRadius:12}}><h2>{tt("Build your own coordination-value illustration","Cree su propia ilustración de valor de coordinación")}</h2><p>{tt("Use your own assumptions. This is arithmetic for planning a conversation, not a savings forecast or promised return.","Use sus propios supuestos. Es aritmética para planificar una conversación, no un pronóstico de ahorro ni un retorno prometido.")}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:12}}>{([['events','Coordination events','Eventos de coordinación'],['hoursPerEvent','Potential hours per event','Horas potenciales por evento'],['hourlyCost','Loaded hourly cost (USD)','Costo horario cargado (USD)'],['annualSoftwareCost','Annual software cost (USD)','Costo anual del software (USD)']] as const).map(([key,en,es])=><label key={key}>{tt(en,es)}<input type="number" min="0" step={key==='hoursPerEvent'?'.25':'1'} value={roi[key]} onChange={e=>setRoi(current=>({...current,[key]:Number(e.target.value)}))} style={{display:"block",width:"100%",padding:8,marginTop:5}}/></label>)}</div><div role="status" style={{display:"flex",gap:24,flexWrap:"wrap",marginTop:20}}><span><b>{illustration.potentialHours.toLocaleString()}</b> {tt("potential hours","horas potenciales")}</span><span><b>{money.format(illustration.potentialTimeValue)}</b> {tt("potential time value","valor potencial del tiempo")}</span><span><b>{money.format(illustration.illustrativeDifference)}</b> {tt("illustrative difference","diferencia ilustrativa")}</span></div><details style={{marginTop:14}}><summary>{tt("Formula and limitations","Fórmula y limitaciones")}</summary><p>{ROI_METHOD}</p></details></section>
 <section style={{marginTop:36}}><h2>{tt("Before you choose","Antes de elegir")}</h2><p>{tt("BIMLog can work alongside approved customer systems through governed file exchange. Connector availability depends on provider approval, customer entitlement and deployment configuration. Storage and retention follow the applicable deployment and customer policy.","BIMLog puede trabajar junto a sistemas aprobados mediante intercambio gobernado. La disponibilidad de conectores depende del proveedor, la habilitación y la configuración. El almacenamiento y la retención siguen la política aplicable.")}</p></section>
 <ConversionBaseline/>
 </main><Footer/></div>;
}
