import { Link } from "wouter";
import { useI18n } from "@/lib/i18n";
import { Footer } from "@/components/layout/Footer";
import { ChevronLeft } from "lucide-react";

const CONTENT = {
  en: {
    title: "Terms of Service",
    effectiveDate: "March 21, 2026",
    lastUpdated: "March 21, 2026",
    sections: [
      {
        heading: "1. Agreement",
        body: "By creating an account or using BIMLog you agree to these Terms of Service. If you do not agree do not use the platform. These Terms constitute a legally binding agreement between you and BIMCapital Partners INC.",
      },
      {
        heading: "2. What BIMLog Is",
        body: "BIMLog is a data recording, tracking, and reporting platform for the AEC industry. BIMLog records, organizes, and presents project data provided by platform users and connected third-party systems. BIMLog is not a legal authority. BIMLog does not provide legal advice, legal determinations, or legal conclusions. Reports, audit trails, delay attribution analyses, and all other outputs generated by BIMLog constitute informational records based on data submitted to the platform. They do not constitute legal findings, binding determinations of liability, or admissions by any party.",
      },
      {
        heading: "3. Your Account",
        body: "You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account. You must be at least 18 years old to use BIMLog. You must provide accurate and complete information when creating your account.",
      },
      {
        heading: "4. Acceptable Use",
        body: "You agree not to use BIMLog for any unlawful purpose, upload malicious files or code, attempt to gain unauthorized access to other accounts or platform infrastructure, use the platform to harass or harm other users, scrape or extract platform data in bulk without written permission, or resell or sublicense access to the platform without written permission from BIMCapital Partners INC.",
      },
      {
        heading: "5. Data Ownership",
        body: "All project data submitted to BIMLog belongs to the project owner and the submitting organization. BIMCapital Partners INC does not claim ownership of any project data, files, RFIs, submittals, or any other content submitted by users. BIMCapital Partners INC may use anonymized and aggregated data for platform improvement and industry benchmarking purposes only, with no personally identifiable information included.",
      },
      {
        heading: "6. Subscription and Payment",
        body: "BIMLog offers a free tier and paid subscription tiers. Free tier access is provided as-is with no service level guarantee. Paid subscriptions are billed in advance on a monthly or annual basis. Refunds are not provided for partial periods. BIMCapital Partners INC reserves the right to change pricing with 30 days written notice to active subscribers.",
      },
      {
        heading: "7. Limitation of Liability",
        body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BIMCAPITAL PARTNERS INC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF BIMLOG. THE TOTAL LIABILITY OF BIMCAPITAL PARTNERS INC TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE PLATFORM SHALL NOT EXCEED THE AMOUNT YOU PAID TO BIMCAPITAL PARTNERS INC IN THE THREE MONTHS PRECEDING THE CLAIM.",
      },
      {
        heading: "8. Use of Reports and Audit Certificates in Legal Proceedings",
        body: "Any use of BIMLog data, reports, Audit Certificates, or any other platform output in legal proceedings, arbitration, contract dispute resolution, or backcharge proceedings is undertaken solely at the user's risk. BIMCapital Partners INC expressly disclaims all liability arising from such use. Users are solely responsible for verifying the accuracy and completeness of all data submitted to BIMLog before relying on platform outputs for any purpose.",
      },
      {
        heading: "9. Service Availability",
        body: "BIMCapital Partners INC will make reasonable efforts to maintain platform availability but does not guarantee uninterrupted access. Scheduled maintenance will be communicated in advance where possible.",
      },
      {
        heading: "10. Termination",
        body: "BIMCapital Partners INC reserves the right to suspend or terminate accounts that violate these Terms. Upon termination your access to the platform will cease but your data will be retained according to our Data Retention Policy.",
      },
      {
        heading: "11. Governing Law",
        body: "These Terms of Service are governed by the laws of the State of Florida, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Pinellas County, Florida.",
      },
      {
        heading: "12. Changes to These Terms",
        body: "We may update these Terms from time to time. We will notify registered users by email of any material changes. Continued use of BIMLog after notification constitutes acceptance of the updated terms.",
      },
      {
        heading: "13. Contact",
        body: "info@ignitesmart.ai\nBIMCapital Partners INC\n7901 4th Street North STE 300\nSt. Petersburg FL 33702",
      },
    ],
  },
  es: {
    title: "Términos de Servicio",
    effectiveDate: "21 de marzo de 2026",
    lastUpdated: "21 de marzo de 2026",
    sections: [
      {
        heading: "1. Acuerdo",
        body: "Al crear una cuenta o usar BIMLog usted acepta estos Términos de Servicio. Si no está de acuerdo no use la plataforma. Estos Términos constituyen un acuerdo legalmente vinculante entre usted y BIMCapital Partners INC.",
      },
      {
        heading: "2. Qué es BIMLog",
        body: "BIMLog es una plataforma de registro, seguimiento e informes de datos para la industria AEC. BIMLog registra, organiza y presenta datos de proyectos proporcionados por usuarios de la plataforma y sistemas de terceros conectados. BIMLog no es una autoridad legal. BIMLog no proporciona asesoramiento legal, determinaciones legales ni conclusiones legales. Los informes, registros de auditoría, análisis de atribución de retrasos y todos los demás resultados generados por BIMLog constituyen registros informativos basados en datos enviados a la plataforma. No constituyen hallazgos legales, determinaciones vinculantes de responsabilidad ni admisiones de ninguna parte.",
      },
      {
        heading: "3. Su Cuenta",
        body: "Usted es responsable de mantener la confidencialidad de sus credenciales de cuenta. Usted es responsable de toda la actividad que ocurra bajo su cuenta. Debe tener al menos 18 años para usar BIMLog. Debe proporcionar información precisa y completa al crear su cuenta.",
      },
      {
        heading: "4. Uso Aceptable",
        body: "Usted acepta no usar BIMLog para ningún propósito ilegal, cargar archivos o código malicioso, intentar obtener acceso no autorizado a otras cuentas o infraestructura de la plataforma, usar la plataforma para acosar o dañar a otros usuarios, raspar o extraer datos de la plataforma en masa sin permiso escrito, o revender o sublicenciar el acceso a la plataforma sin permiso escrito de BIMCapital Partners INC.",
      },
      {
        heading: "5. Propiedad de los Datos",
        body: "Todos los datos de proyectos enviados a BIMLog pertenecen al propietario del proyecto y a la organización que los envía. BIMCapital Partners INC no reclama la propiedad de ningún dato de proyecto, archivos, RFIs, entregables ni ningún otro contenido enviado por los usuarios. BIMCapital Partners INC puede usar datos anonimizados y agregados solo para mejora de la plataforma y benchmarking de la industria, sin información de identificación personal incluida.",
      },
      {
        heading: "6. Suscripción y Pago",
        body: "BIMLog ofrece un nivel gratuito y niveles de suscripción de pago. El acceso al nivel gratuito se proporciona tal como está sin garantía de nivel de servicio. Las suscripciones de pago se facturan por adelantado de forma mensual o anual. No se proporcionan reembolsos por períodos parciales. BIMCapital Partners INC se reserva el derecho de cambiar los precios con 30 días de aviso escrito a los suscriptores activos.",
      },
      {
        heading: "7. Limitación de Responsabilidad",
        body: "EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE, BIMCAPITAL PARTNERS INC NO SERÁ RESPONSABLE DE NINGÚN DAÑO INDIRECTO, INCIDENTAL, ESPECIAL, CONSECUENTE O PUNITIVO DERIVADO DE SU USO DE BIMLOG. LA RESPONSABILIDAD TOTAL DE BIMCAPITAL PARTNERS INC HACIA USTED POR CUALQUIER RECLAMACIÓN DERIVADA DE ESTOS TÉRMINOS O SU USO DE LA PLATAFORMA NO EXCEDERÁ EL MONTO QUE USTED PAGÓ A BIMCAPITAL PARTNERS INC EN LOS TRES MESES ANTERIORES A LA RECLAMACIÓN.",
      },
      {
        heading: "8. Uso de Informes y Certificados de Auditoría en Procedimientos Legales",
        body: "Cualquier uso de datos, informes, Certificados de Auditoría u otros resultados de la plataforma de BIMLog en procedimientos legales, arbitraje, resolución de disputas contractuales o procedimientos de contracargo se realiza únicamente bajo el riesgo del usuario. BIMCapital Partners INC renuncia expresamente a toda responsabilidad derivada de dicho uso. Los usuarios son los únicos responsables de verificar la exactitud y completitud de todos los datos enviados a BIMLog antes de confiar en los resultados de la plataforma para cualquier propósito.",
      },
      {
        heading: "9. Disponibilidad del Servicio",
        body: "BIMCapital Partners INC hará esfuerzos razonables para mantener la disponibilidad de la plataforma, pero no garantiza el acceso ininterrumpido. El mantenimiento programado se comunicará con anticipación cuando sea posible.",
      },
      {
        heading: "10. Terminación",
        body: "BIMCapital Partners INC se reserva el derecho de suspender o terminar cuentas que violen estos Términos. Al momento de la terminación su acceso a la plataforma cesará, pero sus datos serán retenidos de acuerdo con nuestra Política de Retención de Datos.",
      },
      {
        heading: "11. Ley Aplicable",
        body: "Estos Términos de Servicio se rigen por las leyes del Estado de Florida, Estados Unidos, sin considerar principios de conflicto de leyes. Cualquier disputa se resolverá en los tribunales del Condado de Pinellas, Florida.",
      },
      {
        heading: "12. Cambios a Estos Términos",
        body: "Podemos actualizar estos Términos de vez en cuando. Notificaremos a los usuarios registrados por correo electrónico sobre cualquier cambio material. El uso continuado de BIMLog después de la notificación constituye aceptación de los términos actualizados.",
      },
      {
        heading: "13. Contacto",
        body: "info@ignitesmart.ai\nBIMCapital Partners INC\n7901 4th Street North STE 300\nSt. Petersburg FL 33702",
      },
    ],
  },
};

export function Terms() {
  const { language, t } = useI18n();
  const content = language === "es" ? CONTENT.es : CONTENT.en;

  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <div style={{ maxWidth: 760, margin: "0 auto", padding: "40px 24px", flex: 1 }}>
        <Link href="/" style={{ display: "inline-flex", alignItems: "center", gap: 4, fontSize: 13, color: "hsl(var(--muted-foreground))", textDecoration: "none", marginBottom: 32 }}>
          <ChevronLeft style={{ width: 14, height: 14 }} />
          {t("legal.backToHome")}
        </Link>

        <div style={{ marginBottom: 8 }}>
          <span style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "hsl(var(--primary))", background: "hsl(var(--primary)/0.08)", padding: "3px 10px", borderRadius: 4 }}>Legal</span>
        </div>
        <h1 style={{ fontSize: 28, fontWeight: 800, color: "hsl(var(--foreground))", marginBottom: 8, fontFamily: "var(--font-display)" }}>{content.title}</h1>
        <div style={{ fontSize: 13, color: "hsl(var(--muted-foreground))", marginBottom: 4 }}>{t("legal.effectiveDate")}: {content.effectiveDate}</div>
        <div style={{ fontSize: 13, color: "hsl(var(--muted-foreground))", marginBottom: 4 }}>{t("legal.lastUpdated")}: {content.lastUpdated}</div>
        <div style={{ fontSize: 13, color: "hsl(var(--muted-foreground))", marginBottom: 32 }}>BIMCapital Partners INC · 7901 4th Street North, STE 300 · St. Petersburg, FL 33702 · info@ignitesmart.ai</div>

        <div style={{ borderTop: "1px solid hsl(var(--border))", paddingTop: 32 }}>
          {content.sections.map((sec, i) => (
            <div key={i} style={{ marginBottom: 32 }}>
              <h2 style={{ fontSize: 15, fontWeight: 700, color: "hsl(var(--foreground))", marginBottom: 10, fontFamily: "var(--font-display)" }}>{sec.heading}</h2>
              {sec.body.split("\n\n").map((para, j) => (
                <p key={j} style={{ fontSize: 14, color: "hsl(var(--muted-foreground))", lineHeight: 1.7, marginBottom: 10, whiteSpace: "pre-line" }}>{para}</p>
              ))}
            </div>
          ))}
        </div>
      </div>
      <Footer />
    </div>
  );
}
